; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t67 = alloca [4096 x i64]
  %t123 = alloca [224 x i64]
  %t124 = alloca i64
  store i64 0, ptr %t124
  %t127 = alloca i64
  store i64 0, ptr %t127
  %t131 = alloca i64
  store i64 0, ptr %t131
  %t142 = alloca i64
  store i64 0, ptr %t142
  %t185 = alloca i64
  store i64 0, ptr %t185
  %t188 = alloca i64
  store i64 0, ptr %t188
  %t236 = alloca i64
  store i64 0, ptr %t236
  %t239 = alloca i64
  store i64 0, ptr %t239
  %t250 = alloca i64
  store i64 0, ptr %t250
  %t1 = alloca [4096 x i64]
  %t2 = alloca [64 x i64]
  call void @llvm.memset.p0.i64(ptr %t2, i8 0, i64 512, i1 false)
  %t3 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t3, ptr %t2, i64 512, i1 false)
  %t4 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 64
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t2, i64 512, i1 false)
  %t5 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 128
  call void @llvm.memcpy.p0.p0.i64(ptr %t5, ptr %t2, i64 512, i1 false)
  %t6 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 192
  call void @llvm.memcpy.p0.p0.i64(ptr %t6, ptr %t2, i64 512, i1 false)
  %t7 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 256
  call void @llvm.memcpy.p0.p0.i64(ptr %t7, ptr %t2, i64 512, i1 false)
  %t8 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 320
  call void @llvm.memcpy.p0.p0.i64(ptr %t8, ptr %t2, i64 512, i1 false)
  %t9 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 384
  call void @llvm.memcpy.p0.p0.i64(ptr %t9, ptr %t2, i64 512, i1 false)
  %t10 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 448
  call void @llvm.memcpy.p0.p0.i64(ptr %t10, ptr %t2, i64 512, i1 false)
  %t11 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 512
  call void @llvm.memcpy.p0.p0.i64(ptr %t11, ptr %t2, i64 512, i1 false)
  %t12 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 576
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t2, i64 512, i1 false)
  %t13 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 640
  call void @llvm.memcpy.p0.p0.i64(ptr %t13, ptr %t2, i64 512, i1 false)
  %t14 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 704
  call void @llvm.memcpy.p0.p0.i64(ptr %t14, ptr %t2, i64 512, i1 false)
  %t15 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 768
  call void @llvm.memcpy.p0.p0.i64(ptr %t15, ptr %t2, i64 512, i1 false)
  %t16 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 832
  call void @llvm.memcpy.p0.p0.i64(ptr %t16, ptr %t2, i64 512, i1 false)
  %t17 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 896
  call void @llvm.memcpy.p0.p0.i64(ptr %t17, ptr %t2, i64 512, i1 false)
  %t18 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 960
  call void @llvm.memcpy.p0.p0.i64(ptr %t18, ptr %t2, i64 512, i1 false)
  %t19 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1024
  call void @llvm.memcpy.p0.p0.i64(ptr %t19, ptr %t2, i64 512, i1 false)
  %t20 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1088
  call void @llvm.memcpy.p0.p0.i64(ptr %t20, ptr %t2, i64 512, i1 false)
  %t21 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1152
  call void @llvm.memcpy.p0.p0.i64(ptr %t21, ptr %t2, i64 512, i1 false)
  %t22 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1216
  call void @llvm.memcpy.p0.p0.i64(ptr %t22, ptr %t2, i64 512, i1 false)
  %t23 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1280
  call void @llvm.memcpy.p0.p0.i64(ptr %t23, ptr %t2, i64 512, i1 false)
  %t24 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1344
  call void @llvm.memcpy.p0.p0.i64(ptr %t24, ptr %t2, i64 512, i1 false)
  %t25 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1408
  call void @llvm.memcpy.p0.p0.i64(ptr %t25, ptr %t2, i64 512, i1 false)
  %t26 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1472
  call void @llvm.memcpy.p0.p0.i64(ptr %t26, ptr %t2, i64 512, i1 false)
  %t27 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1536
  call void @llvm.memcpy.p0.p0.i64(ptr %t27, ptr %t2, i64 512, i1 false)
  %t28 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1600
  call void @llvm.memcpy.p0.p0.i64(ptr %t28, ptr %t2, i64 512, i1 false)
  %t29 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1664
  call void @llvm.memcpy.p0.p0.i64(ptr %t29, ptr %t2, i64 512, i1 false)
  %t30 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1728
  call void @llvm.memcpy.p0.p0.i64(ptr %t30, ptr %t2, i64 512, i1 false)
  %t31 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1792
  call void @llvm.memcpy.p0.p0.i64(ptr %t31, ptr %t2, i64 512, i1 false)
  %t32 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1856
  call void @llvm.memcpy.p0.p0.i64(ptr %t32, ptr %t2, i64 512, i1 false)
  %t33 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1920
  call void @llvm.memcpy.p0.p0.i64(ptr %t33, ptr %t2, i64 512, i1 false)
  %t34 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1984
  call void @llvm.memcpy.p0.p0.i64(ptr %t34, ptr %t2, i64 512, i1 false)
  %t35 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2048
  call void @llvm.memcpy.p0.p0.i64(ptr %t35, ptr %t2, i64 512, i1 false)
  %t36 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2112
  call void @llvm.memcpy.p0.p0.i64(ptr %t36, ptr %t2, i64 512, i1 false)
  %t37 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2176
  call void @llvm.memcpy.p0.p0.i64(ptr %t37, ptr %t2, i64 512, i1 false)
  %t38 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2240
  call void @llvm.memcpy.p0.p0.i64(ptr %t38, ptr %t2, i64 512, i1 false)
  %t39 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2304
  call void @llvm.memcpy.p0.p0.i64(ptr %t39, ptr %t2, i64 512, i1 false)
  %t40 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2368
  call void @llvm.memcpy.p0.p0.i64(ptr %t40, ptr %t2, i64 512, i1 false)
  %t41 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2432
  call void @llvm.memcpy.p0.p0.i64(ptr %t41, ptr %t2, i64 512, i1 false)
  %t42 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2496
  call void @llvm.memcpy.p0.p0.i64(ptr %t42, ptr %t2, i64 512, i1 false)
  %t43 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2560
  call void @llvm.memcpy.p0.p0.i64(ptr %t43, ptr %t2, i64 512, i1 false)
  %t44 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2624
  call void @llvm.memcpy.p0.p0.i64(ptr %t44, ptr %t2, i64 512, i1 false)
  %t45 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2688
  call void @llvm.memcpy.p0.p0.i64(ptr %t45, ptr %t2, i64 512, i1 false)
  %t46 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2752
  call void @llvm.memcpy.p0.p0.i64(ptr %t46, ptr %t2, i64 512, i1 false)
  %t47 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2816
  call void @llvm.memcpy.p0.p0.i64(ptr %t47, ptr %t2, i64 512, i1 false)
  %t48 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2880
  call void @llvm.memcpy.p0.p0.i64(ptr %t48, ptr %t2, i64 512, i1 false)
  %t49 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2944
  call void @llvm.memcpy.p0.p0.i64(ptr %t49, ptr %t2, i64 512, i1 false)
  %t50 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3008
  call void @llvm.memcpy.p0.p0.i64(ptr %t50, ptr %t2, i64 512, i1 false)
  %t51 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3072
  call void @llvm.memcpy.p0.p0.i64(ptr %t51, ptr %t2, i64 512, i1 false)
  %t52 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3136
  call void @llvm.memcpy.p0.p0.i64(ptr %t52, ptr %t2, i64 512, i1 false)
  %t53 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3200
  call void @llvm.memcpy.p0.p0.i64(ptr %t53, ptr %t2, i64 512, i1 false)
  %t54 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3264
  call void @llvm.memcpy.p0.p0.i64(ptr %t54, ptr %t2, i64 512, i1 false)
  %t55 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3328
  call void @llvm.memcpy.p0.p0.i64(ptr %t55, ptr %t2, i64 512, i1 false)
  %t56 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3392
  call void @llvm.memcpy.p0.p0.i64(ptr %t56, ptr %t2, i64 512, i1 false)
  %t57 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3456
  call void @llvm.memcpy.p0.p0.i64(ptr %t57, ptr %t2, i64 512, i1 false)
  %t58 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3520
  call void @llvm.memcpy.p0.p0.i64(ptr %t58, ptr %t2, i64 512, i1 false)
  %t59 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3584
  call void @llvm.memcpy.p0.p0.i64(ptr %t59, ptr %t2, i64 512, i1 false)
  %t60 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3648
  call void @llvm.memcpy.p0.p0.i64(ptr %t60, ptr %t2, i64 512, i1 false)
  %t61 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3712
  call void @llvm.memcpy.p0.p0.i64(ptr %t61, ptr %t2, i64 512, i1 false)
  %t62 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3776
  call void @llvm.memcpy.p0.p0.i64(ptr %t62, ptr %t2, i64 512, i1 false)
  %t63 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3840
  call void @llvm.memcpy.p0.p0.i64(ptr %t63, ptr %t2, i64 512, i1 false)
  %t64 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3904
  call void @llvm.memcpy.p0.p0.i64(ptr %t64, ptr %t2, i64 512, i1 false)
  %t65 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3968
  call void @llvm.memcpy.p0.p0.i64(ptr %t65, ptr %t2, i64 512, i1 false)
  %t66 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 4032
  call void @llvm.memcpy.p0.p0.i64(ptr %t66, ptr %t2, i64 512, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t67, ptr %t1, i64 32768, i1 false)
  %t68 = alloca [224 x i64]
  %t69 = alloca [7 x i64]
  %t70 = trunc i64 0 to i32
  %t71 = sext i32 %t70 to i64
  %t72 = getelementptr [7 x i64], ptr %t69, i64 0, i64 0
  store i64 %t71, ptr %t72
  %t73 = trunc i64 0 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = getelementptr [7 x i64], ptr %t69, i64 0, i64 1
  store i64 %t74, ptr %t75
  %t76 = trunc i64 0 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = getelementptr [7 x i64], ptr %t69, i64 0, i64 2
  store i64 %t77, ptr %t78
  %t79 = trunc i64 0 to i32
  %t80 = sext i32 %t79 to i64
  %t81 = getelementptr [7 x i64], ptr %t69, i64 0, i64 3
  store i64 %t80, ptr %t81
  %t82 = trunc i64 0 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = getelementptr [7 x i64], ptr %t69, i64 0, i64 4
  store i64 %t83, ptr %t84
  %t85 = trunc i64 0 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = getelementptr [7 x i64], ptr %t69, i64 0, i64 5
  store i64 %t86, ptr %t87
  %t88 = trunc i64 0 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = getelementptr [7 x i64], ptr %t69, i64 0, i64 6
  store i64 %t89, ptr %t90
  %t91 = getelementptr [224 x i64], ptr %t68, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t91, ptr %t69, i64 56, i1 false)
  %t92 = getelementptr [224 x i64], ptr %t68, i64 0, i64 7
  call void @llvm.memcpy.p0.p0.i64(ptr %t92, ptr %t69, i64 56, i1 false)
  %t93 = getelementptr [224 x i64], ptr %t68, i64 0, i64 14
  call void @llvm.memcpy.p0.p0.i64(ptr %t93, ptr %t69, i64 56, i1 false)
  %t94 = getelementptr [224 x i64], ptr %t68, i64 0, i64 21
  call void @llvm.memcpy.p0.p0.i64(ptr %t94, ptr %t69, i64 56, i1 false)
  %t95 = getelementptr [224 x i64], ptr %t68, i64 0, i64 28
  call void @llvm.memcpy.p0.p0.i64(ptr %t95, ptr %t69, i64 56, i1 false)
  %t96 = getelementptr [224 x i64], ptr %t68, i64 0, i64 35
  call void @llvm.memcpy.p0.p0.i64(ptr %t96, ptr %t69, i64 56, i1 false)
  %t97 = getelementptr [224 x i64], ptr %t68, i64 0, i64 42
  call void @llvm.memcpy.p0.p0.i64(ptr %t97, ptr %t69, i64 56, i1 false)
  %t98 = getelementptr [224 x i64], ptr %t68, i64 0, i64 49
  call void @llvm.memcpy.p0.p0.i64(ptr %t98, ptr %t69, i64 56, i1 false)
  %t99 = getelementptr [224 x i64], ptr %t68, i64 0, i64 56
  call void @llvm.memcpy.p0.p0.i64(ptr %t99, ptr %t69, i64 56, i1 false)
  %t100 = getelementptr [224 x i64], ptr %t68, i64 0, i64 63
  call void @llvm.memcpy.p0.p0.i64(ptr %t100, ptr %t69, i64 56, i1 false)
  %t101 = getelementptr [224 x i64], ptr %t68, i64 0, i64 70
  call void @llvm.memcpy.p0.p0.i64(ptr %t101, ptr %t69, i64 56, i1 false)
  %t102 = getelementptr [224 x i64], ptr %t68, i64 0, i64 77
  call void @llvm.memcpy.p0.p0.i64(ptr %t102, ptr %t69, i64 56, i1 false)
  %t103 = getelementptr [224 x i64], ptr %t68, i64 0, i64 84
  call void @llvm.memcpy.p0.p0.i64(ptr %t103, ptr %t69, i64 56, i1 false)
  %t104 = getelementptr [224 x i64], ptr %t68, i64 0, i64 91
  call void @llvm.memcpy.p0.p0.i64(ptr %t104, ptr %t69, i64 56, i1 false)
  %t105 = getelementptr [224 x i64], ptr %t68, i64 0, i64 98
  call void @llvm.memcpy.p0.p0.i64(ptr %t105, ptr %t69, i64 56, i1 false)
  %t106 = getelementptr [224 x i64], ptr %t68, i64 0, i64 105
  call void @llvm.memcpy.p0.p0.i64(ptr %t106, ptr %t69, i64 56, i1 false)
  %t107 = getelementptr [224 x i64], ptr %t68, i64 0, i64 112
  call void @llvm.memcpy.p0.p0.i64(ptr %t107, ptr %t69, i64 56, i1 false)
  %t108 = getelementptr [224 x i64], ptr %t68, i64 0, i64 119
  call void @llvm.memcpy.p0.p0.i64(ptr %t108, ptr %t69, i64 56, i1 false)
  %t109 = getelementptr [224 x i64], ptr %t68, i64 0, i64 126
  call void @llvm.memcpy.p0.p0.i64(ptr %t109, ptr %t69, i64 56, i1 false)
  %t110 = getelementptr [224 x i64], ptr %t68, i64 0, i64 133
  call void @llvm.memcpy.p0.p0.i64(ptr %t110, ptr %t69, i64 56, i1 false)
  %t111 = getelementptr [224 x i64], ptr %t68, i64 0, i64 140
  call void @llvm.memcpy.p0.p0.i64(ptr %t111, ptr %t69, i64 56, i1 false)
  %t112 = getelementptr [224 x i64], ptr %t68, i64 0, i64 147
  call void @llvm.memcpy.p0.p0.i64(ptr %t112, ptr %t69, i64 56, i1 false)
  %t113 = getelementptr [224 x i64], ptr %t68, i64 0, i64 154
  call void @llvm.memcpy.p0.p0.i64(ptr %t113, ptr %t69, i64 56, i1 false)
  %t114 = getelementptr [224 x i64], ptr %t68, i64 0, i64 161
  call void @llvm.memcpy.p0.p0.i64(ptr %t114, ptr %t69, i64 56, i1 false)
  %t115 = getelementptr [224 x i64], ptr %t68, i64 0, i64 168
  call void @llvm.memcpy.p0.p0.i64(ptr %t115, ptr %t69, i64 56, i1 false)
  %t116 = getelementptr [224 x i64], ptr %t68, i64 0, i64 175
  call void @llvm.memcpy.p0.p0.i64(ptr %t116, ptr %t69, i64 56, i1 false)
  %t117 = getelementptr [224 x i64], ptr %t68, i64 0, i64 182
  call void @llvm.memcpy.p0.p0.i64(ptr %t117, ptr %t69, i64 56, i1 false)
  %t118 = getelementptr [224 x i64], ptr %t68, i64 0, i64 189
  call void @llvm.memcpy.p0.p0.i64(ptr %t118, ptr %t69, i64 56, i1 false)
  %t119 = getelementptr [224 x i64], ptr %t68, i64 0, i64 196
  call void @llvm.memcpy.p0.p0.i64(ptr %t119, ptr %t69, i64 56, i1 false)
  %t120 = getelementptr [224 x i64], ptr %t68, i64 0, i64 203
  call void @llvm.memcpy.p0.p0.i64(ptr %t120, ptr %t69, i64 56, i1 false)
  %t121 = getelementptr [224 x i64], ptr %t68, i64 0, i64 210
  call void @llvm.memcpy.p0.p0.i64(ptr %t121, ptr %t69, i64 56, i1 false)
  %t122 = getelementptr [224 x i64], ptr %t68, i64 0, i64 217
  call void @llvm.memcpy.p0.p0.i64(ptr %t122, ptr %t69, i64 56, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t123, ptr %t68, i64 1792, i1 false)
  %t125 = trunc i64 32 to i32
  %t126 = sext i32 %t125 to i64
  store i64 %t126, ptr %t124
  %t128 = trunc i64 64 to i32
  %t129 = sext i32 %t128 to i64
  store i64 %t129, ptr %t127
  %t130 = call i64 @init_world(ptr %t67, ptr %t123)
  %t132 = trunc i64 0 to i32
  %t133 = sext i32 %t132 to i64
  store i64 %t133, ptr %t131
  br label %while1
while1:
  %t134 = load i64, ptr %t131
  %t135 = trunc i64 %t134 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = trunc i64 200 to i32
  %t138 = sext i32 %t137 to i64
  %t139 = icmp slt i64 %t136, %t138
  %t140 = zext i1 %t139 to i64
  %t141 = icmp ne i64 %t140, 0
  br i1 %t141, label %whilebody2, label %whileexit3
whilebody2:
  %t143 = trunc i64 0 to i32
  %t144 = sext i32 %t143 to i64
  store i64 %t144, ptr %t142
  br label %while4
while4:
  %t145 = load i64, ptr %t142
  %t146 = trunc i64 %t145 to i32
  %t147 = sext i32 %t146 to i64
  %t148 = trunc i64 32 to i32
  %t149 = sext i32 %t148 to i64
  %t150 = icmp slt i64 %t147, %t149
  %t151 = zext i1 %t150 to i64
  %t152 = icmp ne i64 %t151, 0
  br i1 %t152, label %whilebody5, label %whileexit6
whilebody5:
  %t153 = load i64, ptr %t142
  %t154 = mul i64 %t153, 7
  %t155 = getelementptr [224 x i64], ptr %t123, i64 0, i64 %t154
  %t156 = load i64, ptr %t142
  %t157 = mul i64 %t156, 7
  %t158 = getelementptr [224 x i64], ptr %t123, i64 0, i64 %t157
  %t159 = call i64 @update_agent(ptr %t158, ptr %t67)
  %t160 = load i64, ptr %t142
  %t161 = trunc i64 %t160 to i32
  %t162 = sext i32 %t161 to i64
  %t163 = trunc i64 1 to i32
  %t164 = sext i32 %t163 to i64
  %t165 = add i64 %t162, %t164
  %t166 = trunc i64 %t165 to i32
  %t167 = sext i32 %t166 to i64
  %t168 = trunc i64 %t167 to i32
  %t169 = sext i32 %t168 to i64
  store i64 %t169, ptr %t142
  br label %while4
whileexit6:
  %t170 = load i64, ptr %t131
  %t171 = trunc i64 %t170 to i32
  %t172 = sext i32 %t171 to i64
  %t173 = trunc i64 20 to i32
  %t174 = sext i32 %t173 to i64
  %t175 = srem i64 %t172, %t174
  %t176 = trunc i64 %t175 to i32
  %t177 = sext i32 %t176 to i64
  %t178 = trunc i64 %t177 to i32
  %t179 = sext i32 %t178 to i64
  %t180 = trunc i64 0 to i32
  %t181 = sext i32 %t180 to i64
  %t182 = icmp eq i64 %t179, %t181
  %t183 = zext i1 %t182 to i64
  %t184 = icmp ne i64 %t183, 0
  br i1 %t184, label %then7, label %else8
then7:
  %t186 = trunc i64 0 to i32
  %t187 = sext i32 %t186 to i64
  store i64 %t187, ptr %t185
  %t189 = trunc i64 0 to i32
  %t190 = sext i32 %t189 to i64
  store i64 %t190, ptr %t188
  br label %while10
while10:
  %t191 = load i64, ptr %t188
  %t192 = trunc i64 %t191 to i32
  %t193 = sext i32 %t192 to i64
  %t194 = trunc i64 32 to i32
  %t195 = sext i32 %t194 to i64
  %t196 = icmp slt i64 %t193, %t195
  %t197 = zext i1 %t196 to i64
  %t198 = icmp ne i64 %t197, 0
  br i1 %t198, label %whilebody11, label %whileexit12
whilebody11:
  %t199 = load i64, ptr %t185
  %t200 = load i64, ptr %t188
  %t201 = mul i64 %t200, 7
  %t202 = getelementptr [224 x i64], ptr %t123, i64 0, i64 %t201
  %t203 = getelementptr i64, ptr %t202, i64 3
  %t204 = load i64, ptr %t203
  %t205 = trunc i64 %t199 to i32
  %t206 = sext i32 %t205 to i64
  %t207 = trunc i64 %t204 to i32
  %t208 = sext i32 %t207 to i64
  %t209 = add i64 %t206, %t208
  %t210 = trunc i64 %t209 to i32
  %t211 = sext i32 %t210 to i64
  %t212 = trunc i64 %t211 to i32
  %t213 = sext i32 %t212 to i64
  store i64 %t213, ptr %t185
  %t214 = load i64, ptr %t188
  %t215 = trunc i64 %t214 to i32
  %t216 = sext i32 %t215 to i64
  %t217 = trunc i64 1 to i32
  %t218 = sext i32 %t217 to i64
  %t219 = add i64 %t216, %t218
  %t220 = trunc i64 %t219 to i32
  %t221 = sext i32 %t220 to i64
  %t222 = trunc i64 %t221 to i32
  %t223 = sext i32 %t222 to i64
  store i64 %t223, ptr %t188
  br label %while10
whileexit12:
  %t224 = load i64, ptr %t185
  %t225 = call i64 @printlnInt(i64 %t224)
  br label %ifend9
else8:
  br label %ifend9
ifend9:
  %t226 = load i64, ptr %t131
  %t227 = trunc i64 %t226 to i32
  %t228 = sext i32 %t227 to i64
  %t229 = trunc i64 1 to i32
  %t230 = sext i32 %t229 to i64
  %t231 = add i64 %t228, %t230
  %t232 = trunc i64 %t231 to i32
  %t233 = sext i32 %t232 to i64
  %t234 = trunc i64 %t233 to i32
  %t235 = sext i32 %t234 to i64
  store i64 %t235, ptr %t131
  br label %while1
whileexit3:
  %t237 = trunc i64 0 to i32
  %t238 = sext i32 %t237 to i64
  store i64 %t238, ptr %t236
  %t240 = trunc i64 0 to i32
  %t241 = sext i32 %t240 to i64
  store i64 %t241, ptr %t239
  br label %while13
while13:
  %t242 = load i64, ptr %t239
  %t243 = trunc i64 %t242 to i32
  %t244 = sext i32 %t243 to i64
  %t245 = trunc i64 64 to i32
  %t246 = sext i32 %t245 to i64
  %t247 = icmp slt i64 %t244, %t246
  %t248 = zext i1 %t247 to i64
  %t249 = icmp ne i64 %t248, 0
  br i1 %t249, label %whilebody14, label %whileexit15
whilebody14:
  %t251 = trunc i64 0 to i32
  %t252 = sext i32 %t251 to i64
  store i64 %t252, ptr %t250
  br label %while16
while16:
  %t253 = load i64, ptr %t250
  %t254 = trunc i64 %t253 to i32
  %t255 = sext i32 %t254 to i64
  %t256 = trunc i64 64 to i32
  %t257 = sext i32 %t256 to i64
  %t258 = icmp slt i64 %t255, %t257
  %t259 = zext i1 %t258 to i64
  %t260 = icmp ne i64 %t259, 0
  br i1 %t260, label %whilebody17, label %whileexit18
whilebody17:
  %t261 = load i64, ptr %t236
  %t262 = load i64, ptr %t239
  %t263 = mul i64 %t262, 64
  %t264 = getelementptr [4096 x i64], ptr %t67, i64 0, i64 %t263
  %t265 = load i64, ptr %t250
  %t266 = mul i64 %t265, 1
  %t267 = getelementptr i64, ptr %t264, i64 %t266
  %t268 = load i64, ptr %t267
  %t269 = trunc i64 %t261 to i32
  %t270 = sext i32 %t269 to i64
  %t271 = trunc i64 %t268 to i32
  %t272 = sext i32 %t271 to i64
  %t273 = add i64 %t270, %t272
  %t274 = trunc i64 %t273 to i32
  %t275 = sext i32 %t274 to i64
  %t276 = trunc i64 %t275 to i32
  %t277 = sext i32 %t276 to i64
  store i64 %t277, ptr %t236
  %t278 = load i64, ptr %t250
  %t279 = trunc i64 %t278 to i32
  %t280 = sext i32 %t279 to i64
  %t281 = trunc i64 1 to i32
  %t282 = sext i32 %t281 to i64
  %t283 = add i64 %t280, %t282
  %t284 = trunc i64 %t283 to i32
  %t285 = sext i32 %t284 to i64
  %t286 = trunc i64 %t285 to i32
  %t287 = sext i32 %t286 to i64
  store i64 %t287, ptr %t250
  br label %while16
whileexit18:
  %t288 = load i64, ptr %t239
  %t289 = trunc i64 %t288 to i32
  %t290 = sext i32 %t289 to i64
  %t291 = trunc i64 1 to i32
  %t292 = sext i32 %t291 to i64
  %t293 = add i64 %t290, %t292
  %t294 = trunc i64 %t293 to i32
  %t295 = sext i32 %t294 to i64
  %t296 = trunc i64 %t295 to i32
  %t297 = sext i32 %t296 to i64
  store i64 %t297, ptr %t239
  br label %while13
whileexit15:
  %t298 = load i64, ptr %t236
  %t299 = call i64 @printlnInt(i64 %t298)
  ret i64 0
}

define i64 @init_world(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t12 = alloca i64
  store i64 0, ptr %t12
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 64 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t13 = trunc i64 0 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t12
  br label %while4
while4:
  %t15 = load i64, ptr %t12
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 64 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = icmp slt i64 %t17, %t19
  %t21 = zext i1 %t20 to i64
  %t22 = icmp ne i64 %t21, 0
  br i1 %t22, label %whilebody5, label %whileexit6
whilebody5:
  %t23 = load i64, ptr %t1
  %t24 = load i64, ptr %t12
  %t25 = trunc i64 %t23 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 %t24 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = mul i64 %t26, %t28
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = load i64, ptr %t1
  %t33 = trunc i64 %t31 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = trunc i64 %t32 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = add i64 %t34, %t36
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = load i64, ptr %t12
  %t41 = trunc i64 %t39 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = trunc i64 %t40 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = add i64 %t42, %t44
  %t46 = trunc i64 %t45 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = trunc i64 %t47 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = trunc i64 100 to i32
  %t51 = sext i32 %t50 to i64
  %t52 = srem i64 %t49, %t51
  %t53 = trunc i64 %t52 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = load i64, ptr %t1
  %t56 = mul i64 %t55, 64
  %t57 = getelementptr [4096 x i64], ptr %p0, i64 0, i64 %t56
  %t58 = load i64, ptr %t12
  %t59 = mul i64 %t58, 1
  %t60 = getelementptr i64, ptr %t57, i64 %t59
  %t61 = trunc i64 %t54 to i32
  %t62 = sext i32 %t61 to i64
  store i64 %t62, ptr %t60
  %t63 = load i64, ptr %t12
  %t64 = trunc i64 %t63 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = trunc i64 1 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = add i64 %t65, %t67
  %t69 = trunc i64 %t68 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = trunc i64 %t70 to i32
  %t72 = sext i32 %t71 to i64
  store i64 %t72, ptr %t12
  br label %while4
whileexit6:
  %t73 = load i64, ptr %t1
  %t74 = trunc i64 %t73 to i32
  %t75 = sext i32 %t74 to i64
  %t76 = trunc i64 1 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = add i64 %t75, %t77
  %t79 = trunc i64 %t78 to i32
  %t80 = sext i32 %t79 to i64
  %t81 = trunc i64 %t80 to i32
  %t82 = sext i32 %t81 to i64
  store i64 %t82, ptr %t1
  br label %while1
whileexit3:
  %t83 = trunc i64 0 to i32
  %t84 = sext i32 %t83 to i64
  store i64 %t84, ptr %t1
  br label %while7
while7:
  %t85 = load i64, ptr %t1
  %t86 = trunc i64 %t85 to i32
  %t87 = sext i32 %t86 to i64
  %t88 = trunc i64 32 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = icmp slt i64 %t87, %t89
  %t91 = zext i1 %t90 to i64
  %t92 = icmp ne i64 %t91, 0
  br i1 %t92, label %whilebody8, label %whileexit9
whilebody8:
  %t93 = load i64, ptr %t1
  %t94 = load i64, ptr %t1
  %t95 = mul i64 %t94, 7
  %t96 = getelementptr [224 x i64], ptr %p1, i64 0, i64 %t95
  %t97 = getelementptr i64, ptr %t96, i64 0
  %t98 = trunc i64 %t93 to i32
  %t99 = sext i32 %t98 to i64
  store i64 %t99, ptr %t97
  %t100 = load i64, ptr %t1
  %t101 = trunc i64 %t100 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = trunc i64 13 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = mul i64 %t102, %t104
  %t106 = trunc i64 %t105 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = trunc i64 64 to i32
  %t111 = sext i32 %t110 to i64
  %t112 = srem i64 %t109, %t111
  %t113 = trunc i64 %t112 to i32
  %t114 = sext i32 %t113 to i64
  %t115 = load i64, ptr %t1
  %t116 = mul i64 %t115, 7
  %t117 = getelementptr [224 x i64], ptr %p1, i64 0, i64 %t116
  %t118 = getelementptr i64, ptr %t117, i64 1
  %t119 = trunc i64 %t114 to i32
  %t120 = sext i32 %t119 to i64
  store i64 %t120, ptr %t118
  %t121 = load i64, ptr %t1
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  %t124 = trunc i64 31 to i32
  %t125 = sext i32 %t124 to i64
  %t126 = mul i64 %t123, %t125
  %t127 = trunc i64 %t126 to i32
  %t128 = sext i32 %t127 to i64
  %t129 = trunc i64 %t128 to i32
  %t130 = sext i32 %t129 to i64
  %t131 = trunc i64 64 to i32
  %t132 = sext i32 %t131 to i64
  %t133 = srem i64 %t130, %t132
  %t134 = trunc i64 %t133 to i32
  %t135 = sext i32 %t134 to i64
  %t136 = load i64, ptr %t1
  %t137 = mul i64 %t136, 7
  %t138 = getelementptr [224 x i64], ptr %p1, i64 0, i64 %t137
  %t139 = getelementptr i64, ptr %t138, i64 2
  %t140 = trunc i64 %t135 to i32
  %t141 = sext i32 %t140 to i64
  store i64 %t141, ptr %t139
  %t142 = load i64, ptr %t1
  %t143 = mul i64 %t142, 7
  %t144 = getelementptr [224 x i64], ptr %p1, i64 0, i64 %t143
  %t145 = getelementptr i64, ptr %t144, i64 3
  %t146 = trunc i64 100 to i32
  %t147 = sext i32 %t146 to i64
  store i64 %t147, ptr %t145
  %t148 = load i64, ptr %t1
  %t149 = mul i64 %t148, 7
  %t150 = getelementptr [224 x i64], ptr %p1, i64 0, i64 %t149
  %t151 = getelementptr i64, ptr %t150, i64 6
  %t152 = trunc i64 0 to i32
  %t153 = sext i32 %t152 to i64
  store i64 %t153, ptr %t151
  %t154 = load i64, ptr %t1
  %t155 = trunc i64 %t154 to i32
  %t156 = sext i32 %t155 to i64
  %t157 = trunc i64 1 to i32
  %t158 = sext i32 %t157 to i64
  %t159 = add i64 %t156, %t158
  %t160 = trunc i64 %t159 to i32
  %t161 = sext i32 %t160 to i64
  %t162 = trunc i64 %t161 to i32
  %t163 = sext i32 %t162 to i64
  store i64 %t163, ptr %t1
  br label %while7
whileexit9:
  ret i64 0
}

define i64 @find_new_target(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t10 = alloca i64
  store i64 0, ptr %t10
  %t21 = alloca i64
  store i64 0, ptr %t21
  %t56 = alloca i64
  store i64 0, ptr %t56
  %t83 = alloca i64
  store i64 0, ptr %t83
  %t2 = trunc i64 -1 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 -1 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  %t8 = trunc i64 -1 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  %t11 = trunc i64 -5 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  br label %while1
while1:
  %t13 = load i64, ptr %t10
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 5 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = icmp sle i64 %t15, %t17
  %t19 = zext i1 %t18 to i64
  %t20 = icmp ne i64 %t19, 0
  br i1 %t20, label %whilebody2, label %whileexit3
whilebody2:
  %t22 = trunc i64 -5 to i32
  %t23 = sext i32 %t22 to i64
  store i64 %t23, ptr %t21
  br label %while4
while4:
  %t24 = load i64, ptr %t21
  %t25 = trunc i64 %t24 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 5 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = icmp sle i64 %t26, %t28
  %t30 = zext i1 %t29 to i64
  %t31 = icmp ne i64 %t30, 0
  br i1 %t31, label %whilebody5, label %whileexit6
whilebody5:
  %t32 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t33 = load i64, ptr %t32
  %t34 = load i64, ptr %t10
  %t35 = trunc i64 %t33 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = trunc i64 %t34 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = add i64 %t36, %t38
  %t40 = trunc i64 %t39 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = trunc i64 64 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = add i64 %t43, %t45
  %t47 = trunc i64 %t46 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = trunc i64 64 to i32
  %t52 = sext i32 %t51 to i64
  %t53 = srem i64 %t50, %t52
  %t54 = trunc i64 %t53 to i32
  %t55 = sext i32 %t54 to i64
  %t57 = trunc i64 %t55 to i32
  %t58 = sext i32 %t57 to i64
  store i64 %t58, ptr %t56
  %t59 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t60 = load i64, ptr %t59
  %t61 = load i64, ptr %t21
  %t62 = trunc i64 %t60 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 %t61 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = add i64 %t63, %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = trunc i64 %t68 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = trunc i64 64 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = add i64 %t70, %t72
  %t74 = trunc i64 %t73 to i32
  %t75 = sext i32 %t74 to i64
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = trunc i64 64 to i32
  %t79 = sext i32 %t78 to i64
  %t80 = srem i64 %t77, %t79
  %t81 = trunc i64 %t80 to i32
  %t82 = sext i32 %t81 to i64
  %t84 = trunc i64 %t82 to i32
  %t85 = sext i32 %t84 to i64
  store i64 %t85, ptr %t83
  %t86 = load i64, ptr %t56
  %t87 = mul i64 %t86, 64
  %t88 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t87
  %t89 = load i64, ptr %t83
  %t90 = mul i64 %t89, 1
  %t91 = getelementptr i64, ptr %t88, i64 %t90
  %t92 = load i64, ptr %t91
  %t93 = load i64, ptr %t7
  %t94 = trunc i64 %t92 to i32
  %t95 = sext i32 %t94 to i64
  %t96 = trunc i64 %t93 to i32
  %t97 = sext i32 %t96 to i64
  %t98 = icmp sgt i64 %t95, %t97
  %t99 = zext i1 %t98 to i64
  %t100 = icmp ne i64 %t99, 0
  br i1 %t100, label %then7, label %else8
then7:
  %t101 = load i64, ptr %t56
  %t102 = mul i64 %t101, 64
  %t103 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t102
  %t104 = load i64, ptr %t83
  %t105 = mul i64 %t104, 1
  %t106 = getelementptr i64, ptr %t103, i64 %t105
  %t107 = load i64, ptr %t106
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  store i64 %t109, ptr %t7
  %t110 = load i64, ptr %t56
  %t111 = trunc i64 %t110 to i32
  %t112 = sext i32 %t111 to i64
  store i64 %t112, ptr %t1
  %t113 = load i64, ptr %t83
  %t114 = trunc i64 %t113 to i32
  %t115 = sext i32 %t114 to i64
  store i64 %t115, ptr %t4
  br label %ifend9
else8:
  br label %ifend9
ifend9:
  %t116 = load i64, ptr %t21
  %t117 = trunc i64 %t116 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = trunc i64 1 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = add i64 %t118, %t120
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  %t124 = trunc i64 %t123 to i32
  %t125 = sext i32 %t124 to i64
  store i64 %t125, ptr %t21
  br label %while4
whileexit6:
  %t126 = load i64, ptr %t10
  %t127 = trunc i64 %t126 to i32
  %t128 = sext i32 %t127 to i64
  %t129 = trunc i64 1 to i32
  %t130 = sext i32 %t129 to i64
  %t131 = add i64 %t128, %t130
  %t132 = trunc i64 %t131 to i32
  %t133 = sext i32 %t132 to i64
  %t134 = trunc i64 %t133 to i32
  %t135 = sext i32 %t134 to i64
  store i64 %t135, ptr %t10
  br label %while1
whileexit3:
  %t136 = load i64, ptr %t1
  %t137 = trunc i64 %t136 to i32
  %t138 = sext i32 %t137 to i64
  %t139 = trunc i64 1000 to i32
  %t140 = sext i32 %t139 to i64
  %t141 = mul i64 %t138, %t140
  %t142 = trunc i64 %t141 to i32
  %t143 = sext i32 %t142 to i64
  %t144 = load i64, ptr %t4
  %t145 = trunc i64 %t143 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = trunc i64 %t144 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = add i64 %t146, %t148
  %t150 = trunc i64 %t149 to i32
  %t151 = sext i32 %t150 to i64
  ret i64 %t151
}

define i64 @update_agent(ptr %p0, ptr %p1) {
entry:
  %t32 = alloca i64
  store i64 0, ptr %t32
  %t207 = alloca i64
  store i64 0, ptr %t207
  %t1 = getelementptr [7 x i64], ptr %p0, i64 0, i64 3
  %t2 = load i64, ptr %t1
  %t3 = trunc i64 %t2 to i32
  %t4 = sext i32 %t3 to i64
  %t5 = trunc i64 0 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = icmp sle i64 %t4, %t6
  %t8 = zext i1 %t7 to i64
  %t9 = icmp ne i64 %t8, 0
  br i1 %t9, label %then1, label %else2
then1:
  ret i64 0
else2:
  br label %ifend3
ifend3:
  %t10 = getelementptr [7 x i64], ptr %p0, i64 0, i64 3
  %t11 = load i64, ptr %t10
  %t12 = trunc i64 %t11 to i32
  %t13 = sext i32 %t12 to i64
  %t14 = trunc i64 1 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = sub i64 %t13, %t15
  %t17 = trunc i64 %t16 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = getelementptr [7 x i64], ptr %p0, i64 0, i64 3
  %t20 = trunc i64 %t18 to i32
  %t21 = sext i32 %t20 to i64
  store i64 %t21, ptr %t19
  %t22 = getelementptr [7 x i64], ptr %p0, i64 0, i64 6
  %t23 = load i64, ptr %t22
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 0 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = icmp eq i64 %t25, %t27
  %t29 = zext i1 %t28 to i64
  %t30 = icmp ne i64 %t29, 0
  br i1 %t30, label %then4, label %else5
then4:
  %t31 = call i64 @find_new_target(ptr %p0, ptr %p1)
  %t33 = trunc i64 %t31 to i32
  %t34 = sext i32 %t33 to i64
  store i64 %t34, ptr %t32
  %t35 = load i64, ptr %t32
  %t36 = trunc i64 %t35 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = trunc i64 1000 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = sdiv i64 %t37, %t39
  %t41 = trunc i64 %t40 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = getelementptr [7 x i64], ptr %p0, i64 0, i64 4
  %t44 = trunc i64 %t42 to i32
  %t45 = sext i32 %t44 to i64
  store i64 %t45, ptr %t43
  %t46 = load i64, ptr %t32
  %t47 = trunc i64 %t46 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 1000 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = srem i64 %t48, %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = getelementptr [7 x i64], ptr %p0, i64 0, i64 5
  %t55 = trunc i64 %t53 to i32
  %t56 = sext i32 %t55 to i64
  store i64 %t56, ptr %t54
  %t57 = getelementptr [7 x i64], ptr %p0, i64 0, i64 6
  %t58 = trunc i64 1 to i32
  %t59 = sext i32 %t58 to i64
  store i64 %t59, ptr %t57
  br label %ifend6
else5:
  %t60 = getelementptr [7 x i64], ptr %p0, i64 0, i64 6
  %t61 = load i64, ptr %t60
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 1 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = icmp eq i64 %t63, %t65
  %t67 = zext i1 %t66 to i64
  %t68 = icmp ne i64 %t67, 0
  br i1 %t68, label %then7, label %else8
then7:
  %t69 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t70 = load i64, ptr %t69
  %t71 = getelementptr [7 x i64], ptr %p0, i64 0, i64 4
  %t72 = load i64, ptr %t71
  %t73 = trunc i64 %t70 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = trunc i64 %t72 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = icmp eq i64 %t74, %t76
  %t78 = zext i1 %t77 to i64
  %t79 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t80 = load i64, ptr %t79
  %t81 = getelementptr [7 x i64], ptr %p0, i64 0, i64 5
  %t82 = load i64, ptr %t81
  %t83 = trunc i64 %t80 to i32
  %t84 = sext i32 %t83 to i64
  %t85 = trunc i64 %t82 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = icmp eq i64 %t84, %t86
  %t88 = zext i1 %t87 to i64
  %t89 = icmp ne i64 %t78, 0
  %t90 = icmp ne i64 %t88, 0
  %t91 = and i1 %t89, %t90
  %t92 = zext i1 %t91 to i64
  %t93 = icmp ne i64 %t92, 0
  br i1 %t93, label %then10, label %else11
then10:
  %t94 = getelementptr [7 x i64], ptr %p0, i64 0, i64 6
  %t95 = trunc i64 2 to i32
  %t96 = sext i32 %t95 to i64
  store i64 %t96, ptr %t94
  br label %ifend12
else11:
  %t97 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t98 = load i64, ptr %t97
  %t99 = getelementptr [7 x i64], ptr %p0, i64 0, i64 4
  %t100 = load i64, ptr %t99
  %t101 = trunc i64 %t98 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = trunc i64 %t100 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = icmp slt i64 %t102, %t104
  %t106 = zext i1 %t105 to i64
  %t107 = icmp ne i64 %t106, 0
  br i1 %t107, label %then13, label %else14
then13:
  %t108 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t109 = load i64, ptr %t108
  %t110 = trunc i64 %t109 to i32
  %t111 = sext i32 %t110 to i64
  %t112 = trunc i64 1 to i32
  %t113 = sext i32 %t112 to i64
  %t114 = add i64 %t111, %t113
  %t115 = trunc i64 %t114 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t118 = trunc i64 %t116 to i32
  %t119 = sext i32 %t118 to i64
  store i64 %t119, ptr %t117
  br label %ifend15
else14:
  %t120 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t121 = load i64, ptr %t120
  %t122 = getelementptr [7 x i64], ptr %p0, i64 0, i64 4
  %t123 = load i64, ptr %t122
  %t124 = trunc i64 %t121 to i32
  %t125 = sext i32 %t124 to i64
  %t126 = trunc i64 %t123 to i32
  %t127 = sext i32 %t126 to i64
  %t128 = icmp sgt i64 %t125, %t127
  %t129 = zext i1 %t128 to i64
  %t130 = icmp ne i64 %t129, 0
  br i1 %t130, label %then16, label %else17
then16:
  %t131 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t132 = load i64, ptr %t131
  %t133 = trunc i64 %t132 to i32
  %t134 = sext i32 %t133 to i64
  %t135 = trunc i64 1 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = sub i64 %t134, %t136
  %t138 = trunc i64 %t137 to i32
  %t139 = sext i32 %t138 to i64
  %t140 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t141 = trunc i64 %t139 to i32
  %t142 = sext i32 %t141 to i64
  store i64 %t142, ptr %t140
  br label %ifend18
else17:
  br label %ifend18
ifend18:
  br label %ifend15
ifend15:
  %t143 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t144 = load i64, ptr %t143
  %t145 = getelementptr [7 x i64], ptr %p0, i64 0, i64 5
  %t146 = load i64, ptr %t145
  %t147 = trunc i64 %t144 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = trunc i64 %t146 to i32
  %t150 = sext i32 %t149 to i64
  %t151 = icmp slt i64 %t148, %t150
  %t152 = zext i1 %t151 to i64
  %t153 = icmp ne i64 %t152, 0
  br i1 %t153, label %then19, label %else20
then19:
  %t154 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t155 = load i64, ptr %t154
  %t156 = trunc i64 %t155 to i32
  %t157 = sext i32 %t156 to i64
  %t158 = trunc i64 1 to i32
  %t159 = sext i32 %t158 to i64
  %t160 = add i64 %t157, %t159
  %t161 = trunc i64 %t160 to i32
  %t162 = sext i32 %t161 to i64
  %t163 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t164 = trunc i64 %t162 to i32
  %t165 = sext i32 %t164 to i64
  store i64 %t165, ptr %t163
  br label %ifend21
else20:
  %t166 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t167 = load i64, ptr %t166
  %t168 = getelementptr [7 x i64], ptr %p0, i64 0, i64 5
  %t169 = load i64, ptr %t168
  %t170 = trunc i64 %t167 to i32
  %t171 = sext i32 %t170 to i64
  %t172 = trunc i64 %t169 to i32
  %t173 = sext i32 %t172 to i64
  %t174 = icmp sgt i64 %t171, %t173
  %t175 = zext i1 %t174 to i64
  %t176 = icmp ne i64 %t175, 0
  br i1 %t176, label %then22, label %else23
then22:
  %t177 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t178 = load i64, ptr %t177
  %t179 = trunc i64 %t178 to i32
  %t180 = sext i32 %t179 to i64
  %t181 = trunc i64 1 to i32
  %t182 = sext i32 %t181 to i64
  %t183 = sub i64 %t180, %t182
  %t184 = trunc i64 %t183 to i32
  %t185 = sext i32 %t184 to i64
  %t186 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t187 = trunc i64 %t185 to i32
  %t188 = sext i32 %t187 to i64
  store i64 %t188, ptr %t186
  br label %ifend24
else23:
  br label %ifend24
ifend24:
  br label %ifend21
ifend21:
  br label %ifend12
ifend12:
  br label %ifend9
else8:
  %t189 = getelementptr [7 x i64], ptr %p0, i64 0, i64 6
  %t190 = load i64, ptr %t189
  %t191 = trunc i64 %t190 to i32
  %t192 = sext i32 %t191 to i64
  %t193 = trunc i64 2 to i32
  %t194 = sext i32 %t193 to i64
  %t195 = icmp eq i64 %t192, %t194
  %t196 = zext i1 %t195 to i64
  %t197 = icmp ne i64 %t196, 0
  br i1 %t197, label %then25, label %else26
then25:
  %t198 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t199 = load i64, ptr %t198
  %t200 = mul i64 %t199, 64
  %t201 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t200
  %t202 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t203 = load i64, ptr %t202
  %t204 = mul i64 %t203, 1
  %t205 = getelementptr i64, ptr %t201, i64 %t204
  %t206 = load i64, ptr %t205
  %t208 = trunc i64 %t206 to i32
  %t209 = sext i32 %t208 to i64
  store i64 %t209, ptr %t207
  %t210 = load i64, ptr %t207
  %t211 = trunc i64 %t210 to i32
  %t212 = sext i32 %t211 to i64
  %t213 = trunc i64 0 to i32
  %t214 = sext i32 %t213 to i64
  %t215 = icmp sgt i64 %t212, %t214
  %t216 = zext i1 %t215 to i64
  %t217 = icmp ne i64 %t216, 0
  br i1 %t217, label %then28, label %else29
then28:
  %t218 = getelementptr [7 x i64], ptr %p0, i64 0, i64 3
  %t219 = load i64, ptr %t218
  %t220 = load i64, ptr %t207
  %t221 = trunc i64 %t220 to i32
  %t222 = sext i32 %t221 to i64
  %t223 = trunc i64 5 to i32
  %t224 = sext i32 %t223 to i64
  %t225 = sdiv i64 %t222, %t224
  %t226 = trunc i64 %t225 to i32
  %t227 = sext i32 %t226 to i64
  %t228 = trunc i64 %t219 to i32
  %t229 = sext i32 %t228 to i64
  %t230 = trunc i64 %t227 to i32
  %t231 = sext i32 %t230 to i64
  %t232 = add i64 %t229, %t231
  %t233 = trunc i64 %t232 to i32
  %t234 = sext i32 %t233 to i64
  %t235 = getelementptr [7 x i64], ptr %p0, i64 0, i64 3
  %t236 = trunc i64 %t234 to i32
  %t237 = sext i32 %t236 to i64
  store i64 %t237, ptr %t235
  %t238 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t239 = load i64, ptr %t238
  %t240 = mul i64 %t239, 64
  %t241 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t240
  %t242 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t243 = load i64, ptr %t242
  %t244 = mul i64 %t243, 1
  %t245 = getelementptr i64, ptr %t241, i64 %t244
  %t246 = load i64, ptr %t245
  %t247 = load i64, ptr %t207
  %t248 = trunc i64 %t247 to i32
  %t249 = sext i32 %t248 to i64
  %t250 = trunc i64 10 to i32
  %t251 = sext i32 %t250 to i64
  %t252 = sdiv i64 %t249, %t251
  %t253 = trunc i64 %t252 to i32
  %t254 = sext i32 %t253 to i64
  %t255 = trunc i64 %t246 to i32
  %t256 = sext i32 %t255 to i64
  %t257 = trunc i64 %t254 to i32
  %t258 = sext i32 %t257 to i64
  %t259 = sub i64 %t256, %t258
  %t260 = trunc i64 %t259 to i32
  %t261 = sext i32 %t260 to i64
  %t262 = trunc i64 %t261 to i32
  %t263 = sext i32 %t262 to i64
  %t264 = trunc i64 1 to i32
  %t265 = sext i32 %t264 to i64
  %t266 = sub i64 %t263, %t265
  %t267 = trunc i64 %t266 to i32
  %t268 = sext i32 %t267 to i64
  %t269 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t270 = load i64, ptr %t269
  %t271 = mul i64 %t270, 64
  %t272 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t271
  %t273 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t274 = load i64, ptr %t273
  %t275 = mul i64 %t274, 1
  %t276 = getelementptr i64, ptr %t272, i64 %t275
  %t277 = trunc i64 %t268 to i32
  %t278 = sext i32 %t277 to i64
  store i64 %t278, ptr %t276
  %t279 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t280 = load i64, ptr %t279
  %t281 = mul i64 %t280, 64
  %t282 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t281
  %t283 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t284 = load i64, ptr %t283
  %t285 = mul i64 %t284, 1
  %t286 = getelementptr i64, ptr %t282, i64 %t285
  %t287 = load i64, ptr %t286
  %t288 = trunc i64 %t287 to i32
  %t289 = sext i32 %t288 to i64
  %t290 = trunc i64 0 to i32
  %t291 = sext i32 %t290 to i64
  %t292 = icmp slt i64 %t289, %t291
  %t293 = zext i1 %t292 to i64
  %t294 = icmp ne i64 %t293, 0
  br i1 %t294, label %then31, label %else32
then31:
  %t295 = getelementptr [7 x i64], ptr %p0, i64 0, i64 1
  %t296 = load i64, ptr %t295
  %t297 = mul i64 %t296, 64
  %t298 = getelementptr [4096 x i64], ptr %p1, i64 0, i64 %t297
  %t299 = getelementptr [7 x i64], ptr %p0, i64 0, i64 2
  %t300 = load i64, ptr %t299
  %t301 = mul i64 %t300, 1
  %t302 = getelementptr i64, ptr %t298, i64 %t301
  %t303 = trunc i64 0 to i32
  %t304 = sext i32 %t303 to i64
  store i64 %t304, ptr %t302
  br label %ifend33
else32:
  br label %ifend33
ifend33:
  br label %ifend30
else29:
  br label %ifend30
ifend30:
  %t305 = getelementptr [7 x i64], ptr %p0, i64 0, i64 6
  %t306 = trunc i64 0 to i32
  %t307 = sext i32 %t306 to i64
  store i64 %t307, ptr %t305
  br label %ifend27
else26:
  br label %ifend27
ifend27:
  br label %ifend9
ifend9:
  br label %ifend6
ifend6:
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

