; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t2 = alloca [1024 x i64]
  %t3 = alloca i64
  store i64 0, ptr %t3
  %t6 = alloca i64
  store i64 0, ptr %t6
  %t12 = alloca [64 x i64]
  %t13 = alloca i64
  store i64 0, ptr %t13
  %t16 = alloca i64
  store i64 0, ptr %t16
  %t29 = alloca i64
  store i64 0, ptr %t29
  %t124 = alloca i64
  store i64 0, ptr %t124
  %t135 = alloca i64
  store i64 0, ptr %t135
  %t138 = alloca i64
  store i64 0, ptr %t138
  %t198 = alloca i64
  store i64 0, ptr %t198
  %t242 = alloca i64
  store i64 0, ptr %t242
  %t253 = alloca i64
  store i64 0, ptr %t253
  %t256 = alloca i64
  store i64 0, ptr %t256
  %t260 = alloca i64
  store i64 0, ptr %t260
  %t285 = alloca i64
  store i64 0, ptr %t285
  %t330 = alloca i64
  store i64 0, ptr %t330
  %t369 = alloca i64
  store i64 0, ptr %t369
  %t427 = alloca i64
  store i64 0, ptr %t427
  %t1 = alloca [1024 x i64]
  call void @llvm.memset.p0.i64(ptr %t1, i8 0, i64 8192, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t2, ptr %t1, i64 8192, i1 false)
  %t4 = trunc i64 0 to i32
  %t5 = sext i32 %t4 to i64
  store i64 %t5, ptr %t3
  %t7 = trunc i64 64 to i32
  %t8 = sext i32 %t7 to i64
  store i64 %t8, ptr %t6
  %t9 = load i64, ptr %t3
  %t10 = call i64 @init_heap(ptr %t2, ptr %t3)
  %t11 = alloca [64 x i64]
  call void @llvm.memset.p0.i64(ptr %t11, i8 0, i64 512, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t11, i64 512, i1 false)
  %t14 = trunc i64 0 to i32
  %t15 = sext i32 %t14 to i64
  store i64 %t15, ptr %t13
  %t17 = trunc i64 0 to i32
  %t18 = sext i32 %t17 to i64
  store i64 %t18, ptr %t16
  br label %while1
while1:
  %t19 = load i64, ptr %t13
  %t20 = trunc i64 %t19 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = trunc i64 64 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = icmp slt i64 %t21, %t23
  %t25 = zext i1 %t24 to i64
  %t26 = icmp ne i64 %t25, 0
  br i1 %t26, label %whilebody2, label %whileexit3
whilebody2:
  %t27 = load i64, ptr %t3
  %t28 = call i64 @halloc(ptr %t2, ptr %t3)
  %t30 = trunc i64 %t28 to i32
  %t31 = sext i32 %t30 to i64
  store i64 %t31, ptr %t29
  %t32 = load i64, ptr %t29
  %t33 = trunc i64 %t32 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = trunc i64 -1 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = icmp ne i64 %t34, %t36
  %t38 = zext i1 %t37 to i64
  %t39 = icmp ne i64 %t38, 0
  br i1 %t39, label %then4, label %else5
then4:
  %t40 = load i64, ptr %t29
  %t41 = load i64, ptr %t13
  %t42 = mul i64 %t41, 1
  %t43 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t42
  %t44 = trunc i64 %t40 to i32
  %t45 = sext i32 %t44 to i64
  store i64 %t45, ptr %t43
  %t46 = load i64, ptr %t16
  %t47 = trunc i64 %t46 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 1 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = add i64 %t48, %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 %t53 to i32
  %t55 = sext i32 %t54 to i64
  store i64 %t55, ptr %t16
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t56 = load i64, ptr %t13
  %t57 = trunc i64 %t56 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = trunc i64 1 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = add i64 %t58, %t60
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 %t63 to i32
  %t65 = sext i32 %t64 to i64
  store i64 %t65, ptr %t13
  br label %while1
whileexit3:
  %t66 = trunc i64 0 to i32
  %t67 = sext i32 %t66 to i64
  store i64 %t67, ptr %t13
  br label %while7
while7:
  %t68 = load i64, ptr %t13
  %t69 = trunc i64 %t68 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = trunc i64 32 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = icmp slt i64 %t70, %t72
  %t74 = zext i1 %t73 to i64
  %t75 = icmp ne i64 %t74, 0
  br i1 %t75, label %whilebody8, label %whileexit9
whilebody8:
  %t76 = load i64, ptr %t13
  %t77 = trunc i64 %t76 to i32
  %t78 = sext i32 %t77 to i64
  %t79 = trunc i64 2 to i32
  %t80 = sext i32 %t79 to i64
  %t81 = srem i64 %t78, %t80
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 %t83 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = trunc i64 0 to i32
  %t87 = sext i32 %t86 to i64
  %t88 = icmp eq i64 %t85, %t87
  %t89 = zext i1 %t88 to i64
  %t90 = icmp ne i64 %t89, 0
  br i1 %t90, label %then10, label %else11
then10:
  %t91 = load i64, ptr %t3
  %t92 = load i64, ptr %t13
  %t93 = mul i64 %t92, 1
  %t94 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t93
  %t95 = load i64, ptr %t94
  %t96 = call i64 @hfree(ptr %t2, ptr %t3, i64 %t95)
  %t97 = load i64, ptr %t13
  %t98 = mul i64 %t97, 1
  %t99 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t98
  %t100 = trunc i64 -1 to i32
  %t101 = sext i32 %t100 to i64
  store i64 %t101, ptr %t99
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  %t102 = load i64, ptr %t13
  %t103 = trunc i64 %t102 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = trunc i64 1 to i32
  %t106 = sext i32 %t105 to i64
  %t107 = add i64 %t104, %t106
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = trunc i64 %t109 to i32
  %t111 = sext i32 %t110 to i64
  store i64 %t111, ptr %t13
  br label %while7
whileexit9:
  %t112 = trunc i64 0 to i32
  %t113 = sext i32 %t112 to i64
  store i64 %t113, ptr %t13
  br label %while13
while13:
  %t114 = load i64, ptr %t13
  %t115 = trunc i64 %t114 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 16 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = icmp slt i64 %t116, %t118
  %t120 = zext i1 %t119 to i64
  %t121 = icmp ne i64 %t120, 0
  br i1 %t121, label %whilebody14, label %whileexit15
whilebody14:
  %t122 = load i64, ptr %t3
  %t123 = call i64 @halloc(ptr %t2, ptr %t3)
  %t125 = trunc i64 %t123 to i32
  %t126 = sext i32 %t125 to i64
  store i64 %t126, ptr %t124
  %t127 = load i64, ptr %t124
  %t128 = trunc i64 %t127 to i32
  %t129 = sext i32 %t128 to i64
  %t130 = trunc i64 -1 to i32
  %t131 = sext i32 %t130 to i64
  %t132 = icmp ne i64 %t129, %t131
  %t133 = zext i1 %t132 to i64
  %t134 = icmp ne i64 %t133, 0
  br i1 %t134, label %then16, label %else17
then16:
  %t136 = trunc i64 0 to i32
  %t137 = sext i32 %t136 to i64
  store i64 %t137, ptr %t135
  %t139 = zext i1 0 to i64
  %t140 = trunc i64 %t139 to i32
  %t141 = sext i32 %t140 to i64
  store i64 %t141, ptr %t138
  br label %while19
while19:
  %t142 = load i64, ptr %t135
  %t143 = trunc i64 %t142 to i32
  %t144 = sext i32 %t143 to i64
  %t145 = trunc i64 64 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = icmp slt i64 %t144, %t146
  %t148 = zext i1 %t147 to i64
  %t149 = icmp ne i64 %t148, 0
  br i1 %t149, label %whilebody20, label %whileexit21
whilebody20:
  %t150 = load i64, ptr %t135
  %t151 = mul i64 %t150, 1
  %t152 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t151
  %t153 = load i64, ptr %t152
  %t154 = trunc i64 %t153 to i32
  %t155 = sext i32 %t154 to i64
  %t156 = trunc i64 -1 to i32
  %t157 = sext i32 %t156 to i64
  %t158 = icmp eq i64 %t155, %t157
  %t159 = zext i1 %t158 to i64
  %t160 = load i64, ptr %t138
  %t161 = icmp ne i64 %t160, 0
  %t162 = xor i1 %t161, 1
  %t163 = zext i1 %t162 to i64
  %t164 = icmp ne i64 %t159, 0
  %t165 = icmp ne i64 %t163, 0
  %t166 = and i1 %t164, %t165
  %t167 = zext i1 %t166 to i64
  %t168 = icmp ne i64 %t167, 0
  br i1 %t168, label %then22, label %else23
then22:
  %t169 = load i64, ptr %t124
  %t170 = load i64, ptr %t135
  %t171 = mul i64 %t170, 1
  %t172 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t171
  %t173 = trunc i64 %t169 to i32
  %t174 = sext i32 %t173 to i64
  store i64 %t174, ptr %t172
  %t175 = zext i1 1 to i64
  %t176 = trunc i64 %t175 to i32
  %t177 = sext i32 %t176 to i64
  store i64 %t177, ptr %t138
  br label %ifend24
else23:
  br label %ifend24
ifend24:
  %t178 = load i64, ptr %t135
  %t179 = trunc i64 %t178 to i32
  %t180 = sext i32 %t179 to i64
  %t181 = trunc i64 1 to i32
  %t182 = sext i32 %t181 to i64
  %t183 = add i64 %t180, %t182
  %t184 = trunc i64 %t183 to i32
  %t185 = sext i32 %t184 to i64
  %t186 = trunc i64 %t185 to i32
  %t187 = sext i32 %t186 to i64
  store i64 %t187, ptr %t135
  br label %while19
whileexit21:
  br label %ifend18
else17:
  br label %ifend18
ifend18:
  %t188 = load i64, ptr %t13
  %t189 = trunc i64 %t188 to i32
  %t190 = sext i32 %t189 to i64
  %t191 = trunc i64 1 to i32
  %t192 = sext i32 %t191 to i64
  %t193 = add i64 %t190, %t192
  %t194 = trunc i64 %t193 to i32
  %t195 = sext i32 %t194 to i64
  %t196 = trunc i64 %t195 to i32
  %t197 = sext i32 %t196 to i64
  store i64 %t197, ptr %t13
  br label %while13
whileexit15:
  %t199 = trunc i64 0 to i32
  %t200 = sext i32 %t199 to i64
  store i64 %t200, ptr %t198
  %t201 = trunc i64 0 to i32
  %t202 = sext i32 %t201 to i64
  store i64 %t202, ptr %t13
  br label %while25
while25:
  %t203 = load i64, ptr %t13
  %t204 = trunc i64 %t203 to i32
  %t205 = sext i32 %t204 to i64
  %t206 = trunc i64 64 to i32
  %t207 = sext i32 %t206 to i64
  %t208 = icmp slt i64 %t205, %t207
  %t209 = zext i1 %t208 to i64
  %t210 = icmp ne i64 %t209, 0
  br i1 %t210, label %whilebody26, label %whileexit27
whilebody26:
  %t211 = load i64, ptr %t13
  %t212 = mul i64 %t211, 1
  %t213 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t212
  %t214 = load i64, ptr %t213
  %t215 = trunc i64 %t214 to i32
  %t216 = sext i32 %t215 to i64
  %t217 = trunc i64 -1 to i32
  %t218 = sext i32 %t217 to i64
  %t219 = icmp ne i64 %t216, %t218
  %t220 = zext i1 %t219 to i64
  %t221 = icmp ne i64 %t220, 0
  br i1 %t221, label %then28, label %else29
then28:
  %t222 = load i64, ptr %t198
  %t223 = trunc i64 %t222 to i32
  %t224 = sext i32 %t223 to i64
  %t225 = trunc i64 1 to i32
  %t226 = sext i32 %t225 to i64
  %t227 = add i64 %t224, %t226
  %t228 = trunc i64 %t227 to i32
  %t229 = sext i32 %t228 to i64
  %t230 = trunc i64 %t229 to i32
  %t231 = sext i32 %t230 to i64
  store i64 %t231, ptr %t198
  br label %ifend30
else29:
  br label %ifend30
ifend30:
  %t232 = load i64, ptr %t13
  %t233 = trunc i64 %t232 to i32
  %t234 = sext i32 %t233 to i64
  %t235 = trunc i64 1 to i32
  %t236 = sext i32 %t235 to i64
  %t237 = add i64 %t234, %t236
  %t238 = trunc i64 %t237 to i32
  %t239 = sext i32 %t238 to i64
  %t240 = trunc i64 %t239 to i32
  %t241 = sext i32 %t240 to i64
  store i64 %t241, ptr %t13
  br label %while25
whileexit27:
  %t243 = trunc i64 0 to i32
  %t244 = sext i32 %t243 to i64
  store i64 %t244, ptr %t242
  %t245 = load i64, ptr %t198
  %t246 = trunc i64 %t245 to i32
  %t247 = sext i32 %t246 to i64
  %t248 = trunc i64 40 to i32
  %t249 = sext i32 %t248 to i64
  %t250 = icmp sgt i64 %t247, %t249
  %t251 = zext i1 %t250 to i64
  %t252 = icmp ne i64 %t251, 0
  br i1 %t252, label %then31, label %else32
then31:
  %t254 = trunc i64 0 to i32
  %t255 = sext i32 %t254 to i64
  store i64 %t255, ptr %t253
  %t257 = trunc i64 0 to i32
  %t258 = sext i32 %t257 to i64
  store i64 %t258, ptr %t256
  %t259 = load i64, ptr %t3
  %t261 = trunc i64 %t259 to i32
  %t262 = sext i32 %t261 to i64
  store i64 %t262, ptr %t260
  br label %while34
while34:
  %t263 = load i64, ptr %t260
  %t264 = trunc i64 %t263 to i32
  %t265 = sext i32 %t264 to i64
  %t266 = trunc i64 -1 to i32
  %t267 = sext i32 %t266 to i64
  %t268 = icmp ne i64 %t265, %t267
  %t269 = zext i1 %t268 to i64
  %t270 = icmp ne i64 %t269, 0
  br i1 %t270, label %whilebody35, label %whileexit36
whilebody35:
  %t271 = load i64, ptr %t256
  %t272 = trunc i64 %t271 to i32
  %t273 = sext i32 %t272 to i64
  %t274 = trunc i64 1 to i32
  %t275 = sext i32 %t274 to i64
  %t276 = add i64 %t273, %t275
  %t277 = trunc i64 %t276 to i32
  %t278 = sext i32 %t277 to i64
  %t279 = trunc i64 %t278 to i32
  %t280 = sext i32 %t279 to i64
  store i64 %t280, ptr %t256
  %t281 = load i64, ptr %t260
  %t282 = mul i64 %t281, 1
  %t283 = getelementptr [1024 x i64], ptr %t2, i64 0, i64 %t282
  %t284 = load i64, ptr %t283
  %t286 = trunc i64 %t284 to i32
  %t287 = sext i32 %t286 to i64
  store i64 %t287, ptr %t285
  %t288 = load i64, ptr %t285
  %t289 = load i64, ptr %t260
  %t290 = trunc i64 %t289 to i32
  %t291 = sext i32 %t290 to i64
  %t292 = trunc i64 16 to i32
  %t293 = sext i32 %t292 to i64
  %t294 = add i64 %t291, %t293
  %t295 = trunc i64 %t294 to i32
  %t296 = sext i32 %t295 to i64
  %t297 = trunc i64 %t288 to i32
  %t298 = sext i32 %t297 to i64
  %t299 = trunc i64 %t296 to i32
  %t300 = sext i32 %t299 to i64
  %t301 = icmp ne i64 %t298, %t300
  %t302 = zext i1 %t301 to i64
  %t303 = icmp ne i64 %t302, 0
  br i1 %t303, label %then37, label %else38
then37:
  %t304 = load i64, ptr %t256
  %t305 = load i64, ptr %t253
  %t306 = trunc i64 %t304 to i32
  %t307 = sext i32 %t306 to i64
  %t308 = trunc i64 %t305 to i32
  %t309 = sext i32 %t308 to i64
  %t310 = icmp sgt i64 %t307, %t309
  %t311 = zext i1 %t310 to i64
  %t312 = icmp ne i64 %t311, 0
  br i1 %t312, label %then40, label %else41
then40:
  %t313 = load i64, ptr %t256
  %t314 = trunc i64 %t313 to i32
  %t315 = sext i32 %t314 to i64
  store i64 %t315, ptr %t253
  br label %ifend42
else41:
  br label %ifend42
ifend42:
  %t316 = trunc i64 0 to i32
  %t317 = sext i32 %t316 to i64
  store i64 %t317, ptr %t256
  br label %ifend39
else38:
  br label %ifend39
ifend39:
  %t318 = load i64, ptr %t285
  %t319 = trunc i64 %t318 to i32
  %t320 = sext i32 %t319 to i64
  store i64 %t320, ptr %t260
  br label %while34
whileexit36:
  %t321 = load i64, ptr %t6
  %t322 = load i64, ptr %t198
  %t323 = trunc i64 %t321 to i32
  %t324 = sext i32 %t323 to i64
  %t325 = trunc i64 %t322 to i32
  %t326 = sext i32 %t325 to i64
  %t327 = sub i64 %t324, %t326
  %t328 = trunc i64 %t327 to i32
  %t329 = sext i32 %t328 to i64
  %t331 = trunc i64 %t329 to i32
  %t332 = sext i32 %t331 to i64
  store i64 %t332, ptr %t330
  %t333 = load i64, ptr %t330
  %t334 = trunc i64 %t333 to i32
  %t335 = sext i32 %t334 to i64
  %t336 = trunc i64 0 to i32
  %t337 = sext i32 %t336 to i64
  %t338 = icmp sgt i64 %t335, %t337
  %t339 = zext i1 %t338 to i64
  %t340 = icmp ne i64 %t339, 0
  br i1 %t340, label %then43, label %else44
then43:
  %t341 = load i64, ptr %t253
  %t342 = trunc i64 %t341 to i32
  %t343 = sext i32 %t342 to i64
  %t344 = trunc i64 100 to i32
  %t345 = sext i32 %t344 to i64
  %t346 = mul i64 %t343, %t345
  %t347 = trunc i64 %t346 to i32
  %t348 = sext i32 %t347 to i64
  %t349 = load i64, ptr %t330
  %t350 = trunc i64 %t348 to i32
  %t351 = sext i32 %t350 to i64
  %t352 = trunc i64 %t349 to i32
  %t353 = sext i32 %t352 to i64
  %t354 = sdiv i64 %t351, %t353
  %t355 = trunc i64 %t354 to i32
  %t356 = sext i32 %t355 to i64
  %t357 = trunc i64 %t356 to i32
  %t358 = sext i32 %t357 to i64
  store i64 %t358, ptr %t242
  br label %ifend45
else44:
  %t359 = trunc i64 0 to i32
  %t360 = sext i32 %t359 to i64
  store i64 %t360, ptr %t242
  br label %ifend45
ifend45:
  br label %ifend33
else32:
  br label %ifend33
ifend33:
  %t361 = load i64, ptr %t198
  %t362 = trunc i64 %t361 to i32
  %t363 = sext i32 %t362 to i64
  %t364 = trunc i64 48 to i32
  %t365 = sext i32 %t364 to i64
  %t366 = icmp slt i64 %t363, %t365
  %t367 = zext i1 %t366 to i64
  %t368 = icmp ne i64 %t367, 0
  br i1 %t368, label %then46, label %else47
then46:
  %t370 = trunc i64 32 to i32
  %t371 = sext i32 %t370 to i64
  store i64 %t371, ptr %t369
  br label %while49
while49:
  %t372 = load i64, ptr %t369
  %t373 = trunc i64 %t372 to i32
  %t374 = sext i32 %t373 to i64
  %t375 = trunc i64 64 to i32
  %t376 = sext i32 %t375 to i64
  %t377 = icmp slt i64 %t374, %t376
  %t378 = zext i1 %t377 to i64
  %t379 = icmp ne i64 %t378, 0
  br i1 %t379, label %whilebody50, label %whileexit51
whilebody50:
  %t380 = load i64, ptr %t369
  %t381 = trunc i64 %t380 to i32
  %t382 = sext i32 %t381 to i64
  %t383 = trunc i64 3 to i32
  %t384 = sext i32 %t383 to i64
  %t385 = srem i64 %t382, %t384
  %t386 = trunc i64 %t385 to i32
  %t387 = sext i32 %t386 to i64
  %t388 = trunc i64 %t387 to i32
  %t389 = sext i32 %t388 to i64
  %t390 = trunc i64 0 to i32
  %t391 = sext i32 %t390 to i64
  %t392 = icmp eq i64 %t389, %t391
  %t393 = zext i1 %t392 to i64
  %t394 = icmp ne i64 %t393, 0
  br i1 %t394, label %then52, label %else53
then52:
  %t395 = load i64, ptr %t369
  %t396 = mul i64 %t395, 1
  %t397 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t396
  %t398 = load i64, ptr %t397
  %t399 = trunc i64 %t398 to i32
  %t400 = sext i32 %t399 to i64
  %t401 = trunc i64 -1 to i32
  %t402 = sext i32 %t401 to i64
  %t403 = icmp ne i64 %t400, %t402
  %t404 = zext i1 %t403 to i64
  %t405 = icmp ne i64 %t404, 0
  br i1 %t405, label %then55, label %else56
then55:
  %t406 = load i64, ptr %t3
  %t407 = load i64, ptr %t369
  %t408 = mul i64 %t407, 1
  %t409 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t408
  %t410 = load i64, ptr %t409
  %t411 = call i64 @hfree(ptr %t2, ptr %t3, i64 %t410)
  %t412 = load i64, ptr %t369
  %t413 = mul i64 %t412, 1
  %t414 = getelementptr [64 x i64], ptr %t12, i64 0, i64 %t413
  %t415 = trunc i64 -1 to i32
  %t416 = sext i32 %t415 to i64
  store i64 %t416, ptr %t414
  br label %ifend57
else56:
  br label %ifend57
ifend57:
  br label %ifend54
else53:
  br label %ifend54
ifend54:
  %t417 = load i64, ptr %t369
  %t418 = trunc i64 %t417 to i32
  %t419 = sext i32 %t418 to i64
  %t420 = trunc i64 1 to i32
  %t421 = sext i32 %t420 to i64
  %t422 = add i64 %t419, %t421
  %t423 = trunc i64 %t422 to i32
  %t424 = sext i32 %t423 to i64
  %t425 = trunc i64 %t424 to i32
  %t426 = sext i32 %t425 to i64
  store i64 %t426, ptr %t369
  br label %while49
whileexit51:
  br label %ifend48
else47:
  br label %ifend48
ifend48:
  %t428 = trunc i64 0 to i32
  %t429 = sext i32 %t428 to i64
  store i64 %t429, ptr %t427
  %t430 = trunc i64 0 to i32
  %t431 = sext i32 %t430 to i64
  store i64 %t431, ptr %t13
  br label %while58
while58:
  %t432 = load i64, ptr %t13
  %t433 = trunc i64 %t432 to i32
  %t434 = sext i32 %t433 to i64
  %t435 = trunc i64 1024 to i32
  %t436 = sext i32 %t435 to i64
  %t437 = icmp slt i64 %t434, %t436
  %t438 = zext i1 %t437 to i64
  %t439 = icmp ne i64 %t438, 0
  br i1 %t439, label %whilebody59, label %whileexit60
whilebody59:
  %t440 = load i64, ptr %t13
  %t441 = mul i64 %t440, 1
  %t442 = getelementptr [1024 x i64], ptr %t2, i64 0, i64 %t441
  %t443 = load i64, ptr %t442
  %t444 = trunc i64 %t443 to i32
  %t445 = sext i32 %t444 to i64
  %t446 = trunc i64 -2 to i32
  %t447 = sext i32 %t446 to i64
  %t448 = icmp eq i64 %t445, %t447
  %t449 = zext i1 %t448 to i64
  %t450 = icmp ne i64 %t449, 0
  br i1 %t450, label %then61, label %else62
then61:
  %t451 = load i64, ptr %t427
  %t452 = load i64, ptr %t13
  %t453 = trunc i64 %t451 to i32
  %t454 = sext i32 %t453 to i64
  %t455 = trunc i64 %t452 to i32
  %t456 = sext i32 %t455 to i64
  %t457 = add i64 %t454, %t456
  %t458 = trunc i64 %t457 to i32
  %t459 = sext i32 %t458 to i64
  %t460 = trunc i64 %t459 to i32
  %t461 = sext i32 %t460 to i64
  store i64 %t461, ptr %t427
  br label %ifend63
else62:
  br label %ifend63
ifend63:
  %t462 = load i64, ptr %t13
  %t463 = trunc i64 %t462 to i32
  %t464 = sext i32 %t463 to i64
  %t465 = trunc i64 1 to i32
  %t466 = sext i32 %t465 to i64
  %t467 = add i64 %t464, %t466
  %t468 = trunc i64 %t467 to i32
  %t469 = sext i32 %t468 to i64
  %t470 = trunc i64 %t469 to i32
  %t471 = sext i32 %t470 to i64
  store i64 %t471, ptr %t13
  br label %while58
whileexit60:
  %t472 = load i64, ptr %t242
  %t473 = call i64 @printlnInt(i64 %t472)
  %t474 = load i64, ptr %t427
  %t475 = call i64 @printlnInt(i64 %t474)
  ret i64 0
}

define i64 @init_heap(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t16 = alloca i64
  store i64 0, ptr %t16
  %t19 = alloca i64
  store i64 0, ptr %t19
  %t40 = alloca i64
  store i64 0, ptr %t40
  %t2 = trunc i64 1024 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 16 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  %t7 = load i64, ptr %t1
  %t8 = load i64, ptr %t4
  %t9 = trunc i64 %t7 to i32
  %t10 = sext i32 %t9 to i64
  %t11 = trunc i64 %t8 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = sdiv i64 %t10, %t12
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t17 = trunc i64 %t15 to i32
  %t18 = sext i32 %t17 to i64
  store i64 %t18, ptr %t16
  %t20 = trunc i64 0 to i32
  %t21 = sext i32 %t20 to i64
  store i64 %t21, ptr %t19
  br label %while1
while1:
  %t22 = load i64, ptr %t19
  %t23 = load i64, ptr %t16
  %t24 = trunc i64 %t22 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 %t23 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = icmp slt i64 %t25, %t27
  %t29 = zext i1 %t28 to i64
  %t30 = icmp ne i64 %t29, 0
  br i1 %t30, label %whilebody2, label %whileexit3
whilebody2:
  %t31 = load i64, ptr %t19
  %t32 = load i64, ptr %t4
  %t33 = trunc i64 %t31 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = trunc i64 %t32 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = mul i64 %t34, %t36
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t41 = trunc i64 %t39 to i32
  %t42 = sext i32 %t41 to i64
  store i64 %t42, ptr %t40
  %t43 = load i64, ptr %t19
  %t44 = trunc i64 %t43 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = trunc i64 1 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = add i64 %t45, %t47
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = load i64, ptr %t4
  %t52 = trunc i64 %t50 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 %t51 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = mul i64 %t53, %t55
  %t57 = trunc i64 %t56 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = load i64, ptr %t40
  %t60 = mul i64 %t59, 1
  %t61 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t60
  %t62 = trunc i64 %t58 to i32
  %t63 = sext i32 %t62 to i64
  store i64 %t63, ptr %t61
  %t64 = load i64, ptr %t19
  %t65 = trunc i64 %t64 to i32
  %t66 = sext i32 %t65 to i64
  %t67 = trunc i64 1 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = add i64 %t66, %t68
  %t70 = trunc i64 %t69 to i32
  %t71 = sext i32 %t70 to i64
  %t72 = trunc i64 %t71 to i32
  %t73 = sext i32 %t72 to i64
  store i64 %t73, ptr %t19
  br label %while1
whileexit3:
  %t74 = load i64, ptr %t16
  %t75 = trunc i64 %t74 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = trunc i64 1 to i32
  %t78 = sext i32 %t77 to i64
  %t79 = sub i64 %t76, %t78
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  %t82 = load i64, ptr %t4
  %t83 = trunc i64 %t81 to i32
  %t84 = sext i32 %t83 to i64
  %t85 = trunc i64 %t82 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = mul i64 %t84, %t86
  %t88 = trunc i64 %t87 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = mul i64 %t89, 1
  %t91 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t90
  %t92 = trunc i64 -1 to i32
  %t93 = sext i32 %t92 to i64
  store i64 %t93, ptr %t91
  %t94 = trunc i64 0 to i32
  %t95 = sext i32 %t94 to i64
  store i64 %t95, ptr %p1
  ret i64 0
}

define i64 @halloc(ptr %p0, ptr %p1) {
entry:
  %t10 = alloca i64
  store i64 0, ptr %t10
  %t1 = load i64, ptr %p1
  %t2 = trunc i64 %t1 to i32
  %t3 = sext i32 %t2 to i64
  %t4 = trunc i64 -1 to i32
  %t5 = sext i32 %t4 to i64
  %t6 = icmp eq i64 %t3, %t5
  %t7 = zext i1 %t6 to i64
  %t8 = icmp ne i64 %t7, 0
  br i1 %t8, label %then1, label %else2
then1:
  ret i64 -1
else2:
  br label %ifend3
ifend3:
  %t9 = load i64, ptr %p1
  %t11 = trunc i64 %t9 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  %t13 = load i64, ptr %t10
  %t14 = mul i64 %t13, 1
  %t15 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t14
  %t16 = load i64, ptr %t15
  %t17 = trunc i64 %t16 to i32
  %t18 = sext i32 %t17 to i64
  store i64 %t18, ptr %p1
  %t19 = load i64, ptr %t10
  %t20 = mul i64 %t19, 1
  %t21 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t20
  %t22 = trunc i64 -2 to i32
  %t23 = sext i32 %t22 to i64
  store i64 %t23, ptr %t21
  %t24 = load i64, ptr %t10
  ret i64 %t24
}

define i64 @hfree(ptr %p0, ptr %p1, i64 %p2) {
entry:
  %t1 = alloca i64
  store i64 %p2, ptr %t1
  %t2 = load i64, ptr %p1
  %t3 = load i64, ptr %t1
  %t4 = mul i64 %t3, 1
  %t5 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t4
  %t6 = trunc i64 %t2 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t8 = load i64, ptr %t1
  %t9 = trunc i64 %t8 to i32
  %t10 = sext i32 %t9 to i64
  store i64 %t10, ptr %p1
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

