; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %fib10 = alloca i64
  store i64 0, ptr %fib10
  %poster = alloca i64
  store i64 0, ptr %poster
  %t1 = call i64 @fib(i64 10)
  store i64 %t1, ptr %fib10
  %t2 = load i64, ptr %fib10
  store i64 %t2, ptr %poster
  ret i64 0
}

define i64 @fib(i64 %p0) {
entry:
  %n = alloca i64
  store i64 %p0, ptr %n
  %prev = alloca i64
  store i64 0, ptr %prev
  %curr = alloca i64
  store i64 0, ptr %curr
  %idx = alloca i64
  store i64 0, ptr %idx
  %next = alloca i64
  store i64 0, ptr %next
  %t1 = load i64, ptr %n
  %t2 = icmp sle i64 %t1, 1
  %t3 = zext i1 %t2 to i64
  %t4 = icmp ne i64 %t3, 0
  br i1 %t4, label %then1, label %else2
then1:
  ret i64 0
else2:
  br label %ifend3
ifend3:
  store i64 0, ptr %prev
  store i64 1, ptr %curr
  store i64 2, ptr %idx
  br label %while4
while4:
  %t5 = load i64, ptr %idx
  %t6 = load i64, ptr %n
  %t7 = icmp sle i64 %t5, %t6
  %t8 = zext i1 %t7 to i64
  %t9 = icmp ne i64 %t8, 0
  br i1 %t9, label %whilebody5, label %whileexit6
whilebody5:
  %t10 = load i64, ptr %prev
  %t11 = load i64, ptr %curr
  %t12 = add i64 %t10, %t11
  store i64 %t12, ptr %next
  %t13 = load i64, ptr %curr
  store i64 %t13, ptr %prev
  %t14 = load i64, ptr %next
  store i64 %t14, ptr %curr
  store i64 1, ptr %idx
  br label %while4
whileexit6:
  %t15 = load i64, ptr %curr
  ret i64 %t15
}

@.fmt_int = private constant [5 x i8] c"%ld\0A\00"
@.fmt_in = private constant [4 x i8] c"%ld\00"
declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)

define i64 @printlnInt(i64 %p0) {
entry:
  %fmt = getelementptr [5 x i8], ptr @.fmt_int, i64 0, i64 0
  %r = call i32 (ptr, ...) @printf(ptr %fmt, i64 %p0)
  ret i64 %p0
}

define i64 @getInt() {
entry:
  %tmp = alloca i64
  %fmt = getelementptr [4 x i8], ptr @.fmt_in, i64 0, i64 0
  %r = call i32 (ptr, ...) @scanf(ptr %fmt, ptr %tmp)
  %v = load i64, ptr %tmp
  ret i64 %v
}

define void @exit_rt(i64 %code) {
entry:
  %c = trunc i64 %code to i32
  call void @exit(i32 %c)
  ret void
}

