; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @push_stack(ptr %p0, ptr %p1, i64 %p2) {
entry:
  %t1 = alloca i64
  store i64 %p2, ptr %t1
  %t2 = load i64, ptr %p1
  %t3 = trunc i64 %t2 to i32
  %t4 = sext i32 %t3 to i64
  %t5 = trunc i64 255 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = icmp slt i64 %t4, %t6
  %t8 = zext i1 %t7 to i64
  %t9 = icmp ne i64 %t8, 0
  br i1 %t9, label %then1, label %else2
then1:
  %t10 = load i64, ptr %p1
  %t11 = trunc i64 %t10 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = trunc i64 1 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = add i64 %t12, %t14
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 %t17 to i32
  %t19 = sext i32 %t18 to i64
  store i64 %t19, ptr %p1
  %t20 = load i64, ptr %t1
  %t21 = load i64, ptr %p1
  %t22 = mul i64 %t21, 1
  %t23 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t22
  %t24 = trunc i64 %t20 to i32
  %t25 = sext i32 %t24 to i64
  store i64 %t25, ptr %t23
  br label %ifend3
else2:
  br label %ifend3
ifend3:
  ret i64 0
}

define i64 @pop_stack(ptr %p0, ptr %p1) {
entry:
  %t13 = alloca i64
  store i64 0, ptr %t13
  %t1 = load i64, ptr %p1
  %t2 = trunc i64 %t1 to i32
  %t3 = sext i32 %t2 to i64
  %t4 = trunc i64 -1 to i32
  %t5 = sext i32 %t4 to i64
  %t6 = icmp sgt i64 %t3, %t5
  %t7 = zext i1 %t6 to i64
  %t8 = icmp ne i64 %t7, 0
  br i1 %t8, label %then1, label %else2
then1:
  %t9 = load i64, ptr %p1
  %t10 = mul i64 %t9, 1
  %t11 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t10
  %t12 = load i64, ptr %t11
  %t14 = trunc i64 %t12 to i32
  %t15 = sext i32 %t14 to i64
  store i64 %t15, ptr %t13
  %t16 = load i64, ptr %p1
  %t17 = trunc i64 %t16 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = trunc i64 1 to i32
  %t20 = sext i32 %t19 to i64
  %t21 = sub i64 %t18, %t20
  %t22 = trunc i64 %t21 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  store i64 %t25, ptr %p1
  %t26 = load i64, ptr %t13
  ret i64 %t26
else2:
  br label %ifend3
ifend3:
  ret i64 0
}

define i64 @load_program(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t185 = alloca i64
  store i64 0, ptr %t185
  %t624 = alloca i64
  store i64 0, ptr %t624
  %t650 = alloca i64
  store i64 0, ptr %t650
  %t721 = alloca i64
  store i64 0, ptr %t721
  %t1002 = alloca i64
  store i64 0, ptr %t1002
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t4 = load i64, ptr %t1
  %t5 = mul i64 %t4, 1
  %t6 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t5
  %t7 = trunc i64 1 to i32
  %t8 = sext i32 %t7 to i64
  store i64 %t8, ptr %t6
  %t9 = load i64, ptr %t1
  %t10 = trunc i64 %t9 to i32
  %t11 = sext i32 %t10 to i64
  %t12 = trunc i64 1 to i32
  %t13 = sext i32 %t12 to i64
  %t14 = add i64 %t11, %t13
  %t15 = trunc i64 %t14 to i32
  %t16 = sext i32 %t15 to i64
  %t17 = trunc i64 %t16 to i32
  %t18 = sext i32 %t17 to i64
  store i64 %t18, ptr %t1
  %t19 = load i64, ptr %t1
  %t20 = mul i64 %t19, 1
  %t21 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t20
  %t22 = trunc i64 10 to i32
  %t23 = sext i32 %t22 to i64
  store i64 %t23, ptr %t21
  %t24 = load i64, ptr %t1
  %t25 = trunc i64 %t24 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 1 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = add i64 %t26, %t28
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = trunc i64 %t31 to i32
  %t33 = sext i32 %t32 to i64
  store i64 %t33, ptr %t1
  %t34 = load i64, ptr %t1
  %t35 = mul i64 %t34, 1
  %t36 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t35
  %t37 = trunc i64 13 to i32
  %t38 = sext i32 %t37 to i64
  store i64 %t38, ptr %t36
  %t39 = load i64, ptr %t1
  %t40 = trunc i64 %t39 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = trunc i64 1 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = add i64 %t41, %t43
  %t45 = trunc i64 %t44 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = trunc i64 %t46 to i32
  %t48 = sext i32 %t47 to i64
  store i64 %t48, ptr %t1
  %t49 = load i64, ptr %t1
  %t50 = mul i64 %t49, 1
  %t51 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t50
  %t52 = trunc i64 256 to i32
  %t53 = sext i32 %t52 to i64
  store i64 %t53, ptr %t51
  %t54 = load i64, ptr %t1
  %t55 = trunc i64 %t54 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = trunc i64 1 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = add i64 %t56, %t58
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  store i64 %t63, ptr %t1
  %t64 = load i64, ptr %t1
  %t65 = mul i64 %t64, 1
  %t66 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t65
  %t67 = trunc i64 1 to i32
  %t68 = sext i32 %t67 to i64
  store i64 %t68, ptr %t66
  %t69 = load i64, ptr %t1
  %t70 = trunc i64 %t69 to i32
  %t71 = sext i32 %t70 to i64
  %t72 = trunc i64 1 to i32
  %t73 = sext i32 %t72 to i64
  %t74 = add i64 %t71, %t73
  %t75 = trunc i64 %t74 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = trunc i64 %t76 to i32
  %t78 = sext i32 %t77 to i64
  store i64 %t78, ptr %t1
  %t79 = load i64, ptr %t1
  %t80 = mul i64 %t79, 1
  %t81 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t80
  %t82 = trunc i64 1 to i32
  %t83 = sext i32 %t82 to i64
  store i64 %t83, ptr %t81
  %t84 = load i64, ptr %t1
  %t85 = trunc i64 %t84 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = trunc i64 1 to i32
  %t88 = sext i32 %t87 to i64
  %t89 = add i64 %t86, %t88
  %t90 = trunc i64 %t89 to i32
  %t91 = sext i32 %t90 to i64
  %t92 = trunc i64 %t91 to i32
  %t93 = sext i32 %t92 to i64
  store i64 %t93, ptr %t1
  %t94 = load i64, ptr %t1
  %t95 = mul i64 %t94, 1
  %t96 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t95
  %t97 = trunc i64 13 to i32
  %t98 = sext i32 %t97 to i64
  store i64 %t98, ptr %t96
  %t99 = load i64, ptr %t1
  %t100 = trunc i64 %t99 to i32
  %t101 = sext i32 %t100 to i64
  %t102 = trunc i64 1 to i32
  %t103 = sext i32 %t102 to i64
  %t104 = add i64 %t101, %t103
  %t105 = trunc i64 %t104 to i32
  %t106 = sext i32 %t105 to i64
  %t107 = trunc i64 %t106 to i32
  %t108 = sext i32 %t107 to i64
  store i64 %t108, ptr %t1
  %t109 = load i64, ptr %t1
  %t110 = mul i64 %t109, 1
  %t111 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t110
  %t112 = trunc i64 257 to i32
  %t113 = sext i32 %t112 to i64
  store i64 %t113, ptr %t111
  %t114 = load i64, ptr %t1
  %t115 = trunc i64 %t114 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 1 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = add i64 %t116, %t118
  %t120 = trunc i64 %t119 to i32
  %t121 = sext i32 %t120 to i64
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  store i64 %t123, ptr %t1
  %t124 = load i64, ptr %t1
  %t125 = mul i64 %t124, 1
  %t126 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t125
  %t127 = trunc i64 1 to i32
  %t128 = sext i32 %t127 to i64
  store i64 %t128, ptr %t126
  %t129 = load i64, ptr %t1
  %t130 = trunc i64 %t129 to i32
  %t131 = sext i32 %t130 to i64
  %t132 = trunc i64 1 to i32
  %t133 = sext i32 %t132 to i64
  %t134 = add i64 %t131, %t133
  %t135 = trunc i64 %t134 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = trunc i64 %t136 to i32
  %t138 = sext i32 %t137 to i64
  store i64 %t138, ptr %t1
  %t139 = load i64, ptr %t1
  %t140 = mul i64 %t139, 1
  %t141 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t140
  %t142 = trunc i64 1 to i32
  %t143 = sext i32 %t142 to i64
  store i64 %t143, ptr %t141
  %t144 = load i64, ptr %t1
  %t145 = trunc i64 %t144 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = trunc i64 1 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = add i64 %t146, %t148
  %t150 = trunc i64 %t149 to i32
  %t151 = sext i32 %t150 to i64
  %t152 = trunc i64 %t151 to i32
  %t153 = sext i32 %t152 to i64
  store i64 %t153, ptr %t1
  %t154 = load i64, ptr %t1
  %t155 = mul i64 %t154, 1
  %t156 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t155
  %t157 = trunc i64 13 to i32
  %t158 = sext i32 %t157 to i64
  store i64 %t158, ptr %t156
  %t159 = load i64, ptr %t1
  %t160 = trunc i64 %t159 to i32
  %t161 = sext i32 %t160 to i64
  %t162 = trunc i64 1 to i32
  %t163 = sext i32 %t162 to i64
  %t164 = add i64 %t161, %t163
  %t165 = trunc i64 %t164 to i32
  %t166 = sext i32 %t165 to i64
  %t167 = trunc i64 %t166 to i32
  %t168 = sext i32 %t167 to i64
  store i64 %t168, ptr %t1
  %t169 = load i64, ptr %t1
  %t170 = mul i64 %t169, 1
  %t171 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t170
  %t172 = trunc i64 258 to i32
  %t173 = sext i32 %t172 to i64
  store i64 %t173, ptr %t171
  %t174 = load i64, ptr %t1
  %t175 = trunc i64 %t174 to i32
  %t176 = sext i32 %t175 to i64
  %t177 = trunc i64 1 to i32
  %t178 = sext i32 %t177 to i64
  %t179 = add i64 %t176, %t178
  %t180 = trunc i64 %t179 to i32
  %t181 = sext i32 %t180 to i64
  %t182 = trunc i64 %t181 to i32
  %t183 = sext i32 %t182 to i64
  store i64 %t183, ptr %t1
  %t184 = load i64, ptr %t1
  %t186 = trunc i64 %t184 to i32
  %t187 = sext i32 %t186 to i64
  store i64 %t187, ptr %t185
  %t188 = load i64, ptr %t1
  %t189 = mul i64 %t188, 1
  %t190 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t189
  %t191 = trunc i64 14 to i32
  %t192 = sext i32 %t191 to i64
  store i64 %t192, ptr %t190
  %t193 = load i64, ptr %t1
  %t194 = trunc i64 %t193 to i32
  %t195 = sext i32 %t194 to i64
  %t196 = trunc i64 1 to i32
  %t197 = sext i32 %t196 to i64
  %t198 = add i64 %t195, %t197
  %t199 = trunc i64 %t198 to i32
  %t200 = sext i32 %t199 to i64
  %t201 = trunc i64 %t200 to i32
  %t202 = sext i32 %t201 to i64
  store i64 %t202, ptr %t1
  %t203 = load i64, ptr %t1
  %t204 = mul i64 %t203, 1
  %t205 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t204
  %t206 = trunc i64 256 to i32
  %t207 = sext i32 %t206 to i64
  store i64 %t207, ptr %t205
  %t208 = load i64, ptr %t1
  %t209 = trunc i64 %t208 to i32
  %t210 = sext i32 %t209 to i64
  %t211 = trunc i64 1 to i32
  %t212 = sext i32 %t211 to i64
  %t213 = add i64 %t210, %t212
  %t214 = trunc i64 %t213 to i32
  %t215 = sext i32 %t214 to i64
  %t216 = trunc i64 %t215 to i32
  %t217 = sext i32 %t216 to i64
  store i64 %t217, ptr %t1
  %t218 = load i64, ptr %t1
  %t219 = mul i64 %t218, 1
  %t220 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t219
  %t221 = trunc i64 1 to i32
  %t222 = sext i32 %t221 to i64
  store i64 %t222, ptr %t220
  %t223 = load i64, ptr %t1
  %t224 = trunc i64 %t223 to i32
  %t225 = sext i32 %t224 to i64
  %t226 = trunc i64 1 to i32
  %t227 = sext i32 %t226 to i64
  %t228 = add i64 %t225, %t227
  %t229 = trunc i64 %t228 to i32
  %t230 = sext i32 %t229 to i64
  %t231 = trunc i64 %t230 to i32
  %t232 = sext i32 %t231 to i64
  store i64 %t232, ptr %t1
  %t233 = load i64, ptr %t1
  %t234 = mul i64 %t233, 1
  %t235 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t234
  %t236 = trunc i64 1 to i32
  %t237 = sext i32 %t236 to i64
  store i64 %t237, ptr %t235
  %t238 = load i64, ptr %t1
  %t239 = trunc i64 %t238 to i32
  %t240 = sext i32 %t239 to i64
  %t241 = trunc i64 1 to i32
  %t242 = sext i32 %t241 to i64
  %t243 = add i64 %t240, %t242
  %t244 = trunc i64 %t243 to i32
  %t245 = sext i32 %t244 to i64
  %t246 = trunc i64 %t245 to i32
  %t247 = sext i32 %t246 to i64
  store i64 %t247, ptr %t1
  %t248 = load i64, ptr %t1
  %t249 = mul i64 %t248, 1
  %t250 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t249
  %t251 = trunc i64 4 to i32
  %t252 = sext i32 %t251 to i64
  store i64 %t252, ptr %t250
  %t253 = load i64, ptr %t1
  %t254 = trunc i64 %t253 to i32
  %t255 = sext i32 %t254 to i64
  %t256 = trunc i64 1 to i32
  %t257 = sext i32 %t256 to i64
  %t258 = add i64 %t255, %t257
  %t259 = trunc i64 %t258 to i32
  %t260 = sext i32 %t259 to i64
  %t261 = trunc i64 %t260 to i32
  %t262 = sext i32 %t261 to i64
  store i64 %t262, ptr %t1
  %t263 = load i64, ptr %t1
  %t264 = mul i64 %t263, 1
  %t265 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t264
  %t266 = trunc i64 15 to i32
  %t267 = sext i32 %t266 to i64
  store i64 %t267, ptr %t265
  %t268 = load i64, ptr %t1
  %t269 = trunc i64 %t268 to i32
  %t270 = sext i32 %t269 to i64
  %t271 = trunc i64 1 to i32
  %t272 = sext i32 %t271 to i64
  %t273 = add i64 %t270, %t272
  %t274 = trunc i64 %t273 to i32
  %t275 = sext i32 %t274 to i64
  %t276 = trunc i64 %t275 to i32
  %t277 = sext i32 %t276 to i64
  store i64 %t277, ptr %t1
  %t278 = load i64, ptr %t1
  %t279 = mul i64 %t278, 1
  %t280 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t279
  %t281 = trunc i64 13 to i32
  %t282 = sext i32 %t281 to i64
  store i64 %t282, ptr %t280
  %t283 = load i64, ptr %t1
  %t284 = trunc i64 %t283 to i32
  %t285 = sext i32 %t284 to i64
  %t286 = trunc i64 1 to i32
  %t287 = sext i32 %t286 to i64
  %t288 = add i64 %t285, %t287
  %t289 = trunc i64 %t288 to i32
  %t290 = sext i32 %t289 to i64
  %t291 = trunc i64 %t290 to i32
  %t292 = sext i32 %t291 to i64
  store i64 %t292, ptr %t1
  %t293 = load i64, ptr %t1
  %t294 = mul i64 %t293, 1
  %t295 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t294
  %t296 = trunc i64 256 to i32
  %t297 = sext i32 %t296 to i64
  store i64 %t297, ptr %t295
  %t298 = load i64, ptr %t1
  %t299 = trunc i64 %t298 to i32
  %t300 = sext i32 %t299 to i64
  %t301 = trunc i64 1 to i32
  %t302 = sext i32 %t301 to i64
  %t303 = add i64 %t300, %t302
  %t304 = trunc i64 %t303 to i32
  %t305 = sext i32 %t304 to i64
  %t306 = trunc i64 %t305 to i32
  %t307 = sext i32 %t306 to i64
  store i64 %t307, ptr %t1
  %t308 = load i64, ptr %t1
  %t309 = mul i64 %t308, 1
  %t310 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t309
  %t311 = trunc i64 9 to i32
  %t312 = sext i32 %t311 to i64
  store i64 %t312, ptr %t310
  %t313 = load i64, ptr %t1
  %t314 = trunc i64 %t313 to i32
  %t315 = sext i32 %t314 to i64
  %t316 = trunc i64 1 to i32
  %t317 = sext i32 %t316 to i64
  %t318 = add i64 %t315, %t317
  %t319 = trunc i64 %t318 to i32
  %t320 = sext i32 %t319 to i64
  %t321 = trunc i64 %t320 to i32
  %t322 = sext i32 %t321 to i64
  store i64 %t322, ptr %t1
  %t323 = load i64, ptr %t1
  %t324 = mul i64 %t323, 1
  %t325 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t324
  %t326 = trunc i64 50 to i32
  %t327 = sext i32 %t326 to i64
  store i64 %t327, ptr %t325
  %t328 = load i64, ptr %t1
  %t329 = trunc i64 %t328 to i32
  %t330 = sext i32 %t329 to i64
  %t331 = trunc i64 1 to i32
  %t332 = sext i32 %t331 to i64
  %t333 = add i64 %t330, %t332
  %t334 = trunc i64 %t333 to i32
  %t335 = sext i32 %t334 to i64
  %t336 = trunc i64 %t335 to i32
  %t337 = sext i32 %t336 to i64
  store i64 %t337, ptr %t1
  %t338 = load i64, ptr %t1
  %t339 = mul i64 %t338, 1
  %t340 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t339
  %t341 = trunc i64 14 to i32
  %t342 = sext i32 %t341 to i64
  store i64 %t342, ptr %t340
  %t343 = load i64, ptr %t1
  %t344 = trunc i64 %t343 to i32
  %t345 = sext i32 %t344 to i64
  %t346 = trunc i64 1 to i32
  %t347 = sext i32 %t346 to i64
  %t348 = add i64 %t345, %t347
  %t349 = trunc i64 %t348 to i32
  %t350 = sext i32 %t349 to i64
  %t351 = trunc i64 %t350 to i32
  %t352 = sext i32 %t351 to i64
  store i64 %t352, ptr %t1
  %t353 = load i64, ptr %t1
  %t354 = mul i64 %t353, 1
  %t355 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t354
  %t356 = trunc i64 257 to i32
  %t357 = sext i32 %t356 to i64
  store i64 %t357, ptr %t355
  %t358 = load i64, ptr %t1
  %t359 = trunc i64 %t358 to i32
  %t360 = sext i32 %t359 to i64
  %t361 = trunc i64 1 to i32
  %t362 = sext i32 %t361 to i64
  %t363 = add i64 %t360, %t362
  %t364 = trunc i64 %t363 to i32
  %t365 = sext i32 %t364 to i64
  %t366 = trunc i64 %t365 to i32
  %t367 = sext i32 %t366 to i64
  store i64 %t367, ptr %t1
  %t368 = load i64, ptr %t1
  %t369 = mul i64 %t368, 1
  %t370 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t369
  %t371 = trunc i64 14 to i32
  %t372 = sext i32 %t371 to i64
  store i64 %t372, ptr %t370
  %t373 = load i64, ptr %t1
  %t374 = trunc i64 %t373 to i32
  %t375 = sext i32 %t374 to i64
  %t376 = trunc i64 1 to i32
  %t377 = sext i32 %t376 to i64
  %t378 = add i64 %t375, %t377
  %t379 = trunc i64 %t378 to i32
  %t380 = sext i32 %t379 to i64
  %t381 = trunc i64 %t380 to i32
  %t382 = sext i32 %t381 to i64
  store i64 %t382, ptr %t1
  %t383 = load i64, ptr %t1
  %t384 = mul i64 %t383, 1
  %t385 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t384
  %t386 = trunc i64 258 to i32
  %t387 = sext i32 %t386 to i64
  store i64 %t387, ptr %t385
  %t388 = load i64, ptr %t1
  %t389 = trunc i64 %t388 to i32
  %t390 = sext i32 %t389 to i64
  %t391 = trunc i64 1 to i32
  %t392 = sext i32 %t391 to i64
  %t393 = add i64 %t390, %t392
  %t394 = trunc i64 %t393 to i32
  %t395 = sext i32 %t394 to i64
  %t396 = trunc i64 %t395 to i32
  %t397 = sext i32 %t396 to i64
  store i64 %t397, ptr %t1
  %t398 = load i64, ptr %t1
  %t399 = mul i64 %t398, 1
  %t400 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t399
  %t401 = trunc i64 3 to i32
  %t402 = sext i32 %t401 to i64
  store i64 %t402, ptr %t400
  %t403 = load i64, ptr %t1
  %t404 = trunc i64 %t403 to i32
  %t405 = sext i32 %t404 to i64
  %t406 = trunc i64 1 to i32
  %t407 = sext i32 %t406 to i64
  %t408 = add i64 %t405, %t407
  %t409 = trunc i64 %t408 to i32
  %t410 = sext i32 %t409 to i64
  %t411 = trunc i64 %t410 to i32
  %t412 = sext i32 %t411 to i64
  store i64 %t412, ptr %t1
  %t413 = load i64, ptr %t1
  %t414 = mul i64 %t413, 1
  %t415 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t414
  %t416 = trunc i64 15 to i32
  %t417 = sext i32 %t416 to i64
  store i64 %t417, ptr %t415
  %t418 = load i64, ptr %t1
  %t419 = trunc i64 %t418 to i32
  %t420 = sext i32 %t419 to i64
  %t421 = trunc i64 1 to i32
  %t422 = sext i32 %t421 to i64
  %t423 = add i64 %t420, %t422
  %t424 = trunc i64 %t423 to i32
  %t425 = sext i32 %t424 to i64
  %t426 = trunc i64 %t425 to i32
  %t427 = sext i32 %t426 to i64
  store i64 %t427, ptr %t1
  %t428 = load i64, ptr %t1
  %t429 = mul i64 %t428, 1
  %t430 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t429
  %t431 = trunc i64 13 to i32
  %t432 = sext i32 %t431 to i64
  store i64 %t432, ptr %t430
  %t433 = load i64, ptr %t1
  %t434 = trunc i64 %t433 to i32
  %t435 = sext i32 %t434 to i64
  %t436 = trunc i64 1 to i32
  %t437 = sext i32 %t436 to i64
  %t438 = add i64 %t435, %t437
  %t439 = trunc i64 %t438 to i32
  %t440 = sext i32 %t439 to i64
  %t441 = trunc i64 %t440 to i32
  %t442 = sext i32 %t441 to i64
  store i64 %t442, ptr %t1
  %t443 = load i64, ptr %t1
  %t444 = mul i64 %t443, 1
  %t445 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t444
  %t446 = trunc i64 257 to i32
  %t447 = sext i32 %t446 to i64
  store i64 %t447, ptr %t445
  %t448 = load i64, ptr %t1
  %t449 = trunc i64 %t448 to i32
  %t450 = sext i32 %t449 to i64
  %t451 = trunc i64 1 to i32
  %t452 = sext i32 %t451 to i64
  %t453 = add i64 %t450, %t452
  %t454 = trunc i64 %t453 to i32
  %t455 = sext i32 %t454 to i64
  %t456 = trunc i64 %t455 to i32
  %t457 = sext i32 %t456 to i64
  store i64 %t457, ptr %t1
  %t458 = load i64, ptr %t1
  %t459 = mul i64 %t458, 1
  %t460 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t459
  %t461 = trunc i64 2 to i32
  %t462 = sext i32 %t461 to i64
  store i64 %t462, ptr %t460
  %t463 = load i64, ptr %t1
  %t464 = trunc i64 %t463 to i32
  %t465 = sext i32 %t464 to i64
  %t466 = trunc i64 1 to i32
  %t467 = sext i32 %t466 to i64
  %t468 = add i64 %t465, %t467
  %t469 = trunc i64 %t468 to i32
  %t470 = sext i32 %t469 to i64
  %t471 = trunc i64 %t470 to i32
  %t472 = sext i32 %t471 to i64
  store i64 %t472, ptr %t1
  %t473 = load i64, ptr %t1
  %t474 = mul i64 %t473, 1
  %t475 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t474
  %t476 = trunc i64 14 to i32
  %t477 = sext i32 %t476 to i64
  store i64 %t477, ptr %t475
  %t478 = load i64, ptr %t1
  %t479 = trunc i64 %t478 to i32
  %t480 = sext i32 %t479 to i64
  %t481 = trunc i64 1 to i32
  %t482 = sext i32 %t481 to i64
  %t483 = add i64 %t480, %t482
  %t484 = trunc i64 %t483 to i32
  %t485 = sext i32 %t484 to i64
  %t486 = trunc i64 %t485 to i32
  %t487 = sext i32 %t486 to i64
  store i64 %t487, ptr %t1
  %t488 = load i64, ptr %t1
  %t489 = mul i64 %t488, 1
  %t490 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t489
  %t491 = trunc i64 257 to i32
  %t492 = sext i32 %t491 to i64
  store i64 %t492, ptr %t490
  %t493 = load i64, ptr %t1
  %t494 = trunc i64 %t493 to i32
  %t495 = sext i32 %t494 to i64
  %t496 = trunc i64 1 to i32
  %t497 = sext i32 %t496 to i64
  %t498 = add i64 %t495, %t497
  %t499 = trunc i64 %t498 to i32
  %t500 = sext i32 %t499 to i64
  %t501 = trunc i64 %t500 to i32
  %t502 = sext i32 %t501 to i64
  store i64 %t502, ptr %t1
  %t503 = load i64, ptr %t1
  %t504 = mul i64 %t503, 1
  %t505 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t504
  %t506 = trunc i64 13 to i32
  %t507 = sext i32 %t506 to i64
  store i64 %t507, ptr %t505
  %t508 = load i64, ptr %t1
  %t509 = trunc i64 %t508 to i32
  %t510 = sext i32 %t509 to i64
  %t511 = trunc i64 1 to i32
  %t512 = sext i32 %t511 to i64
  %t513 = add i64 %t510, %t512
  %t514 = trunc i64 %t513 to i32
  %t515 = sext i32 %t514 to i64
  %t516 = trunc i64 %t515 to i32
  %t517 = sext i32 %t516 to i64
  store i64 %t517, ptr %t1
  %t518 = load i64, ptr %t1
  %t519 = mul i64 %t518, 1
  %t520 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t519
  %t521 = trunc i64 258 to i32
  %t522 = sext i32 %t521 to i64
  store i64 %t522, ptr %t520
  %t523 = load i64, ptr %t1
  %t524 = trunc i64 %t523 to i32
  %t525 = sext i32 %t524 to i64
  %t526 = trunc i64 1 to i32
  %t527 = sext i32 %t526 to i64
  %t528 = add i64 %t525, %t527
  %t529 = trunc i64 %t528 to i32
  %t530 = sext i32 %t529 to i64
  %t531 = trunc i64 %t530 to i32
  %t532 = sext i32 %t531 to i64
  store i64 %t532, ptr %t1
  %t533 = load i64, ptr %t1
  %t534 = mul i64 %t533, 1
  %t535 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t534
  %t536 = trunc i64 8 to i32
  %t537 = sext i32 %t536 to i64
  store i64 %t537, ptr %t535
  %t538 = load i64, ptr %t1
  %t539 = trunc i64 %t538 to i32
  %t540 = sext i32 %t539 to i64
  %t541 = trunc i64 1 to i32
  %t542 = sext i32 %t541 to i64
  %t543 = add i64 %t540, %t542
  %t544 = trunc i64 %t543 to i32
  %t545 = sext i32 %t544 to i64
  %t546 = trunc i64 %t545 to i32
  %t547 = sext i32 %t546 to i64
  store i64 %t547, ptr %t1
  %t548 = load i64, ptr %t185
  %t549 = load i64, ptr %t1
  %t550 = mul i64 %t549, 1
  %t551 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t550
  %t552 = trunc i64 %t548 to i32
  %t553 = sext i32 %t552 to i64
  store i64 %t553, ptr %t551
  %t554 = load i64, ptr %t1
  %t555 = trunc i64 %t554 to i32
  %t556 = sext i32 %t555 to i64
  %t557 = trunc i64 1 to i32
  %t558 = sext i32 %t557 to i64
  %t559 = add i64 %t556, %t558
  %t560 = trunc i64 %t559 to i32
  %t561 = sext i32 %t560 to i64
  %t562 = trunc i64 %t561 to i32
  %t563 = sext i32 %t562 to i64
  store i64 %t563, ptr %t1
  %t564 = load i64, ptr %t1
  %t565 = mul i64 %t564, 1
  %t566 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t565
  %t567 = trunc i64 14 to i32
  %t568 = sext i32 %t567 to i64
  store i64 %t568, ptr %t566
  %t569 = load i64, ptr %t1
  %t570 = trunc i64 %t569 to i32
  %t571 = sext i32 %t570 to i64
  %t572 = trunc i64 1 to i32
  %t573 = sext i32 %t572 to i64
  %t574 = add i64 %t571, %t573
  %t575 = trunc i64 %t574 to i32
  %t576 = sext i32 %t575 to i64
  %t577 = trunc i64 %t576 to i32
  %t578 = sext i32 %t577 to i64
  store i64 %t578, ptr %t1
  %t579 = load i64, ptr %t1
  %t580 = mul i64 %t579, 1
  %t581 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t580
  %t582 = trunc i64 258 to i32
  %t583 = sext i32 %t582 to i64
  store i64 %t583, ptr %t581
  %t584 = load i64, ptr %t1
  %t585 = trunc i64 %t584 to i32
  %t586 = sext i32 %t585 to i64
  %t587 = trunc i64 1 to i32
  %t588 = sext i32 %t587 to i64
  %t589 = add i64 %t586, %t588
  %t590 = trunc i64 %t589 to i32
  %t591 = sext i32 %t590 to i64
  %t592 = trunc i64 %t591 to i32
  %t593 = sext i32 %t592 to i64
  store i64 %t593, ptr %t1
  %t594 = load i64, ptr %t1
  %t595 = mul i64 %t594, 1
  %t596 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t595
  %t597 = trunc i64 7 to i32
  %t598 = sext i32 %t597 to i64
  store i64 %t598, ptr %t596
  %t599 = load i64, ptr %t1
  %t600 = trunc i64 %t599 to i32
  %t601 = sext i32 %t600 to i64
  %t602 = trunc i64 1 to i32
  %t603 = sext i32 %t602 to i64
  %t604 = add i64 %t601, %t603
  %t605 = trunc i64 %t604 to i32
  %t606 = sext i32 %t605 to i64
  %t607 = trunc i64 %t606 to i32
  %t608 = sext i32 %t607 to i64
  store i64 %t608, ptr %t1
  %t609 = load i64, ptr %t1
  %t610 = mul i64 %t609, 1
  %t611 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t610
  %t612 = trunc i64 0 to i32
  %t613 = sext i32 %t612 to i64
  store i64 %t613, ptr %t611
  %t614 = load i64, ptr %t1
  %t615 = trunc i64 %t614 to i32
  %t616 = sext i32 %t615 to i64
  %t617 = trunc i64 1 to i32
  %t618 = sext i32 %t617 to i64
  %t619 = add i64 %t616, %t618
  %t620 = trunc i64 %t619 to i32
  %t621 = sext i32 %t620 to i64
  %t622 = trunc i64 %t621 to i32
  %t623 = sext i32 %t622 to i64
  store i64 %t623, ptr %t1
  %t625 = trunc i64 0 to i32
  %t626 = sext i32 %t625 to i64
  store i64 %t626, ptr %t624
  br label %while1
while1:
  %t627 = load i64, ptr %t624
  %t628 = trunc i64 %t627 to i32
  %t629 = sext i32 %t628 to i64
  %t630 = trunc i64 20 to i32
  %t631 = sext i32 %t630 to i64
  %t632 = icmp slt i64 %t629, %t631
  %t633 = zext i1 %t632 to i64
  %t634 = icmp ne i64 %t633, 0
  br i1 %t634, label %whilebody2, label %whileexit3
whilebody2:
  %t635 = load i64, ptr %t624
  %t636 = trunc i64 %t635 to i32
  %t637 = sext i32 %t636 to i64
  %t638 = trunc i64 10 to i32
  %t639 = sext i32 %t638 to i64
  %t640 = mul i64 %t637, %t639
  %t641 = trunc i64 %t640 to i32
  %t642 = sext i32 %t641 to i64
  %t643 = trunc i64 100 to i32
  %t644 = sext i32 %t643 to i64
  %t645 = trunc i64 %t642 to i32
  %t646 = sext i32 %t645 to i64
  %t647 = add i64 %t644, %t646
  %t648 = trunc i64 %t647 to i32
  %t649 = sext i32 %t648 to i64
  %t651 = trunc i64 %t649 to i32
  %t652 = sext i32 %t651 to i64
  store i64 %t652, ptr %t650
  %t653 = load i64, ptr %t650
  %t654 = mul i64 %t653, 1
  %t655 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t654
  %t656 = trunc i64 1 to i32
  %t657 = sext i32 %t656 to i64
  store i64 %t657, ptr %t655
  %t658 = load i64, ptr %t624
  %t659 = load i64, ptr %t650
  %t660 = add i64 %t659, 1
  %t661 = mul i64 %t660, 1
  %t662 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t661
  %t663 = trunc i64 %t658 to i32
  %t664 = sext i32 %t663 to i64
  store i64 %t664, ptr %t662
  %t665 = load i64, ptr %t650
  %t666 = add i64 %t665, 2
  %t667 = mul i64 %t666, 1
  %t668 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t667
  %t669 = trunc i64 1 to i32
  %t670 = sext i32 %t669 to i64
  store i64 %t670, ptr %t668
  %t671 = load i64, ptr %t624
  %t672 = trunc i64 %t671 to i32
  %t673 = sext i32 %t672 to i64
  %t674 = trunc i64 1 to i32
  %t675 = sext i32 %t674 to i64
  %t676 = add i64 %t673, %t675
  %t677 = trunc i64 %t676 to i32
  %t678 = sext i32 %t677 to i64
  %t679 = load i64, ptr %t650
  %t680 = add i64 %t679, 3
  %t681 = mul i64 %t680, 1
  %t682 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t681
  %t683 = trunc i64 %t678 to i32
  %t684 = sext i32 %t683 to i64
  store i64 %t684, ptr %t682
  %t685 = load i64, ptr %t650
  %t686 = add i64 %t685, 4
  %t687 = mul i64 %t686, 1
  %t688 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t687
  %t689 = trunc i64 5 to i32
  %t690 = sext i32 %t689 to i64
  store i64 %t690, ptr %t688
  %t691 = load i64, ptr %t650
  %t692 = add i64 %t691, 5
  %t693 = mul i64 %t692, 1
  %t694 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t693
  %t695 = trunc i64 7 to i32
  %t696 = sext i32 %t695 to i64
  store i64 %t696, ptr %t694
  %t697 = load i64, ptr %t650
  %t698 = add i64 %t697, 6
  %t699 = mul i64 %t698, 1
  %t700 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t699
  %t701 = trunc i64 2 to i32
  %t702 = sext i32 %t701 to i64
  store i64 %t702, ptr %t700
  %t703 = load i64, ptr %t624
  %t704 = trunc i64 %t703 to i32
  %t705 = sext i32 %t704 to i64
  %t706 = trunc i64 1 to i32
  %t707 = sext i32 %t706 to i64
  %t708 = add i64 %t705, %t707
  %t709 = trunc i64 %t708 to i32
  %t710 = sext i32 %t709 to i64
  %t711 = trunc i64 %t710 to i32
  %t712 = sext i32 %t711 to i64
  store i64 %t712, ptr %t624
  br label %while1
whileexit3:
  %t713 = mul i64 99, 1
  %t714 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t713
  %t715 = trunc i64 8 to i32
  %t716 = sext i32 %t715 to i64
  store i64 %t716, ptr %t714
  %t717 = mul i64 100, 1
  %t718 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t717
  %t719 = trunc i64 100 to i32
  %t720 = sext i32 %t719 to i64
  store i64 %t720, ptr %t718
  %t722 = trunc i64 400 to i32
  %t723 = sext i32 %t722 to i64
  store i64 %t723, ptr %t721
  %t724 = load i64, ptr %t721
  %t725 = mul i64 %t724, 1
  %t726 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t725
  %t727 = trunc i64 13 to i32
  %t728 = sext i32 %t727 to i64
  store i64 %t728, ptr %t726
  %t729 = load i64, ptr %t721
  %t730 = trunc i64 %t729 to i32
  %t731 = sext i32 %t730 to i64
  %t732 = trunc i64 1 to i32
  %t733 = sext i32 %t732 to i64
  %t734 = add i64 %t731, %t733
  %t735 = trunc i64 %t734 to i32
  %t736 = sext i32 %t735 to i64
  %t737 = trunc i64 %t736 to i32
  %t738 = sext i32 %t737 to i64
  store i64 %t738, ptr %t721
  %t739 = load i64, ptr %t721
  %t740 = mul i64 %t739, 1
  %t741 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t740
  %t742 = trunc i64 500 to i32
  %t743 = sext i32 %t742 to i64
  store i64 %t743, ptr %t741
  %t744 = load i64, ptr %t721
  %t745 = trunc i64 %t744 to i32
  %t746 = sext i32 %t745 to i64
  %t747 = trunc i64 1 to i32
  %t748 = sext i32 %t747 to i64
  %t749 = add i64 %t746, %t748
  %t750 = trunc i64 %t749 to i32
  %t751 = sext i32 %t750 to i64
  %t752 = trunc i64 %t751 to i32
  %t753 = sext i32 %t752 to i64
  store i64 %t753, ptr %t721
  %t754 = load i64, ptr %t721
  %t755 = mul i64 %t754, 1
  %t756 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t755
  %t757 = trunc i64 14 to i32
  %t758 = sext i32 %t757 to i64
  store i64 %t758, ptr %t756
  %t759 = load i64, ptr %t721
  %t760 = trunc i64 %t759 to i32
  %t761 = sext i32 %t760 to i64
  %t762 = trunc i64 1 to i32
  %t763 = sext i32 %t762 to i64
  %t764 = add i64 %t761, %t763
  %t765 = trunc i64 %t764 to i32
  %t766 = sext i32 %t765 to i64
  %t767 = trunc i64 %t766 to i32
  %t768 = sext i32 %t767 to i64
  store i64 %t768, ptr %t721
  %t769 = load i64, ptr %t721
  %t770 = mul i64 %t769, 1
  %t771 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t770
  %t772 = trunc i64 500 to i32
  %t773 = sext i32 %t772 to i64
  store i64 %t773, ptr %t771
  %t774 = load i64, ptr %t721
  %t775 = trunc i64 %t774 to i32
  %t776 = sext i32 %t775 to i64
  %t777 = trunc i64 1 to i32
  %t778 = sext i32 %t777 to i64
  %t779 = add i64 %t776, %t778
  %t780 = trunc i64 %t779 to i32
  %t781 = sext i32 %t780 to i64
  %t782 = trunc i64 %t781 to i32
  %t783 = sext i32 %t782 to i64
  store i64 %t783, ptr %t721
  %t784 = load i64, ptr %t721
  %t785 = mul i64 %t784, 1
  %t786 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t785
  %t787 = trunc i64 1 to i32
  %t788 = sext i32 %t787 to i64
  store i64 %t788, ptr %t786
  %t789 = load i64, ptr %t721
  %t790 = trunc i64 %t789 to i32
  %t791 = sext i32 %t790 to i64
  %t792 = trunc i64 1 to i32
  %t793 = sext i32 %t792 to i64
  %t794 = add i64 %t791, %t793
  %t795 = trunc i64 %t794 to i32
  %t796 = sext i32 %t795 to i64
  %t797 = trunc i64 %t796 to i32
  %t798 = sext i32 %t797 to i64
  store i64 %t798, ptr %t721
  %t799 = load i64, ptr %t721
  %t800 = mul i64 %t799, 1
  %t801 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t800
  %t802 = trunc i64 1 to i32
  %t803 = sext i32 %t802 to i64
  store i64 %t803, ptr %t801
  %t804 = load i64, ptr %t721
  %t805 = trunc i64 %t804 to i32
  %t806 = sext i32 %t805 to i64
  %t807 = trunc i64 1 to i32
  %t808 = sext i32 %t807 to i64
  %t809 = add i64 %t806, %t808
  %t810 = trunc i64 %t809 to i32
  %t811 = sext i32 %t810 to i64
  %t812 = trunc i64 %t811 to i32
  %t813 = sext i32 %t812 to i64
  store i64 %t813, ptr %t721
  %t814 = load i64, ptr %t721
  %t815 = mul i64 %t814, 1
  %t816 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t815
  %t817 = trunc i64 12 to i32
  %t818 = sext i32 %t817 to i64
  store i64 %t818, ptr %t816
  %t819 = load i64, ptr %t721
  %t820 = trunc i64 %t819 to i32
  %t821 = sext i32 %t820 to i64
  %t822 = trunc i64 1 to i32
  %t823 = sext i32 %t822 to i64
  %t824 = add i64 %t821, %t823
  %t825 = trunc i64 %t824 to i32
  %t826 = sext i32 %t825 to i64
  %t827 = trunc i64 %t826 to i32
  %t828 = sext i32 %t827 to i64
  store i64 %t828, ptr %t721
  %t829 = load i64, ptr %t721
  %t830 = mul i64 %t829, 1
  %t831 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t830
  %t832 = trunc i64 9 to i32
  %t833 = sext i32 %t832 to i64
  store i64 %t833, ptr %t831
  %t834 = load i64, ptr %t721
  %t835 = trunc i64 %t834 to i32
  %t836 = sext i32 %t835 to i64
  %t837 = trunc i64 1 to i32
  %t838 = sext i32 %t837 to i64
  %t839 = add i64 %t836, %t838
  %t840 = trunc i64 %t839 to i32
  %t841 = sext i32 %t840 to i64
  %t842 = trunc i64 %t841 to i32
  %t843 = sext i32 %t842 to i64
  store i64 %t843, ptr %t721
  %t844 = load i64, ptr %t721
  %t845 = trunc i64 %t844 to i32
  %t846 = sext i32 %t845 to i64
  %t847 = trunc i64 12 to i32
  %t848 = sext i32 %t847 to i64
  %t849 = add i64 %t846, %t848
  %t850 = trunc i64 %t849 to i32
  %t851 = sext i32 %t850 to i64
  %t852 = load i64, ptr %t721
  %t853 = mul i64 %t852, 1
  %t854 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t853
  %t855 = trunc i64 %t851 to i32
  %t856 = sext i32 %t855 to i64
  store i64 %t856, ptr %t854
  %t857 = load i64, ptr %t721
  %t858 = trunc i64 %t857 to i32
  %t859 = sext i32 %t858 to i64
  %t860 = trunc i64 1 to i32
  %t861 = sext i32 %t860 to i64
  %t862 = add i64 %t859, %t861
  %t863 = trunc i64 %t862 to i32
  %t864 = sext i32 %t863 to i64
  %t865 = trunc i64 %t864 to i32
  %t866 = sext i32 %t865 to i64
  store i64 %t866, ptr %t721
  %t867 = load i64, ptr %t721
  %t868 = mul i64 %t867, 1
  %t869 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t868
  %t870 = trunc i64 1 to i32
  %t871 = sext i32 %t870 to i64
  store i64 %t871, ptr %t869
  %t872 = load i64, ptr %t721
  %t873 = trunc i64 %t872 to i32
  %t874 = sext i32 %t873 to i64
  %t875 = trunc i64 1 to i32
  %t876 = sext i32 %t875 to i64
  %t877 = add i64 %t874, %t876
  %t878 = trunc i64 %t877 to i32
  %t879 = sext i32 %t878 to i64
  %t880 = trunc i64 %t879 to i32
  %t881 = sext i32 %t880 to i64
  store i64 %t881, ptr %t721
  %t882 = load i64, ptr %t721
  %t883 = mul i64 %t882, 1
  %t884 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t883
  %t885 = trunc i64 1 to i32
  %t886 = sext i32 %t885 to i64
  store i64 %t886, ptr %t884
  %t887 = load i64, ptr %t721
  %t888 = trunc i64 %t887 to i32
  %t889 = sext i32 %t888 to i64
  %t890 = trunc i64 1 to i32
  %t891 = sext i32 %t890 to i64
  %t892 = add i64 %t889, %t891
  %t893 = trunc i64 %t892 to i32
  %t894 = sext i32 %t893 to i64
  %t895 = trunc i64 %t894 to i32
  %t896 = sext i32 %t895 to i64
  store i64 %t896, ptr %t721
  %t897 = load i64, ptr %t721
  %t898 = mul i64 %t897, 1
  %t899 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t898
  %t900 = trunc i64 8 to i32
  %t901 = sext i32 %t900 to i64
  store i64 %t901, ptr %t899
  %t902 = load i64, ptr %t721
  %t903 = trunc i64 %t902 to i32
  %t904 = sext i32 %t903 to i64
  %t905 = trunc i64 1 to i32
  %t906 = sext i32 %t905 to i64
  %t907 = add i64 %t904, %t906
  %t908 = trunc i64 %t907 to i32
  %t909 = sext i32 %t908 to i64
  %t910 = trunc i64 %t909 to i32
  %t911 = sext i32 %t910 to i64
  store i64 %t911, ptr %t721
  %t912 = load i64, ptr %t721
  %t913 = mul i64 %t912, 1
  %t914 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t913
  %t915 = trunc i64 500 to i32
  %t916 = sext i32 %t915 to i64
  store i64 %t916, ptr %t914
  %t917 = load i64, ptr %t721
  %t918 = mul i64 %t917, 1
  %t919 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t918
  %t920 = trunc i64 14 to i32
  %t921 = sext i32 %t920 to i64
  store i64 %t921, ptr %t919
  %t922 = load i64, ptr %t721
  %t923 = trunc i64 %t922 to i32
  %t924 = sext i32 %t923 to i64
  %t925 = trunc i64 1 to i32
  %t926 = sext i32 %t925 to i64
  %t927 = add i64 %t924, %t926
  %t928 = trunc i64 %t927 to i32
  %t929 = sext i32 %t928 to i64
  %t930 = trunc i64 %t929 to i32
  %t931 = sext i32 %t930 to i64
  store i64 %t931, ptr %t721
  %t932 = load i64, ptr %t721
  %t933 = mul i64 %t932, 1
  %t934 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t933
  %t935 = trunc i64 500 to i32
  %t936 = sext i32 %t935 to i64
  store i64 %t936, ptr %t934
  %t937 = load i64, ptr %t721
  %t938 = trunc i64 %t937 to i32
  %t939 = sext i32 %t938 to i64
  %t940 = trunc i64 1 to i32
  %t941 = sext i32 %t940 to i64
  %t942 = add i64 %t939, %t941
  %t943 = trunc i64 %t942 to i32
  %t944 = sext i32 %t943 to i64
  %t945 = trunc i64 %t944 to i32
  %t946 = sext i32 %t945 to i64
  store i64 %t946, ptr %t721
  %t947 = load i64, ptr %t721
  %t948 = mul i64 %t947, 1
  %t949 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t948
  %t950 = trunc i64 1 to i32
  %t951 = sext i32 %t950 to i64
  store i64 %t951, ptr %t949
  %t952 = load i64, ptr %t721
  %t953 = trunc i64 %t952 to i32
  %t954 = sext i32 %t953 to i64
  %t955 = trunc i64 1 to i32
  %t956 = sext i32 %t955 to i64
  %t957 = add i64 %t954, %t956
  %t958 = trunc i64 %t957 to i32
  %t959 = sext i32 %t958 to i64
  %t960 = trunc i64 %t959 to i32
  %t961 = sext i32 %t960 to i64
  store i64 %t961, ptr %t721
  %t962 = load i64, ptr %t721
  %t963 = mul i64 %t962, 1
  %t964 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t963
  %t965 = trunc i64 1 to i32
  %t966 = sext i32 %t965 to i64
  store i64 %t966, ptr %t964
  %t967 = load i64, ptr %t721
  %t968 = trunc i64 %t967 to i32
  %t969 = sext i32 %t968 to i64
  %t970 = trunc i64 1 to i32
  %t971 = sext i32 %t970 to i64
  %t972 = add i64 %t969, %t971
  %t973 = trunc i64 %t972 to i32
  %t974 = sext i32 %t973 to i64
  %t975 = trunc i64 %t974 to i32
  %t976 = sext i32 %t975 to i64
  store i64 %t976, ptr %t721
  %t977 = load i64, ptr %t721
  %t978 = mul i64 %t977, 1
  %t979 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t978
  %t980 = trunc i64 4 to i32
  %t981 = sext i32 %t980 to i64
  store i64 %t981, ptr %t979
  %t982 = load i64, ptr %t721
  %t983 = trunc i64 %t982 to i32
  %t984 = sext i32 %t983 to i64
  %t985 = trunc i64 1 to i32
  %t986 = sext i32 %t985 to i64
  %t987 = add i64 %t984, %t986
  %t988 = trunc i64 %t987 to i32
  %t989 = sext i32 %t988 to i64
  %t990 = trunc i64 %t989 to i32
  %t991 = sext i32 %t990 to i64
  store i64 %t991, ptr %t721
  %t992 = load i64, ptr %t721
  %t993 = mul i64 %t992, 1
  %t994 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t993
  %t995 = trunc i64 8 to i32
  %t996 = sext i32 %t995 to i64
  store i64 %t996, ptr %t994
  %t997 = load i64, ptr %t721
  %t998 = mul i64 %t997, 1
  %t999 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t998
  %t1000 = trunc i64 400 to i32
  %t1001 = sext i32 %t1000 to i64
  store i64 %t1001, ptr %t999
  %t1003 = trunc i64 600 to i32
  %t1004 = sext i32 %t1003 to i64
  store i64 %t1004, ptr %t1002
  %t1005 = load i64, ptr %t1002
  %t1006 = mul i64 %t1005, 1
  %t1007 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1006
  %t1008 = trunc i64 13 to i32
  %t1009 = sext i32 %t1008 to i64
  store i64 %t1009, ptr %t1007
  %t1010 = load i64, ptr %t1002
  %t1011 = trunc i64 %t1010 to i32
  %t1012 = sext i32 %t1011 to i64
  %t1013 = trunc i64 1 to i32
  %t1014 = sext i32 %t1013 to i64
  %t1015 = add i64 %t1012, %t1014
  %t1016 = trunc i64 %t1015 to i32
  %t1017 = sext i32 %t1016 to i64
  %t1018 = trunc i64 %t1017 to i32
  %t1019 = sext i32 %t1018 to i64
  store i64 %t1019, ptr %t1002
  %t1020 = load i64, ptr %t1002
  %t1021 = mul i64 %t1020, 1
  %t1022 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1021
  %t1023 = trunc i64 700 to i32
  %t1024 = sext i32 %t1023 to i64
  store i64 %t1024, ptr %t1022
  %t1025 = load i64, ptr %t1002
  %t1026 = trunc i64 %t1025 to i32
  %t1027 = sext i32 %t1026 to i64
  %t1028 = trunc i64 1 to i32
  %t1029 = sext i32 %t1028 to i64
  %t1030 = add i64 %t1027, %t1029
  %t1031 = trunc i64 %t1030 to i32
  %t1032 = sext i32 %t1031 to i64
  %t1033 = trunc i64 %t1032 to i32
  %t1034 = sext i32 %t1033 to i64
  store i64 %t1034, ptr %t1002
  %t1035 = load i64, ptr %t1002
  %t1036 = mul i64 %t1035, 1
  %t1037 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1036
  %t1038 = trunc i64 14 to i32
  %t1039 = sext i32 %t1038 to i64
  store i64 %t1039, ptr %t1037
  %t1040 = load i64, ptr %t1002
  %t1041 = trunc i64 %t1040 to i32
  %t1042 = sext i32 %t1041 to i64
  %t1043 = trunc i64 1 to i32
  %t1044 = sext i32 %t1043 to i64
  %t1045 = add i64 %t1042, %t1044
  %t1046 = trunc i64 %t1045 to i32
  %t1047 = sext i32 %t1046 to i64
  %t1048 = trunc i64 %t1047 to i32
  %t1049 = sext i32 %t1048 to i64
  store i64 %t1049, ptr %t1002
  %t1050 = load i64, ptr %t1002
  %t1051 = mul i64 %t1050, 1
  %t1052 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1051
  %t1053 = trunc i64 700 to i32
  %t1054 = sext i32 %t1053 to i64
  store i64 %t1054, ptr %t1052
  %t1055 = load i64, ptr %t1002
  %t1056 = trunc i64 %t1055 to i32
  %t1057 = sext i32 %t1056 to i64
  %t1058 = trunc i64 1 to i32
  %t1059 = sext i32 %t1058 to i64
  %t1060 = add i64 %t1057, %t1059
  %t1061 = trunc i64 %t1060 to i32
  %t1062 = sext i32 %t1061 to i64
  %t1063 = trunc i64 %t1062 to i32
  %t1064 = sext i32 %t1063 to i64
  store i64 %t1064, ptr %t1002
  %t1065 = load i64, ptr %t1002
  %t1066 = mul i64 %t1065, 1
  %t1067 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1066
  %t1068 = trunc i64 1 to i32
  %t1069 = sext i32 %t1068 to i64
  store i64 %t1069, ptr %t1067
  %t1070 = load i64, ptr %t1002
  %t1071 = trunc i64 %t1070 to i32
  %t1072 = sext i32 %t1071 to i64
  %t1073 = trunc i64 1 to i32
  %t1074 = sext i32 %t1073 to i64
  %t1075 = add i64 %t1072, %t1074
  %t1076 = trunc i64 %t1075 to i32
  %t1077 = sext i32 %t1076 to i64
  %t1078 = trunc i64 %t1077 to i32
  %t1079 = sext i32 %t1078 to i64
  store i64 %t1079, ptr %t1002
  %t1080 = load i64, ptr %t1002
  %t1081 = mul i64 %t1080, 1
  %t1082 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1081
  %t1083 = trunc i64 2 to i32
  %t1084 = sext i32 %t1083 to i64
  store i64 %t1084, ptr %t1082
  %t1085 = load i64, ptr %t1002
  %t1086 = trunc i64 %t1085 to i32
  %t1087 = sext i32 %t1086 to i64
  %t1088 = trunc i64 1 to i32
  %t1089 = sext i32 %t1088 to i64
  %t1090 = add i64 %t1087, %t1089
  %t1091 = trunc i64 %t1090 to i32
  %t1092 = sext i32 %t1091 to i64
  %t1093 = trunc i64 %t1092 to i32
  %t1094 = sext i32 %t1093 to i64
  store i64 %t1094, ptr %t1002
  %t1095 = load i64, ptr %t1002
  %t1096 = mul i64 %t1095, 1
  %t1097 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1096
  %t1098 = trunc i64 12 to i32
  %t1099 = sext i32 %t1098 to i64
  store i64 %t1099, ptr %t1097
  %t1100 = load i64, ptr %t1002
  %t1101 = trunc i64 %t1100 to i32
  %t1102 = sext i32 %t1101 to i64
  %t1103 = trunc i64 1 to i32
  %t1104 = sext i32 %t1103 to i64
  %t1105 = add i64 %t1102, %t1104
  %t1106 = trunc i64 %t1105 to i32
  %t1107 = sext i32 %t1106 to i64
  %t1108 = trunc i64 %t1107 to i32
  %t1109 = sext i32 %t1108 to i64
  store i64 %t1109, ptr %t1002
  %t1110 = load i64, ptr %t1002
  %t1111 = mul i64 %t1110, 1
  %t1112 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1111
  %t1113 = trunc i64 9 to i32
  %t1114 = sext i32 %t1113 to i64
  store i64 %t1114, ptr %t1112
  %t1115 = load i64, ptr %t1002
  %t1116 = trunc i64 %t1115 to i32
  %t1117 = sext i32 %t1116 to i64
  %t1118 = trunc i64 1 to i32
  %t1119 = sext i32 %t1118 to i64
  %t1120 = add i64 %t1117, %t1119
  %t1121 = trunc i64 %t1120 to i32
  %t1122 = sext i32 %t1121 to i64
  %t1123 = trunc i64 %t1122 to i32
  %t1124 = sext i32 %t1123 to i64
  store i64 %t1124, ptr %t1002
  %t1125 = load i64, ptr %t1002
  %t1126 = trunc i64 %t1125 to i32
  %t1127 = sext i32 %t1126 to i64
  %t1128 = trunc i64 4 to i32
  %t1129 = sext i32 %t1128 to i64
  %t1130 = add i64 %t1127, %t1129
  %t1131 = trunc i64 %t1130 to i32
  %t1132 = sext i32 %t1131 to i64
  %t1133 = load i64, ptr %t1002
  %t1134 = mul i64 %t1133, 1
  %t1135 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1134
  %t1136 = trunc i64 %t1132 to i32
  %t1137 = sext i32 %t1136 to i64
  store i64 %t1137, ptr %t1135
  %t1138 = load i64, ptr %t1002
  %t1139 = trunc i64 %t1138 to i32
  %t1140 = sext i32 %t1139 to i64
  %t1141 = trunc i64 1 to i32
  %t1142 = sext i32 %t1141 to i64
  %t1143 = add i64 %t1140, %t1142
  %t1144 = trunc i64 %t1143 to i32
  %t1145 = sext i32 %t1144 to i64
  %t1146 = trunc i64 %t1145 to i32
  %t1147 = sext i32 %t1146 to i64
  store i64 %t1147, ptr %t1002
  %t1148 = load i64, ptr %t1002
  %t1149 = mul i64 %t1148, 1
  %t1150 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1149
  %t1151 = trunc i64 14 to i32
  %t1152 = sext i32 %t1151 to i64
  store i64 %t1152, ptr %t1150
  %t1153 = load i64, ptr %t1002
  %t1154 = trunc i64 %t1153 to i32
  %t1155 = sext i32 %t1154 to i64
  %t1156 = trunc i64 1 to i32
  %t1157 = sext i32 %t1156 to i64
  %t1158 = add i64 %t1155, %t1157
  %t1159 = trunc i64 %t1158 to i32
  %t1160 = sext i32 %t1159 to i64
  %t1161 = trunc i64 %t1160 to i32
  %t1162 = sext i32 %t1161 to i64
  store i64 %t1162, ptr %t1002
  %t1163 = load i64, ptr %t1002
  %t1164 = mul i64 %t1163, 1
  %t1165 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1164
  %t1166 = trunc i64 700 to i32
  %t1167 = sext i32 %t1166 to i64
  store i64 %t1167, ptr %t1165
  %t1168 = load i64, ptr %t1002
  %t1169 = trunc i64 %t1168 to i32
  %t1170 = sext i32 %t1169 to i64
  %t1171 = trunc i64 1 to i32
  %t1172 = sext i32 %t1171 to i64
  %t1173 = add i64 %t1170, %t1172
  %t1174 = trunc i64 %t1173 to i32
  %t1175 = sext i32 %t1174 to i64
  %t1176 = trunc i64 %t1175 to i32
  %t1177 = sext i32 %t1176 to i64
  store i64 %t1177, ptr %t1002
  %t1178 = load i64, ptr %t1002
  %t1179 = mul i64 %t1178, 1
  %t1180 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1179
  %t1181 = trunc i64 8 to i32
  %t1182 = sext i32 %t1181 to i64
  store i64 %t1182, ptr %t1180
  %t1183 = load i64, ptr %t1002
  %t1184 = trunc i64 %t1183 to i32
  %t1185 = sext i32 %t1184 to i64
  %t1186 = trunc i64 1 to i32
  %t1187 = sext i32 %t1186 to i64
  %t1188 = add i64 %t1185, %t1187
  %t1189 = trunc i64 %t1188 to i32
  %t1190 = sext i32 %t1189 to i64
  %t1191 = trunc i64 %t1190 to i32
  %t1192 = sext i32 %t1191 to i64
  store i64 %t1192, ptr %t1002
  %t1193 = load i64, ptr %t1002
  %t1194 = mul i64 %t1193, 1
  %t1195 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1194
  %t1196 = trunc i64 800 to i32
  %t1197 = sext i32 %t1196 to i64
  store i64 %t1197, ptr %t1195
  %t1198 = load i64, ptr %t1002
  %t1199 = mul i64 %t1198, 1
  %t1200 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1199
  %t1201 = trunc i64 14 to i32
  %t1202 = sext i32 %t1201 to i64
  store i64 %t1202, ptr %t1200
  %t1203 = load i64, ptr %t1002
  %t1204 = trunc i64 %t1203 to i32
  %t1205 = sext i32 %t1204 to i64
  %t1206 = trunc i64 1 to i32
  %t1207 = sext i32 %t1206 to i64
  %t1208 = add i64 %t1205, %t1207
  %t1209 = trunc i64 %t1208 to i32
  %t1210 = sext i32 %t1209 to i64
  %t1211 = trunc i64 %t1210 to i32
  %t1212 = sext i32 %t1211 to i64
  store i64 %t1212, ptr %t1002
  %t1213 = load i64, ptr %t1002
  %t1214 = mul i64 %t1213, 1
  %t1215 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1214
  %t1216 = trunc i64 700 to i32
  %t1217 = sext i32 %t1216 to i64
  store i64 %t1217, ptr %t1215
  %t1218 = load i64, ptr %t1002
  %t1219 = trunc i64 %t1218 to i32
  %t1220 = sext i32 %t1219 to i64
  %t1221 = trunc i64 1 to i32
  %t1222 = sext i32 %t1221 to i64
  %t1223 = add i64 %t1220, %t1222
  %t1224 = trunc i64 %t1223 to i32
  %t1225 = sext i32 %t1224 to i64
  %t1226 = trunc i64 %t1225 to i32
  %t1227 = sext i32 %t1226 to i64
  store i64 %t1227, ptr %t1002
  %t1228 = load i64, ptr %t1002
  %t1229 = mul i64 %t1228, 1
  %t1230 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1229
  %t1231 = trunc i64 1 to i32
  %t1232 = sext i32 %t1231 to i64
  store i64 %t1232, ptr %t1230
  %t1233 = load i64, ptr %t1002
  %t1234 = trunc i64 %t1233 to i32
  %t1235 = sext i32 %t1234 to i64
  %t1236 = trunc i64 1 to i32
  %t1237 = sext i32 %t1236 to i64
  %t1238 = add i64 %t1235, %t1237
  %t1239 = trunc i64 %t1238 to i32
  %t1240 = sext i32 %t1239 to i64
  %t1241 = trunc i64 %t1240 to i32
  %t1242 = sext i32 %t1241 to i64
  store i64 %t1242, ptr %t1002
  %t1243 = load i64, ptr %t1002
  %t1244 = mul i64 %t1243, 1
  %t1245 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1244
  %t1246 = trunc i64 1 to i32
  %t1247 = sext i32 %t1246 to i64
  store i64 %t1247, ptr %t1245
  %t1248 = load i64, ptr %t1002
  %t1249 = trunc i64 %t1248 to i32
  %t1250 = sext i32 %t1249 to i64
  %t1251 = trunc i64 1 to i32
  %t1252 = sext i32 %t1251 to i64
  %t1253 = add i64 %t1250, %t1252
  %t1254 = trunc i64 %t1253 to i32
  %t1255 = sext i32 %t1254 to i64
  %t1256 = trunc i64 %t1255 to i32
  %t1257 = sext i32 %t1256 to i64
  store i64 %t1257, ptr %t1002
  %t1258 = load i64, ptr %t1002
  %t1259 = mul i64 %t1258, 1
  %t1260 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1259
  %t1261 = trunc i64 4 to i32
  %t1262 = sext i32 %t1261 to i64
  store i64 %t1262, ptr %t1260
  %t1263 = load i64, ptr %t1002
  %t1264 = trunc i64 %t1263 to i32
  %t1265 = sext i32 %t1264 to i64
  %t1266 = trunc i64 1 to i32
  %t1267 = sext i32 %t1266 to i64
  %t1268 = add i64 %t1265, %t1267
  %t1269 = trunc i64 %t1268 to i32
  %t1270 = sext i32 %t1269 to i64
  %t1271 = trunc i64 %t1270 to i32
  %t1272 = sext i32 %t1271 to i64
  store i64 %t1272, ptr %t1002
  %t1273 = load i64, ptr %t1002
  %t1274 = mul i64 %t1273, 1
  %t1275 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1274
  %t1276 = trunc i64 8 to i32
  %t1277 = sext i32 %t1276 to i64
  store i64 %t1277, ptr %t1275
  %t1278 = load i64, ptr %t1002
  %t1279 = trunc i64 %t1278 to i32
  %t1280 = sext i32 %t1279 to i64
  %t1281 = trunc i64 1 to i32
  %t1282 = sext i32 %t1281 to i64
  %t1283 = add i64 %t1280, %t1282
  %t1284 = trunc i64 %t1283 to i32
  %t1285 = sext i32 %t1284 to i64
  %t1286 = trunc i64 %t1285 to i32
  %t1287 = sext i32 %t1286 to i64
  store i64 %t1287, ptr %t1002
  %t1288 = load i64, ptr %t1002
  %t1289 = mul i64 %t1288, 1
  %t1290 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1289
  %t1291 = trunc i64 600 to i32
  %t1292 = sext i32 %t1291 to i64
  store i64 %t1292, ptr %t1290
  %t1293 = load i64, ptr %t1002
  %t1294 = trunc i64 %t1293 to i32
  %t1295 = sext i32 %t1294 to i64
  %t1296 = trunc i64 1 to i32
  %t1297 = sext i32 %t1296 to i64
  %t1298 = add i64 %t1295, %t1297
  %t1299 = trunc i64 %t1298 to i32
  %t1300 = sext i32 %t1299 to i64
  %t1301 = trunc i64 %t1300 to i32
  %t1302 = sext i32 %t1301 to i64
  store i64 %t1302, ptr %t1002
  %t1303 = load i64, ptr %t1002
  %t1304 = mul i64 %t1303, 1
  %t1305 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1304
  %t1306 = trunc i64 14 to i32
  %t1307 = sext i32 %t1306 to i64
  store i64 %t1307, ptr %t1305
  %t1308 = load i64, ptr %t1002
  %t1309 = trunc i64 %t1308 to i32
  %t1310 = sext i32 %t1309 to i64
  %t1311 = trunc i64 1 to i32
  %t1312 = sext i32 %t1311 to i64
  %t1313 = add i64 %t1310, %t1312
  %t1314 = trunc i64 %t1313 to i32
  %t1315 = sext i32 %t1314 to i64
  %t1316 = trunc i64 %t1315 to i32
  %t1317 = sext i32 %t1316 to i64
  store i64 %t1317, ptr %t1002
  %t1318 = load i64, ptr %t1002
  %t1319 = mul i64 %t1318, 1
  %t1320 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1319
  %t1321 = trunc i64 700 to i32
  %t1322 = sext i32 %t1321 to i64
  store i64 %t1322, ptr %t1320
  %t1323 = load i64, ptr %t1002
  %t1324 = trunc i64 %t1323 to i32
  %t1325 = sext i32 %t1324 to i64
  %t1326 = trunc i64 1 to i32
  %t1327 = sext i32 %t1326 to i64
  %t1328 = add i64 %t1325, %t1327
  %t1329 = trunc i64 %t1328 to i32
  %t1330 = sext i32 %t1329 to i64
  %t1331 = trunc i64 %t1330 to i32
  %t1332 = sext i32 %t1331 to i64
  store i64 %t1332, ptr %t1002
  %t1333 = load i64, ptr %t1002
  %t1334 = mul i64 %t1333, 1
  %t1335 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1334
  %t1336 = trunc i64 1 to i32
  %t1337 = sext i32 %t1336 to i64
  store i64 %t1337, ptr %t1335
  %t1338 = load i64, ptr %t1002
  %t1339 = trunc i64 %t1338 to i32
  %t1340 = sext i32 %t1339 to i64
  %t1341 = trunc i64 1 to i32
  %t1342 = sext i32 %t1341 to i64
  %t1343 = add i64 %t1340, %t1342
  %t1344 = trunc i64 %t1343 to i32
  %t1345 = sext i32 %t1344 to i64
  %t1346 = trunc i64 %t1345 to i32
  %t1347 = sext i32 %t1346 to i64
  store i64 %t1347, ptr %t1002
  %t1348 = load i64, ptr %t1002
  %t1349 = mul i64 %t1348, 1
  %t1350 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1349
  %t1351 = trunc i64 2 to i32
  %t1352 = sext i32 %t1351 to i64
  store i64 %t1352, ptr %t1350
  %t1353 = load i64, ptr %t1002
  %t1354 = trunc i64 %t1353 to i32
  %t1355 = sext i32 %t1354 to i64
  %t1356 = trunc i64 1 to i32
  %t1357 = sext i32 %t1356 to i64
  %t1358 = add i64 %t1355, %t1357
  %t1359 = trunc i64 %t1358 to i32
  %t1360 = sext i32 %t1359 to i64
  %t1361 = trunc i64 %t1360 to i32
  %t1362 = sext i32 %t1361 to i64
  store i64 %t1362, ptr %t1002
  %t1363 = load i64, ptr %t1002
  %t1364 = mul i64 %t1363, 1
  %t1365 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1364
  %t1366 = trunc i64 4 to i32
  %t1367 = sext i32 %t1366 to i64
  store i64 %t1367, ptr %t1365
  %t1368 = load i64, ptr %t1002
  %t1369 = trunc i64 %t1368 to i32
  %t1370 = sext i32 %t1369 to i64
  %t1371 = trunc i64 1 to i32
  %t1372 = sext i32 %t1371 to i64
  %t1373 = add i64 %t1370, %t1372
  %t1374 = trunc i64 %t1373 to i32
  %t1375 = sext i32 %t1374 to i64
  %t1376 = trunc i64 %t1375 to i32
  %t1377 = sext i32 %t1376 to i64
  store i64 %t1377, ptr %t1002
  %t1378 = load i64, ptr %t1002
  %t1379 = mul i64 %t1378, 1
  %t1380 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1379
  %t1381 = trunc i64 8 to i32
  %t1382 = sext i32 %t1381 to i64
  store i64 %t1382, ptr %t1380
  %t1383 = load i64, ptr %t1002
  %t1384 = trunc i64 %t1383 to i32
  %t1385 = sext i32 %t1384 to i64
  %t1386 = trunc i64 1 to i32
  %t1387 = sext i32 %t1386 to i64
  %t1388 = add i64 %t1385, %t1387
  %t1389 = trunc i64 %t1388 to i32
  %t1390 = sext i32 %t1389 to i64
  %t1391 = trunc i64 %t1390 to i32
  %t1392 = sext i32 %t1391 to i64
  store i64 %t1392, ptr %t1002
  %t1393 = load i64, ptr %t1002
  %t1394 = mul i64 %t1393, 1
  %t1395 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1394
  %t1396 = trunc i64 600 to i32
  %t1397 = sext i32 %t1396 to i64
  store i64 %t1397, ptr %t1395
  %t1398 = load i64, ptr %t1002
  %t1399 = trunc i64 %t1398 to i32
  %t1400 = sext i32 %t1399 to i64
  %t1401 = trunc i64 1 to i32
  %t1402 = sext i32 %t1401 to i64
  %t1403 = add i64 %t1400, %t1402
  %t1404 = trunc i64 %t1403 to i32
  %t1405 = sext i32 %t1404 to i64
  %t1406 = trunc i64 %t1405 to i32
  %t1407 = sext i32 %t1406 to i64
  store i64 %t1407, ptr %t1002
  %t1408 = load i64, ptr %t1002
  %t1409 = mul i64 %t1408, 1
  %t1410 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1409
  %t1411 = trunc i64 3 to i32
  %t1412 = sext i32 %t1411 to i64
  store i64 %t1412, ptr %t1410
  %t1413 = load i64, ptr %t1002
  %t1414 = trunc i64 %t1413 to i32
  %t1415 = sext i32 %t1414 to i64
  %t1416 = trunc i64 1 to i32
  %t1417 = sext i32 %t1416 to i64
  %t1418 = add i64 %t1415, %t1417
  %t1419 = trunc i64 %t1418 to i32
  %t1420 = sext i32 %t1419 to i64
  %t1421 = trunc i64 %t1420 to i32
  %t1422 = sext i32 %t1421 to i64
  store i64 %t1422, ptr %t1002
  %t1423 = load i64, ptr %t1002
  %t1424 = mul i64 %t1423, 1
  %t1425 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1424
  %t1426 = trunc i64 8 to i32
  %t1427 = sext i32 %t1426 to i64
  store i64 %t1427, ptr %t1425
  %t1428 = load i64, ptr %t1002
  %t1429 = trunc i64 %t1428 to i32
  %t1430 = sext i32 %t1429 to i64
  %t1431 = trunc i64 1 to i32
  %t1432 = sext i32 %t1431 to i64
  %t1433 = add i64 %t1430, %t1432
  %t1434 = trunc i64 %t1433 to i32
  %t1435 = sext i32 %t1434 to i64
  %t1436 = trunc i64 %t1435 to i32
  %t1437 = sext i32 %t1436 to i64
  store i64 %t1437, ptr %t1002
  %t1438 = load i64, ptr %t1002
  %t1439 = mul i64 %t1438, 1
  %t1440 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t1439
  %t1441 = trunc i64 800 to i32
  %t1442 = sext i32 %t1441 to i64
  store i64 %t1442, ptr %t1440
  ret i64 0
}

define i64 @execute_cycle(ptr %p0, ptr %p1, ptr %p2, ptr %p3, ptr %p4) {
entry:
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t41 = alloca i64
  store i64 0, ptr %t41
  %t74 = alloca i64
  store i64 0, ptr %t74
  %t78 = alloca i64
  store i64 0, ptr %t78
  %t100 = alloca i64
  store i64 0, ptr %t100
  %t104 = alloca i64
  store i64 0, ptr %t104
  %t126 = alloca i64
  store i64 0, ptr %t126
  %t130 = alloca i64
  store i64 0, ptr %t130
  %t152 = alloca i64
  store i64 0, ptr %t152
  %t156 = alloca i64
  store i64 0, ptr %t156
  %t189 = alloca i64
  store i64 0, ptr %t189
  %t217 = alloca i64
  store i64 0, ptr %t217
  %t253 = alloca i64
  store i64 0, ptr %t253
  %t289 = alloca i64
  store i64 0, ptr %t289
  %t293 = alloca i64
  store i64 0, ptr %t293
  %t316 = alloca i64
  store i64 0, ptr %t316
  %t320 = alloca i64
  store i64 0, ptr %t320
  %t346 = alloca i64
  store i64 0, ptr %t346
  %t360 = alloca i64
  store i64 0, ptr %t360
  %t381 = alloca i64
  store i64 0, ptr %t381
  %t398 = alloca i64
  store i64 0, ptr %t398
  %t415 = alloca i64
  store i64 0, ptr %t415
  %t1 = load i64, ptr %p1
  %t2 = mul i64 %t1, 1
  %t3 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t2
  %t4 = load i64, ptr %t3
  %t6 = trunc i64 %t4 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t8 = load i64, ptr %p1
  %t9 = trunc i64 %t8 to i32
  %t10 = sext i32 %t9 to i64
  %t11 = trunc i64 1 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = add i64 %t10, %t12
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  store i64 %t17, ptr %p1
  %t18 = load i64, ptr %t5
  %t19 = trunc i64 %t18 to i32
  %t20 = sext i32 %t19 to i64
  %t21 = trunc i64 0 to i32
  %t22 = sext i32 %t21 to i64
  %t23 = icmp eq i64 %t20, %t22
  %t24 = zext i1 %t23 to i64
  %t25 = icmp ne i64 %t24, 0
  br i1 %t25, label %then1, label %else2
then1:
  %t26 = zext i1 0 to i64
  %t27 = trunc i64 %t26 to i32
  %t28 = sext i32 %t27 to i64
  store i64 %t28, ptr %p4
  br label %ifend3
else2:
  %t29 = load i64, ptr %t5
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = trunc i64 1 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = icmp eq i64 %t31, %t33
  %t35 = zext i1 %t34 to i64
  %t36 = icmp ne i64 %t35, 0
  br i1 %t36, label %then4, label %else5
then4:
  %t37 = load i64, ptr %p1
  %t38 = mul i64 %t37, 1
  %t39 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t38
  %t40 = load i64, ptr %t39
  %t42 = trunc i64 %t40 to i32
  %t43 = sext i32 %t42 to i64
  store i64 %t43, ptr %t41
  %t44 = load i64, ptr %p1
  %t45 = trunc i64 %t44 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = trunc i64 1 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = add i64 %t46, %t48
  %t50 = trunc i64 %t49 to i32
  %t51 = sext i32 %t50 to i64
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  store i64 %t53, ptr %p1
  %t54 = load i64, ptr %t41
  %t55 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t54)
  br label %ifend6
else5:
  %t56 = load i64, ptr %t5
  %t57 = trunc i64 %t56 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = trunc i64 2 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = icmp eq i64 %t58, %t60
  %t62 = zext i1 %t61 to i64
  %t63 = icmp ne i64 %t62, 0
  br i1 %t63, label %then7, label %else8
then7:
  %t64 = call i64 @pop_stack(ptr %p2, ptr %p3)
  br label %ifend9
else8:
  %t65 = load i64, ptr %t5
  %t66 = trunc i64 %t65 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = trunc i64 3 to i32
  %t69 = sext i32 %t68 to i64
  %t70 = icmp eq i64 %t67, %t69
  %t71 = zext i1 %t70 to i64
  %t72 = icmp ne i64 %t71, 0
  br i1 %t72, label %then10, label %else11
then10:
  %t73 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t75 = trunc i64 %t73 to i32
  %t76 = sext i32 %t75 to i64
  store i64 %t76, ptr %t74
  %t77 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t79 = trunc i64 %t77 to i32
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  %t81 = load i64, ptr %t78
  %t82 = load i64, ptr %t74
  %t83 = trunc i64 %t81 to i32
  %t84 = sext i32 %t83 to i64
  %t85 = trunc i64 %t82 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = add i64 %t84, %t86
  %t88 = trunc i64 %t87 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t89)
  br label %ifend12
else11:
  %t91 = load i64, ptr %t5
  %t92 = trunc i64 %t91 to i32
  %t93 = sext i32 %t92 to i64
  %t94 = trunc i64 4 to i32
  %t95 = sext i32 %t94 to i64
  %t96 = icmp eq i64 %t93, %t95
  %t97 = zext i1 %t96 to i64
  %t98 = icmp ne i64 %t97, 0
  br i1 %t98, label %then13, label %else14
then13:
  %t99 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t101 = trunc i64 %t99 to i32
  %t102 = sext i32 %t101 to i64
  store i64 %t102, ptr %t100
  %t103 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t105 = trunc i64 %t103 to i32
  %t106 = sext i32 %t105 to i64
  store i64 %t106, ptr %t104
  %t107 = load i64, ptr %t104
  %t108 = load i64, ptr %t100
  %t109 = trunc i64 %t107 to i32
  %t110 = sext i32 %t109 to i64
  %t111 = trunc i64 %t108 to i32
  %t112 = sext i32 %t111 to i64
  %t113 = sub i64 %t110, %t112
  %t114 = trunc i64 %t113 to i32
  %t115 = sext i32 %t114 to i64
  %t116 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t115)
  br label %ifend15
else14:
  %t117 = load i64, ptr %t5
  %t118 = trunc i64 %t117 to i32
  %t119 = sext i32 %t118 to i64
  %t120 = trunc i64 5 to i32
  %t121 = sext i32 %t120 to i64
  %t122 = icmp eq i64 %t119, %t121
  %t123 = zext i1 %t122 to i64
  %t124 = icmp ne i64 %t123, 0
  br i1 %t124, label %then16, label %else17
then16:
  %t125 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t127 = trunc i64 %t125 to i32
  %t128 = sext i32 %t127 to i64
  store i64 %t128, ptr %t126
  %t129 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t131 = trunc i64 %t129 to i32
  %t132 = sext i32 %t131 to i64
  store i64 %t132, ptr %t130
  %t133 = load i64, ptr %t130
  %t134 = load i64, ptr %t126
  %t135 = trunc i64 %t133 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = trunc i64 %t134 to i32
  %t138 = sext i32 %t137 to i64
  %t139 = mul i64 %t136, %t138
  %t140 = trunc i64 %t139 to i32
  %t141 = sext i32 %t140 to i64
  %t142 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t141)
  br label %ifend18
else17:
  %t143 = load i64, ptr %t5
  %t144 = trunc i64 %t143 to i32
  %t145 = sext i32 %t144 to i64
  %t146 = trunc i64 6 to i32
  %t147 = sext i32 %t146 to i64
  %t148 = icmp eq i64 %t145, %t147
  %t149 = zext i1 %t148 to i64
  %t150 = icmp ne i64 %t149, 0
  br i1 %t150, label %then19, label %else20
then19:
  %t151 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t153 = trunc i64 %t151 to i32
  %t154 = sext i32 %t153 to i64
  store i64 %t154, ptr %t152
  %t155 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t157 = trunc i64 %t155 to i32
  %t158 = sext i32 %t157 to i64
  store i64 %t158, ptr %t156
  %t159 = load i64, ptr %t152
  %t160 = trunc i64 %t159 to i32
  %t161 = sext i32 %t160 to i64
  %t162 = trunc i64 0 to i32
  %t163 = sext i32 %t162 to i64
  %t164 = icmp ne i64 %t161, %t163
  %t165 = zext i1 %t164 to i64
  %t166 = icmp ne i64 %t165, 0
  br i1 %t166, label %then22, label %else23
then22:
  %t167 = load i64, ptr %t156
  %t168 = load i64, ptr %t152
  %t169 = trunc i64 %t167 to i32
  %t170 = sext i32 %t169 to i64
  %t171 = trunc i64 %t168 to i32
  %t172 = sext i32 %t171 to i64
  %t173 = sdiv i64 %t170, %t172
  %t174 = trunc i64 %t173 to i32
  %t175 = sext i32 %t174 to i64
  %t176 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t175)
  br label %ifend24
else23:
  %t177 = zext i1 0 to i64
  %t178 = trunc i64 %t177 to i32
  %t179 = sext i32 %t178 to i64
  store i64 %t179, ptr %p4
  br label %ifend24
ifend24:
  br label %ifend21
else20:
  %t180 = load i64, ptr %t5
  %t181 = trunc i64 %t180 to i32
  %t182 = sext i32 %t181 to i64
  %t183 = trunc i64 7 to i32
  %t184 = sext i32 %t183 to i64
  %t185 = icmp eq i64 %t182, %t184
  %t186 = zext i1 %t185 to i64
  %t187 = icmp ne i64 %t186, 0
  br i1 %t187, label %then25, label %else26
then25:
  %t188 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t190 = trunc i64 %t188 to i32
  %t191 = sext i32 %t190 to i64
  store i64 %t191, ptr %t189
  %t192 = load i64, ptr %t189
  %t193 = call i64 @printlnInt(i64 %t192)
  br label %ifend27
else26:
  %t194 = load i64, ptr %t5
  %t195 = trunc i64 %t194 to i32
  %t196 = sext i32 %t195 to i64
  %t197 = trunc i64 8 to i32
  %t198 = sext i32 %t197 to i64
  %t199 = icmp eq i64 %t196, %t198
  %t200 = zext i1 %t199 to i64
  %t201 = icmp ne i64 %t200, 0
  br i1 %t201, label %then28, label %else29
then28:
  %t202 = load i64, ptr %p1
  %t203 = mul i64 %t202, 1
  %t204 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t203
  %t205 = load i64, ptr %t204
  %t206 = trunc i64 %t205 to i32
  %t207 = sext i32 %t206 to i64
  store i64 %t207, ptr %p1
  br label %ifend30
else29:
  %t208 = load i64, ptr %t5
  %t209 = trunc i64 %t208 to i32
  %t210 = sext i32 %t209 to i64
  %t211 = trunc i64 9 to i32
  %t212 = sext i32 %t211 to i64
  %t213 = icmp eq i64 %t210, %t212
  %t214 = zext i1 %t213 to i64
  %t215 = icmp ne i64 %t214, 0
  br i1 %t215, label %then31, label %else32
then31:
  %t216 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t218 = trunc i64 %t216 to i32
  %t219 = sext i32 %t218 to i64
  store i64 %t219, ptr %t217
  %t220 = load i64, ptr %t217
  %t221 = trunc i64 %t220 to i32
  %t222 = sext i32 %t221 to i64
  %t223 = trunc i64 0 to i32
  %t224 = sext i32 %t223 to i64
  %t225 = icmp eq i64 %t222, %t224
  %t226 = zext i1 %t225 to i64
  %t227 = icmp ne i64 %t226, 0
  br i1 %t227, label %then34, label %else35
then34:
  %t228 = load i64, ptr %p1
  %t229 = mul i64 %t228, 1
  %t230 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t229
  %t231 = load i64, ptr %t230
  %t232 = trunc i64 %t231 to i32
  %t233 = sext i32 %t232 to i64
  store i64 %t233, ptr %p1
  br label %ifend36
else35:
  %t234 = load i64, ptr %p1
  %t235 = trunc i64 %t234 to i32
  %t236 = sext i32 %t235 to i64
  %t237 = trunc i64 1 to i32
  %t238 = sext i32 %t237 to i64
  %t239 = add i64 %t236, %t238
  %t240 = trunc i64 %t239 to i32
  %t241 = sext i32 %t240 to i64
  %t242 = trunc i64 %t241 to i32
  %t243 = sext i32 %t242 to i64
  store i64 %t243, ptr %p1
  br label %ifend36
ifend36:
  br label %ifend33
else32:
  %t244 = load i64, ptr %t5
  %t245 = trunc i64 %t244 to i32
  %t246 = sext i32 %t245 to i64
  %t247 = trunc i64 10 to i32
  %t248 = sext i32 %t247 to i64
  %t249 = icmp eq i64 %t246, %t248
  %t250 = zext i1 %t249 to i64
  %t251 = icmp ne i64 %t250, 0
  br i1 %t251, label %then37, label %else38
then37:
  %t252 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t254 = trunc i64 %t252 to i32
  %t255 = sext i32 %t254 to i64
  store i64 %t255, ptr %t253
  %t256 = load i64, ptr %t253
  %t257 = trunc i64 %t256 to i32
  %t258 = sext i32 %t257 to i64
  %t259 = trunc i64 0 to i32
  %t260 = sext i32 %t259 to i64
  %t261 = icmp ne i64 %t258, %t260
  %t262 = zext i1 %t261 to i64
  %t263 = icmp ne i64 %t262, 0
  br i1 %t263, label %then40, label %else41
then40:
  %t264 = load i64, ptr %p1
  %t265 = mul i64 %t264, 1
  %t266 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t265
  %t267 = load i64, ptr %t266
  %t268 = trunc i64 %t267 to i32
  %t269 = sext i32 %t268 to i64
  store i64 %t269, ptr %p1
  br label %ifend42
else41:
  %t270 = load i64, ptr %p1
  %t271 = trunc i64 %t270 to i32
  %t272 = sext i32 %t271 to i64
  %t273 = trunc i64 1 to i32
  %t274 = sext i32 %t273 to i64
  %t275 = add i64 %t272, %t274
  %t276 = trunc i64 %t275 to i32
  %t277 = sext i32 %t276 to i64
  %t278 = trunc i64 %t277 to i32
  %t279 = sext i32 %t278 to i64
  store i64 %t279, ptr %p1
  br label %ifend42
ifend42:
  br label %ifend39
else38:
  %t280 = load i64, ptr %t5
  %t281 = trunc i64 %t280 to i32
  %t282 = sext i32 %t281 to i64
  %t283 = trunc i64 11 to i32
  %t284 = sext i32 %t283 to i64
  %t285 = icmp eq i64 %t282, %t284
  %t286 = zext i1 %t285 to i64
  %t287 = icmp ne i64 %t286, 0
  br i1 %t287, label %then43, label %else44
then43:
  %t288 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t290 = trunc i64 %t288 to i32
  %t291 = sext i32 %t290 to i64
  store i64 %t291, ptr %t289
  %t292 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t294 = trunc i64 %t292 to i32
  %t295 = sext i32 %t294 to i64
  store i64 %t295, ptr %t293
  %t296 = load i64, ptr %t293
  %t297 = load i64, ptr %t289
  %t298 = trunc i64 %t296 to i32
  %t299 = sext i32 %t298 to i64
  %t300 = trunc i64 %t297 to i32
  %t301 = sext i32 %t300 to i64
  %t302 = icmp eq i64 %t299, %t301
  %t303 = zext i1 %t302 to i64
  %t304 = icmp ne i64 %t303, 0
  br i1 %t304, label %then46, label %else47
then46:
  %t305 = call i64 @push_stack(ptr %p2, ptr %p3, i64 1)
  br label %ifend48
else47:
  %t306 = call i64 @push_stack(ptr %p2, ptr %p3, i64 0)
  br label %ifend48
ifend48:
  br label %ifend45
else44:
  %t307 = load i64, ptr %t5
  %t308 = trunc i64 %t307 to i32
  %t309 = sext i32 %t308 to i64
  %t310 = trunc i64 12 to i32
  %t311 = sext i32 %t310 to i64
  %t312 = icmp eq i64 %t309, %t311
  %t313 = zext i1 %t312 to i64
  %t314 = icmp ne i64 %t313, 0
  br i1 %t314, label %then49, label %else50
then49:
  %t315 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t317 = trunc i64 %t315 to i32
  %t318 = sext i32 %t317 to i64
  store i64 %t318, ptr %t316
  %t319 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t321 = trunc i64 %t319 to i32
  %t322 = sext i32 %t321 to i64
  store i64 %t322, ptr %t320
  %t323 = load i64, ptr %t320
  %t324 = load i64, ptr %t316
  %t325 = trunc i64 %t323 to i32
  %t326 = sext i32 %t325 to i64
  %t327 = trunc i64 %t324 to i32
  %t328 = sext i32 %t327 to i64
  %t329 = icmp slt i64 %t326, %t328
  %t330 = zext i1 %t329 to i64
  %t331 = icmp ne i64 %t330, 0
  br i1 %t331, label %then52, label %else53
then52:
  %t332 = call i64 @push_stack(ptr %p2, ptr %p3, i64 1)
  br label %ifend54
else53:
  %t333 = call i64 @push_stack(ptr %p2, ptr %p3, i64 0)
  br label %ifend54
ifend54:
  br label %ifend51
else50:
  %t334 = load i64, ptr %t5
  %t335 = trunc i64 %t334 to i32
  %t336 = sext i32 %t335 to i64
  %t337 = trunc i64 13 to i32
  %t338 = sext i32 %t337 to i64
  %t339 = icmp eq i64 %t336, %t338
  %t340 = zext i1 %t339 to i64
  %t341 = icmp ne i64 %t340, 0
  br i1 %t341, label %then55, label %else56
then55:
  %t342 = load i64, ptr %p1
  %t343 = mul i64 %t342, 1
  %t344 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t343
  %t345 = load i64, ptr %t344
  %t347 = trunc i64 %t345 to i32
  %t348 = sext i32 %t347 to i64
  store i64 %t348, ptr %t346
  %t349 = load i64, ptr %p1
  %t350 = trunc i64 %t349 to i32
  %t351 = sext i32 %t350 to i64
  %t352 = trunc i64 1 to i32
  %t353 = sext i32 %t352 to i64
  %t354 = add i64 %t351, %t353
  %t355 = trunc i64 %t354 to i32
  %t356 = sext i32 %t355 to i64
  %t357 = trunc i64 %t356 to i32
  %t358 = sext i32 %t357 to i64
  store i64 %t358, ptr %p1
  %t359 = call i64 @pop_stack(ptr %p2, ptr %p3)
  %t361 = trunc i64 %t359 to i32
  %t362 = sext i32 %t361 to i64
  store i64 %t362, ptr %t360
  %t363 = load i64, ptr %t360
  %t364 = load i64, ptr %t346
  %t365 = mul i64 %t364, 1
  %t366 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t365
  %t367 = trunc i64 %t363 to i32
  %t368 = sext i32 %t367 to i64
  store i64 %t368, ptr %t366
  br label %ifend57
else56:
  %t369 = load i64, ptr %t5
  %t370 = trunc i64 %t369 to i32
  %t371 = sext i32 %t370 to i64
  %t372 = trunc i64 14 to i32
  %t373 = sext i32 %t372 to i64
  %t374 = icmp eq i64 %t371, %t373
  %t375 = zext i1 %t374 to i64
  %t376 = icmp ne i64 %t375, 0
  br i1 %t376, label %then58, label %else59
then58:
  %t377 = load i64, ptr %p1
  %t378 = mul i64 %t377, 1
  %t379 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t378
  %t380 = load i64, ptr %t379
  %t382 = trunc i64 %t380 to i32
  %t383 = sext i32 %t382 to i64
  store i64 %t383, ptr %t381
  %t384 = load i64, ptr %p1
  %t385 = trunc i64 %t384 to i32
  %t386 = sext i32 %t385 to i64
  %t387 = trunc i64 1 to i32
  %t388 = sext i32 %t387 to i64
  %t389 = add i64 %t386, %t388
  %t390 = trunc i64 %t389 to i32
  %t391 = sext i32 %t390 to i64
  %t392 = trunc i64 %t391 to i32
  %t393 = sext i32 %t392 to i64
  store i64 %t393, ptr %p1
  %t394 = load i64, ptr %t381
  %t395 = mul i64 %t394, 1
  %t396 = getelementptr [1024 x i64], ptr %p0, i64 0, i64 %t395
  %t397 = load i64, ptr %t396
  %t399 = trunc i64 %t397 to i32
  %t400 = sext i32 %t399 to i64
  store i64 %t400, ptr %t398
  %t401 = load i64, ptr %t398
  %t402 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t401)
  br label %ifend60
else59:
  %t403 = load i64, ptr %t5
  %t404 = trunc i64 %t403 to i32
  %t405 = sext i32 %t404 to i64
  %t406 = trunc i64 15 to i32
  %t407 = sext i32 %t406 to i64
  %t408 = icmp eq i64 %t405, %t407
  %t409 = zext i1 %t408 to i64
  %t410 = icmp ne i64 %t409, 0
  br i1 %t410, label %then61, label %else62
then61:
  %t411 = load i64, ptr %p3
  %t412 = mul i64 %t411, 1
  %t413 = getelementptr [256 x i64], ptr %p2, i64 0, i64 %t412
  %t414 = load i64, ptr %t413
  %t416 = trunc i64 %t414 to i32
  %t417 = sext i32 %t416 to i64
  store i64 %t417, ptr %t415
  %t418 = load i64, ptr %t415
  %t419 = call i64 @push_stack(ptr %p2, ptr %p3, i64 %t418)
  br label %ifend63
else62:
  br label %ifend63
ifend63:
  br label %ifend60
ifend60:
  br label %ifend57
ifend57:
  br label %ifend51
ifend51:
  br label %ifend45
ifend45:
  br label %ifend39
ifend39:
  br label %ifend33
ifend33:
  br label %ifend30
ifend30:
  br label %ifend27
ifend27:
  br label %ifend21
ifend21:
  br label %ifend18
ifend18:
  br label %ifend15
ifend15:
  br label %ifend12
ifend12:
  br label %ifend9
ifend9:
  br label %ifend6
ifend6:
  br label %ifend3
ifend3:
  ret i64 0
}

define i64 @main() {
entry:
  %t2 = alloca [1024 x i64]
  %t4 = alloca [256 x i64]
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t8 = alloca i64
  store i64 0, ptr %t8
  %t11 = alloca i64
  store i64 0, ptr %t11
  %t16 = alloca i64
  store i64 0, ptr %t16
  %t19 = alloca i64
  store i64 0, ptr %t19
  %t51 = alloca i64
  store i64 0, ptr %t51
  %t54 = alloca i64
  store i64 0, ptr %t54
  %t124 = alloca i64
  store i64 0, ptr %t124
  %t127 = alloca i64
  store i64 0, ptr %t127
  %t147 = alloca i64
  store i64 0, ptr %t147
  %t1 = alloca [1024 x i64]
  call void @llvm.memset.p0.i64(ptr %t1, i8 0, i64 8192, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t2, ptr %t1, i64 8192, i1 false)
  %t3 = alloca [256 x i64]
  call void @llvm.memset.p0.i64(ptr %t3, i8 0, i64 2048, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 2048, i1 false)
  %t6 = trunc i64 0 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t9 = trunc i64 -1 to i32
  %t10 = sext i32 %t9 to i64
  store i64 %t10, ptr %t8
  %t12 = zext i1 1 to i64
  %t13 = trunc i64 %t12 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t11
  %t15 = call i64 @load_program(ptr %t2)
  %t17 = trunc i64 0 to i32
  %t18 = sext i32 %t17 to i64
  store i64 %t18, ptr %t16
  %t20 = trunc i64 5000 to i32
  %t21 = sext i32 %t20 to i64
  store i64 %t21, ptr %t19
  br label %while1
while1:
  %t22 = load i64, ptr %t11
  %t23 = icmp ne i64 %t22, 0
  br i1 %t23, label %whilebody2, label %whileexit3
whilebody2:
  %t24 = load i64, ptr %t16
  %t25 = load i64, ptr %t19
  %t26 = trunc i64 %t24 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = trunc i64 %t25 to i32
  %t29 = sext i32 %t28 to i64
  %t30 = icmp sgt i64 %t27, %t29
  %t31 = zext i1 %t30 to i64
  %t32 = icmp ne i64 %t31, 0
  br i1 %t32, label %then4, label %else5
then4:
  br label %whileexit3
else5:
  br label %ifend6
ifend6:
  %t33 = load i64, ptr %t5
  %t34 = load i64, ptr %t8
  %t35 = load i64, ptr %t11
  %t36 = call i64 @execute_cycle(ptr %t2, ptr %t5, ptr %t4, ptr %t8, ptr %t11)
  %t37 = load i64, ptr %t16
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = trunc i64 1 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = add i64 %t39, %t41
  %t43 = trunc i64 %t42 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = trunc i64 %t44 to i32
  %t46 = sext i32 %t45 to i64
  store i64 %t46, ptr %t16
  br label %while1
whileexit3:
  %t47 = load i64, ptr %t16
  %t48 = call i64 @printlnInt(i64 %t47)
  %t49 = load i64, ptr %t8
  %t50 = call i64 @printlnInt(i64 %t49)
  %t52 = trunc i64 0 to i32
  %t53 = sext i32 %t52 to i64
  store i64 %t53, ptr %t51
  %t55 = trunc i64 0 to i32
  %t56 = sext i32 %t55 to i64
  store i64 %t56, ptr %t54
  br label %while7
while7:
  %t57 = load i64, ptr %t51
  %t58 = trunc i64 %t57 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = trunc i64 256 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = icmp slt i64 %t59, %t61
  %t63 = zext i1 %t62 to i64
  %t64 = icmp ne i64 %t63, 0
  br i1 %t64, label %whilebody8, label %whileexit9
whilebody8:
  %t65 = load i64, ptr %t54
  %t66 = load i64, ptr %t51
  %t67 = mul i64 %t66, 1
  %t68 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t67
  %t69 = load i64, ptr %t68
  %t70 = trunc i64 %t65 to i32
  %t71 = sext i32 %t70 to i64
  %t72 = trunc i64 %t69 to i32
  %t73 = sext i32 %t72 to i64
  %t74 = add i64 %t71, %t73
  %t75 = trunc i64 %t74 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = trunc i64 %t76 to i32
  %t78 = sext i32 %t77 to i64
  store i64 %t78, ptr %t54
  %t79 = load i64, ptr %t51
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  %t82 = trunc i64 1 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = add i64 %t81, %t83
  %t85 = trunc i64 %t84 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = trunc i64 %t86 to i32
  %t88 = sext i32 %t87 to i64
  store i64 %t88, ptr %t51
  br label %while7
whileexit9:
  %t89 = load i64, ptr %t54
  %t90 = call i64 @printlnInt(i64 %t89)
  %t91 = trunc i64 100 to i32
  %t92 = sext i32 %t91 to i64
  store i64 %t92, ptr %t5
  %t93 = trunc i64 -1 to i32
  %t94 = sext i32 %t93 to i64
  store i64 %t94, ptr %t8
  %t95 = zext i1 1 to i64
  %t96 = trunc i64 %t95 to i32
  %t97 = sext i32 %t96 to i64
  store i64 %t97, ptr %t11
  %t98 = trunc i64 0 to i32
  %t99 = sext i32 %t98 to i64
  store i64 %t99, ptr %t16
  br label %while10
while10:
  %t100 = load i64, ptr %t11
  %t101 = icmp ne i64 %t100, 0
  br i1 %t101, label %whilebody11, label %whileexit12
whilebody11:
  %t102 = load i64, ptr %t16
  %t103 = trunc i64 %t102 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = trunc i64 100 to i32
  %t106 = sext i32 %t105 to i64
  %t107 = icmp sgt i64 %t104, %t106
  %t108 = zext i1 %t107 to i64
  %t109 = icmp ne i64 %t108, 0
  br i1 %t109, label %then13, label %else14
then13:
  br label %whileexit12
else14:
  br label %ifend15
ifend15:
  %t110 = load i64, ptr %t5
  %t111 = load i64, ptr %t8
  %t112 = load i64, ptr %t11
  %t113 = call i64 @execute_cycle(ptr %t2, ptr %t5, ptr %t4, ptr %t8, ptr %t11)
  %t114 = load i64, ptr %t16
  %t115 = trunc i64 %t114 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 1 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = add i64 %t116, %t118
  %t120 = trunc i64 %t119 to i32
  %t121 = sext i32 %t120 to i64
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  store i64 %t123, ptr %t16
  br label %while10
whileexit12:
  %t125 = trunc i64 1 to i32
  %t126 = sext i32 %t125 to i64
  store i64 %t126, ptr %t124
  %t128 = trunc i64 0 to i32
  %t129 = sext i32 %t128 to i64
  store i64 %t129, ptr %t127
  br label %while16
while16:
  %t130 = load i64, ptr %t127
  %t131 = trunc i64 %t130 to i32
  %t132 = sext i32 %t131 to i64
  %t133 = trunc i64 10 to i32
  %t134 = sext i32 %t133 to i64
  %t135 = icmp slt i64 %t132, %t134
  %t136 = zext i1 %t135 to i64
  %t137 = icmp ne i64 %t136, 0
  br i1 %t137, label %whilebody17, label %whileexit18
whilebody17:
  %t138 = load i64, ptr %t124
  %t139 = load i64, ptr %t127
  %t140 = trunc i64 %t138 to i32
  %t141 = sext i32 %t140 to i64
  %t142 = trunc i64 %t139 to i32
  %t143 = sext i32 %t142 to i64
  %t144 = add i64 %t141, %t143
  %t145 = trunc i64 %t144 to i32
  %t146 = sext i32 %t145 to i64
  %t148 = trunc i64 %t146 to i32
  %t149 = sext i32 %t148 to i64
  store i64 %t149, ptr %t147
  %t150 = load i64, ptr %t127
  %t151 = trunc i64 %t150 to i32
  %t152 = sext i32 %t151 to i64
  %t153 = trunc i64 1 to i32
  %t154 = sext i32 %t153 to i64
  %t155 = add i64 %t152, %t154
  %t156 = trunc i64 %t155 to i32
  %t157 = sext i32 %t156 to i64
  %t158 = trunc i64 %t157 to i32
  %t159 = sext i32 %t158 to i64
  store i64 %t159, ptr %t127
  br label %while16
whileexit18:
  %t160 = load i64, ptr %t124
  %t161 = call i64 @printlnInt(i64 %t160)
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

