; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t2 = alloca [512 x i64]
  %t4 = alloca [512 x i64]
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t9 = alloca i64
  store i64 0, ptr %t9
  %t12 = alloca i64
  store i64 0, ptr %t12
  %t42 = alloca i64
  store i64 0, ptr %t42
  %t48 = alloca i64
  store i64 0, ptr %t48
  %t67 = alloca i64
  store i64 0, ptr %t67
  %t78 = alloca i64
  store i64 0, ptr %t78
  %t143 = alloca i64
  store i64 0, ptr %t143
  %t195 = alloca i64
  store i64 0, ptr %t195
  %t198 = alloca i64
  store i64 0, ptr %t198
  %t1 = alloca [512 x i64]
  call void @llvm.memset.p0.i64(ptr %t1, i8 0, i64 4096, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t2, ptr %t1, i64 4096, i1 false)
  %t3 = alloca [512 x i64]
  call void @llvm.memset.p0.i64(ptr %t3, i8 0, i64 4096, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 4096, i1 false)
  %t6 = trunc i64 0 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t8 = call i64 @generate_input(ptr %t2)
  %t10 = trunc i64 0 to i32
  %t11 = sext i32 %t10 to i64
  store i64 %t11, ptr %t9
  %t13 = trunc i64 128 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t12
  br label %while1
while1:
  %t15 = load i64, ptr %t9
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 512 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = icmp slt i64 %t17, %t19
  %t21 = zext i1 %t20 to i64
  %t22 = icmp ne i64 %t21, 0
  br i1 %t22, label %whilebody2, label %whileexit3
whilebody2:
  %t23 = load i64, ptr %t9
  %t24 = load i64, ptr %t12
  %t25 = trunc i64 %t23 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 %t24 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = icmp sgt i64 %t26, %t28
  %t30 = zext i1 %t29 to i64
  %t31 = icmp ne i64 %t30, 0
  br i1 %t31, label %then4, label %else5
then4:
  %t32 = load i64, ptr %t9
  %t33 = load i64, ptr %t12
  %t34 = trunc i64 %t32 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = trunc i64 %t33 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = sub i64 %t35, %t37
  %t39 = trunc i64 %t38 to i32
  %t40 = sext i32 %t39 to i64
  br label %thencont7
thencont7:
  br label %ifend6
else5:
  br label %elsecont8
elsecont8:
  br label %ifend6
ifend6:
  %t41 = phi i64 [ %t40, %thencont7 ], [ 0, %elsecont8 ]
  %t43 = trunc i64 %t41 to i32
  %t44 = sext i32 %t43 to i64
  store i64 %t44, ptr %t42
  %t45 = load i64, ptr %t9
  %t46 = load i64, ptr %t42
  %t47 = call i64 @find_longest_match(ptr %t2, i64 %t45, i64 %t46)
  %t49 = trunc i64 %t47 to i32
  %t50 = sext i32 %t49 to i64
  store i64 %t50, ptr %t48
  %t51 = load i64, ptr %t48
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 0 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = icmp sgt i64 %t53, %t55
  %t57 = zext i1 %t56 to i64
  %t58 = icmp ne i64 %t57, 0
  br i1 %t58, label %then9, label %else10
then9:
  %t59 = load i64, ptr %t48
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 1000 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = sdiv i64 %t61, %t63
  %t65 = trunc i64 %t64 to i32
  %t66 = sext i32 %t65 to i64
  %t68 = trunc i64 %t66 to i32
  %t69 = sext i32 %t68 to i64
  store i64 %t69, ptr %t67
  %t70 = load i64, ptr %t48
  %t71 = trunc i64 %t70 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = trunc i64 1000 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = srem i64 %t72, %t74
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t79 = trunc i64 %t77 to i32
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  %t81 = load i64, ptr %t5
  %t82 = mul i64 %t81, 1
  %t83 = getelementptr [512 x i64], ptr %t4, i64 0, i64 %t82
  %t84 = trunc i64 1 to i32
  %t85 = sext i32 %t84 to i64
  store i64 %t85, ptr %t83
  %t86 = load i64, ptr %t5
  %t87 = trunc i64 %t86 to i32
  %t88 = sext i32 %t87 to i64
  %t89 = trunc i64 1 to i32
  %t90 = sext i32 %t89 to i64
  %t91 = add i64 %t88, %t90
  %t92 = trunc i64 %t91 to i32
  %t93 = sext i32 %t92 to i64
  %t94 = trunc i64 %t93 to i32
  %t95 = sext i32 %t94 to i64
  store i64 %t95, ptr %t5
  %t96 = load i64, ptr %t67
  %t97 = load i64, ptr %t5
  %t98 = mul i64 %t97, 1
  %t99 = getelementptr [512 x i64], ptr %t4, i64 0, i64 %t98
  %t100 = trunc i64 %t96 to i32
  %t101 = sext i32 %t100 to i64
  store i64 %t101, ptr %t99
  %t102 = load i64, ptr %t5
  %t103 = trunc i64 %t102 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = trunc i64 1 to i32
  %t106 = sext i32 %t105 to i64
  %t107 = add i64 %t104, %t106
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = trunc i64 %t109 to i32
  %t111 = sext i32 %t110 to i64
  store i64 %t111, ptr %t5
  %t112 = load i64, ptr %t78
  %t113 = load i64, ptr %t5
  %t114 = mul i64 %t113, 1
  %t115 = getelementptr [512 x i64], ptr %t4, i64 0, i64 %t114
  %t116 = trunc i64 %t112 to i32
  %t117 = sext i32 %t116 to i64
  store i64 %t117, ptr %t115
  %t118 = load i64, ptr %t5
  %t119 = trunc i64 %t118 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = trunc i64 1 to i32
  %t122 = sext i32 %t121 to i64
  %t123 = add i64 %t120, %t122
  %t124 = trunc i64 %t123 to i32
  %t125 = sext i32 %t124 to i64
  %t126 = trunc i64 %t125 to i32
  %t127 = sext i32 %t126 to i64
  store i64 %t127, ptr %t5
  %t128 = load i64, ptr %t9
  %t129 = load i64, ptr %t78
  %t130 = trunc i64 %t128 to i32
  %t131 = sext i32 %t130 to i64
  %t132 = trunc i64 %t129 to i32
  %t133 = sext i32 %t132 to i64
  %t134 = add i64 %t131, %t133
  %t135 = trunc i64 %t134 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = trunc i64 %t136 to i32
  %t138 = sext i32 %t137 to i64
  store i64 %t138, ptr %t9
  br label %ifend11
else10:
  %t139 = load i64, ptr %t9
  %t140 = mul i64 %t139, 1
  %t141 = getelementptr [512 x i64], ptr %t2, i64 0, i64 %t140
  %t142 = load i64, ptr %t141
  %t144 = trunc i64 %t142 to i32
  %t145 = sext i32 %t144 to i64
  store i64 %t145, ptr %t143
  %t146 = load i64, ptr %t5
  %t147 = trunc i64 %t146 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = trunc i64 510 to i32
  %t150 = sext i32 %t149 to i64
  %t151 = icmp slt i64 %t148, %t150
  %t152 = zext i1 %t151 to i64
  %t153 = icmp ne i64 %t152, 0
  br i1 %t153, label %then12, label %else13
then12:
  %t154 = load i64, ptr %t5
  %t155 = mul i64 %t154, 1
  %t156 = getelementptr [512 x i64], ptr %t4, i64 0, i64 %t155
  %t157 = trunc i64 0 to i32
  %t158 = sext i32 %t157 to i64
  store i64 %t158, ptr %t156
  %t159 = load i64, ptr %t5
  %t160 = trunc i64 %t159 to i32
  %t161 = sext i32 %t160 to i64
  %t162 = trunc i64 1 to i32
  %t163 = sext i32 %t162 to i64
  %t164 = add i64 %t161, %t163
  %t165 = trunc i64 %t164 to i32
  %t166 = sext i32 %t165 to i64
  %t167 = trunc i64 %t166 to i32
  %t168 = sext i32 %t167 to i64
  store i64 %t168, ptr %t5
  br label %ifend14
else13:
  br label %ifend14
ifend14:
  %t169 = load i64, ptr %t143
  %t170 = load i64, ptr %t5
  %t171 = mul i64 %t170, 1
  %t172 = getelementptr [512 x i64], ptr %t4, i64 0, i64 %t171
  %t173 = trunc i64 %t169 to i32
  %t174 = sext i32 %t173 to i64
  store i64 %t174, ptr %t172
  %t175 = load i64, ptr %t5
  %t176 = trunc i64 %t175 to i32
  %t177 = sext i32 %t176 to i64
  %t178 = trunc i64 1 to i32
  %t179 = sext i32 %t178 to i64
  %t180 = add i64 %t177, %t179
  %t181 = trunc i64 %t180 to i32
  %t182 = sext i32 %t181 to i64
  %t183 = trunc i64 %t182 to i32
  %t184 = sext i32 %t183 to i64
  store i64 %t184, ptr %t5
  %t185 = load i64, ptr %t9
  %t186 = trunc i64 %t185 to i32
  %t187 = sext i32 %t186 to i64
  %t188 = trunc i64 1 to i32
  %t189 = sext i32 %t188 to i64
  %t190 = add i64 %t187, %t189
  %t191 = trunc i64 %t190 to i32
  %t192 = sext i32 %t191 to i64
  %t193 = trunc i64 %t192 to i32
  %t194 = sext i32 %t193 to i64
  store i64 %t194, ptr %t9
  br label %ifend11
ifend11:
  br label %while1
whileexit3:
  %t196 = trunc i64 0 to i32
  %t197 = sext i32 %t196 to i64
  store i64 %t197, ptr %t195
  %t199 = trunc i64 0 to i32
  %t200 = sext i32 %t199 to i64
  store i64 %t200, ptr %t198
  br label %while15
while15:
  %t201 = load i64, ptr %t198
  %t202 = load i64, ptr %t5
  %t203 = trunc i64 %t201 to i32
  %t204 = sext i32 %t203 to i64
  %t205 = trunc i64 %t202 to i32
  %t206 = sext i32 %t205 to i64
  %t207 = icmp slt i64 %t204, %t206
  %t208 = zext i1 %t207 to i64
  %t209 = icmp ne i64 %t208, 0
  br i1 %t209, label %whilebody16, label %whileexit17
whilebody16:
  %t210 = load i64, ptr %t195
  %t211 = load i64, ptr %t198
  %t212 = mul i64 %t211, 1
  %t213 = getelementptr [512 x i64], ptr %t4, i64 0, i64 %t212
  %t214 = load i64, ptr %t213
  %t215 = load i64, ptr %t198
  %t216 = trunc i64 %t215 to i32
  %t217 = sext i32 %t216 to i64
  %t218 = trunc i64 1 to i32
  %t219 = sext i32 %t218 to i64
  %t220 = add i64 %t217, %t219
  %t221 = trunc i64 %t220 to i32
  %t222 = sext i32 %t221 to i64
  %t223 = trunc i64 %t214 to i32
  %t224 = sext i32 %t223 to i64
  %t225 = trunc i64 %t222 to i32
  %t226 = sext i32 %t225 to i64
  %t227 = mul i64 %t224, %t226
  %t228 = trunc i64 %t227 to i32
  %t229 = sext i32 %t228 to i64
  %t230 = trunc i64 %t210 to i32
  %t231 = sext i32 %t230 to i64
  %t232 = trunc i64 %t229 to i32
  %t233 = sext i32 %t232 to i64
  %t234 = add i64 %t231, %t233
  %t235 = trunc i64 %t234 to i32
  %t236 = sext i32 %t235 to i64
  %t237 = trunc i64 %t236 to i32
  %t238 = sext i32 %t237 to i64
  store i64 %t238, ptr %t195
  %t239 = load i64, ptr %t198
  %t240 = trunc i64 %t239 to i32
  %t241 = sext i32 %t240 to i64
  %t242 = trunc i64 1 to i32
  %t243 = sext i32 %t242 to i64
  %t244 = add i64 %t241, %t243
  %t245 = trunc i64 %t244 to i32
  %t246 = sext i32 %t245 to i64
  %t247 = trunc i64 %t246 to i32
  %t248 = sext i32 %t247 to i64
  store i64 %t248, ptr %t198
  br label %while15
whileexit17:
  %t249 = load i64, ptr %t195
  %t250 = call i64 @printlnInt(i64 %t249)
  %t251 = load i64, ptr %t5
  %t252 = call i64 @printlnInt(i64 %t251)
  ret i64 0
}

define i64 @generate_input(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 512 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t12 = load i64, ptr %t1
  %t13 = trunc i64 %t12 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = trunc i64 20 to i32
  %t16 = sext i32 %t15 to i64
  %t17 = srem i64 %t14, %t16
  %t18 = trunc i64 %t17 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = trunc i64 %t19 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = trunc i64 10 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = icmp slt i64 %t21, %t23
  %t25 = zext i1 %t24 to i64
  %t26 = icmp ne i64 %t25, 0
  br i1 %t26, label %then4, label %else5
then4:
  %t27 = load i64, ptr %t1
  %t28 = trunc i64 %t27 to i32
  %t29 = sext i32 %t28 to i64
  %t30 = trunc i64 10 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = srem i64 %t29, %t31
  %t33 = trunc i64 %t32 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = trunc i64 %t34 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = trunc i64 65 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = add i64 %t36, %t38
  %t40 = trunc i64 %t39 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = load i64, ptr %t1
  %t43 = mul i64 %t42, 1
  %t44 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t43
  %t45 = trunc i64 %t41 to i32
  %t46 = sext i32 %t45 to i64
  store i64 %t46, ptr %t44
  br label %ifend6
else5:
  %t47 = load i64, ptr %t1
  %t48 = trunc i64 %t47 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = trunc i64 17 to i32
  %t51 = sext i32 %t50 to i64
  %t52 = mul i64 %t49, %t51
  %t53 = trunc i64 %t52 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = trunc i64 %t54 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = trunc i64 15 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = srem i64 %t56, %t58
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 97 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = add i64 %t63, %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = load i64, ptr %t1
  %t70 = mul i64 %t69, 1
  %t71 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t70
  %t72 = trunc i64 %t68 to i32
  %t73 = sext i32 %t72 to i64
  store i64 %t73, ptr %t71
  br label %ifend6
ifend6:
  %t74 = load i64, ptr %t1
  %t75 = trunc i64 %t74 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = trunc i64 1 to i32
  %t78 = sext i32 %t77 to i64
  %t79 = add i64 %t76, %t78
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  store i64 %t83, ptr %t1
  br label %while1
whileexit3:
  %t84 = trunc i64 100 to i32
  %t85 = sext i32 %t84 to i64
  store i64 %t85, ptr %t1
  br label %while7
while7:
  %t86 = load i64, ptr %t1
  %t87 = trunc i64 %t86 to i32
  %t88 = sext i32 %t87 to i64
  %t89 = trunc i64 120 to i32
  %t90 = sext i32 %t89 to i64
  %t91 = icmp slt i64 %t88, %t90
  %t92 = zext i1 %t91 to i64
  %t93 = icmp ne i64 %t92, 0
  br i1 %t93, label %whilebody8, label %whileexit9
whilebody8:
  %t94 = load i64, ptr %t1
  %t95 = sub i64 %t94, 20
  %t96 = mul i64 %t95, 1
  %t97 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t96
  %t98 = load i64, ptr %t97
  %t99 = load i64, ptr %t1
  %t100 = mul i64 %t99, 1
  %t101 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t100
  %t102 = trunc i64 %t98 to i32
  %t103 = sext i32 %t102 to i64
  store i64 %t103, ptr %t101
  %t104 = load i64, ptr %t1
  %t105 = trunc i64 %t104 to i32
  %t106 = sext i32 %t105 to i64
  %t107 = trunc i64 1 to i32
  %t108 = sext i32 %t107 to i64
  %t109 = add i64 %t106, %t108
  %t110 = trunc i64 %t109 to i32
  %t111 = sext i32 %t110 to i64
  %t112 = trunc i64 %t111 to i32
  %t113 = sext i32 %t112 to i64
  store i64 %t113, ptr %t1
  br label %while7
whileexit9:
  %t114 = trunc i64 300 to i32
  %t115 = sext i32 %t114 to i64
  store i64 %t115, ptr %t1
  br label %while10
while10:
  %t116 = load i64, ptr %t1
  %t117 = trunc i64 %t116 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = trunc i64 330 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = icmp slt i64 %t118, %t120
  %t122 = zext i1 %t121 to i64
  %t123 = icmp ne i64 %t122, 0
  br i1 %t123, label %whilebody11, label %whileexit12
whilebody11:
  %t124 = load i64, ptr %t1
  %t125 = sub i64 %t124, 30
  %t126 = mul i64 %t125, 1
  %t127 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t126
  %t128 = load i64, ptr %t127
  %t129 = load i64, ptr %t1
  %t130 = mul i64 %t129, 1
  %t131 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t130
  %t132 = trunc i64 %t128 to i32
  %t133 = sext i32 %t132 to i64
  store i64 %t133, ptr %t131
  %t134 = load i64, ptr %t1
  %t135 = trunc i64 %t134 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = trunc i64 1 to i32
  %t138 = sext i32 %t137 to i64
  %t139 = add i64 %t136, %t138
  %t140 = trunc i64 %t139 to i32
  %t141 = sext i32 %t140 to i64
  %t142 = trunc i64 %t141 to i32
  %t143 = sext i32 %t142 to i64
  store i64 %t143, ptr %t1
  br label %while10
whileexit12:
  ret i64 0
}

define i64 @find_longest_match(ptr %p0, i64 %p1, i64 %p2) {
entry:
  %t1 = alloca i64
  store i64 %p1, ptr %t1
  %t2 = alloca i64
  store i64 %p2, ptr %t2
  %t3 = alloca i64
  store i64 0, ptr %t3
  %t6 = alloca i64
  store i64 0, ptr %t6
  %t9 = alloca i64
  store i64 0, ptr %t9
  %t20 = alloca i64
  store i64 0, ptr %t20
  %t32 = alloca i64
  store i64 0, ptr %t32
  %t4 = trunc i64 0 to i32
  %t5 = sext i32 %t4 to i64
  store i64 %t5, ptr %t3
  %t7 = trunc i64 0 to i32
  %t8 = sext i32 %t7 to i64
  store i64 %t8, ptr %t6
  %t10 = trunc i64 18 to i32
  %t11 = sext i32 %t10 to i64
  store i64 %t11, ptr %t9
  %t12 = load i64, ptr %t1
  %t13 = trunc i64 %t12 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = trunc i64 1 to i32
  %t16 = sext i32 %t15 to i64
  %t17 = sub i64 %t14, %t16
  %t18 = trunc i64 %t17 to i32
  %t19 = sext i32 %t18 to i64
  %t21 = trunc i64 %t19 to i32
  %t22 = sext i32 %t21 to i64
  store i64 %t22, ptr %t20
  br label %while1
while1:
  %t23 = load i64, ptr %t20
  %t24 = load i64, ptr %t2
  %t25 = trunc i64 %t23 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 %t24 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = icmp sge i64 %t26, %t28
  %t30 = zext i1 %t29 to i64
  %t31 = icmp ne i64 %t30, 0
  br i1 %t31, label %whilebody2, label %whileexit3
whilebody2:
  %t33 = trunc i64 0 to i32
  %t34 = sext i32 %t33 to i64
  store i64 %t34, ptr %t32
  br label %while4
while4:
  %t35 = load i64, ptr %t1
  %t36 = load i64, ptr %t32
  %t37 = trunc i64 %t35 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = trunc i64 %t36 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = add i64 %t38, %t40
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = trunc i64 %t43 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = trunc i64 512 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = icmp slt i64 %t45, %t47
  %t49 = zext i1 %t48 to i64
  %t50 = load i64, ptr %t32
  %t51 = load i64, ptr %t9
  %t52 = trunc i64 %t50 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 %t51 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = icmp slt i64 %t53, %t55
  %t57 = zext i1 %t56 to i64
  %t58 = icmp ne i64 %t49, 0
  %t59 = icmp ne i64 %t57, 0
  %t60 = and i1 %t58, %t59
  %t61 = zext i1 %t60 to i64
  %t62 = load i64, ptr %t20
  %t63 = load i64, ptr %t32
  %t64 = trunc i64 %t62 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = trunc i64 %t63 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = add i64 %t65, %t67
  %t69 = trunc i64 %t68 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = mul i64 %t70, 1
  %t72 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t71
  %t73 = load i64, ptr %t72
  %t74 = load i64, ptr %t1
  %t75 = load i64, ptr %t32
  %t76 = trunc i64 %t74 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = trunc i64 %t75 to i32
  %t79 = sext i32 %t78 to i64
  %t80 = add i64 %t77, %t79
  %t81 = trunc i64 %t80 to i32
  %t82 = sext i32 %t81 to i64
  %t83 = mul i64 %t82, 1
  %t84 = getelementptr [512 x i64], ptr %p0, i64 0, i64 %t83
  %t85 = load i64, ptr %t84
  %t86 = trunc i64 %t73 to i32
  %t87 = sext i32 %t86 to i64
  %t88 = trunc i64 %t85 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = icmp eq i64 %t87, %t89
  %t91 = zext i1 %t90 to i64
  %t92 = icmp ne i64 %t61, 0
  %t93 = icmp ne i64 %t91, 0
  %t94 = and i1 %t92, %t93
  %t95 = zext i1 %t94 to i64
  %t96 = icmp ne i64 %t95, 0
  br i1 %t96, label %whilebody5, label %whileexit6
whilebody5:
  %t97 = load i64, ptr %t32
  %t98 = trunc i64 %t97 to i32
  %t99 = sext i32 %t98 to i64
  %t100 = trunc i64 1 to i32
  %t101 = sext i32 %t100 to i64
  %t102 = add i64 %t99, %t101
  %t103 = trunc i64 %t102 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = trunc i64 %t104 to i32
  %t106 = sext i32 %t105 to i64
  store i64 %t106, ptr %t32
  br label %while4
whileexit6:
  %t107 = load i64, ptr %t32
  %t108 = load i64, ptr %t3
  %t109 = trunc i64 %t107 to i32
  %t110 = sext i32 %t109 to i64
  %t111 = trunc i64 %t108 to i32
  %t112 = sext i32 %t111 to i64
  %t113 = icmp sgt i64 %t110, %t112
  %t114 = zext i1 %t113 to i64
  %t115 = icmp ne i64 %t114, 0
  br i1 %t115, label %then7, label %else8
then7:
  %t116 = load i64, ptr %t32
  %t117 = trunc i64 %t116 to i32
  %t118 = sext i32 %t117 to i64
  store i64 %t118, ptr %t3
  %t119 = load i64, ptr %t1
  %t120 = load i64, ptr %t20
  %t121 = trunc i64 %t119 to i32
  %t122 = sext i32 %t121 to i64
  %t123 = trunc i64 %t120 to i32
  %t124 = sext i32 %t123 to i64
  %t125 = sub i64 %t122, %t124
  %t126 = trunc i64 %t125 to i32
  %t127 = sext i32 %t126 to i64
  %t128 = trunc i64 %t127 to i32
  %t129 = sext i32 %t128 to i64
  store i64 %t129, ptr %t6
  br label %ifend9
else8:
  br label %ifend9
ifend9:
  %t130 = load i64, ptr %t20
  %t131 = trunc i64 %t130 to i32
  %t132 = sext i32 %t131 to i64
  %t133 = trunc i64 1 to i32
  %t134 = sext i32 %t133 to i64
  %t135 = sub i64 %t132, %t134
  %t136 = trunc i64 %t135 to i32
  %t137 = sext i32 %t136 to i64
  %t138 = trunc i64 %t137 to i32
  %t139 = sext i32 %t138 to i64
  store i64 %t139, ptr %t20
  br label %while1
whileexit3:
  %t140 = load i64, ptr %t3
  %t141 = trunc i64 %t140 to i32
  %t142 = sext i32 %t141 to i64
  %t143 = trunc i64 3 to i32
  %t144 = sext i32 %t143 to i64
  %t145 = icmp sge i64 %t142, %t144
  %t146 = zext i1 %t145 to i64
  %t147 = icmp ne i64 %t146, 0
  br i1 %t147, label %then10, label %else11
then10:
  %t148 = load i64, ptr %t6
  %t149 = trunc i64 %t148 to i32
  %t150 = sext i32 %t149 to i64
  %t151 = trunc i64 1000 to i32
  %t152 = sext i32 %t151 to i64
  %t153 = mul i64 %t150, %t152
  %t154 = trunc i64 %t153 to i32
  %t155 = sext i32 %t154 to i64
  %t156 = load i64, ptr %t3
  %t157 = trunc i64 %t155 to i32
  %t158 = sext i32 %t157 to i64
  %t159 = trunc i64 %t156 to i32
  %t160 = sext i32 %t159 to i64
  %t161 = add i64 %t158, %t160
  %t162 = trunc i64 %t161 to i32
  %t163 = sext i32 %t162 to i64
  ret i64 %t163
else11:
  br label %ifend12
ifend12:
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

