; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @pm_rand_update(i64 %p0) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 0, ptr %t2
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t8 = alloca i64
  store i64 0, ptr %t8
  %t11 = alloca i64
  store i64 0, ptr %t11
  %t23 = alloca i64
  store i64 0, ptr %t23
  %t67 = alloca i64
  store i64 0, ptr %t67
  %t3 = trunc i64 16807 to i32
  %t4 = sext i32 %t3 to i64
  store i64 %t4, ptr %t2
  %t6 = trunc i64 2147483647 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t9 = trunc i64 127773 to i32
  %t10 = sext i32 %t9 to i64
  store i64 %t10, ptr %t8
  %t12 = trunc i64 2836 to i32
  %t13 = sext i32 %t12 to i64
  store i64 %t13, ptr %t11
  %t14 = load i64, ptr %t1
  %t15 = load i64, ptr %t8
  %t16 = trunc i64 %t14 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 %t15 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = sdiv i64 %t17, %t19
  %t21 = trunc i64 %t20 to i32
  %t22 = sext i32 %t21 to i64
  %t24 = trunc i64 %t22 to i32
  %t25 = sext i32 %t24 to i64
  store i64 %t25, ptr %t23
  %t26 = load i64, ptr %t2
  %t27 = load i64, ptr %t1
  %t28 = load i64, ptr %t23
  %t29 = load i64, ptr %t8
  %t30 = trunc i64 %t28 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = trunc i64 %t29 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = mul i64 %t31, %t33
  %t35 = trunc i64 %t34 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = trunc i64 %t27 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = trunc i64 %t36 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = sub i64 %t38, %t40
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = trunc i64 %t26 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = trunc i64 %t43 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = mul i64 %t45, %t47
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = load i64, ptr %t11
  %t52 = load i64, ptr %t23
  %t53 = trunc i64 %t51 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = trunc i64 %t52 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = mul i64 %t54, %t56
  %t58 = trunc i64 %t57 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = trunc i64 %t50 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 %t59 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = sub i64 %t61, %t63
  %t65 = trunc i64 %t64 to i32
  %t66 = sext i32 %t65 to i64
  %t68 = trunc i64 %t66 to i32
  %t69 = sext i32 %t68 to i64
  store i64 %t69, ptr %t67
  %t70 = load i64, ptr %t67
  %t71 = trunc i64 %t70 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = trunc i64 0 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = icmp sle i64 %t72, %t74
  %t76 = zext i1 %t75 to i64
  %t77 = icmp ne i64 %t76, 0
  br i1 %t77, label %then1, label %else2
then1:
  %t78 = load i64, ptr %t5
  %t79 = load i64, ptr %t67
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  %t82 = trunc i64 %t78 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = add i64 %t81, %t83
  %t85 = trunc i64 %t84 to i32
  %t86 = sext i32 %t85 to i64
  store i64 %t86, ptr %t67
  br label %ifend3
else2:
  br label %ifend3
ifend3:
  %t87 = load i64, ptr %t67
  ret i64 %t87
}

define i64 @main() {
entry:
  %t100 = alloca [2640 x i64]
  %t102 = alloca i64
  store i64 0, ptr %t102
  %t1 = alloca [2640 x i64]
  %t2 = alloca [2500 x i64]
  %t3 = alloca [50 x i64]
  call void @llvm.memset.p0.i64(ptr %t3, i8 0, i64 400, i1 false)
  %t4 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 400, i1 false)
  %t5 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 50
  call void @llvm.memcpy.p0.p0.i64(ptr %t5, ptr %t3, i64 400, i1 false)
  %t6 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 100
  call void @llvm.memcpy.p0.p0.i64(ptr %t6, ptr %t3, i64 400, i1 false)
  %t7 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 150
  call void @llvm.memcpy.p0.p0.i64(ptr %t7, ptr %t3, i64 400, i1 false)
  %t8 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 200
  call void @llvm.memcpy.p0.p0.i64(ptr %t8, ptr %t3, i64 400, i1 false)
  %t9 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 250
  call void @llvm.memcpy.p0.p0.i64(ptr %t9, ptr %t3, i64 400, i1 false)
  %t10 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 300
  call void @llvm.memcpy.p0.p0.i64(ptr %t10, ptr %t3, i64 400, i1 false)
  %t11 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 350
  call void @llvm.memcpy.p0.p0.i64(ptr %t11, ptr %t3, i64 400, i1 false)
  %t12 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 400
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t3, i64 400, i1 false)
  %t13 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 450
  call void @llvm.memcpy.p0.p0.i64(ptr %t13, ptr %t3, i64 400, i1 false)
  %t14 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 500
  call void @llvm.memcpy.p0.p0.i64(ptr %t14, ptr %t3, i64 400, i1 false)
  %t15 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 550
  call void @llvm.memcpy.p0.p0.i64(ptr %t15, ptr %t3, i64 400, i1 false)
  %t16 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 600
  call void @llvm.memcpy.p0.p0.i64(ptr %t16, ptr %t3, i64 400, i1 false)
  %t17 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 650
  call void @llvm.memcpy.p0.p0.i64(ptr %t17, ptr %t3, i64 400, i1 false)
  %t18 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 700
  call void @llvm.memcpy.p0.p0.i64(ptr %t18, ptr %t3, i64 400, i1 false)
  %t19 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 750
  call void @llvm.memcpy.p0.p0.i64(ptr %t19, ptr %t3, i64 400, i1 false)
  %t20 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 800
  call void @llvm.memcpy.p0.p0.i64(ptr %t20, ptr %t3, i64 400, i1 false)
  %t21 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 850
  call void @llvm.memcpy.p0.p0.i64(ptr %t21, ptr %t3, i64 400, i1 false)
  %t22 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 900
  call void @llvm.memcpy.p0.p0.i64(ptr %t22, ptr %t3, i64 400, i1 false)
  %t23 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 950
  call void @llvm.memcpy.p0.p0.i64(ptr %t23, ptr %t3, i64 400, i1 false)
  %t24 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1000
  call void @llvm.memcpy.p0.p0.i64(ptr %t24, ptr %t3, i64 400, i1 false)
  %t25 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1050
  call void @llvm.memcpy.p0.p0.i64(ptr %t25, ptr %t3, i64 400, i1 false)
  %t26 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1100
  call void @llvm.memcpy.p0.p0.i64(ptr %t26, ptr %t3, i64 400, i1 false)
  %t27 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1150
  call void @llvm.memcpy.p0.p0.i64(ptr %t27, ptr %t3, i64 400, i1 false)
  %t28 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1200
  call void @llvm.memcpy.p0.p0.i64(ptr %t28, ptr %t3, i64 400, i1 false)
  %t29 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1250
  call void @llvm.memcpy.p0.p0.i64(ptr %t29, ptr %t3, i64 400, i1 false)
  %t30 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1300
  call void @llvm.memcpy.p0.p0.i64(ptr %t30, ptr %t3, i64 400, i1 false)
  %t31 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1350
  call void @llvm.memcpy.p0.p0.i64(ptr %t31, ptr %t3, i64 400, i1 false)
  %t32 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1400
  call void @llvm.memcpy.p0.p0.i64(ptr %t32, ptr %t3, i64 400, i1 false)
  %t33 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1450
  call void @llvm.memcpy.p0.p0.i64(ptr %t33, ptr %t3, i64 400, i1 false)
  %t34 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1500
  call void @llvm.memcpy.p0.p0.i64(ptr %t34, ptr %t3, i64 400, i1 false)
  %t35 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1550
  call void @llvm.memcpy.p0.p0.i64(ptr %t35, ptr %t3, i64 400, i1 false)
  %t36 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1600
  call void @llvm.memcpy.p0.p0.i64(ptr %t36, ptr %t3, i64 400, i1 false)
  %t37 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1650
  call void @llvm.memcpy.p0.p0.i64(ptr %t37, ptr %t3, i64 400, i1 false)
  %t38 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1700
  call void @llvm.memcpy.p0.p0.i64(ptr %t38, ptr %t3, i64 400, i1 false)
  %t39 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1750
  call void @llvm.memcpy.p0.p0.i64(ptr %t39, ptr %t3, i64 400, i1 false)
  %t40 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1800
  call void @llvm.memcpy.p0.p0.i64(ptr %t40, ptr %t3, i64 400, i1 false)
  %t41 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1850
  call void @llvm.memcpy.p0.p0.i64(ptr %t41, ptr %t3, i64 400, i1 false)
  %t42 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1900
  call void @llvm.memcpy.p0.p0.i64(ptr %t42, ptr %t3, i64 400, i1 false)
  %t43 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1950
  call void @llvm.memcpy.p0.p0.i64(ptr %t43, ptr %t3, i64 400, i1 false)
  %t44 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2000
  call void @llvm.memcpy.p0.p0.i64(ptr %t44, ptr %t3, i64 400, i1 false)
  %t45 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2050
  call void @llvm.memcpy.p0.p0.i64(ptr %t45, ptr %t3, i64 400, i1 false)
  %t46 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2100
  call void @llvm.memcpy.p0.p0.i64(ptr %t46, ptr %t3, i64 400, i1 false)
  %t47 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2150
  call void @llvm.memcpy.p0.p0.i64(ptr %t47, ptr %t3, i64 400, i1 false)
  %t48 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2200
  call void @llvm.memcpy.p0.p0.i64(ptr %t48, ptr %t3, i64 400, i1 false)
  %t49 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2250
  call void @llvm.memcpy.p0.p0.i64(ptr %t49, ptr %t3, i64 400, i1 false)
  %t50 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2300
  call void @llvm.memcpy.p0.p0.i64(ptr %t50, ptr %t3, i64 400, i1 false)
  %t51 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2350
  call void @llvm.memcpy.p0.p0.i64(ptr %t51, ptr %t3, i64 400, i1 false)
  %t52 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2400
  call void @llvm.memcpy.p0.p0.i64(ptr %t52, ptr %t3, i64 400, i1 false)
  %t53 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2450
  call void @llvm.memcpy.p0.p0.i64(ptr %t53, ptr %t3, i64 400, i1 false)
  %t54 = getelementptr [2640 x i64], ptr %t1, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t54, ptr %t2, i64 20000, i1 false)
  %t55 = alloca [140 x i64]
  %t56 = alloca [7 x i64]
  %t57 = trunc i64 0 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = getelementptr [7 x i64], ptr %t56, i64 0, i64 0
  store i64 %t58, ptr %t59
  %t60 = trunc i64 0 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = getelementptr [7 x i64], ptr %t56, i64 0, i64 1
  store i64 %t61, ptr %t62
  %t63 = trunc i64 0 to i32
  %t64 = sext i32 %t63 to i64
  %t65 = getelementptr [7 x i64], ptr %t56, i64 0, i64 2
  store i64 %t64, ptr %t65
  %t66 = trunc i64 0 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = getelementptr [7 x i64], ptr %t56, i64 0, i64 3
  store i64 %t67, ptr %t68
  %t69 = trunc i64 0 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = getelementptr [7 x i64], ptr %t56, i64 0, i64 4
  store i64 %t70, ptr %t71
  %t72 = trunc i64 0 to i32
  %t73 = sext i32 %t72 to i64
  %t74 = getelementptr [7 x i64], ptr %t56, i64 0, i64 5
  store i64 %t73, ptr %t74
  %t75 = zext i1 0 to i64
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = getelementptr [7 x i64], ptr %t56, i64 0, i64 6
  store i64 %t77, ptr %t78
  %t79 = getelementptr [140 x i64], ptr %t55, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t79, ptr %t56, i64 56, i1 false)
  %t80 = getelementptr [140 x i64], ptr %t55, i64 0, i64 7
  call void @llvm.memcpy.p0.p0.i64(ptr %t80, ptr %t56, i64 56, i1 false)
  %t81 = getelementptr [140 x i64], ptr %t55, i64 0, i64 14
  call void @llvm.memcpy.p0.p0.i64(ptr %t81, ptr %t56, i64 56, i1 false)
  %t82 = getelementptr [140 x i64], ptr %t55, i64 0, i64 21
  call void @llvm.memcpy.p0.p0.i64(ptr %t82, ptr %t56, i64 56, i1 false)
  %t83 = getelementptr [140 x i64], ptr %t55, i64 0, i64 28
  call void @llvm.memcpy.p0.p0.i64(ptr %t83, ptr %t56, i64 56, i1 false)
  %t84 = getelementptr [140 x i64], ptr %t55, i64 0, i64 35
  call void @llvm.memcpy.p0.p0.i64(ptr %t84, ptr %t56, i64 56, i1 false)
  %t85 = getelementptr [140 x i64], ptr %t55, i64 0, i64 42
  call void @llvm.memcpy.p0.p0.i64(ptr %t85, ptr %t56, i64 56, i1 false)
  %t86 = getelementptr [140 x i64], ptr %t55, i64 0, i64 49
  call void @llvm.memcpy.p0.p0.i64(ptr %t86, ptr %t56, i64 56, i1 false)
  %t87 = getelementptr [140 x i64], ptr %t55, i64 0, i64 56
  call void @llvm.memcpy.p0.p0.i64(ptr %t87, ptr %t56, i64 56, i1 false)
  %t88 = getelementptr [140 x i64], ptr %t55, i64 0, i64 63
  call void @llvm.memcpy.p0.p0.i64(ptr %t88, ptr %t56, i64 56, i1 false)
  %t89 = getelementptr [140 x i64], ptr %t55, i64 0, i64 70
  call void @llvm.memcpy.p0.p0.i64(ptr %t89, ptr %t56, i64 56, i1 false)
  %t90 = getelementptr [140 x i64], ptr %t55, i64 0, i64 77
  call void @llvm.memcpy.p0.p0.i64(ptr %t90, ptr %t56, i64 56, i1 false)
  %t91 = getelementptr [140 x i64], ptr %t55, i64 0, i64 84
  call void @llvm.memcpy.p0.p0.i64(ptr %t91, ptr %t56, i64 56, i1 false)
  %t92 = getelementptr [140 x i64], ptr %t55, i64 0, i64 91
  call void @llvm.memcpy.p0.p0.i64(ptr %t92, ptr %t56, i64 56, i1 false)
  %t93 = getelementptr [140 x i64], ptr %t55, i64 0, i64 98
  call void @llvm.memcpy.p0.p0.i64(ptr %t93, ptr %t56, i64 56, i1 false)
  %t94 = getelementptr [140 x i64], ptr %t55, i64 0, i64 105
  call void @llvm.memcpy.p0.p0.i64(ptr %t94, ptr %t56, i64 56, i1 false)
  %t95 = getelementptr [140 x i64], ptr %t55, i64 0, i64 112
  call void @llvm.memcpy.p0.p0.i64(ptr %t95, ptr %t56, i64 56, i1 false)
  %t96 = getelementptr [140 x i64], ptr %t55, i64 0, i64 119
  call void @llvm.memcpy.p0.p0.i64(ptr %t96, ptr %t56, i64 56, i1 false)
  %t97 = getelementptr [140 x i64], ptr %t55, i64 0, i64 126
  call void @llvm.memcpy.p0.p0.i64(ptr %t97, ptr %t56, i64 56, i1 false)
  %t98 = getelementptr [140 x i64], ptr %t55, i64 0, i64 133
  call void @llvm.memcpy.p0.p0.i64(ptr %t98, ptr %t56, i64 56, i1 false)
  %t99 = getelementptr [2640 x i64], ptr %t1, i64 0, i64 2500
  call void @llvm.memcpy.p0.p0.i64(ptr %t99, ptr %t55, i64 1120, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t100, ptr %t1, i64 21120, i1 false)
  %t101 = call i64 @initialize_world(ptr %t100, i64 98765)
  %t103 = trunc i64 0 to i32
  %t104 = sext i32 %t103 to i64
  store i64 %t104, ptr %t102
  br label %while1
while1:
  %t105 = load i64, ptr %t102
  %t106 = trunc i64 %t105 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = trunc i64 100 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = icmp slt i64 %t107, %t109
  %t111 = zext i1 %t110 to i64
  %t112 = icmp ne i64 %t111, 0
  br i1 %t112, label %whilebody2, label %whileexit3
whilebody2:
  %t113 = call i64 @update_world(ptr %t100)
  %t114 = call i64 @process_interactions(ptr %t100)
  %t115 = load i64, ptr %t102
  %t116 = trunc i64 %t115 to i32
  %t117 = sext i32 %t116 to i64
  %t118 = trunc i64 10 to i32
  %t119 = sext i32 %t118 to i64
  %t120 = srem i64 %t117, %t119
  %t121 = trunc i64 %t120 to i32
  %t122 = sext i32 %t121 to i64
  %t123 = trunc i64 %t122 to i32
  %t124 = sext i32 %t123 to i64
  %t125 = trunc i64 0 to i32
  %t126 = sext i32 %t125 to i64
  %t127 = icmp eq i64 %t124, %t126
  %t128 = zext i1 %t127 to i64
  %t129 = icmp ne i64 %t128, 0
  br i1 %t129, label %then4, label %else5
then4:
  %t130 = call i64 @run_diagnostics(ptr %t100)
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t131 = load i64, ptr %t102
  %t132 = trunc i64 %t131 to i32
  %t133 = sext i32 %t132 to i64
  %t134 = trunc i64 1 to i32
  %t135 = sext i32 %t134 to i64
  %t136 = add i64 %t133, %t135
  %t137 = trunc i64 %t136 to i32
  %t138 = sext i32 %t137 to i64
  %t139 = trunc i64 %t138 to i32
  %t140 = sext i32 %t139 to i64
  store i64 %t140, ptr %t102
  br label %while1
whileexit3:
  %t141 = call i64 @final_report(ptr %t100)
  %t142 = call i64 @printlnInt(i64 9999)
  ret i64 0
}

define i64 @initialize_world(ptr %p0, i64 %p1) {
entry:
  %t1 = alloca i64
  store i64 %p1, ptr %t1
  %t3 = alloca i64
  store i64 0, ptr %t3
  %t6 = alloca i64
  store i64 0, ptr %t6
  %t43 = alloca i64
  store i64 0, ptr %t43
  %t72 = alloca i64
  store i64 0, ptr %t72
  %t108 = alloca i64
  store i64 0, ptr %t108
  %t198 = alloca i64
  store i64 0, ptr %t198
  %t2 = load i64, ptr %t1
  %t4 = trunc i64 %t2 to i32
  %t5 = sext i32 %t4 to i64
  store i64 %t5, ptr %t3
  %t7 = trunc i64 0 to i32
  %t8 = sext i32 %t7 to i64
  store i64 %t8, ptr %t6
  br label %while1
while1:
  %t9 = load i64, ptr %t6
  %t10 = trunc i64 %t9 to i32
  %t11 = sext i32 %t10 to i64
  %t12 = trunc i64 20 to i32
  %t13 = sext i32 %t12 to i64
  %t14 = icmp slt i64 %t11, %t13
  %t15 = zext i1 %t14 to i64
  %t16 = icmp ne i64 %t15, 0
  br i1 %t16, label %whilebody2, label %whileexit3
whilebody2:
  %t17 = load i64, ptr %t3
  %t18 = call i64 @pm_rand_update(i64 %t17)
  %t19 = trunc i64 %t18 to i32
  %t20 = sext i32 %t19 to i64
  %t21 = trunc i64 65536 to i32
  %t22 = sext i32 %t21 to i64
  %t23 = sdiv i64 %t20, %t22
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 %t25 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = trunc i64 32768 to i32
  %t29 = sext i32 %t28 to i64
  %t30 = srem i64 %t27, %t29
  %t31 = trunc i64 %t30 to i32
  %t32 = sext i32 %t31 to i64
  %t33 = trunc i64 %t32 to i32
  %t34 = sext i32 %t33 to i64
  store i64 %t34, ptr %t3
  %t35 = load i64, ptr %t3
  %t36 = trunc i64 %t35 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = trunc i64 50 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = srem i64 %t37, %t39
  %t41 = trunc i64 %t40 to i32
  %t42 = sext i32 %t41 to i64
  %t44 = trunc i64 %t42 to i32
  %t45 = sext i32 %t44 to i64
  store i64 %t45, ptr %t43
  %t46 = load i64, ptr %t3
  %t47 = call i64 @pm_rand_update(i64 %t46)
  %t48 = trunc i64 %t47 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = trunc i64 65536 to i32
  %t51 = sext i32 %t50 to i64
  %t52 = sdiv i64 %t49, %t51
  %t53 = trunc i64 %t52 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = trunc i64 %t54 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = trunc i64 32768 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = srem i64 %t56, %t58
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  store i64 %t63, ptr %t3
  %t64 = load i64, ptr %t3
  %t65 = trunc i64 %t64 to i32
  %t66 = sext i32 %t65 to i64
  %t67 = trunc i64 50 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = srem i64 %t66, %t68
  %t70 = trunc i64 %t69 to i32
  %t71 = sext i32 %t70 to i64
  %t73 = trunc i64 %t71 to i32
  %t74 = sext i32 %t73 to i64
  store i64 %t74, ptr %t72
  %t75 = load i64, ptr %t3
  %t76 = call i64 @pm_rand_update(i64 %t75)
  %t77 = trunc i64 %t76 to i32
  %t78 = sext i32 %t77 to i64
  %t79 = trunc i64 65536 to i32
  %t80 = sext i32 %t79 to i64
  %t81 = sdiv i64 %t78, %t80
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 %t83 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = trunc i64 32768 to i32
  %t87 = sext i32 %t86 to i64
  %t88 = srem i64 %t85, %t87
  %t89 = trunc i64 %t88 to i32
  %t90 = sext i32 %t89 to i64
  %t91 = trunc i64 %t90 to i32
  %t92 = sext i32 %t91 to i64
  store i64 %t92, ptr %t3
  %t93 = load i64, ptr %t3
  %t94 = trunc i64 %t93 to i32
  %t95 = sext i32 %t94 to i64
  %t96 = trunc i64 100 to i32
  %t97 = sext i32 %t96 to i64
  %t98 = srem i64 %t95, %t97
  %t99 = trunc i64 %t98 to i32
  %t100 = sext i32 %t99 to i64
  %t101 = trunc i64 100 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = trunc i64 %t100 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = add i64 %t102, %t104
  %t106 = trunc i64 %t105 to i32
  %t107 = sext i32 %t106 to i64
  %t109 = trunc i64 %t107 to i32
  %t110 = sext i32 %t109 to i64
  store i64 %t110, ptr %t108
  %t111 = load i64, ptr %t6
  %t112 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t113 = load i64, ptr %t6
  %t114 = mul i64 %t113, 7
  %t115 = getelementptr i64, ptr %t112, i64 %t114
  %t116 = getelementptr i64, ptr %t115, i64 0
  %t117 = trunc i64 %t111 to i32
  %t118 = sext i32 %t117 to i64
  store i64 %t118, ptr %t116
  %t119 = load i64, ptr %t43
  %t120 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t121 = load i64, ptr %t6
  %t122 = mul i64 %t121, 7
  %t123 = getelementptr i64, ptr %t120, i64 %t122
  %t124 = getelementptr i64, ptr %t123, i64 1
  %t125 = trunc i64 %t119 to i32
  %t126 = sext i32 %t125 to i64
  store i64 %t126, ptr %t124
  %t127 = load i64, ptr %t72
  %t128 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t129 = load i64, ptr %t6
  %t130 = mul i64 %t129, 7
  %t131 = getelementptr i64, ptr %t128, i64 %t130
  %t132 = getelementptr i64, ptr %t131, i64 2
  %t133 = trunc i64 %t127 to i32
  %t134 = sext i32 %t133 to i64
  store i64 %t134, ptr %t132
  %t135 = load i64, ptr %t108
  %t136 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t137 = load i64, ptr %t6
  %t138 = mul i64 %t137, 7
  %t139 = getelementptr i64, ptr %t136, i64 %t138
  %t140 = getelementptr i64, ptr %t139, i64 3
  %t141 = trunc i64 %t135 to i32
  %t142 = sext i32 %t141 to i64
  store i64 %t142, ptr %t140
  %t143 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t144 = load i64, ptr %t6
  %t145 = mul i64 %t144, 7
  %t146 = getelementptr i64, ptr %t143, i64 %t145
  %t147 = getelementptr i64, ptr %t146, i64 6
  %t148 = zext i1 1 to i64
  %t149 = trunc i64 %t148 to i32
  %t150 = sext i32 %t149 to i64
  store i64 %t150, ptr %t147
  %t151 = load i64, ptr %t6
  %t152 = trunc i64 %t151 to i32
  %t153 = sext i32 %t152 to i64
  %t154 = trunc i64 1 to i32
  %t155 = sext i32 %t154 to i64
  %t156 = add i64 %t153, %t155
  %t157 = trunc i64 %t156 to i32
  %t158 = sext i32 %t157 to i64
  %t159 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t160 = load i64, ptr %t72
  %t161 = mul i64 %t160, 50
  %t162 = getelementptr i64, ptr %t159, i64 %t161
  %t163 = load i64, ptr %t43
  %t164 = mul i64 %t163, 1
  %t165 = getelementptr i64, ptr %t162, i64 %t164
  %t166 = trunc i64 %t158 to i32
  %t167 = sext i32 %t166 to i64
  store i64 %t167, ptr %t165
  %t168 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t169 = load i64, ptr %t6
  %t170 = mul i64 %t169, 7
  %t171 = getelementptr i64, ptr %t168, i64 %t170
  %t172 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t173 = load i64, ptr %t6
  %t174 = mul i64 %t173, 7
  %t175 = getelementptr i64, ptr %t172, i64 %t174
  %t176 = load i64, ptr %t3
  %t177 = call i64 @update_agent_target(ptr %t175, i64 %t176)
  %t178 = load i64, ptr %t6
  %t179 = trunc i64 %t178 to i32
  %t180 = sext i32 %t179 to i64
  %t181 = trunc i64 1 to i32
  %t182 = sext i32 %t181 to i64
  %t183 = add i64 %t180, %t182
  %t184 = trunc i64 %t183 to i32
  %t185 = sext i32 %t184 to i64
  %t186 = trunc i64 %t185 to i32
  %t187 = sext i32 %t186 to i64
  store i64 %t187, ptr %t6
  br label %while1
whileexit3:
  %t188 = trunc i64 0 to i32
  %t189 = sext i32 %t188 to i64
  store i64 %t189, ptr %t6
  br label %while4
while4:
  %t190 = load i64, ptr %t6
  %t191 = trunc i64 %t190 to i32
  %t192 = sext i32 %t191 to i64
  %t193 = trunc i64 50 to i32
  %t194 = sext i32 %t193 to i64
  %t195 = icmp slt i64 %t192, %t194
  %t196 = zext i1 %t195 to i64
  %t197 = icmp ne i64 %t196, 0
  br i1 %t197, label %whilebody5, label %whileexit6
whilebody5:
  %t199 = trunc i64 0 to i32
  %t200 = sext i32 %t199 to i64
  store i64 %t200, ptr %t198
  br label %while7
while7:
  %t201 = load i64, ptr %t198
  %t202 = trunc i64 %t201 to i32
  %t203 = sext i32 %t202 to i64
  %t204 = trunc i64 50 to i32
  %t205 = sext i32 %t204 to i64
  %t206 = icmp slt i64 %t203, %t205
  %t207 = zext i1 %t206 to i64
  %t208 = icmp ne i64 %t207, 0
  br i1 %t208, label %whilebody8, label %whileexit9
whilebody8:
  %t209 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t210 = load i64, ptr %t6
  %t211 = mul i64 %t210, 50
  %t212 = getelementptr i64, ptr %t209, i64 %t211
  %t213 = load i64, ptr %t198
  %t214 = mul i64 %t213, 1
  %t215 = getelementptr i64, ptr %t212, i64 %t214
  %t216 = load i64, ptr %t215
  %t217 = trunc i64 %t216 to i32
  %t218 = sext i32 %t217 to i64
  %t219 = trunc i64 0 to i32
  %t220 = sext i32 %t219 to i64
  %t221 = icmp eq i64 %t218, %t220
  %t222 = zext i1 %t221 to i64
  %t223 = icmp ne i64 %t222, 0
  br i1 %t223, label %then10, label %else11
then10:
  %t224 = load i64, ptr %t3
  %t225 = call i64 @pm_rand_update(i64 %t224)
  %t226 = trunc i64 %t225 to i32
  %t227 = sext i32 %t226 to i64
  %t228 = trunc i64 65536 to i32
  %t229 = sext i32 %t228 to i64
  %t230 = sdiv i64 %t227, %t229
  %t231 = trunc i64 %t230 to i32
  %t232 = sext i32 %t231 to i64
  %t233 = trunc i64 %t232 to i32
  %t234 = sext i32 %t233 to i64
  %t235 = trunc i64 32768 to i32
  %t236 = sext i32 %t235 to i64
  %t237 = srem i64 %t234, %t236
  %t238 = trunc i64 %t237 to i32
  %t239 = sext i32 %t238 to i64
  %t240 = trunc i64 %t239 to i32
  %t241 = sext i32 %t240 to i64
  store i64 %t241, ptr %t3
  %t242 = load i64, ptr %t3
  %t243 = trunc i64 %t242 to i32
  %t244 = sext i32 %t243 to i64
  %t245 = trunc i64 10 to i32
  %t246 = sext i32 %t245 to i64
  %t247 = srem i64 %t244, %t246
  %t248 = trunc i64 %t247 to i32
  %t249 = sext i32 %t248 to i64
  %t250 = trunc i64 %t249 to i32
  %t251 = sext i32 %t250 to i64
  %t252 = trunc i64 0 to i32
  %t253 = sext i32 %t252 to i64
  %t254 = icmp eq i64 %t251, %t253
  %t255 = zext i1 %t254 to i64
  %t256 = icmp ne i64 %t255, 0
  br i1 %t256, label %then13, label %else14
then13:
  %t257 = load i64, ptr %t3
  %t258 = trunc i64 %t257 to i32
  %t259 = sext i32 %t258 to i64
  %t260 = trunc i64 5 to i32
  %t261 = sext i32 %t260 to i64
  %t262 = srem i64 %t259, %t261
  %t263 = trunc i64 %t262 to i32
  %t264 = sext i32 %t263 to i64
  %t265 = trunc i64 %t264 to i32
  %t266 = sext i32 %t265 to i64
  %t267 = trunc i64 1 to i32
  %t268 = sext i32 %t267 to i64
  %t269 = add i64 %t266, %t268
  %t270 = trunc i64 %t269 to i32
  %t271 = sext i32 %t270 to i64
  %t272 = trunc i64 -1 to i32
  %t273 = sext i32 %t272 to i64
  %t274 = trunc i64 %t271 to i32
  %t275 = sext i32 %t274 to i64
  %t276 = mul i64 %t273, %t275
  %t277 = trunc i64 %t276 to i32
  %t278 = sext i32 %t277 to i64
  %t279 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t280 = load i64, ptr %t6
  %t281 = mul i64 %t280, 50
  %t282 = getelementptr i64, ptr %t279, i64 %t281
  %t283 = load i64, ptr %t198
  %t284 = mul i64 %t283, 1
  %t285 = getelementptr i64, ptr %t282, i64 %t284
  %t286 = trunc i64 %t278 to i32
  %t287 = sext i32 %t286 to i64
  store i64 %t287, ptr %t285
  br label %ifend15
else14:
  br label %ifend15
ifend15:
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  %t288 = load i64, ptr %t198
  %t289 = trunc i64 %t288 to i32
  %t290 = sext i32 %t289 to i64
  %t291 = trunc i64 1 to i32
  %t292 = sext i32 %t291 to i64
  %t293 = add i64 %t290, %t292
  %t294 = trunc i64 %t293 to i32
  %t295 = sext i32 %t294 to i64
  %t296 = trunc i64 %t295 to i32
  %t297 = sext i32 %t296 to i64
  store i64 %t297, ptr %t198
  br label %while7
whileexit9:
  %t298 = load i64, ptr %t6
  %t299 = trunc i64 %t298 to i32
  %t300 = sext i32 %t299 to i64
  %t301 = trunc i64 1 to i32
  %t302 = sext i32 %t301 to i64
  %t303 = add i64 %t300, %t302
  %t304 = trunc i64 %t303 to i32
  %t305 = sext i32 %t304 to i64
  %t306 = trunc i64 %t305 to i32
  %t307 = sext i32 %t306 to i64
  store i64 %t307, ptr %t6
  br label %while4
whileexit6:
  ret i64 0
}

define i64 @update_agent_target(ptr %p0, i64 %p1) {
entry:
  %t1 = alloca i64
  store i64 %p1, ptr %t1
  %t3 = alloca i64
  store i64 0, ptr %t3
  %t2 = load i64, ptr %t1
  %t4 = trunc i64 %t2 to i32
  %t5 = sext i32 %t4 to i64
  store i64 %t5, ptr %t3
  %t6 = load i64, ptr %t3
  %t7 = call i64 @pm_rand_update(i64 %t6)
  %t8 = trunc i64 %t7 to i32
  %t9 = sext i32 %t8 to i64
  %t10 = trunc i64 65536 to i32
  %t11 = sext i32 %t10 to i64
  %t12 = sdiv i64 %t9, %t11
  %t13 = trunc i64 %t12 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = trunc i64 %t14 to i32
  %t16 = sext i32 %t15 to i64
  %t17 = trunc i64 32768 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = srem i64 %t16, %t18
  %t20 = trunc i64 %t19 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = trunc i64 %t21 to i32
  %t23 = sext i32 %t22 to i64
  store i64 %t23, ptr %t3
  %t24 = load i64, ptr %t3
  %t25 = trunc i64 %t24 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 50 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = srem i64 %t26, %t28
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = getelementptr [7 x i64], ptr %p0, i64 0, i64 4
  %t33 = trunc i64 %t31 to i32
  %t34 = sext i32 %t33 to i64
  store i64 %t34, ptr %t32
  %t35 = load i64, ptr %t3
  %t36 = call i64 @pm_rand_update(i64 %t35)
  %t37 = trunc i64 %t36 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = trunc i64 65536 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = sdiv i64 %t38, %t40
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = trunc i64 %t43 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = trunc i64 32768 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = srem i64 %t45, %t47
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = trunc i64 %t50 to i32
  %t52 = sext i32 %t51 to i64
  store i64 %t52, ptr %t3
  %t53 = load i64, ptr %t3
  %t54 = trunc i64 %t53 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = trunc i64 50 to i32
  %t57 = sext i32 %t56 to i64
  %t58 = srem i64 %t55, %t57
  %t59 = trunc i64 %t58 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = getelementptr [7 x i64], ptr %p0, i64 0, i64 5
  %t62 = trunc i64 %t60 to i32
  %t63 = sext i32 %t62 to i64
  store i64 %t63, ptr %t61
  ret i64 0
}

define i64 @update_world(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t27 = alloca i64
  store i64 0, ptr %t27
  %t33 = alloca i64
  store i64 0, ptr %t33
  %t40 = alloca i64
  store i64 0, ptr %t40
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 20 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t12 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t13 = load i64, ptr %t1
  %t14 = mul i64 %t13, 7
  %t15 = getelementptr i64, ptr %t12, i64 %t14
  %t16 = getelementptr i64, ptr %t15, i64 6
  %t17 = load i64, ptr %t16
  %t18 = icmp ne i64 %t17, 0
  br i1 %t18, label %then4, label %else5
then4:
  %t19 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t20 = load i64, ptr %t1
  %t21 = mul i64 %t20, 7
  %t22 = getelementptr i64, ptr %t19, i64 %t21
  %t23 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t24 = load i64, ptr %t1
  %t25 = mul i64 %t24, 7
  %t26 = getelementptr i64, ptr %t23, i64 %t25
  %t28 = ptrtoint ptr %t26 to i64
  store i64 %t28, ptr %t27
  %t29 = load i64, ptr %t27
  %t30 = inttoptr i64 %t29 to ptr
  %t31 = getelementptr [7 x i64], ptr %t30, i64 0, i64 1
  %t32 = load i64, ptr %t31
  %t34 = trunc i64 %t32 to i32
  %t35 = sext i32 %t34 to i64
  store i64 %t35, ptr %t33
  %t36 = load i64, ptr %t27
  %t37 = inttoptr i64 %t36 to ptr
  %t38 = getelementptr [7 x i64], ptr %t37, i64 0, i64 2
  %t39 = load i64, ptr %t38
  %t41 = trunc i64 %t39 to i32
  %t42 = sext i32 %t41 to i64
  store i64 %t42, ptr %t40
  %t43 = load i64, ptr %t27
  %t44 = inttoptr i64 %t43 to ptr
  %t45 = getelementptr [7 x i64], ptr %t44, i64 0, i64 1
  %t46 = load i64, ptr %t45
  %t47 = load i64, ptr %t27
  %t48 = inttoptr i64 %t47 to ptr
  %t49 = getelementptr [7 x i64], ptr %t48, i64 0, i64 4
  %t50 = load i64, ptr %t49
  %t51 = trunc i64 %t46 to i32
  %t52 = sext i32 %t51 to i64
  %t53 = trunc i64 %t50 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = icmp slt i64 %t52, %t54
  %t56 = zext i1 %t55 to i64
  %t57 = icmp ne i64 %t56, 0
  br i1 %t57, label %then7, label %else8
then7:
  %t58 = load i64, ptr %t27
  %t59 = inttoptr i64 %t58 to ptr
  %t60 = getelementptr [7 x i64], ptr %t59, i64 0, i64 1
  %t61 = load i64, ptr %t60
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 1 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = add i64 %t63, %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = load i64, ptr %t27
  %t70 = inttoptr i64 %t69 to ptr
  %t71 = getelementptr [7 x i64], ptr %t70, i64 0, i64 1
  %t72 = trunc i64 %t68 to i32
  %t73 = sext i32 %t72 to i64
  store i64 %t73, ptr %t71
  br label %ifend9
else8:
  %t74 = load i64, ptr %t27
  %t75 = inttoptr i64 %t74 to ptr
  %t76 = getelementptr [7 x i64], ptr %t75, i64 0, i64 1
  %t77 = load i64, ptr %t76
  %t78 = load i64, ptr %t27
  %t79 = inttoptr i64 %t78 to ptr
  %t80 = getelementptr [7 x i64], ptr %t79, i64 0, i64 4
  %t81 = load i64, ptr %t80
  %t82 = trunc i64 %t77 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 %t81 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = icmp sgt i64 %t83, %t85
  %t87 = zext i1 %t86 to i64
  %t88 = icmp ne i64 %t87, 0
  br i1 %t88, label %then10, label %else11
then10:
  %t89 = load i64, ptr %t27
  %t90 = inttoptr i64 %t89 to ptr
  %t91 = getelementptr [7 x i64], ptr %t90, i64 0, i64 1
  %t92 = load i64, ptr %t91
  %t93 = trunc i64 %t92 to i32
  %t94 = sext i32 %t93 to i64
  %t95 = trunc i64 1 to i32
  %t96 = sext i32 %t95 to i64
  %t97 = sub i64 %t94, %t96
  %t98 = trunc i64 %t97 to i32
  %t99 = sext i32 %t98 to i64
  %t100 = load i64, ptr %t27
  %t101 = inttoptr i64 %t100 to ptr
  %t102 = getelementptr [7 x i64], ptr %t101, i64 0, i64 1
  %t103 = trunc i64 %t99 to i32
  %t104 = sext i32 %t103 to i64
  store i64 %t104, ptr %t102
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  br label %ifend9
ifend9:
  %t105 = load i64, ptr %t27
  %t106 = inttoptr i64 %t105 to ptr
  %t107 = getelementptr [7 x i64], ptr %t106, i64 0, i64 2
  %t108 = load i64, ptr %t107
  %t109 = load i64, ptr %t27
  %t110 = inttoptr i64 %t109 to ptr
  %t111 = getelementptr [7 x i64], ptr %t110, i64 0, i64 5
  %t112 = load i64, ptr %t111
  %t113 = trunc i64 %t108 to i32
  %t114 = sext i32 %t113 to i64
  %t115 = trunc i64 %t112 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = icmp slt i64 %t114, %t116
  %t118 = zext i1 %t117 to i64
  %t119 = icmp ne i64 %t118, 0
  br i1 %t119, label %then13, label %else14
then13:
  %t120 = load i64, ptr %t27
  %t121 = inttoptr i64 %t120 to ptr
  %t122 = getelementptr [7 x i64], ptr %t121, i64 0, i64 2
  %t123 = load i64, ptr %t122
  %t124 = trunc i64 %t123 to i32
  %t125 = sext i32 %t124 to i64
  %t126 = trunc i64 1 to i32
  %t127 = sext i32 %t126 to i64
  %t128 = add i64 %t125, %t127
  %t129 = trunc i64 %t128 to i32
  %t130 = sext i32 %t129 to i64
  %t131 = load i64, ptr %t27
  %t132 = inttoptr i64 %t131 to ptr
  %t133 = getelementptr [7 x i64], ptr %t132, i64 0, i64 2
  %t134 = trunc i64 %t130 to i32
  %t135 = sext i32 %t134 to i64
  store i64 %t135, ptr %t133
  br label %ifend15
else14:
  %t136 = load i64, ptr %t27
  %t137 = inttoptr i64 %t136 to ptr
  %t138 = getelementptr [7 x i64], ptr %t137, i64 0, i64 2
  %t139 = load i64, ptr %t138
  %t140 = load i64, ptr %t27
  %t141 = inttoptr i64 %t140 to ptr
  %t142 = getelementptr [7 x i64], ptr %t141, i64 0, i64 5
  %t143 = load i64, ptr %t142
  %t144 = trunc i64 %t139 to i32
  %t145 = sext i32 %t144 to i64
  %t146 = trunc i64 %t143 to i32
  %t147 = sext i32 %t146 to i64
  %t148 = icmp sgt i64 %t145, %t147
  %t149 = zext i1 %t148 to i64
  %t150 = icmp ne i64 %t149, 0
  br i1 %t150, label %then16, label %else17
then16:
  %t151 = load i64, ptr %t27
  %t152 = inttoptr i64 %t151 to ptr
  %t153 = getelementptr [7 x i64], ptr %t152, i64 0, i64 2
  %t154 = load i64, ptr %t153
  %t155 = trunc i64 %t154 to i32
  %t156 = sext i32 %t155 to i64
  %t157 = trunc i64 1 to i32
  %t158 = sext i32 %t157 to i64
  %t159 = sub i64 %t156, %t158
  %t160 = trunc i64 %t159 to i32
  %t161 = sext i32 %t160 to i64
  %t162 = load i64, ptr %t27
  %t163 = inttoptr i64 %t162 to ptr
  %t164 = getelementptr [7 x i64], ptr %t163, i64 0, i64 2
  %t165 = trunc i64 %t161 to i32
  %t166 = sext i32 %t165 to i64
  store i64 %t166, ptr %t164
  br label %ifend18
else17:
  br label %ifend18
ifend18:
  br label %ifend15
ifend15:
  %t167 = load i64, ptr %t27
  %t168 = inttoptr i64 %t167 to ptr
  %t169 = getelementptr [7 x i64], ptr %t168, i64 0, i64 1
  %t170 = load i64, ptr %t169
  %t171 = call i64 @clamp(i64 %t170, i64 0, i64 49)
  %t172 = load i64, ptr %t27
  %t173 = inttoptr i64 %t172 to ptr
  %t174 = getelementptr [7 x i64], ptr %t173, i64 0, i64 1
  %t175 = trunc i64 %t171 to i32
  %t176 = sext i32 %t175 to i64
  store i64 %t176, ptr %t174
  %t177 = load i64, ptr %t27
  %t178 = inttoptr i64 %t177 to ptr
  %t179 = getelementptr [7 x i64], ptr %t178, i64 0, i64 2
  %t180 = load i64, ptr %t179
  %t181 = call i64 @clamp(i64 %t180, i64 0, i64 49)
  %t182 = load i64, ptr %t27
  %t183 = inttoptr i64 %t182 to ptr
  %t184 = getelementptr [7 x i64], ptr %t183, i64 0, i64 2
  %t185 = trunc i64 %t181 to i32
  %t186 = sext i32 %t185 to i64
  store i64 %t186, ptr %t184
  %t187 = load i64, ptr %t27
  %t188 = inttoptr i64 %t187 to ptr
  %t189 = getelementptr [7 x i64], ptr %t188, i64 0, i64 3
  %t190 = load i64, ptr %t189
  %t191 = trunc i64 %t190 to i32
  %t192 = sext i32 %t191 to i64
  %t193 = trunc i64 1 to i32
  %t194 = sext i32 %t193 to i64
  %t195 = sub i64 %t192, %t194
  %t196 = trunc i64 %t195 to i32
  %t197 = sext i32 %t196 to i64
  %t198 = load i64, ptr %t27
  %t199 = inttoptr i64 %t198 to ptr
  %t200 = getelementptr [7 x i64], ptr %t199, i64 0, i64 3
  %t201 = trunc i64 %t197 to i32
  %t202 = sext i32 %t201 to i64
  store i64 %t202, ptr %t200
  %t203 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t204 = load i64, ptr %t27
  %t205 = inttoptr i64 %t204 to ptr
  %t206 = getelementptr [7 x i64], ptr %t205, i64 0, i64 2
  %t207 = load i64, ptr %t206
  %t208 = mul i64 %t207, 50
  %t209 = getelementptr i64, ptr %t203, i64 %t208
  %t210 = load i64, ptr %t27
  %t211 = inttoptr i64 %t210 to ptr
  %t212 = getelementptr [7 x i64], ptr %t211, i64 0, i64 1
  %t213 = load i64, ptr %t212
  %t214 = mul i64 %t213, 1
  %t215 = getelementptr i64, ptr %t209, i64 %t214
  %t216 = load i64, ptr %t215
  %t217 = trunc i64 %t216 to i32
  %t218 = sext i32 %t217 to i64
  %t219 = trunc i64 0 to i32
  %t220 = sext i32 %t219 to i64
  %t221 = icmp eq i64 %t218, %t220
  %t222 = zext i1 %t221 to i64
  %t223 = icmp ne i64 %t222, 0
  br i1 %t223, label %then19, label %else20
then19:
  %t224 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t225 = load i64, ptr %t40
  %t226 = mul i64 %t225, 50
  %t227 = getelementptr i64, ptr %t224, i64 %t226
  %t228 = load i64, ptr %t33
  %t229 = mul i64 %t228, 1
  %t230 = getelementptr i64, ptr %t227, i64 %t229
  %t231 = trunc i64 0 to i32
  %t232 = sext i32 %t231 to i64
  store i64 %t232, ptr %t230
  %t233 = load i64, ptr %t27
  %t234 = inttoptr i64 %t233 to ptr
  %t235 = getelementptr [7 x i64], ptr %t234, i64 0, i64 0
  %t236 = load i64, ptr %t235
  %t237 = trunc i64 %t236 to i32
  %t238 = sext i32 %t237 to i64
  %t239 = trunc i64 1 to i32
  %t240 = sext i32 %t239 to i64
  %t241 = add i64 %t238, %t240
  %t242 = trunc i64 %t241 to i32
  %t243 = sext i32 %t242 to i64
  %t244 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t245 = load i64, ptr %t27
  %t246 = inttoptr i64 %t245 to ptr
  %t247 = getelementptr [7 x i64], ptr %t246, i64 0, i64 2
  %t248 = load i64, ptr %t247
  %t249 = mul i64 %t248, 50
  %t250 = getelementptr i64, ptr %t244, i64 %t249
  %t251 = load i64, ptr %t27
  %t252 = inttoptr i64 %t251 to ptr
  %t253 = getelementptr [7 x i64], ptr %t252, i64 0, i64 1
  %t254 = load i64, ptr %t253
  %t255 = mul i64 %t254, 1
  %t256 = getelementptr i64, ptr %t250, i64 %t255
  %t257 = trunc i64 %t243 to i32
  %t258 = sext i32 %t257 to i64
  store i64 %t258, ptr %t256
  br label %ifend21
else20:
  %t259 = load i64, ptr %t33
  %t260 = load i64, ptr %t27
  %t261 = inttoptr i64 %t260 to ptr
  %t262 = getelementptr [7 x i64], ptr %t261, i64 0, i64 1
  %t263 = trunc i64 %t259 to i32
  %t264 = sext i32 %t263 to i64
  store i64 %t264, ptr %t262
  %t265 = load i64, ptr %t40
  %t266 = load i64, ptr %t27
  %t267 = inttoptr i64 %t266 to ptr
  %t268 = getelementptr [7 x i64], ptr %t267, i64 0, i64 2
  %t269 = trunc i64 %t265 to i32
  %t270 = sext i32 %t269 to i64
  store i64 %t270, ptr %t268
  %t271 = load i64, ptr %t27
  %t272 = inttoptr i64 %t271 to ptr
  %t273 = getelementptr [7 x i64], ptr %t272, i64 0, i64 3
  %t274 = load i64, ptr %t273
  %t275 = trunc i64 %t274 to i32
  %t276 = sext i32 %t275 to i64
  %t277 = trunc i64 5 to i32
  %t278 = sext i32 %t277 to i64
  %t279 = sub i64 %t276, %t278
  %t280 = trunc i64 %t279 to i32
  %t281 = sext i32 %t280 to i64
  %t282 = load i64, ptr %t27
  %t283 = inttoptr i64 %t282 to ptr
  %t284 = getelementptr [7 x i64], ptr %t283, i64 0, i64 3
  %t285 = trunc i64 %t281 to i32
  %t286 = sext i32 %t285 to i64
  store i64 %t286, ptr %t284
  br label %ifend21
ifend21:
  %t287 = load i64, ptr %t27
  %t288 = inttoptr i64 %t287 to ptr
  %t289 = getelementptr [7 x i64], ptr %t288, i64 0, i64 1
  %t290 = load i64, ptr %t289
  %t291 = load i64, ptr %t27
  %t292 = inttoptr i64 %t291 to ptr
  %t293 = getelementptr [7 x i64], ptr %t292, i64 0, i64 4
  %t294 = load i64, ptr %t293
  %t295 = trunc i64 %t290 to i32
  %t296 = sext i32 %t295 to i64
  %t297 = trunc i64 %t294 to i32
  %t298 = sext i32 %t297 to i64
  %t299 = icmp eq i64 %t296, %t298
  %t300 = zext i1 %t299 to i64
  %t301 = load i64, ptr %t27
  %t302 = inttoptr i64 %t301 to ptr
  %t303 = getelementptr [7 x i64], ptr %t302, i64 0, i64 2
  %t304 = load i64, ptr %t303
  %t305 = load i64, ptr %t27
  %t306 = inttoptr i64 %t305 to ptr
  %t307 = getelementptr [7 x i64], ptr %t306, i64 0, i64 5
  %t308 = load i64, ptr %t307
  %t309 = trunc i64 %t304 to i32
  %t310 = sext i32 %t309 to i64
  %t311 = trunc i64 %t308 to i32
  %t312 = sext i32 %t311 to i64
  %t313 = icmp eq i64 %t310, %t312
  %t314 = zext i1 %t313 to i64
  %t315 = icmp ne i64 %t300, 0
  %t316 = icmp ne i64 %t314, 0
  %t317 = and i1 %t315, %t316
  %t318 = zext i1 %t317 to i64
  %t319 = icmp ne i64 %t318, 0
  br i1 %t319, label %then22, label %else23
then22:
  %t320 = load i64, ptr %t27
  %t321 = inttoptr i64 %t320 to ptr
  %t322 = load i64, ptr %t27
  %t323 = inttoptr i64 %t322 to ptr
  %t324 = getelementptr [7 x i64], ptr %t323, i64 0, i64 0
  %t325 = load i64, ptr %t324
  %t326 = load i64, ptr %t27
  %t327 = inttoptr i64 %t326 to ptr
  %t328 = getelementptr [7 x i64], ptr %t327, i64 0, i64 3
  %t329 = load i64, ptr %t328
  %t330 = trunc i64 %t325 to i32
  %t331 = sext i32 %t330 to i64
  %t332 = trunc i64 %t329 to i32
  %t333 = sext i32 %t332 to i64
  %t334 = add i64 %t331, %t333
  %t335 = trunc i64 %t334 to i32
  %t336 = sext i32 %t335 to i64
  %t337 = call i64 @update_agent_target(ptr %t321, i64 %t336)
  br label %ifend24
else23:
  br label %ifend24
ifend24:
  %t338 = load i64, ptr %t27
  %t339 = inttoptr i64 %t338 to ptr
  %t340 = getelementptr [7 x i64], ptr %t339, i64 0, i64 3
  %t341 = load i64, ptr %t340
  %t342 = trunc i64 %t341 to i32
  %t343 = sext i32 %t342 to i64
  %t344 = trunc i64 0 to i32
  %t345 = sext i32 %t344 to i64
  %t346 = icmp sle i64 %t343, %t345
  %t347 = zext i1 %t346 to i64
  %t348 = icmp ne i64 %t347, 0
  br i1 %t348, label %then25, label %else26
then25:
  %t349 = load i64, ptr %t27
  %t350 = inttoptr i64 %t349 to ptr
  %t351 = getelementptr [7 x i64], ptr %t350, i64 0, i64 6
  %t352 = zext i1 0 to i64
  %t353 = trunc i64 %t352 to i32
  %t354 = sext i32 %t353 to i64
  store i64 %t354, ptr %t351
  %t355 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t356 = load i64, ptr %t27
  %t357 = inttoptr i64 %t356 to ptr
  %t358 = getelementptr [7 x i64], ptr %t357, i64 0, i64 2
  %t359 = load i64, ptr %t358
  %t360 = mul i64 %t359, 50
  %t361 = getelementptr i64, ptr %t355, i64 %t360
  %t362 = load i64, ptr %t27
  %t363 = inttoptr i64 %t362 to ptr
  %t364 = getelementptr [7 x i64], ptr %t363, i64 0, i64 1
  %t365 = load i64, ptr %t364
  %t366 = mul i64 %t365, 1
  %t367 = getelementptr i64, ptr %t361, i64 %t366
  %t368 = trunc i64 0 to i32
  %t369 = sext i32 %t368 to i64
  store i64 %t369, ptr %t367
  br label %ifend27
else26:
  br label %ifend27
ifend27:
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t370 = load i64, ptr %t1
  %t371 = trunc i64 %t370 to i32
  %t372 = sext i32 %t371 to i64
  %t373 = trunc i64 1 to i32
  %t374 = sext i32 %t373 to i64
  %t375 = add i64 %t372, %t374
  %t376 = trunc i64 %t375 to i32
  %t377 = sext i32 %t376 to i64
  %t378 = trunc i64 %t377 to i32
  %t379 = sext i32 %t378 to i64
  store i64 %t379, ptr %t1
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @process_interactions(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t40 = alloca i64
  store i64 0, ptr %t40
  %t79 = alloca i64
  store i64 0, ptr %t79
  %t89 = alloca i64
  store i64 0, ptr %t89
  %t106 = alloca i64
  store i64 0, ptr %t106
  %t124 = alloca i64
  store i64 0, ptr %t124
  %t270 = alloca i64
  store i64 0, ptr %t270
  %t279 = alloca i64
  store i64 0, ptr %t279
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 20 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t12 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t13 = load i64, ptr %t1
  %t14 = mul i64 %t13, 7
  %t15 = getelementptr i64, ptr %t12, i64 %t14
  %t16 = getelementptr i64, ptr %t15, i64 6
  %t17 = load i64, ptr %t16
  %t18 = icmp ne i64 %t17, 0
  %t19 = xor i1 %t18, 1
  %t20 = zext i1 %t19 to i64
  %t21 = icmp ne i64 %t20, 0
  br i1 %t21, label %then4, label %else5
then4:
  %t22 = load i64, ptr %t1
  %t23 = trunc i64 %t22 to i32
  %t24 = sext i32 %t23 to i64
  %t25 = trunc i64 1 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = add i64 %t24, %t26
  %t28 = trunc i64 %t27 to i32
  %t29 = sext i32 %t28 to i64
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  store i64 %t31, ptr %t1
  br label %while1
else5:
  br label %ifend6
ifend6:
  %t32 = load i64, ptr %t1
  %t33 = trunc i64 %t32 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = trunc i64 1 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = add i64 %t34, %t36
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t41 = trunc i64 %t39 to i32
  %t42 = sext i32 %t41 to i64
  store i64 %t42, ptr %t40
  br label %while7
while7:
  %t43 = load i64, ptr %t40
  %t44 = trunc i64 %t43 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = trunc i64 20 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = icmp slt i64 %t45, %t47
  %t49 = zext i1 %t48 to i64
  %t50 = icmp ne i64 %t49, 0
  br i1 %t50, label %whilebody8, label %whileexit9
whilebody8:
  %t51 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t52 = load i64, ptr %t40
  %t53 = mul i64 %t52, 7
  %t54 = getelementptr i64, ptr %t51, i64 %t53
  %t55 = getelementptr i64, ptr %t54, i64 6
  %t56 = load i64, ptr %t55
  %t57 = icmp ne i64 %t56, 0
  %t58 = xor i1 %t57, 1
  %t59 = zext i1 %t58 to i64
  %t60 = icmp ne i64 %t59, 0
  br i1 %t60, label %then10, label %else11
then10:
  %t61 = load i64, ptr %t40
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 1 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = add i64 %t63, %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = trunc i64 %t68 to i32
  %t70 = sext i32 %t69 to i64
  store i64 %t70, ptr %t40
  br label %while7
else11:
  br label %ifend12
ifend12:
  %t71 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t72 = load i64, ptr %t1
  %t73 = mul i64 %t72, 7
  %t74 = getelementptr i64, ptr %t71, i64 %t73
  %t75 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t76 = load i64, ptr %t1
  %t77 = mul i64 %t76, 7
  %t78 = getelementptr i64, ptr %t75, i64 %t77
  %t80 = ptrtoint ptr %t78 to i64
  store i64 %t80, ptr %t79
  %t81 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t82 = load i64, ptr %t40
  %t83 = mul i64 %t82, 7
  %t84 = getelementptr i64, ptr %t81, i64 %t83
  %t85 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t86 = load i64, ptr %t40
  %t87 = mul i64 %t86, 7
  %t88 = getelementptr i64, ptr %t85, i64 %t87
  %t90 = ptrtoint ptr %t88 to i64
  store i64 %t90, ptr %t89
  %t91 = load i64, ptr %t79
  %t92 = inttoptr i64 %t91 to ptr
  %t93 = getelementptr [7 x i64], ptr %t92, i64 0, i64 1
  %t94 = load i64, ptr %t93
  %t95 = load i64, ptr %t89
  %t96 = inttoptr i64 %t95 to ptr
  %t97 = getelementptr [7 x i64], ptr %t96, i64 0, i64 1
  %t98 = load i64, ptr %t97
  %t99 = trunc i64 %t94 to i32
  %t100 = sext i32 %t99 to i64
  %t101 = trunc i64 %t98 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = sub i64 %t100, %t102
  %t104 = trunc i64 %t103 to i32
  %t105 = sext i32 %t104 to i64
  %t107 = trunc i64 %t105 to i32
  %t108 = sext i32 %t107 to i64
  store i64 %t108, ptr %t106
  %t109 = load i64, ptr %t79
  %t110 = inttoptr i64 %t109 to ptr
  %t111 = getelementptr [7 x i64], ptr %t110, i64 0, i64 2
  %t112 = load i64, ptr %t111
  %t113 = load i64, ptr %t89
  %t114 = inttoptr i64 %t113 to ptr
  %t115 = getelementptr [7 x i64], ptr %t114, i64 0, i64 2
  %t116 = load i64, ptr %t115
  %t117 = trunc i64 %t112 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = trunc i64 %t116 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = sub i64 %t118, %t120
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  %t125 = trunc i64 %t123 to i32
  %t126 = sext i32 %t125 to i64
  store i64 %t126, ptr %t124
  %t127 = load i64, ptr %t106
  %t128 = load i64, ptr %t106
  %t129 = trunc i64 %t127 to i32
  %t130 = sext i32 %t129 to i64
  %t131 = trunc i64 %t128 to i32
  %t132 = sext i32 %t131 to i64
  %t133 = mul i64 %t130, %t132
  %t134 = trunc i64 %t133 to i32
  %t135 = sext i32 %t134 to i64
  %t136 = load i64, ptr %t124
  %t137 = load i64, ptr %t124
  %t138 = trunc i64 %t136 to i32
  %t139 = sext i32 %t138 to i64
  %t140 = trunc i64 %t137 to i32
  %t141 = sext i32 %t140 to i64
  %t142 = mul i64 %t139, %t141
  %t143 = trunc i64 %t142 to i32
  %t144 = sext i32 %t143 to i64
  %t145 = trunc i64 %t135 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = trunc i64 %t144 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = add i64 %t146, %t148
  %t150 = trunc i64 %t149 to i32
  %t151 = sext i32 %t150 to i64
  %t152 = trunc i64 %t151 to i32
  %t153 = sext i32 %t152 to i64
  %t154 = trunc i64 4 to i32
  %t155 = sext i32 %t154 to i64
  %t156 = icmp slt i64 %t153, %t155
  %t157 = zext i1 %t156 to i64
  %t158 = icmp ne i64 %t157, 0
  br i1 %t158, label %then13, label %else14
then13:
  %t159 = load i64, ptr %t79
  %t160 = inttoptr i64 %t159 to ptr
  %t161 = getelementptr [7 x i64], ptr %t160, i64 0, i64 3
  %t162 = load i64, ptr %t161
  %t163 = load i64, ptr %t89
  %t164 = inttoptr i64 %t163 to ptr
  %t165 = getelementptr [7 x i64], ptr %t164, i64 0, i64 3
  %t166 = load i64, ptr %t165
  %t167 = trunc i64 %t162 to i32
  %t168 = sext i32 %t167 to i64
  %t169 = trunc i64 %t166 to i32
  %t170 = sext i32 %t169 to i64
  %t171 = icmp sgt i64 %t168, %t170
  %t172 = zext i1 %t171 to i64
  %t173 = icmp ne i64 %t172, 0
  br i1 %t173, label %then16, label %else17
then16:
  %t174 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t175 = load i64, ptr %t1
  %t176 = mul i64 %t175, 7
  %t177 = getelementptr i64, ptr %t174, i64 %t176
  %t178 = getelementptr i64, ptr %t177, i64 3
  %t179 = load i64, ptr %t178
  %t180 = trunc i64 %t179 to i32
  %t181 = sext i32 %t180 to i64
  %t182 = trunc i64 10 to i32
  %t183 = sext i32 %t182 to i64
  %t184 = add i64 %t181, %t183
  %t185 = trunc i64 %t184 to i32
  %t186 = sext i32 %t185 to i64
  %t187 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t188 = load i64, ptr %t1
  %t189 = mul i64 %t188, 7
  %t190 = getelementptr i64, ptr %t187, i64 %t189
  %t191 = getelementptr i64, ptr %t190, i64 3
  %t192 = trunc i64 %t186 to i32
  %t193 = sext i32 %t192 to i64
  store i64 %t193, ptr %t191
  %t194 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t195 = load i64, ptr %t40
  %t196 = mul i64 %t195, 7
  %t197 = getelementptr i64, ptr %t194, i64 %t196
  %t198 = getelementptr i64, ptr %t197, i64 3
  %t199 = load i64, ptr %t198
  %t200 = trunc i64 %t199 to i32
  %t201 = sext i32 %t200 to i64
  %t202 = trunc i64 10 to i32
  %t203 = sext i32 %t202 to i64
  %t204 = sub i64 %t201, %t203
  %t205 = trunc i64 %t204 to i32
  %t206 = sext i32 %t205 to i64
  %t207 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t208 = load i64, ptr %t40
  %t209 = mul i64 %t208, 7
  %t210 = getelementptr i64, ptr %t207, i64 %t209
  %t211 = getelementptr i64, ptr %t210, i64 3
  %t212 = trunc i64 %t206 to i32
  %t213 = sext i32 %t212 to i64
  store i64 %t213, ptr %t211
  br label %ifend18
else17:
  %t214 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t215 = load i64, ptr %t1
  %t216 = mul i64 %t215, 7
  %t217 = getelementptr i64, ptr %t214, i64 %t216
  %t218 = getelementptr i64, ptr %t217, i64 3
  %t219 = load i64, ptr %t218
  %t220 = trunc i64 %t219 to i32
  %t221 = sext i32 %t220 to i64
  %t222 = trunc i64 10 to i32
  %t223 = sext i32 %t222 to i64
  %t224 = sub i64 %t221, %t223
  %t225 = trunc i64 %t224 to i32
  %t226 = sext i32 %t225 to i64
  %t227 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t228 = load i64, ptr %t1
  %t229 = mul i64 %t228, 7
  %t230 = getelementptr i64, ptr %t227, i64 %t229
  %t231 = getelementptr i64, ptr %t230, i64 3
  %t232 = trunc i64 %t226 to i32
  %t233 = sext i32 %t232 to i64
  store i64 %t233, ptr %t231
  %t234 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t235 = load i64, ptr %t40
  %t236 = mul i64 %t235, 7
  %t237 = getelementptr i64, ptr %t234, i64 %t236
  %t238 = getelementptr i64, ptr %t237, i64 3
  %t239 = load i64, ptr %t238
  %t240 = trunc i64 %t239 to i32
  %t241 = sext i32 %t240 to i64
  %t242 = trunc i64 10 to i32
  %t243 = sext i32 %t242 to i64
  %t244 = add i64 %t241, %t243
  %t245 = trunc i64 %t244 to i32
  %t246 = sext i32 %t245 to i64
  %t247 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t248 = load i64, ptr %t40
  %t249 = mul i64 %t248, 7
  %t250 = getelementptr i64, ptr %t247, i64 %t249
  %t251 = getelementptr i64, ptr %t250, i64 3
  %t252 = trunc i64 %t246 to i32
  %t253 = sext i32 %t252 to i64
  store i64 %t253, ptr %t251
  br label %ifend18
ifend18:
  br label %ifend15
else14:
  br label %ifend15
ifend15:
  %t254 = load i64, ptr %t40
  %t255 = trunc i64 %t254 to i32
  %t256 = sext i32 %t255 to i64
  %t257 = trunc i64 1 to i32
  %t258 = sext i32 %t257 to i64
  %t259 = add i64 %t256, %t258
  %t260 = trunc i64 %t259 to i32
  %t261 = sext i32 %t260 to i64
  %t262 = trunc i64 %t261 to i32
  %t263 = sext i32 %t262 to i64
  store i64 %t263, ptr %t40
  br label %while7
whileexit9:
  %t264 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t265 = load i64, ptr %t1
  %t266 = mul i64 %t265, 7
  %t267 = getelementptr i64, ptr %t264, i64 %t266
  %t268 = getelementptr i64, ptr %t267, i64 1
  %t269 = load i64, ptr %t268
  %t271 = trunc i64 %t269 to i32
  %t272 = sext i32 %t271 to i64
  store i64 %t272, ptr %t270
  %t273 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t274 = load i64, ptr %t1
  %t275 = mul i64 %t274, 7
  %t276 = getelementptr i64, ptr %t273, i64 %t275
  %t277 = getelementptr i64, ptr %t276, i64 2
  %t278 = load i64, ptr %t277
  %t280 = trunc i64 %t278 to i32
  %t281 = sext i32 %t280 to i64
  store i64 %t281, ptr %t279
  %t282 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t283 = load i64, ptr %t279
  %t284 = mul i64 %t283, 50
  %t285 = getelementptr i64, ptr %t282, i64 %t284
  %t286 = load i64, ptr %t270
  %t287 = mul i64 %t286, 1
  %t288 = getelementptr i64, ptr %t285, i64 %t287
  %t289 = load i64, ptr %t288
  %t290 = trunc i64 %t289 to i32
  %t291 = sext i32 %t290 to i64
  %t292 = trunc i64 0 to i32
  %t293 = sext i32 %t292 to i64
  %t294 = icmp slt i64 %t291, %t293
  %t295 = zext i1 %t294 to i64
  %t296 = icmp ne i64 %t295, 0
  br i1 %t296, label %then19, label %else20
then19:
  %t297 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t298 = load i64, ptr %t1
  %t299 = mul i64 %t298, 7
  %t300 = getelementptr i64, ptr %t297, i64 %t299
  %t301 = getelementptr i64, ptr %t300, i64 3
  %t302 = load i64, ptr %t301
  %t303 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t304 = load i64, ptr %t279
  %t305 = mul i64 %t304, 50
  %t306 = getelementptr i64, ptr %t303, i64 %t305
  %t307 = load i64, ptr %t270
  %t308 = mul i64 %t307, 1
  %t309 = getelementptr i64, ptr %t306, i64 %t308
  %t310 = load i64, ptr %t309
  %t311 = trunc i64 %t310 to i32
  %t312 = sext i32 %t311 to i64
  %t313 = trunc i64 -10 to i32
  %t314 = sext i32 %t313 to i64
  %t315 = mul i64 %t312, %t314
  %t316 = trunc i64 %t315 to i32
  %t317 = sext i32 %t316 to i64
  %t318 = trunc i64 %t302 to i32
  %t319 = sext i32 %t318 to i64
  %t320 = trunc i64 %t317 to i32
  %t321 = sext i32 %t320 to i64
  %t322 = add i64 %t319, %t321
  %t323 = trunc i64 %t322 to i32
  %t324 = sext i32 %t323 to i64
  %t325 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t326 = load i64, ptr %t1
  %t327 = mul i64 %t326, 7
  %t328 = getelementptr i64, ptr %t325, i64 %t327
  %t329 = getelementptr i64, ptr %t328, i64 3
  %t330 = trunc i64 %t324 to i32
  %t331 = sext i32 %t330 to i64
  store i64 %t331, ptr %t329
  %t332 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t333 = load i64, ptr %t1
  %t334 = mul i64 %t333, 7
  %t335 = getelementptr i64, ptr %t332, i64 %t334
  %t336 = getelementptr i64, ptr %t335, i64 0
  %t337 = load i64, ptr %t336
  %t338 = trunc i64 %t337 to i32
  %t339 = sext i32 %t338 to i64
  %t340 = trunc i64 1 to i32
  %t341 = sext i32 %t340 to i64
  %t342 = add i64 %t339, %t341
  %t343 = trunc i64 %t342 to i32
  %t344 = sext i32 %t343 to i64
  %t345 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 0
  %t346 = load i64, ptr %t279
  %t347 = mul i64 %t346, 50
  %t348 = getelementptr i64, ptr %t345, i64 %t347
  %t349 = load i64, ptr %t270
  %t350 = mul i64 %t349, 1
  %t351 = getelementptr i64, ptr %t348, i64 %t350
  %t352 = trunc i64 %t344 to i32
  %t353 = sext i32 %t352 to i64
  store i64 %t353, ptr %t351
  br label %ifend21
else20:
  br label %ifend21
ifend21:
  %t354 = load i64, ptr %t1
  %t355 = trunc i64 %t354 to i32
  %t356 = sext i32 %t355 to i64
  %t357 = trunc i64 1 to i32
  %t358 = sext i32 %t357 to i64
  %t359 = add i64 %t356, %t358
  %t360 = trunc i64 %t359 to i32
  %t361 = sext i32 %t360 to i64
  %t362 = trunc i64 %t361 to i32
  %t363 = sext i32 %t362 to i64
  store i64 %t363, ptr %t1
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @run_diagnostics(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 0 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  %t8 = trunc i64 0 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  br label %while1
while1:
  %t10 = load i64, ptr %t7
  %t11 = trunc i64 %t10 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = trunc i64 20 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = icmp slt i64 %t12, %t14
  %t16 = zext i1 %t15 to i64
  %t17 = icmp ne i64 %t16, 0
  br i1 %t17, label %whilebody2, label %whileexit3
whilebody2:
  %t18 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t19 = load i64, ptr %t7
  %t20 = mul i64 %t19, 7
  %t21 = getelementptr i64, ptr %t18, i64 %t20
  %t22 = getelementptr i64, ptr %t21, i64 6
  %t23 = load i64, ptr %t22
  %t24 = icmp ne i64 %t23, 0
  br i1 %t24, label %then4, label %else5
then4:
  %t25 = load i64, ptr %t1
  %t26 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t27 = load i64, ptr %t7
  %t28 = mul i64 %t27, 7
  %t29 = getelementptr i64, ptr %t26, i64 %t28
  %t30 = getelementptr i64, ptr %t29, i64 3
  %t31 = load i64, ptr %t30
  %t32 = trunc i64 %t25 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = trunc i64 %t31 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = add i64 %t33, %t35
  %t37 = trunc i64 %t36 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = trunc i64 %t38 to i32
  %t40 = sext i32 %t39 to i64
  store i64 %t40, ptr %t1
  %t41 = load i64, ptr %t4
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = trunc i64 1 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = add i64 %t43, %t45
  %t47 = trunc i64 %t46 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  store i64 %t50, ptr %t4
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t51 = load i64, ptr %t7
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 1 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = add i64 %t53, %t55
  %t57 = trunc i64 %t56 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = trunc i64 %t58 to i32
  %t60 = sext i32 %t59 to i64
  store i64 %t60, ptr %t7
  br label %while1
whileexit3:
  %t61 = load i64, ptr %t4
  %t62 = trunc i64 100000 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 %t61 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = add i64 %t63, %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = call i64 @printlnInt(i64 %t68)
  %t70 = load i64, ptr %t1
  %t71 = trunc i64 200000 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = trunc i64 %t70 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = add i64 %t72, %t74
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = call i64 @printlnInt(i64 %t77)
  %t79 = call i64 @provoke_error(ptr %p0)
  ret i64 0
}

define i64 @final_report(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 20 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t12 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t13 = load i64, ptr %t1
  %t14 = mul i64 %t13, 7
  %t15 = getelementptr i64, ptr %t12, i64 %t14
  %t16 = getelementptr i64, ptr %t15, i64 6
  %t17 = load i64, ptr %t16
  %t18 = icmp ne i64 %t17, 0
  br i1 %t18, label %then4, label %else5
then4:
  %t19 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t20 = load i64, ptr %t1
  %t21 = mul i64 %t20, 7
  %t22 = getelementptr i64, ptr %t19, i64 %t21
  %t23 = getelementptr i64, ptr %t22, i64 0
  %t24 = load i64, ptr %t23
  %t25 = trunc i64 %t24 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 10000 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = mul i64 %t26, %t28
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t33 = load i64, ptr %t1
  %t34 = mul i64 %t33, 7
  %t35 = getelementptr i64, ptr %t32, i64 %t34
  %t36 = getelementptr i64, ptr %t35, i64 3
  %t37 = load i64, ptr %t36
  %t38 = trunc i64 %t31 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = trunc i64 %t37 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = add i64 %t39, %t41
  %t43 = trunc i64 %t42 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = call i64 @printlnInt(i64 %t44)
  br label %ifend6
else5:
  %t46 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t47 = load i64, ptr %t1
  %t48 = mul i64 %t47, 7
  %t49 = getelementptr i64, ptr %t46, i64 %t48
  %t50 = getelementptr i64, ptr %t49, i64 0
  %t51 = load i64, ptr %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 10000 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = mul i64 %t53, %t55
  %t57 = trunc i64 %t56 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = trunc i64 %t58 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = trunc i64 -1 to i32
  %t62 = sext i32 %t61 to i64
  %t63 = add i64 %t60, %t62
  %t64 = trunc i64 %t63 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = call i64 @printlnInt(i64 %t65)
  br label %ifend6
ifend6:
  %t67 = load i64, ptr %t1
  %t68 = trunc i64 %t67 to i32
  %t69 = sext i32 %t68 to i64
  %t70 = trunc i64 1 to i32
  %t71 = sext i32 %t70 to i64
  %t72 = add i64 %t69, %t71
  %t73 = trunc i64 %t72 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = trunc i64 %t74 to i32
  %t76 = sext i32 %t75 to i64
  store i64 %t76, ptr %t1
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @clamp(i64 %p0, i64 %p1, i64 %p2) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 %p1, ptr %t2
  %t3 = alloca i64
  store i64 %p2, ptr %t3
  %t4 = load i64, ptr %t1
  %t5 = load i64, ptr %t2
  %t6 = trunc i64 %t4 to i32
  %t7 = sext i32 %t6 to i64
  %t8 = trunc i64 %t5 to i32
  %t9 = sext i32 %t8 to i64
  %t10 = icmp slt i64 %t7, %t9
  %t11 = zext i1 %t10 to i64
  %t12 = icmp ne i64 %t11, 0
  br i1 %t12, label %then1, label %else2
then1:
  %t13 = load i64, ptr %t2
  ret i64 %t13
else2:
  br label %ifend3
ifend3:
  %t14 = load i64, ptr %t1
  %t15 = load i64, ptr %t3
  %t16 = trunc i64 %t14 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 %t15 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = icmp sgt i64 %t17, %t19
  %t21 = zext i1 %t20 to i64
  %t22 = icmp ne i64 %t21, 0
  br i1 %t22, label %then4, label %else5
then4:
  %t23 = load i64, ptr %t3
  ret i64 %t23
else5:
  br label %ifend6
ifend6:
  %t24 = load i64, ptr %t1
  ret i64 %t24
}

define i64 @provoke_error(ptr %p0) {
entry:
  %t4 = alloca [7 x i64]
  %t8 = alloca i64
  store i64 0, ptr %t8
  %t43 = alloca [7 x i64]
  %t85 = alloca i64
  store i64 0, ptr %t85
  %t88 = alloca i64
  store i64 0, ptr %t88
  %t1 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t2 = mul i64 0, 7
  %t3 = getelementptr i64, ptr %t1, i64 %t2
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 56, i1 false)
  %t5 = getelementptr [7 x i64], ptr %t4, i64 0, i64 3
  %t6 = trunc i64 -100 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t9 = trunc i64 0 to i32
  %t10 = sext i32 %t9 to i64
  store i64 %t10, ptr %t8
  br label %while1
while1:
  %t11 = load i64, ptr %t8
  %t12 = trunc i64 %t11 to i32
  %t13 = sext i32 %t12 to i64
  %t14 = trunc i64 20 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = icmp slt i64 %t13, %t15
  %t17 = zext i1 %t16 to i64
  %t18 = icmp ne i64 %t17, 0
  br i1 %t18, label %whilebody2, label %whileexit3
whilebody2:
  %t19 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t20 = load i64, ptr %t8
  %t21 = mul i64 %t20, 7
  %t22 = getelementptr i64, ptr %t19, i64 %t21
  %t23 = getelementptr i64, ptr %t22, i64 6
  %t24 = load i64, ptr %t23
  %t25 = icmp ne i64 %t24, 0
  br i1 %t25, label %then4, label %else5
then4:
  %t26 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t27 = load i64, ptr %t8
  %t28 = mul i64 %t27, 7
  %t29 = getelementptr i64, ptr %t26, i64 %t28
  %t30 = getelementptr i64, ptr %t29, i64 3
  %t31 = load i64, ptr %t30
  %t32 = trunc i64 %t31 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = trunc i64 150 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = icmp sgt i64 %t33, %t35
  %t37 = zext i1 %t36 to i64
  %t38 = icmp ne i64 %t37, 0
  br i1 %t38, label %then7, label %else8
then7:
  %t39 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t40 = load i64, ptr %t8
  %t41 = mul i64 %t40, 7
  %t42 = getelementptr i64, ptr %t39, i64 %t41
  call void @llvm.memcpy.p0.p0.i64(ptr %t43, ptr %t42, i64 56, i1 false)
  %t44 = getelementptr [7 x i64], ptr %t43, i64 0, i64 3
  %t45 = load i64, ptr %t44
  %t46 = trunc i64 %t45 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = trunc i64 2 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = sdiv i64 %t47, %t49
  %t51 = trunc i64 %t50 to i32
  %t52 = sext i32 %t51 to i64
  %t53 = getelementptr [7 x i64], ptr %t43, i64 0, i64 3
  %t54 = trunc i64 %t52 to i32
  %t55 = sext i32 %t54 to i64
  store i64 %t55, ptr %t53
  %t56 = getelementptr [7 x i64], ptr %t43, i64 0, i64 3
  %t57 = load i64, ptr %t56
  %t58 = trunc i64 %t57 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = trunc i64 100 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = icmp sgt i64 %t59, %t61
  %t63 = zext i1 %t62 to i64
  %t64 = icmp ne i64 %t63, 0
  br i1 %t64, label %then10, label %else11
then10:
  %t65 = getelementptr [7 x i64], ptr %t43, i64 0, i64 0
  %t66 = load i64, ptr %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = trunc i64 5000 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = add i64 %t68, %t70
  %t72 = trunc i64 %t71 to i32
  %t73 = sext i32 %t72 to i64
  %t74 = call i64 @printlnInt(i64 %t73)
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  br label %ifend9
else8:
  br label %ifend9
ifend9:
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t75 = load i64, ptr %t8
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = trunc i64 1 to i32
  %t79 = sext i32 %t78 to i64
  %t80 = add i64 %t77, %t79
  %t81 = trunc i64 %t80 to i32
  %t82 = sext i32 %t81 to i64
  %t83 = trunc i64 %t82 to i32
  %t84 = sext i32 %t83 to i64
  store i64 %t84, ptr %t8
  br label %while1
whileexit3:
  %t86 = trunc i64 -1 to i32
  %t87 = sext i32 %t86 to i64
  store i64 %t87, ptr %t85
  %t89 = trunc i64 -1 to i32
  %t90 = sext i32 %t89 to i64
  store i64 %t90, ptr %t88
  %t91 = trunc i64 0 to i32
  %t92 = sext i32 %t91 to i64
  store i64 %t92, ptr %t8
  br label %while13
while13:
  %t93 = load i64, ptr %t8
  %t94 = trunc i64 %t93 to i32
  %t95 = sext i32 %t94 to i64
  %t96 = trunc i64 20 to i32
  %t97 = sext i32 %t96 to i64
  %t98 = icmp slt i64 %t95, %t97
  %t99 = zext i1 %t98 to i64
  %t100 = icmp ne i64 %t99, 0
  br i1 %t100, label %whilebody14, label %whileexit15
whilebody14:
  %t101 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t102 = load i64, ptr %t8
  %t103 = mul i64 %t102, 7
  %t104 = getelementptr i64, ptr %t101, i64 %t103
  %t105 = getelementptr i64, ptr %t104, i64 6
  %t106 = load i64, ptr %t105
  %t107 = icmp ne i64 %t106, 0
  br i1 %t107, label %then16, label %else17
then16:
  %t108 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t109 = load i64, ptr %t8
  %t110 = mul i64 %t109, 7
  %t111 = getelementptr i64, ptr %t108, i64 %t110
  %t112 = getelementptr i64, ptr %t111, i64 3
  %t113 = load i64, ptr %t112
  %t114 = load i64, ptr %t88
  %t115 = trunc i64 %t113 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 %t114 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = icmp sgt i64 %t116, %t118
  %t120 = zext i1 %t119 to i64
  %t121 = icmp ne i64 %t120, 0
  br i1 %t121, label %then19, label %else20
then19:
  %t122 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t123 = load i64, ptr %t8
  %t124 = mul i64 %t123, 7
  %t125 = getelementptr i64, ptr %t122, i64 %t124
  %t126 = getelementptr i64, ptr %t125, i64 3
  %t127 = load i64, ptr %t126
  %t128 = trunc i64 %t127 to i32
  %t129 = sext i32 %t128 to i64
  store i64 %t129, ptr %t88
  %t130 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t131 = load i64, ptr %t8
  %t132 = mul i64 %t131, 7
  %t133 = getelementptr i64, ptr %t130, i64 %t132
  %t134 = getelementptr i64, ptr %t133, i64 0
  %t135 = load i64, ptr %t134
  %t136 = trunc i64 %t135 to i32
  %t137 = sext i32 %t136 to i64
  store i64 %t137, ptr %t85
  br label %ifend21
else20:
  br label %ifend21
ifend21:
  br label %ifend18
else17:
  br label %ifend18
ifend18:
  %t138 = load i64, ptr %t8
  %t139 = trunc i64 %t138 to i32
  %t140 = sext i32 %t139 to i64
  %t141 = trunc i64 1 to i32
  %t142 = sext i32 %t141 to i64
  %t143 = add i64 %t140, %t142
  %t144 = trunc i64 %t143 to i32
  %t145 = sext i32 %t144 to i64
  %t146 = trunc i64 %t145 to i32
  %t147 = sext i32 %t146 to i64
  store i64 %t147, ptr %t8
  br label %while13
whileexit15:
  %t148 = load i64, ptr %t85
  %t149 = trunc i64 %t148 to i32
  %t150 = sext i32 %t149 to i64
  %t151 = trunc i64 -1 to i32
  %t152 = sext i32 %t151 to i64
  %t153 = icmp ne i64 %t150, %t152
  %t154 = zext i1 %t153 to i64
  %t155 = icmp ne i64 %t154, 0
  br i1 %t155, label %then22, label %else23
then22:
  %t156 = getelementptr [2640 x i64], ptr %p0, i64 0, i64 2500
  %t157 = load i64, ptr %t85
  %t158 = mul i64 %t157, 7
  %t159 = getelementptr i64, ptr %t156, i64 %t158
  %t160 = getelementptr i64, ptr %t159, i64 3
  %t161 = trunc i64 0 to i32
  %t162 = sext i32 %t161 to i64
  store i64 %t162, ptr %t160
  br label %ifend24
else23:
  br label %ifend24
ifend24:
  ret i64 0
}

define i64 @another_simulation_scenario() {
entry:
  %t100 = alloca [2640 x i64]
  %t102 = alloca i64
  store i64 0, ptr %t102
  %t1 = alloca [2640 x i64]
  %t2 = alloca [2500 x i64]
  %t3 = alloca [50 x i64]
  call void @llvm.memset.p0.i64(ptr %t3, i8 0, i64 400, i1 false)
  %t4 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 400, i1 false)
  %t5 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 50
  call void @llvm.memcpy.p0.p0.i64(ptr %t5, ptr %t3, i64 400, i1 false)
  %t6 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 100
  call void @llvm.memcpy.p0.p0.i64(ptr %t6, ptr %t3, i64 400, i1 false)
  %t7 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 150
  call void @llvm.memcpy.p0.p0.i64(ptr %t7, ptr %t3, i64 400, i1 false)
  %t8 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 200
  call void @llvm.memcpy.p0.p0.i64(ptr %t8, ptr %t3, i64 400, i1 false)
  %t9 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 250
  call void @llvm.memcpy.p0.p0.i64(ptr %t9, ptr %t3, i64 400, i1 false)
  %t10 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 300
  call void @llvm.memcpy.p0.p0.i64(ptr %t10, ptr %t3, i64 400, i1 false)
  %t11 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 350
  call void @llvm.memcpy.p0.p0.i64(ptr %t11, ptr %t3, i64 400, i1 false)
  %t12 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 400
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t3, i64 400, i1 false)
  %t13 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 450
  call void @llvm.memcpy.p0.p0.i64(ptr %t13, ptr %t3, i64 400, i1 false)
  %t14 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 500
  call void @llvm.memcpy.p0.p0.i64(ptr %t14, ptr %t3, i64 400, i1 false)
  %t15 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 550
  call void @llvm.memcpy.p0.p0.i64(ptr %t15, ptr %t3, i64 400, i1 false)
  %t16 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 600
  call void @llvm.memcpy.p0.p0.i64(ptr %t16, ptr %t3, i64 400, i1 false)
  %t17 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 650
  call void @llvm.memcpy.p0.p0.i64(ptr %t17, ptr %t3, i64 400, i1 false)
  %t18 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 700
  call void @llvm.memcpy.p0.p0.i64(ptr %t18, ptr %t3, i64 400, i1 false)
  %t19 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 750
  call void @llvm.memcpy.p0.p0.i64(ptr %t19, ptr %t3, i64 400, i1 false)
  %t20 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 800
  call void @llvm.memcpy.p0.p0.i64(ptr %t20, ptr %t3, i64 400, i1 false)
  %t21 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 850
  call void @llvm.memcpy.p0.p0.i64(ptr %t21, ptr %t3, i64 400, i1 false)
  %t22 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 900
  call void @llvm.memcpy.p0.p0.i64(ptr %t22, ptr %t3, i64 400, i1 false)
  %t23 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 950
  call void @llvm.memcpy.p0.p0.i64(ptr %t23, ptr %t3, i64 400, i1 false)
  %t24 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1000
  call void @llvm.memcpy.p0.p0.i64(ptr %t24, ptr %t3, i64 400, i1 false)
  %t25 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1050
  call void @llvm.memcpy.p0.p0.i64(ptr %t25, ptr %t3, i64 400, i1 false)
  %t26 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1100
  call void @llvm.memcpy.p0.p0.i64(ptr %t26, ptr %t3, i64 400, i1 false)
  %t27 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1150
  call void @llvm.memcpy.p0.p0.i64(ptr %t27, ptr %t3, i64 400, i1 false)
  %t28 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1200
  call void @llvm.memcpy.p0.p0.i64(ptr %t28, ptr %t3, i64 400, i1 false)
  %t29 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1250
  call void @llvm.memcpy.p0.p0.i64(ptr %t29, ptr %t3, i64 400, i1 false)
  %t30 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1300
  call void @llvm.memcpy.p0.p0.i64(ptr %t30, ptr %t3, i64 400, i1 false)
  %t31 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1350
  call void @llvm.memcpy.p0.p0.i64(ptr %t31, ptr %t3, i64 400, i1 false)
  %t32 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1400
  call void @llvm.memcpy.p0.p0.i64(ptr %t32, ptr %t3, i64 400, i1 false)
  %t33 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1450
  call void @llvm.memcpy.p0.p0.i64(ptr %t33, ptr %t3, i64 400, i1 false)
  %t34 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1500
  call void @llvm.memcpy.p0.p0.i64(ptr %t34, ptr %t3, i64 400, i1 false)
  %t35 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1550
  call void @llvm.memcpy.p0.p0.i64(ptr %t35, ptr %t3, i64 400, i1 false)
  %t36 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1600
  call void @llvm.memcpy.p0.p0.i64(ptr %t36, ptr %t3, i64 400, i1 false)
  %t37 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1650
  call void @llvm.memcpy.p0.p0.i64(ptr %t37, ptr %t3, i64 400, i1 false)
  %t38 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1700
  call void @llvm.memcpy.p0.p0.i64(ptr %t38, ptr %t3, i64 400, i1 false)
  %t39 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1750
  call void @llvm.memcpy.p0.p0.i64(ptr %t39, ptr %t3, i64 400, i1 false)
  %t40 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1800
  call void @llvm.memcpy.p0.p0.i64(ptr %t40, ptr %t3, i64 400, i1 false)
  %t41 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1850
  call void @llvm.memcpy.p0.p0.i64(ptr %t41, ptr %t3, i64 400, i1 false)
  %t42 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1900
  call void @llvm.memcpy.p0.p0.i64(ptr %t42, ptr %t3, i64 400, i1 false)
  %t43 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 1950
  call void @llvm.memcpy.p0.p0.i64(ptr %t43, ptr %t3, i64 400, i1 false)
  %t44 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2000
  call void @llvm.memcpy.p0.p0.i64(ptr %t44, ptr %t3, i64 400, i1 false)
  %t45 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2050
  call void @llvm.memcpy.p0.p0.i64(ptr %t45, ptr %t3, i64 400, i1 false)
  %t46 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2100
  call void @llvm.memcpy.p0.p0.i64(ptr %t46, ptr %t3, i64 400, i1 false)
  %t47 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2150
  call void @llvm.memcpy.p0.p0.i64(ptr %t47, ptr %t3, i64 400, i1 false)
  %t48 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2200
  call void @llvm.memcpy.p0.p0.i64(ptr %t48, ptr %t3, i64 400, i1 false)
  %t49 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2250
  call void @llvm.memcpy.p0.p0.i64(ptr %t49, ptr %t3, i64 400, i1 false)
  %t50 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2300
  call void @llvm.memcpy.p0.p0.i64(ptr %t50, ptr %t3, i64 400, i1 false)
  %t51 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2350
  call void @llvm.memcpy.p0.p0.i64(ptr %t51, ptr %t3, i64 400, i1 false)
  %t52 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2400
  call void @llvm.memcpy.p0.p0.i64(ptr %t52, ptr %t3, i64 400, i1 false)
  %t53 = getelementptr [2500 x i64], ptr %t2, i64 0, i64 2450
  call void @llvm.memcpy.p0.p0.i64(ptr %t53, ptr %t3, i64 400, i1 false)
  %t54 = getelementptr [2640 x i64], ptr %t1, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t54, ptr %t2, i64 20000, i1 false)
  %t55 = alloca [140 x i64]
  %t56 = alloca [7 x i64]
  %t57 = trunc i64 0 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = getelementptr [7 x i64], ptr %t56, i64 0, i64 0
  store i64 %t58, ptr %t59
  %t60 = trunc i64 0 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = getelementptr [7 x i64], ptr %t56, i64 0, i64 1
  store i64 %t61, ptr %t62
  %t63 = trunc i64 0 to i32
  %t64 = sext i32 %t63 to i64
  %t65 = getelementptr [7 x i64], ptr %t56, i64 0, i64 2
  store i64 %t64, ptr %t65
  %t66 = trunc i64 0 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = getelementptr [7 x i64], ptr %t56, i64 0, i64 3
  store i64 %t67, ptr %t68
  %t69 = trunc i64 0 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = getelementptr [7 x i64], ptr %t56, i64 0, i64 4
  store i64 %t70, ptr %t71
  %t72 = trunc i64 0 to i32
  %t73 = sext i32 %t72 to i64
  %t74 = getelementptr [7 x i64], ptr %t56, i64 0, i64 5
  store i64 %t73, ptr %t74
  %t75 = zext i1 0 to i64
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = getelementptr [7 x i64], ptr %t56, i64 0, i64 6
  store i64 %t77, ptr %t78
  %t79 = getelementptr [140 x i64], ptr %t55, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t79, ptr %t56, i64 56, i1 false)
  %t80 = getelementptr [140 x i64], ptr %t55, i64 0, i64 7
  call void @llvm.memcpy.p0.p0.i64(ptr %t80, ptr %t56, i64 56, i1 false)
  %t81 = getelementptr [140 x i64], ptr %t55, i64 0, i64 14
  call void @llvm.memcpy.p0.p0.i64(ptr %t81, ptr %t56, i64 56, i1 false)
  %t82 = getelementptr [140 x i64], ptr %t55, i64 0, i64 21
  call void @llvm.memcpy.p0.p0.i64(ptr %t82, ptr %t56, i64 56, i1 false)
  %t83 = getelementptr [140 x i64], ptr %t55, i64 0, i64 28
  call void @llvm.memcpy.p0.p0.i64(ptr %t83, ptr %t56, i64 56, i1 false)
  %t84 = getelementptr [140 x i64], ptr %t55, i64 0, i64 35
  call void @llvm.memcpy.p0.p0.i64(ptr %t84, ptr %t56, i64 56, i1 false)
  %t85 = getelementptr [140 x i64], ptr %t55, i64 0, i64 42
  call void @llvm.memcpy.p0.p0.i64(ptr %t85, ptr %t56, i64 56, i1 false)
  %t86 = getelementptr [140 x i64], ptr %t55, i64 0, i64 49
  call void @llvm.memcpy.p0.p0.i64(ptr %t86, ptr %t56, i64 56, i1 false)
  %t87 = getelementptr [140 x i64], ptr %t55, i64 0, i64 56
  call void @llvm.memcpy.p0.p0.i64(ptr %t87, ptr %t56, i64 56, i1 false)
  %t88 = getelementptr [140 x i64], ptr %t55, i64 0, i64 63
  call void @llvm.memcpy.p0.p0.i64(ptr %t88, ptr %t56, i64 56, i1 false)
  %t89 = getelementptr [140 x i64], ptr %t55, i64 0, i64 70
  call void @llvm.memcpy.p0.p0.i64(ptr %t89, ptr %t56, i64 56, i1 false)
  %t90 = getelementptr [140 x i64], ptr %t55, i64 0, i64 77
  call void @llvm.memcpy.p0.p0.i64(ptr %t90, ptr %t56, i64 56, i1 false)
  %t91 = getelementptr [140 x i64], ptr %t55, i64 0, i64 84
  call void @llvm.memcpy.p0.p0.i64(ptr %t91, ptr %t56, i64 56, i1 false)
  %t92 = getelementptr [140 x i64], ptr %t55, i64 0, i64 91
  call void @llvm.memcpy.p0.p0.i64(ptr %t92, ptr %t56, i64 56, i1 false)
  %t93 = getelementptr [140 x i64], ptr %t55, i64 0, i64 98
  call void @llvm.memcpy.p0.p0.i64(ptr %t93, ptr %t56, i64 56, i1 false)
  %t94 = getelementptr [140 x i64], ptr %t55, i64 0, i64 105
  call void @llvm.memcpy.p0.p0.i64(ptr %t94, ptr %t56, i64 56, i1 false)
  %t95 = getelementptr [140 x i64], ptr %t55, i64 0, i64 112
  call void @llvm.memcpy.p0.p0.i64(ptr %t95, ptr %t56, i64 56, i1 false)
  %t96 = getelementptr [140 x i64], ptr %t55, i64 0, i64 119
  call void @llvm.memcpy.p0.p0.i64(ptr %t96, ptr %t56, i64 56, i1 false)
  %t97 = getelementptr [140 x i64], ptr %t55, i64 0, i64 126
  call void @llvm.memcpy.p0.p0.i64(ptr %t97, ptr %t56, i64 56, i1 false)
  %t98 = getelementptr [140 x i64], ptr %t55, i64 0, i64 133
  call void @llvm.memcpy.p0.p0.i64(ptr %t98, ptr %t56, i64 56, i1 false)
  %t99 = getelementptr [2640 x i64], ptr %t1, i64 0, i64 2500
  call void @llvm.memcpy.p0.p0.i64(ptr %t99, ptr %t55, i64 1120, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t100, ptr %t1, i64 21120, i1 false)
  %t101 = call i64 @initialize_world(ptr %t100, i64 11223)
  %t103 = trunc i64 0 to i32
  %t104 = sext i32 %t103 to i64
  store i64 %t104, ptr %t102
  br label %while1
while1:
  %t105 = load i64, ptr %t102
  %t106 = trunc i64 %t105 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = trunc i64 50 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = icmp slt i64 %t107, %t109
  %t111 = zext i1 %t110 to i64
  %t112 = icmp ne i64 %t111, 0
  br i1 %t112, label %whilebody2, label %whileexit3
whilebody2:
  %t113 = call i64 @update_world(ptr %t100)
  %t114 = load i64, ptr %t102
  %t115 = trunc i64 %t114 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 1 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = add i64 %t116, %t118
  %t120 = trunc i64 %t119 to i32
  %t121 = sext i32 %t120 to i64
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  store i64 %t123, ptr %t102
  br label %while1
whileexit3:
  %t124 = call i64 @process_interactions(ptr %t100)
  %t125 = call i64 @final_report(ptr %t100)
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

