; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t67 = alloca [4096 x i64]
  %t99 = alloca [28 x i64]
  %t118 = alloca [8 x i64]
  %t120 = alloca i64
  store i64 0, ptr %t120
  %t123 = alloca i64
  store i64 0, ptr %t123
  %t126 = alloca i64
  store i64 0, ptr %t126
  %t138 = alloca i64
  store i64 0, ptr %t138
  %t222 = alloca [3 x i64]
  %t236 = alloca [6 x i64]
  %t237 = alloca i64
  store i64 0, ptr %t237
  %t250 = alloca [3 x i64]
  %t251 = alloca i64
  store i64 0, ptr %t251
  %t269 = alloca i64
  store i64 0, ptr %t269
  %t364 = alloca i64
  store i64 0, ptr %t364
  %t378 = alloca i64
  store i64 0, ptr %t378
  %t1 = alloca [4096 x i64]
  %t2 = alloca [64 x i64]
  call void @llvm.memset.p0.i64(ptr %t2, i8 0, i64 512, i1 false)
  %t3 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t3, ptr %t2, i64 512, i1 false)
  %t4 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 64
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t2, i64 512, i1 false)
  %t5 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 128
  call void @llvm.memcpy.p0.p0.i64(ptr %t5, ptr %t2, i64 512, i1 false)
  %t6 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 192
  call void @llvm.memcpy.p0.p0.i64(ptr %t6, ptr %t2, i64 512, i1 false)
  %t7 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 256
  call void @llvm.memcpy.p0.p0.i64(ptr %t7, ptr %t2, i64 512, i1 false)
  %t8 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 320
  call void @llvm.memcpy.p0.p0.i64(ptr %t8, ptr %t2, i64 512, i1 false)
  %t9 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 384
  call void @llvm.memcpy.p0.p0.i64(ptr %t9, ptr %t2, i64 512, i1 false)
  %t10 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 448
  call void @llvm.memcpy.p0.p0.i64(ptr %t10, ptr %t2, i64 512, i1 false)
  %t11 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 512
  call void @llvm.memcpy.p0.p0.i64(ptr %t11, ptr %t2, i64 512, i1 false)
  %t12 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 576
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t2, i64 512, i1 false)
  %t13 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 640
  call void @llvm.memcpy.p0.p0.i64(ptr %t13, ptr %t2, i64 512, i1 false)
  %t14 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 704
  call void @llvm.memcpy.p0.p0.i64(ptr %t14, ptr %t2, i64 512, i1 false)
  %t15 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 768
  call void @llvm.memcpy.p0.p0.i64(ptr %t15, ptr %t2, i64 512, i1 false)
  %t16 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 832
  call void @llvm.memcpy.p0.p0.i64(ptr %t16, ptr %t2, i64 512, i1 false)
  %t17 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 896
  call void @llvm.memcpy.p0.p0.i64(ptr %t17, ptr %t2, i64 512, i1 false)
  %t18 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 960
  call void @llvm.memcpy.p0.p0.i64(ptr %t18, ptr %t2, i64 512, i1 false)
  %t19 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1024
  call void @llvm.memcpy.p0.p0.i64(ptr %t19, ptr %t2, i64 512, i1 false)
  %t20 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1088
  call void @llvm.memcpy.p0.p0.i64(ptr %t20, ptr %t2, i64 512, i1 false)
  %t21 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1152
  call void @llvm.memcpy.p0.p0.i64(ptr %t21, ptr %t2, i64 512, i1 false)
  %t22 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1216
  call void @llvm.memcpy.p0.p0.i64(ptr %t22, ptr %t2, i64 512, i1 false)
  %t23 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1280
  call void @llvm.memcpy.p0.p0.i64(ptr %t23, ptr %t2, i64 512, i1 false)
  %t24 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1344
  call void @llvm.memcpy.p0.p0.i64(ptr %t24, ptr %t2, i64 512, i1 false)
  %t25 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1408
  call void @llvm.memcpy.p0.p0.i64(ptr %t25, ptr %t2, i64 512, i1 false)
  %t26 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1472
  call void @llvm.memcpy.p0.p0.i64(ptr %t26, ptr %t2, i64 512, i1 false)
  %t27 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1536
  call void @llvm.memcpy.p0.p0.i64(ptr %t27, ptr %t2, i64 512, i1 false)
  %t28 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1600
  call void @llvm.memcpy.p0.p0.i64(ptr %t28, ptr %t2, i64 512, i1 false)
  %t29 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1664
  call void @llvm.memcpy.p0.p0.i64(ptr %t29, ptr %t2, i64 512, i1 false)
  %t30 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1728
  call void @llvm.memcpy.p0.p0.i64(ptr %t30, ptr %t2, i64 512, i1 false)
  %t31 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1792
  call void @llvm.memcpy.p0.p0.i64(ptr %t31, ptr %t2, i64 512, i1 false)
  %t32 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1856
  call void @llvm.memcpy.p0.p0.i64(ptr %t32, ptr %t2, i64 512, i1 false)
  %t33 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1920
  call void @llvm.memcpy.p0.p0.i64(ptr %t33, ptr %t2, i64 512, i1 false)
  %t34 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 1984
  call void @llvm.memcpy.p0.p0.i64(ptr %t34, ptr %t2, i64 512, i1 false)
  %t35 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2048
  call void @llvm.memcpy.p0.p0.i64(ptr %t35, ptr %t2, i64 512, i1 false)
  %t36 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2112
  call void @llvm.memcpy.p0.p0.i64(ptr %t36, ptr %t2, i64 512, i1 false)
  %t37 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2176
  call void @llvm.memcpy.p0.p0.i64(ptr %t37, ptr %t2, i64 512, i1 false)
  %t38 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2240
  call void @llvm.memcpy.p0.p0.i64(ptr %t38, ptr %t2, i64 512, i1 false)
  %t39 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2304
  call void @llvm.memcpy.p0.p0.i64(ptr %t39, ptr %t2, i64 512, i1 false)
  %t40 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2368
  call void @llvm.memcpy.p0.p0.i64(ptr %t40, ptr %t2, i64 512, i1 false)
  %t41 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2432
  call void @llvm.memcpy.p0.p0.i64(ptr %t41, ptr %t2, i64 512, i1 false)
  %t42 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2496
  call void @llvm.memcpy.p0.p0.i64(ptr %t42, ptr %t2, i64 512, i1 false)
  %t43 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2560
  call void @llvm.memcpy.p0.p0.i64(ptr %t43, ptr %t2, i64 512, i1 false)
  %t44 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2624
  call void @llvm.memcpy.p0.p0.i64(ptr %t44, ptr %t2, i64 512, i1 false)
  %t45 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2688
  call void @llvm.memcpy.p0.p0.i64(ptr %t45, ptr %t2, i64 512, i1 false)
  %t46 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2752
  call void @llvm.memcpy.p0.p0.i64(ptr %t46, ptr %t2, i64 512, i1 false)
  %t47 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2816
  call void @llvm.memcpy.p0.p0.i64(ptr %t47, ptr %t2, i64 512, i1 false)
  %t48 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2880
  call void @llvm.memcpy.p0.p0.i64(ptr %t48, ptr %t2, i64 512, i1 false)
  %t49 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 2944
  call void @llvm.memcpy.p0.p0.i64(ptr %t49, ptr %t2, i64 512, i1 false)
  %t50 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3008
  call void @llvm.memcpy.p0.p0.i64(ptr %t50, ptr %t2, i64 512, i1 false)
  %t51 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3072
  call void @llvm.memcpy.p0.p0.i64(ptr %t51, ptr %t2, i64 512, i1 false)
  %t52 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3136
  call void @llvm.memcpy.p0.p0.i64(ptr %t52, ptr %t2, i64 512, i1 false)
  %t53 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3200
  call void @llvm.memcpy.p0.p0.i64(ptr %t53, ptr %t2, i64 512, i1 false)
  %t54 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3264
  call void @llvm.memcpy.p0.p0.i64(ptr %t54, ptr %t2, i64 512, i1 false)
  %t55 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3328
  call void @llvm.memcpy.p0.p0.i64(ptr %t55, ptr %t2, i64 512, i1 false)
  %t56 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3392
  call void @llvm.memcpy.p0.p0.i64(ptr %t56, ptr %t2, i64 512, i1 false)
  %t57 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3456
  call void @llvm.memcpy.p0.p0.i64(ptr %t57, ptr %t2, i64 512, i1 false)
  %t58 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3520
  call void @llvm.memcpy.p0.p0.i64(ptr %t58, ptr %t2, i64 512, i1 false)
  %t59 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3584
  call void @llvm.memcpy.p0.p0.i64(ptr %t59, ptr %t2, i64 512, i1 false)
  %t60 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3648
  call void @llvm.memcpy.p0.p0.i64(ptr %t60, ptr %t2, i64 512, i1 false)
  %t61 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3712
  call void @llvm.memcpy.p0.p0.i64(ptr %t61, ptr %t2, i64 512, i1 false)
  %t62 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3776
  call void @llvm.memcpy.p0.p0.i64(ptr %t62, ptr %t2, i64 512, i1 false)
  %t63 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3840
  call void @llvm.memcpy.p0.p0.i64(ptr %t63, ptr %t2, i64 512, i1 false)
  %t64 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3904
  call void @llvm.memcpy.p0.p0.i64(ptr %t64, ptr %t2, i64 512, i1 false)
  %t65 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 3968
  call void @llvm.memcpy.p0.p0.i64(ptr %t65, ptr %t2, i64 512, i1 false)
  %t66 = getelementptr [4096 x i64], ptr %t1, i64 0, i64 4032
  call void @llvm.memcpy.p0.p0.i64(ptr %t66, ptr %t2, i64 512, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t67, ptr %t1, i64 32768, i1 false)
  %t68 = alloca [28 x i64]
  %t69 = alloca [7 x i64]
  %t70 = alloca [3 x i64]
  %t71 = trunc i64 0 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = getelementptr [3 x i64], ptr %t70, i64 0, i64 0
  store i64 %t72, ptr %t73
  %t74 = trunc i64 0 to i32
  %t75 = sext i32 %t74 to i64
  %t76 = getelementptr [3 x i64], ptr %t70, i64 0, i64 1
  store i64 %t75, ptr %t76
  %t77 = trunc i64 0 to i32
  %t78 = sext i32 %t77 to i64
  %t79 = getelementptr [3 x i64], ptr %t70, i64 0, i64 2
  store i64 %t78, ptr %t79
  %t80 = getelementptr [7 x i64], ptr %t69, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t80, ptr %t70, i64 24, i1 false)
  %t81 = trunc i64 0 to i32
  %t82 = sext i32 %t81 to i64
  %t83 = getelementptr [7 x i64], ptr %t69, i64 0, i64 3
  store i64 %t82, ptr %t83
  %t84 = alloca [3 x i64]
  %t85 = trunc i64 0 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = getelementptr [3 x i64], ptr %t84, i64 0, i64 0
  store i64 %t86, ptr %t87
  %t88 = trunc i64 0 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = getelementptr [3 x i64], ptr %t84, i64 0, i64 1
  store i64 %t89, ptr %t90
  %t91 = trunc i64 0 to i32
  %t92 = sext i32 %t91 to i64
  %t93 = getelementptr [3 x i64], ptr %t84, i64 0, i64 2
  store i64 %t92, ptr %t93
  %t94 = getelementptr [7 x i64], ptr %t69, i64 0, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t94, ptr %t84, i64 24, i1 false)
  %t95 = getelementptr [28 x i64], ptr %t68, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t95, ptr %t69, i64 56, i1 false)
  %t96 = getelementptr [28 x i64], ptr %t68, i64 0, i64 7
  call void @llvm.memcpy.p0.p0.i64(ptr %t96, ptr %t69, i64 56, i1 false)
  %t97 = getelementptr [28 x i64], ptr %t68, i64 0, i64 14
  call void @llvm.memcpy.p0.p0.i64(ptr %t97, ptr %t69, i64 56, i1 false)
  %t98 = getelementptr [28 x i64], ptr %t68, i64 0, i64 21
  call void @llvm.memcpy.p0.p0.i64(ptr %t98, ptr %t69, i64 56, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t99, ptr %t68, i64 224, i1 false)
  %t100 = alloca [8 x i64]
  %t101 = alloca [4 x i64]
  %t102 = alloca [3 x i64]
  %t103 = trunc i64 0 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = getelementptr [3 x i64], ptr %t102, i64 0, i64 0
  store i64 %t104, ptr %t105
  %t106 = trunc i64 0 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = getelementptr [3 x i64], ptr %t102, i64 0, i64 1
  store i64 %t107, ptr %t108
  %t109 = trunc i64 0 to i32
  %t110 = sext i32 %t109 to i64
  %t111 = getelementptr [3 x i64], ptr %t102, i64 0, i64 2
  store i64 %t110, ptr %t111
  %t112 = getelementptr [4 x i64], ptr %t101, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t112, ptr %t102, i64 24, i1 false)
  %t113 = trunc i64 0 to i32
  %t114 = sext i32 %t113 to i64
  %t115 = getelementptr [4 x i64], ptr %t101, i64 0, i64 3
  store i64 %t114, ptr %t115
  %t116 = getelementptr [8 x i64], ptr %t100, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t116, ptr %t101, i64 32, i1 false)
  %t117 = getelementptr [8 x i64], ptr %t100, i64 0, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t117, ptr %t101, i64 32, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t118, ptr %t100, i64 64, i1 false)
  %t119 = call i64 @setup_scene(ptr %t99, ptr %t118)
  %t121 = trunc i64 64 to i32
  %t122 = sext i32 %t121 to i64
  store i64 %t122, ptr %t120
  %t124 = trunc i64 64 to i32
  %t125 = sext i32 %t124 to i64
  store i64 %t125, ptr %t123
  %t127 = trunc i64 0 to i32
  %t128 = sext i32 %t127 to i64
  store i64 %t128, ptr %t126
  br label %while1
while1:
  %t129 = load i64, ptr %t126
  %t130 = load i64, ptr %t123
  %t131 = trunc i64 %t129 to i32
  %t132 = sext i32 %t131 to i64
  %t133 = trunc i64 %t130 to i32
  %t134 = sext i32 %t133 to i64
  %t135 = icmp slt i64 %t132, %t134
  %t136 = zext i1 %t135 to i64
  %t137 = icmp ne i64 %t136, 0
  br i1 %t137, label %whilebody2, label %whileexit3
whilebody2:
  %t139 = trunc i64 0 to i32
  %t140 = sext i32 %t139 to i64
  store i64 %t140, ptr %t138
  br label %while4
while4:
  %t141 = load i64, ptr %t138
  %t142 = load i64, ptr %t120
  %t143 = trunc i64 %t141 to i32
  %t144 = sext i32 %t143 to i64
  %t145 = trunc i64 %t142 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = icmp slt i64 %t144, %t146
  %t148 = zext i1 %t147 to i64
  %t149 = icmp ne i64 %t148, 0
  br i1 %t149, label %whilebody5, label %whileexit6
whilebody5:
  %t150 = alloca [3 x i64]
  %t151 = load i64, ptr %t138
  %t152 = load i64, ptr %t120
  %t153 = trunc i64 %t152 to i32
  %t154 = sext i32 %t153 to i64
  %t155 = trunc i64 2 to i32
  %t156 = sext i32 %t155 to i64
  %t157 = sdiv i64 %t154, %t156
  %t158 = trunc i64 %t157 to i32
  %t159 = sext i32 %t158 to i64
  %t160 = trunc i64 %t151 to i32
  %t161 = sext i32 %t160 to i64
  %t162 = trunc i64 %t159 to i32
  %t163 = sext i32 %t162 to i64
  %t164 = sub i64 %t161, %t163
  %t165 = trunc i64 %t164 to i32
  %t166 = sext i32 %t165 to i64
  %t167 = trunc i64 %t166 to i32
  %t168 = sext i32 %t167 to i64
  %t169 = trunc i64 80 to i32
  %t170 = sext i32 %t169 to i64
  %t171 = mul i64 %t168, %t170
  %t172 = trunc i64 %t171 to i32
  %t173 = sext i32 %t172 to i64
  %t174 = load i64, ptr %t120
  %t175 = trunc i64 %t173 to i32
  %t176 = sext i32 %t175 to i64
  %t177 = trunc i64 %t174 to i32
  %t178 = sext i32 %t177 to i64
  %t179 = sdiv i64 %t176, %t178
  %t180 = trunc i64 %t179 to i32
  %t181 = sext i32 %t180 to i64
  %t182 = trunc i64 %t181 to i32
  %t183 = sext i32 %t182 to i64
  %t184 = getelementptr [3 x i64], ptr %t150, i64 0, i64 0
  store i64 %t183, ptr %t184
  %t185 = load i64, ptr %t126
  %t186 = load i64, ptr %t123
  %t187 = trunc i64 %t186 to i32
  %t188 = sext i32 %t187 to i64
  %t189 = trunc i64 2 to i32
  %t190 = sext i32 %t189 to i64
  %t191 = sdiv i64 %t188, %t190
  %t192 = trunc i64 %t191 to i32
  %t193 = sext i32 %t192 to i64
  %t194 = trunc i64 %t185 to i32
  %t195 = sext i32 %t194 to i64
  %t196 = trunc i64 %t193 to i32
  %t197 = sext i32 %t196 to i64
  %t198 = sub i64 %t195, %t197
  %t199 = trunc i64 %t198 to i32
  %t200 = sext i32 %t199 to i64
  %t201 = trunc i64 %t200 to i32
  %t202 = sext i32 %t201 to i64
  %t203 = trunc i64 80 to i32
  %t204 = sext i32 %t203 to i64
  %t205 = mul i64 %t202, %t204
  %t206 = trunc i64 %t205 to i32
  %t207 = sext i32 %t206 to i64
  %t208 = load i64, ptr %t123
  %t209 = trunc i64 %t207 to i32
  %t210 = sext i32 %t209 to i64
  %t211 = trunc i64 %t208 to i32
  %t212 = sext i32 %t211 to i64
  %t213 = sdiv i64 %t210, %t212
  %t214 = trunc i64 %t213 to i32
  %t215 = sext i32 %t214 to i64
  %t216 = trunc i64 %t215 to i32
  %t217 = sext i32 %t216 to i64
  %t218 = getelementptr [3 x i64], ptr %t150, i64 0, i64 1
  store i64 %t217, ptr %t218
  %t219 = trunc i64 80 to i32
  %t220 = sext i32 %t219 to i64
  %t221 = getelementptr [3 x i64], ptr %t150, i64 0, i64 2
  store i64 %t220, ptr %t221
  call void @llvm.memcpy.p0.p0.i64(ptr %t222, ptr %t150, i64 24, i1 false)
  %t223 = alloca [6 x i64]
  %t224 = alloca [3 x i64]
  %t225 = trunc i64 0 to i32
  %t226 = sext i32 %t225 to i64
  %t227 = getelementptr [3 x i64], ptr %t224, i64 0, i64 0
  store i64 %t226, ptr %t227
  %t228 = trunc i64 0 to i32
  %t229 = sext i32 %t228 to i64
  %t230 = getelementptr [3 x i64], ptr %t224, i64 0, i64 1
  store i64 %t229, ptr %t230
  %t231 = trunc i64 -80 to i32
  %t232 = sext i32 %t231 to i64
  %t233 = getelementptr [3 x i64], ptr %t224, i64 0, i64 2
  store i64 %t232, ptr %t233
  %t234 = getelementptr [6 x i64], ptr %t223, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t234, ptr %t224, i64 24, i1 false)
  %t235 = getelementptr [6 x i64], ptr %t223, i64 0, i64 3
  call void @llvm.memcpy.p0.p0.i64(ptr %t235, ptr %t222, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t236, ptr %t223, i64 48, i1 false)
  %t238 = trunc i64 800000 to i32
  %t239 = sext i32 %t238 to i64
  store i64 %t239, ptr %t237
  %t240 = alloca [3 x i64]
  %t241 = trunc i64 20 to i32
  %t242 = sext i32 %t241 to i64
  %t243 = getelementptr [3 x i64], ptr %t240, i64 0, i64 0
  store i64 %t242, ptr %t243
  %t244 = trunc i64 20 to i32
  %t245 = sext i32 %t244 to i64
  %t246 = getelementptr [3 x i64], ptr %t240, i64 0, i64 1
  store i64 %t245, ptr %t246
  %t247 = trunc i64 40 to i32
  %t248 = sext i32 %t247 to i64
  %t249 = getelementptr [3 x i64], ptr %t240, i64 0, i64 2
  store i64 %t248, ptr %t249
  call void @llvm.memcpy.p0.p0.i64(ptr %t250, ptr %t240, i64 24, i1 false)
  %t252 = trunc i64 0 to i32
  %t253 = sext i32 %t252 to i64
  store i64 %t253, ptr %t251
  br label %while7
while7:
  %t254 = load i64, ptr %t251
  %t255 = trunc i64 %t254 to i32
  %t256 = sext i32 %t255 to i64
  %t257 = trunc i64 4 to i32
  %t258 = sext i32 %t257 to i64
  %t259 = icmp slt i64 %t256, %t258
  %t260 = zext i1 %t259 to i64
  %t261 = icmp ne i64 %t260, 0
  br i1 %t261, label %whilebody8, label %whileexit9
whilebody8:
  %t262 = load i64, ptr %t251
  %t263 = mul i64 %t262, 7
  %t264 = getelementptr [28 x i64], ptr %t99, i64 0, i64 %t263
  %t265 = load i64, ptr %t251
  %t266 = mul i64 %t265, 7
  %t267 = getelementptr [28 x i64], ptr %t99, i64 0, i64 %t266
  %t268 = call i64 @intersect(ptr %t236, ptr %t267)
  %t270 = trunc i64 %t268 to i32
  %t271 = sext i32 %t270 to i64
  store i64 %t271, ptr %t269
  %t272 = load i64, ptr %t269
  %t273 = trunc i64 %t272 to i32
  %t274 = sext i32 %t273 to i64
  %t275 = trunc i64 0 to i32
  %t276 = sext i32 %t275 to i64
  %t277 = icmp sgt i64 %t274, %t276
  %t278 = zext i1 %t277 to i64
  %t279 = load i64, ptr %t269
  %t280 = load i64, ptr %t237
  %t281 = trunc i64 %t279 to i32
  %t282 = sext i32 %t281 to i64
  %t283 = trunc i64 %t280 to i32
  %t284 = sext i32 %t283 to i64
  %t285 = icmp slt i64 %t282, %t284
  %t286 = zext i1 %t285 to i64
  %t287 = icmp ne i64 %t278, 0
  %t288 = icmp ne i64 %t286, 0
  %t289 = and i1 %t287, %t288
  %t290 = zext i1 %t289 to i64
  %t291 = icmp ne i64 %t290, 0
  br i1 %t291, label %then10, label %else11
then10:
  %t292 = load i64, ptr %t269
  %t293 = trunc i64 %t292 to i32
  %t294 = sext i32 %t293 to i64
  store i64 %t294, ptr %t237
  %t295 = load i64, ptr %t251
  %t296 = mul i64 %t295, 7
  %t297 = getelementptr [28 x i64], ptr %t99, i64 0, i64 %t296
  %t298 = getelementptr i64, ptr %t297, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t250, ptr %t298, i64 24, i1 false)
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  %t299 = load i64, ptr %t251
  %t300 = trunc i64 %t299 to i32
  %t301 = sext i32 %t300 to i64
  %t302 = trunc i64 1 to i32
  %t303 = sext i32 %t302 to i64
  %t304 = add i64 %t301, %t303
  %t305 = trunc i64 %t304 to i32
  %t306 = sext i32 %t305 to i64
  %t307 = trunc i64 %t306 to i32
  %t308 = sext i32 %t307 to i64
  store i64 %t308, ptr %t251
  br label %while7
whileexit9:
  %t309 = getelementptr [3 x i64], ptr %t250, i64 0, i64 0
  %t310 = load i64, ptr %t309
  %t311 = getelementptr [3 x i64], ptr %t250, i64 0, i64 1
  %t312 = load i64, ptr %t311
  %t313 = trunc i64 %t310 to i32
  %t314 = sext i32 %t313 to i64
  %t315 = trunc i64 %t312 to i32
  %t316 = sext i32 %t315 to i64
  %t317 = add i64 %t314, %t316
  %t318 = trunc i64 %t317 to i32
  %t319 = sext i32 %t318 to i64
  %t320 = getelementptr [3 x i64], ptr %t250, i64 0, i64 2
  %t321 = load i64, ptr %t320
  %t322 = trunc i64 %t319 to i32
  %t323 = sext i32 %t322 to i64
  %t324 = trunc i64 %t321 to i32
  %t325 = sext i32 %t324 to i64
  %t326 = add i64 %t323, %t325
  %t327 = trunc i64 %t326 to i32
  %t328 = sext i32 %t327 to i64
  %t329 = trunc i64 %t328 to i32
  %t330 = sext i32 %t329 to i64
  %t331 = trunc i64 3 to i32
  %t332 = sext i32 %t331 to i64
  %t333 = sdiv i64 %t330, %t332
  %t334 = trunc i64 %t333 to i32
  %t335 = sext i32 %t334 to i64
  %t336 = load i64, ptr %t138
  %t337 = mul i64 %t336, 64
  %t338 = getelementptr [4096 x i64], ptr %t67, i64 0, i64 %t337
  %t339 = load i64, ptr %t126
  %t340 = mul i64 %t339, 1
  %t341 = getelementptr i64, ptr %t338, i64 %t340
  %t342 = trunc i64 %t335 to i32
  %t343 = sext i32 %t342 to i64
  store i64 %t343, ptr %t341
  %t344 = load i64, ptr %t138
  %t345 = trunc i64 %t344 to i32
  %t346 = sext i32 %t345 to i64
  %t347 = trunc i64 1 to i32
  %t348 = sext i32 %t347 to i64
  %t349 = add i64 %t346, %t348
  %t350 = trunc i64 %t349 to i32
  %t351 = sext i32 %t350 to i64
  %t352 = trunc i64 %t351 to i32
  %t353 = sext i32 %t352 to i64
  store i64 %t353, ptr %t138
  br label %while4
whileexit6:
  %t354 = load i64, ptr %t126
  %t355 = trunc i64 %t354 to i32
  %t356 = sext i32 %t355 to i64
  %t357 = trunc i64 1 to i32
  %t358 = sext i32 %t357 to i64
  %t359 = add i64 %t356, %t358
  %t360 = trunc i64 %t359 to i32
  %t361 = sext i32 %t360 to i64
  %t362 = trunc i64 %t361 to i32
  %t363 = sext i32 %t362 to i64
  store i64 %t363, ptr %t126
  br label %while1
whileexit3:
  %t365 = trunc i64 0 to i32
  %t366 = sext i32 %t365 to i64
  store i64 %t366, ptr %t364
  %t367 = trunc i64 0 to i32
  %t368 = sext i32 %t367 to i64
  store i64 %t368, ptr %t126
  br label %while13
while13:
  %t369 = load i64, ptr %t126
  %t370 = load i64, ptr %t123
  %t371 = trunc i64 %t369 to i32
  %t372 = sext i32 %t371 to i64
  %t373 = trunc i64 %t370 to i32
  %t374 = sext i32 %t373 to i64
  %t375 = icmp slt i64 %t372, %t374
  %t376 = zext i1 %t375 to i64
  %t377 = icmp ne i64 %t376, 0
  br i1 %t377, label %whilebody14, label %whileexit15
whilebody14:
  %t379 = trunc i64 0 to i32
  %t380 = sext i32 %t379 to i64
  store i64 %t380, ptr %t378
  br label %while16
while16:
  %t381 = load i64, ptr %t378
  %t382 = load i64, ptr %t120
  %t383 = trunc i64 %t381 to i32
  %t384 = sext i32 %t383 to i64
  %t385 = trunc i64 %t382 to i32
  %t386 = sext i32 %t385 to i64
  %t387 = icmp slt i64 %t384, %t386
  %t388 = zext i1 %t387 to i64
  %t389 = icmp ne i64 %t388, 0
  br i1 %t389, label %whilebody17, label %whileexit18
whilebody17:
  %t390 = load i64, ptr %t364
  %t391 = load i64, ptr %t378
  %t392 = mul i64 %t391, 64
  %t393 = getelementptr [4096 x i64], ptr %t67, i64 0, i64 %t392
  %t394 = load i64, ptr %t126
  %t395 = mul i64 %t394, 1
  %t396 = getelementptr i64, ptr %t393, i64 %t395
  %t397 = load i64, ptr %t396
  %t398 = load i64, ptr %t378
  %t399 = load i64, ptr %t126
  %t400 = load i64, ptr %t120
  %t401 = trunc i64 %t399 to i32
  %t402 = sext i32 %t401 to i64
  %t403 = trunc i64 %t400 to i32
  %t404 = sext i32 %t403 to i64
  %t405 = mul i64 %t402, %t404
  %t406 = trunc i64 %t405 to i32
  %t407 = sext i32 %t406 to i64
  %t408 = trunc i64 %t398 to i32
  %t409 = sext i32 %t408 to i64
  %t410 = trunc i64 %t407 to i32
  %t411 = sext i32 %t410 to i64
  %t412 = add i64 %t409, %t411
  %t413 = trunc i64 %t412 to i32
  %t414 = sext i32 %t413 to i64
  %t415 = trunc i64 %t397 to i32
  %t416 = sext i32 %t415 to i64
  %t417 = trunc i64 %t414 to i32
  %t418 = sext i32 %t417 to i64
  %t419 = mul i64 %t416, %t418
  %t420 = trunc i64 %t419 to i32
  %t421 = sext i32 %t420 to i64
  %t422 = trunc i64 %t390 to i32
  %t423 = sext i32 %t422 to i64
  %t424 = trunc i64 %t421 to i32
  %t425 = sext i32 %t424 to i64
  %t426 = add i64 %t423, %t425
  %t427 = trunc i64 %t426 to i32
  %t428 = sext i32 %t427 to i64
  %t429 = trunc i64 %t428 to i32
  %t430 = sext i32 %t429 to i64
  store i64 %t430, ptr %t364
  %t431 = load i64, ptr %t378
  %t432 = trunc i64 %t431 to i32
  %t433 = sext i32 %t432 to i64
  %t434 = trunc i64 1 to i32
  %t435 = sext i32 %t434 to i64
  %t436 = add i64 %t433, %t435
  %t437 = trunc i64 %t436 to i32
  %t438 = sext i32 %t437 to i64
  %t439 = trunc i64 %t438 to i32
  %t440 = sext i32 %t439 to i64
  store i64 %t440, ptr %t378
  br label %while16
whileexit18:
  %t441 = load i64, ptr %t126
  %t442 = trunc i64 %t441 to i32
  %t443 = sext i32 %t442 to i64
  %t444 = trunc i64 1 to i32
  %t445 = sext i32 %t444 to i64
  %t446 = add i64 %t443, %t445
  %t447 = trunc i64 %t446 to i32
  %t448 = sext i32 %t447 to i64
  %t449 = trunc i64 %t448 to i32
  %t450 = sext i32 %t449 to i64
  store i64 %t450, ptr %t126
  br label %while13
whileexit15:
  %t451 = load i64, ptr %t364
  %t452 = call i64 @printlnInt(i64 %t451)
  ret i64 0
}

define i64 @setup_scene(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca [7 x i64]
  %t2 = alloca [3 x i64]
  %t3 = trunc i64 0 to i32
  %t4 = sext i32 %t3 to i64
  %t5 = getelementptr [3 x i64], ptr %t2, i64 0, i64 0
  store i64 %t4, ptr %t5
  %t6 = trunc i64 -80 to i32
  %t7 = sext i32 %t6 to i64
  %t8 = getelementptr [3 x i64], ptr %t2, i64 0, i64 1
  store i64 %t7, ptr %t8
  %t9 = trunc i64 240 to i32
  %t10 = sext i32 %t9 to i64
  %t11 = getelementptr [3 x i64], ptr %t2, i64 0, i64 2
  store i64 %t10, ptr %t11
  %t12 = getelementptr [7 x i64], ptr %t1, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t2, i64 24, i1 false)
  %t13 = trunc i64 80 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = getelementptr [7 x i64], ptr %t1, i64 0, i64 3
  store i64 %t14, ptr %t15
  %t16 = alloca [3 x i64]
  %t17 = trunc i64 255 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = getelementptr [3 x i64], ptr %t16, i64 0, i64 0
  store i64 %t18, ptr %t19
  %t20 = trunc i64 0 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = getelementptr [3 x i64], ptr %t16, i64 0, i64 1
  store i64 %t21, ptr %t22
  %t23 = trunc i64 0 to i32
  %t24 = sext i32 %t23 to i64
  %t25 = getelementptr [3 x i64], ptr %t16, i64 0, i64 2
  store i64 %t24, ptr %t25
  %t26 = getelementptr [7 x i64], ptr %t1, i64 0, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t26, ptr %t16, i64 24, i1 false)
  %t27 = mul i64 0, 7
  %t28 = getelementptr [28 x i64], ptr %p0, i64 0, i64 %t27
  call void @llvm.memcpy.p0.p0.i64(ptr %t28, ptr %t1, i64 56, i1 false)
  %t29 = alloca [7 x i64]
  %t30 = alloca [3 x i64]
  %t31 = trunc i64 160 to i32
  %t32 = sext i32 %t31 to i64
  %t33 = getelementptr [3 x i64], ptr %t30, i64 0, i64 0
  store i64 %t32, ptr %t33
  %t34 = trunc i64 0 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = getelementptr [3 x i64], ptr %t30, i64 0, i64 1
  store i64 %t35, ptr %t36
  %t37 = trunc i64 320 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = getelementptr [3 x i64], ptr %t30, i64 0, i64 2
  store i64 %t38, ptr %t39
  %t40 = getelementptr [7 x i64], ptr %t29, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t40, ptr %t30, i64 24, i1 false)
  %t41 = trunc i64 80 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = getelementptr [7 x i64], ptr %t29, i64 0, i64 3
  store i64 %t42, ptr %t43
  %t44 = alloca [3 x i64]
  %t45 = trunc i64 0 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = getelementptr [3 x i64], ptr %t44, i64 0, i64 0
  store i64 %t46, ptr %t47
  %t48 = trunc i64 0 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = getelementptr [3 x i64], ptr %t44, i64 0, i64 1
  store i64 %t49, ptr %t50
  %t51 = trunc i64 255 to i32
  %t52 = sext i32 %t51 to i64
  %t53 = getelementptr [3 x i64], ptr %t44, i64 0, i64 2
  store i64 %t52, ptr %t53
  %t54 = getelementptr [7 x i64], ptr %t29, i64 0, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t54, ptr %t44, i64 24, i1 false)
  %t55 = mul i64 1, 7
  %t56 = getelementptr [28 x i64], ptr %p0, i64 0, i64 %t55
  call void @llvm.memcpy.p0.p0.i64(ptr %t56, ptr %t29, i64 56, i1 false)
  %t57 = alloca [7 x i64]
  %t58 = alloca [3 x i64]
  %t59 = trunc i64 -160 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = getelementptr [3 x i64], ptr %t58, i64 0, i64 0
  store i64 %t60, ptr %t61
  %t62 = trunc i64 0 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = getelementptr [3 x i64], ptr %t58, i64 0, i64 1
  store i64 %t63, ptr %t64
  %t65 = trunc i64 320 to i32
  %t66 = sext i32 %t65 to i64
  %t67 = getelementptr [3 x i64], ptr %t58, i64 0, i64 2
  store i64 %t66, ptr %t67
  %t68 = getelementptr [7 x i64], ptr %t57, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t68, ptr %t58, i64 24, i1 false)
  %t69 = trunc i64 80 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = getelementptr [7 x i64], ptr %t57, i64 0, i64 3
  store i64 %t70, ptr %t71
  %t72 = alloca [3 x i64]
  %t73 = trunc i64 0 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = getelementptr [3 x i64], ptr %t72, i64 0, i64 0
  store i64 %t74, ptr %t75
  %t76 = trunc i64 255 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = getelementptr [3 x i64], ptr %t72, i64 0, i64 1
  store i64 %t77, ptr %t78
  %t79 = trunc i64 0 to i32
  %t80 = sext i32 %t79 to i64
  %t81 = getelementptr [3 x i64], ptr %t72, i64 0, i64 2
  store i64 %t80, ptr %t81
  %t82 = getelementptr [7 x i64], ptr %t57, i64 0, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t82, ptr %t72, i64 24, i1 false)
  %t83 = mul i64 2, 7
  %t84 = getelementptr [28 x i64], ptr %p0, i64 0, i64 %t83
  call void @llvm.memcpy.p0.p0.i64(ptr %t84, ptr %t57, i64 56, i1 false)
  %t85 = alloca [7 x i64]
  %t86 = alloca [3 x i64]
  %t87 = trunc i64 0 to i32
  %t88 = sext i32 %t87 to i64
  %t89 = getelementptr [3 x i64], ptr %t86, i64 0, i64 0
  store i64 %t88, ptr %t89
  %t90 = trunc i64 -16080 to i32
  %t91 = sext i32 %t90 to i64
  %t92 = getelementptr [3 x i64], ptr %t86, i64 0, i64 1
  store i64 %t91, ptr %t92
  %t93 = trunc i64 0 to i32
  %t94 = sext i32 %t93 to i64
  %t95 = getelementptr [3 x i64], ptr %t86, i64 0, i64 2
  store i64 %t94, ptr %t95
  %t96 = getelementptr [7 x i64], ptr %t85, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t96, ptr %t86, i64 24, i1 false)
  %t97 = trunc i64 16000 to i32
  %t98 = sext i32 %t97 to i64
  %t99 = getelementptr [7 x i64], ptr %t85, i64 0, i64 3
  store i64 %t98, ptr %t99
  %t100 = alloca [3 x i64]
  %t101 = trunc i64 200 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = getelementptr [3 x i64], ptr %t100, i64 0, i64 0
  store i64 %t102, ptr %t103
  %t104 = trunc i64 200 to i32
  %t105 = sext i32 %t104 to i64
  %t106 = getelementptr [3 x i64], ptr %t100, i64 0, i64 1
  store i64 %t105, ptr %t106
  %t107 = trunc i64 0 to i32
  %t108 = sext i32 %t107 to i64
  %t109 = getelementptr [3 x i64], ptr %t100, i64 0, i64 2
  store i64 %t108, ptr %t109
  %t110 = getelementptr [7 x i64], ptr %t85, i64 0, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %t110, ptr %t100, i64 24, i1 false)
  %t111 = mul i64 3, 7
  %t112 = getelementptr [28 x i64], ptr %p0, i64 0, i64 %t111
  call void @llvm.memcpy.p0.p0.i64(ptr %t112, ptr %t85, i64 56, i1 false)
  %t113 = alloca [4 x i64]
  %t114 = alloca [3 x i64]
  %t115 = trunc i64 -1600 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = getelementptr [3 x i64], ptr %t114, i64 0, i64 0
  store i64 %t116, ptr %t117
  %t118 = trunc i64 1600 to i32
  %t119 = sext i32 %t118 to i64
  %t120 = getelementptr [3 x i64], ptr %t114, i64 0, i64 1
  store i64 %t119, ptr %t120
  %t121 = trunc i64 -1600 to i32
  %t122 = sext i32 %t121 to i64
  %t123 = getelementptr [3 x i64], ptr %t114, i64 0, i64 2
  store i64 %t122, ptr %t123
  %t124 = getelementptr [4 x i64], ptr %t113, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t124, ptr %t114, i64 24, i1 false)
  %t125 = trunc i64 150 to i32
  %t126 = sext i32 %t125 to i64
  %t127 = getelementptr [4 x i64], ptr %t113, i64 0, i64 3
  store i64 %t126, ptr %t127
  %t128 = mul i64 0, 4
  %t129 = getelementptr [8 x i64], ptr %p1, i64 0, i64 %t128
  call void @llvm.memcpy.p0.p0.i64(ptr %t129, ptr %t113, i64 32, i1 false)
  %t130 = alloca [4 x i64]
  %t131 = alloca [3 x i64]
  %t132 = trunc i64 1600 to i32
  %t133 = sext i32 %t132 to i64
  %t134 = getelementptr [3 x i64], ptr %t131, i64 0, i64 0
  store i64 %t133, ptr %t134
  %t135 = trunc i64 2400 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = getelementptr [3 x i64], ptr %t131, i64 0, i64 1
  store i64 %t136, ptr %t137
  %t138 = trunc i64 -800 to i32
  %t139 = sext i32 %t138 to i64
  %t140 = getelementptr [3 x i64], ptr %t131, i64 0, i64 2
  store i64 %t139, ptr %t140
  %t141 = getelementptr [4 x i64], ptr %t130, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t141, ptr %t131, i64 24, i1 false)
  %t142 = trunc i64 120 to i32
  %t143 = sext i32 %t142 to i64
  %t144 = getelementptr [4 x i64], ptr %t130, i64 0, i64 3
  store i64 %t143, ptr %t144
  %t145 = mul i64 1, 4
  %t146 = getelementptr [8 x i64], ptr %p1, i64 0, i64 %t145
  call void @llvm.memcpy.p0.p0.i64(ptr %t146, ptr %t130, i64 32, i1 false)
  ret i64 0
}

define i64 @vec_dot(ptr %p0, ptr %p1) {
entry:
  %t1 = getelementptr [3 x i64], ptr %p0, i64 0, i64 0
  %t2 = load i64, ptr %t1
  %t3 = getelementptr [3 x i64], ptr %p1, i64 0, i64 0
  %t4 = load i64, ptr %t3
  %t5 = trunc i64 %t2 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 %t4 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = mul i64 %t6, %t8
  %t10 = trunc i64 %t9 to i32
  %t11 = sext i32 %t10 to i64
  %t12 = getelementptr [3 x i64], ptr %p0, i64 0, i64 1
  %t13 = load i64, ptr %t12
  %t14 = getelementptr [3 x i64], ptr %p1, i64 0, i64 1
  %t15 = load i64, ptr %t14
  %t16 = trunc i64 %t13 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 %t15 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = mul i64 %t17, %t19
  %t21 = trunc i64 %t20 to i32
  %t22 = sext i32 %t21 to i64
  %t23 = trunc i64 %t11 to i32
  %t24 = sext i32 %t23 to i64
  %t25 = trunc i64 %t22 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = add i64 %t24, %t26
  %t28 = trunc i64 %t27 to i32
  %t29 = sext i32 %t28 to i64
  %t30 = getelementptr [3 x i64], ptr %p0, i64 0, i64 2
  %t31 = load i64, ptr %t30
  %t32 = getelementptr [3 x i64], ptr %p1, i64 0, i64 2
  %t33 = load i64, ptr %t32
  %t34 = trunc i64 %t31 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = trunc i64 %t33 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = mul i64 %t35, %t37
  %t39 = trunc i64 %t38 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = trunc i64 %t29 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = trunc i64 %t40 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = add i64 %t42, %t44
  %t46 = trunc i64 %t45 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = trunc i64 %t47 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = trunc i64 80 to i32
  %t51 = sext i32 %t50 to i64
  %t52 = sdiv i64 %t49, %t51
  %t53 = trunc i64 %t52 to i32
  %t54 = sext i32 %t53 to i64
  ret i64 %t54
}

define void @vec_sub(ptr %ret, ptr %p0, ptr %p1) {
entry:
  %t1 = alloca [3 x i64]
  %t2 = getelementptr [3 x i64], ptr %p0, i64 0, i64 0
  %t3 = load i64, ptr %t2
  %t4 = getelementptr [3 x i64], ptr %p1, i64 0, i64 0
  %t5 = load i64, ptr %t4
  %t6 = trunc i64 %t3 to i32
  %t7 = sext i32 %t6 to i64
  %t8 = trunc i64 %t5 to i32
  %t9 = sext i32 %t8 to i64
  %t10 = sub i64 %t7, %t9
  %t11 = trunc i64 %t10 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = trunc i64 %t12 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = getelementptr [3 x i64], ptr %t1, i64 0, i64 0
  store i64 %t14, ptr %t15
  %t16 = getelementptr [3 x i64], ptr %p0, i64 0, i64 1
  %t17 = load i64, ptr %t16
  %t18 = getelementptr [3 x i64], ptr %p1, i64 0, i64 1
  %t19 = load i64, ptr %t18
  %t20 = trunc i64 %t17 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = trunc i64 %t19 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = sub i64 %t21, %t23
  %t25 = trunc i64 %t24 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 %t26 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = getelementptr [3 x i64], ptr %t1, i64 0, i64 1
  store i64 %t28, ptr %t29
  %t30 = getelementptr [3 x i64], ptr %p0, i64 0, i64 2
  %t31 = load i64, ptr %t30
  %t32 = getelementptr [3 x i64], ptr %p1, i64 0, i64 2
  %t33 = load i64, ptr %t32
  %t34 = trunc i64 %t31 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = trunc i64 %t33 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = sub i64 %t35, %t37
  %t39 = trunc i64 %t38 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = trunc i64 %t40 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = getelementptr [3 x i64], ptr %t1, i64 0, i64 2
  store i64 %t42, ptr %t43
  call void @llvm.memcpy.p0.p0.i64(ptr %ret, ptr %t1, i64 24, i1 false)
  ret void
}

define i64 @intersect(ptr %p0, ptr %p1) {
entry:
  %t6 = alloca [3 x i64]
  %t12 = alloca i64
  store i64 0, ptr %t12
  %t25 = alloca i64
  store i64 0, ptr %t25
  %t54 = alloca i64
  store i64 0, ptr %t54
  %t96 = alloca i64
  store i64 0, ptr %t96
  %t1 = alloca [3 x i64]
  %t2 = getelementptr [6 x i64], ptr %p0, i64 0, i64 0
  %t3 = getelementptr [6 x i64], ptr %p0, i64 0, i64 0
  %t4 = getelementptr [7 x i64], ptr %p1, i64 0, i64 0
  %t5 = getelementptr [7 x i64], ptr %p1, i64 0, i64 0
  call void @vec_sub(ptr %t1, ptr %t3, ptr %t5)
  call void @llvm.memcpy.p0.p0.i64(ptr %t6, ptr %t1, i64 24, i1 false)
  %t7 = getelementptr [6 x i64], ptr %p0, i64 0, i64 3
  %t8 = getelementptr [6 x i64], ptr %p0, i64 0, i64 3
  %t9 = getelementptr [6 x i64], ptr %p0, i64 0, i64 3
  %t10 = getelementptr [6 x i64], ptr %p0, i64 0, i64 3
  %t11 = call i64 @vec_dot(ptr %t8, ptr %t10)
  %t13 = trunc i64 %t11 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t12
  %t15 = getelementptr [6 x i64], ptr %p0, i64 0, i64 3
  %t16 = getelementptr [6 x i64], ptr %p0, i64 0, i64 3
  %t17 = call i64 @vec_dot(ptr %t6, ptr %t16)
  %t18 = trunc i64 2 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = trunc i64 %t17 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = mul i64 %t19, %t21
  %t23 = trunc i64 %t22 to i32
  %t24 = sext i32 %t23 to i64
  %t26 = trunc i64 %t24 to i32
  %t27 = sext i32 %t26 to i64
  store i64 %t27, ptr %t25
  %t28 = call i64 @vec_dot(ptr %t6, ptr %t6)
  %t29 = getelementptr [7 x i64], ptr %p1, i64 0, i64 3
  %t30 = load i64, ptr %t29
  %t31 = getelementptr [7 x i64], ptr %p1, i64 0, i64 3
  %t32 = load i64, ptr %t31
  %t33 = trunc i64 %t30 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = trunc i64 %t32 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = mul i64 %t34, %t36
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = trunc i64 %t39 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = trunc i64 80 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = sdiv i64 %t41, %t43
  %t45 = trunc i64 %t44 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = trunc i64 %t28 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 %t46 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = sub i64 %t48, %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t55 = trunc i64 %t53 to i32
  %t56 = sext i32 %t55 to i64
  store i64 %t56, ptr %t54
  %t57 = load i64, ptr %t25
  %t58 = load i64, ptr %t25
  %t59 = trunc i64 %t57 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = trunc i64 %t58 to i32
  %t62 = sext i32 %t61 to i64
  %t63 = mul i64 %t60, %t62
  %t64 = trunc i64 %t63 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = load i64, ptr %t12
  %t67 = trunc i64 4 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = trunc i64 %t66 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = mul i64 %t68, %t70
  %t72 = trunc i64 %t71 to i32
  %t73 = sext i32 %t72 to i64
  %t74 = load i64, ptr %t54
  %t75 = trunc i64 %t73 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = trunc i64 %t74 to i32
  %t78 = sext i32 %t77 to i64
  %t79 = mul i64 %t76, %t78
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 80 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = sdiv i64 %t83, %t85
  %t87 = trunc i64 %t86 to i32
  %t88 = sext i32 %t87 to i64
  %t89 = trunc i64 %t65 to i32
  %t90 = sext i32 %t89 to i64
  %t91 = trunc i64 %t88 to i32
  %t92 = sext i32 %t91 to i64
  %t93 = sub i64 %t90, %t92
  %t94 = trunc i64 %t93 to i32
  %t95 = sext i32 %t94 to i64
  %t97 = trunc i64 %t95 to i32
  %t98 = sext i32 %t97 to i64
  store i64 %t98, ptr %t96
  %t99 = load i64, ptr %t96
  %t100 = trunc i64 %t99 to i32
  %t101 = sext i32 %t100 to i64
  %t102 = trunc i64 0 to i32
  %t103 = sext i32 %t102 to i64
  %t104 = icmp slt i64 %t101, %t103
  %t105 = zext i1 %t104 to i64
  %t106 = icmp ne i64 %t105, 0
  br i1 %t106, label %then1, label %else2
then1:
  ret i64 -1
else2:
  br label %ifend3
ifend3:
  %t107 = load i64, ptr %t25
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = sub i64 0, %t109
  %t111 = trunc i64 %t110 to i32
  %t112 = sext i32 %t111 to i64
  %t113 = load i64, ptr %t96
  %t114 = call i64 @isqrt(i64 %t113)
  %t115 = trunc i64 %t112 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 %t114 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = sub i64 %t116, %t118
  %t120 = trunc i64 %t119 to i32
  %t121 = sext i32 %t120 to i64
  %t122 = load i64, ptr %t12
  %t123 = trunc i64 2 to i32
  %t124 = sext i32 %t123 to i64
  %t125 = trunc i64 %t122 to i32
  %t126 = sext i32 %t125 to i64
  %t127 = mul i64 %t124, %t126
  %t128 = trunc i64 %t127 to i32
  %t129 = sext i32 %t128 to i64
  %t130 = trunc i64 %t129 to i32
  %t131 = sext i32 %t130 to i64
  %t132 = trunc i64 80 to i32
  %t133 = sext i32 %t132 to i64
  %t134 = sdiv i64 %t131, %t133
  %t135 = trunc i64 %t134 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = trunc i64 %t121 to i32
  %t138 = sext i32 %t137 to i64
  %t139 = trunc i64 %t136 to i32
  %t140 = sext i32 %t139 to i64
  %t141 = sdiv i64 %t138, %t140
  %t142 = trunc i64 %t141 to i32
  %t143 = sext i32 %t142 to i64
  ret i64 %t143
}

define i64 @isqrt(i64 %p0) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t11 = alloca i64
  store i64 0, ptr %t11
  %t29 = alloca i64
  store i64 0, ptr %t29
  %t2 = load i64, ptr %t1
  %t3 = trunc i64 %t2 to i32
  %t4 = sext i32 %t3 to i64
  %t5 = trunc i64 0 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = icmp slt i64 %t4, %t6
  %t8 = zext i1 %t7 to i64
  %t9 = icmp ne i64 %t8, 0
  br i1 %t9, label %then1, label %else2
then1:
  ret i64 0
else2:
  br label %ifend3
ifend3:
  %t10 = load i64, ptr %t1
  %t12 = trunc i64 %t10 to i32
  %t13 = sext i32 %t12 to i64
  store i64 %t13, ptr %t11
  %t14 = load i64, ptr %t11
  %t15 = trunc i64 %t14 to i32
  %t16 = sext i32 %t15 to i64
  %t17 = trunc i64 1 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = add i64 %t16, %t18
  %t20 = trunc i64 %t19 to i32
  %t21 = sext i32 %t20 to i64
  %t22 = trunc i64 %t21 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = trunc i64 2 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = sdiv i64 %t23, %t25
  %t27 = trunc i64 %t26 to i32
  %t28 = sext i32 %t27 to i64
  %t30 = trunc i64 %t28 to i32
  %t31 = sext i32 %t30 to i64
  store i64 %t31, ptr %t29
  br label %while4
while4:
  %t32 = load i64, ptr %t29
  %t33 = load i64, ptr %t11
  %t34 = trunc i64 %t32 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = trunc i64 %t33 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = icmp slt i64 %t35, %t37
  %t39 = zext i1 %t38 to i64
  %t40 = icmp ne i64 %t39, 0
  br i1 %t40, label %whilebody5, label %whileexit6
whilebody5:
  %t41 = load i64, ptr %t29
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  store i64 %t43, ptr %t11
  %t44 = load i64, ptr %t11
  %t45 = load i64, ptr %t1
  %t46 = load i64, ptr %t11
  %t47 = trunc i64 %t45 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 %t46 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = sdiv i64 %t48, %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 %t44 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = trunc i64 %t53 to i32
  %t57 = sext i32 %t56 to i64
  %t58 = add i64 %t55, %t57
  %t59 = trunc i64 %t58 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = trunc i64 %t60 to i32
  %t62 = sext i32 %t61 to i64
  %t63 = trunc i64 2 to i32
  %t64 = sext i32 %t63 to i64
  %t65 = sdiv i64 %t62, %t64
  %t66 = trunc i64 %t65 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = trunc i64 %t67 to i32
  %t69 = sext i32 %t68 to i64
  store i64 %t69, ptr %t29
  br label %while4
whileexit6:
  %t70 = load i64, ptr %t11
  ret i64 %t70
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

