; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t72 = alloca [1088 x i64]
  %t73 = alloca i64
  store i64 0, ptr %t73
  %t78 = alloca i64
  store i64 0, ptr %t78
  %t161 = alloca [1088 x i64]
  %t162 = alloca i64
  store i64 0, ptr %t162
  %t175 = alloca i64
  store i64 0, ptr %t175
  %t178 = alloca i64
  store i64 0, ptr %t178
  %t209 = alloca i64
  store i64 0, ptr %t209
  %t239 = alloca i64
  store i64 0, ptr %t239
  %t242 = alloca i64
  store i64 0, ptr %t242
  %t1 = alloca [1088 x i64]
  %t2 = alloca [17 x i64]
  %t3 = alloca [16 x i64]
  call void @llvm.memset.p0.i64(ptr %t3, i8 0, i64 128, i1 false)
  %t4 = getelementptr [17 x i64], ptr %t2, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 128, i1 false)
  %t5 = trunc i64 0 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = getelementptr [17 x i64], ptr %t2, i64 0, i64 16
  store i64 %t6, ptr %t7
  %t8 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t8, ptr %t2, i64 136, i1 false)
  %t9 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 17
  call void @llvm.memcpy.p0.p0.i64(ptr %t9, ptr %t2, i64 136, i1 false)
  %t10 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 34
  call void @llvm.memcpy.p0.p0.i64(ptr %t10, ptr %t2, i64 136, i1 false)
  %t11 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 51
  call void @llvm.memcpy.p0.p0.i64(ptr %t11, ptr %t2, i64 136, i1 false)
  %t12 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 68
  call void @llvm.memcpy.p0.p0.i64(ptr %t12, ptr %t2, i64 136, i1 false)
  %t13 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 85
  call void @llvm.memcpy.p0.p0.i64(ptr %t13, ptr %t2, i64 136, i1 false)
  %t14 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 102
  call void @llvm.memcpy.p0.p0.i64(ptr %t14, ptr %t2, i64 136, i1 false)
  %t15 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 119
  call void @llvm.memcpy.p0.p0.i64(ptr %t15, ptr %t2, i64 136, i1 false)
  %t16 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 136
  call void @llvm.memcpy.p0.p0.i64(ptr %t16, ptr %t2, i64 136, i1 false)
  %t17 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 153
  call void @llvm.memcpy.p0.p0.i64(ptr %t17, ptr %t2, i64 136, i1 false)
  %t18 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 170
  call void @llvm.memcpy.p0.p0.i64(ptr %t18, ptr %t2, i64 136, i1 false)
  %t19 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 187
  call void @llvm.memcpy.p0.p0.i64(ptr %t19, ptr %t2, i64 136, i1 false)
  %t20 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 204
  call void @llvm.memcpy.p0.p0.i64(ptr %t20, ptr %t2, i64 136, i1 false)
  %t21 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 221
  call void @llvm.memcpy.p0.p0.i64(ptr %t21, ptr %t2, i64 136, i1 false)
  %t22 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 238
  call void @llvm.memcpy.p0.p0.i64(ptr %t22, ptr %t2, i64 136, i1 false)
  %t23 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 255
  call void @llvm.memcpy.p0.p0.i64(ptr %t23, ptr %t2, i64 136, i1 false)
  %t24 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 272
  call void @llvm.memcpy.p0.p0.i64(ptr %t24, ptr %t2, i64 136, i1 false)
  %t25 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 289
  call void @llvm.memcpy.p0.p0.i64(ptr %t25, ptr %t2, i64 136, i1 false)
  %t26 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 306
  call void @llvm.memcpy.p0.p0.i64(ptr %t26, ptr %t2, i64 136, i1 false)
  %t27 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 323
  call void @llvm.memcpy.p0.p0.i64(ptr %t27, ptr %t2, i64 136, i1 false)
  %t28 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 340
  call void @llvm.memcpy.p0.p0.i64(ptr %t28, ptr %t2, i64 136, i1 false)
  %t29 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 357
  call void @llvm.memcpy.p0.p0.i64(ptr %t29, ptr %t2, i64 136, i1 false)
  %t30 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 374
  call void @llvm.memcpy.p0.p0.i64(ptr %t30, ptr %t2, i64 136, i1 false)
  %t31 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 391
  call void @llvm.memcpy.p0.p0.i64(ptr %t31, ptr %t2, i64 136, i1 false)
  %t32 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 408
  call void @llvm.memcpy.p0.p0.i64(ptr %t32, ptr %t2, i64 136, i1 false)
  %t33 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 425
  call void @llvm.memcpy.p0.p0.i64(ptr %t33, ptr %t2, i64 136, i1 false)
  %t34 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 442
  call void @llvm.memcpy.p0.p0.i64(ptr %t34, ptr %t2, i64 136, i1 false)
  %t35 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 459
  call void @llvm.memcpy.p0.p0.i64(ptr %t35, ptr %t2, i64 136, i1 false)
  %t36 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 476
  call void @llvm.memcpy.p0.p0.i64(ptr %t36, ptr %t2, i64 136, i1 false)
  %t37 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 493
  call void @llvm.memcpy.p0.p0.i64(ptr %t37, ptr %t2, i64 136, i1 false)
  %t38 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 510
  call void @llvm.memcpy.p0.p0.i64(ptr %t38, ptr %t2, i64 136, i1 false)
  %t39 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 527
  call void @llvm.memcpy.p0.p0.i64(ptr %t39, ptr %t2, i64 136, i1 false)
  %t40 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 544
  call void @llvm.memcpy.p0.p0.i64(ptr %t40, ptr %t2, i64 136, i1 false)
  %t41 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 561
  call void @llvm.memcpy.p0.p0.i64(ptr %t41, ptr %t2, i64 136, i1 false)
  %t42 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 578
  call void @llvm.memcpy.p0.p0.i64(ptr %t42, ptr %t2, i64 136, i1 false)
  %t43 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 595
  call void @llvm.memcpy.p0.p0.i64(ptr %t43, ptr %t2, i64 136, i1 false)
  %t44 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 612
  call void @llvm.memcpy.p0.p0.i64(ptr %t44, ptr %t2, i64 136, i1 false)
  %t45 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 629
  call void @llvm.memcpy.p0.p0.i64(ptr %t45, ptr %t2, i64 136, i1 false)
  %t46 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 646
  call void @llvm.memcpy.p0.p0.i64(ptr %t46, ptr %t2, i64 136, i1 false)
  %t47 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 663
  call void @llvm.memcpy.p0.p0.i64(ptr %t47, ptr %t2, i64 136, i1 false)
  %t48 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 680
  call void @llvm.memcpy.p0.p0.i64(ptr %t48, ptr %t2, i64 136, i1 false)
  %t49 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 697
  call void @llvm.memcpy.p0.p0.i64(ptr %t49, ptr %t2, i64 136, i1 false)
  %t50 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 714
  call void @llvm.memcpy.p0.p0.i64(ptr %t50, ptr %t2, i64 136, i1 false)
  %t51 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 731
  call void @llvm.memcpy.p0.p0.i64(ptr %t51, ptr %t2, i64 136, i1 false)
  %t52 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 748
  call void @llvm.memcpy.p0.p0.i64(ptr %t52, ptr %t2, i64 136, i1 false)
  %t53 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 765
  call void @llvm.memcpy.p0.p0.i64(ptr %t53, ptr %t2, i64 136, i1 false)
  %t54 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 782
  call void @llvm.memcpy.p0.p0.i64(ptr %t54, ptr %t2, i64 136, i1 false)
  %t55 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 799
  call void @llvm.memcpy.p0.p0.i64(ptr %t55, ptr %t2, i64 136, i1 false)
  %t56 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 816
  call void @llvm.memcpy.p0.p0.i64(ptr %t56, ptr %t2, i64 136, i1 false)
  %t57 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 833
  call void @llvm.memcpy.p0.p0.i64(ptr %t57, ptr %t2, i64 136, i1 false)
  %t58 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 850
  call void @llvm.memcpy.p0.p0.i64(ptr %t58, ptr %t2, i64 136, i1 false)
  %t59 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 867
  call void @llvm.memcpy.p0.p0.i64(ptr %t59, ptr %t2, i64 136, i1 false)
  %t60 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 884
  call void @llvm.memcpy.p0.p0.i64(ptr %t60, ptr %t2, i64 136, i1 false)
  %t61 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 901
  call void @llvm.memcpy.p0.p0.i64(ptr %t61, ptr %t2, i64 136, i1 false)
  %t62 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 918
  call void @llvm.memcpy.p0.p0.i64(ptr %t62, ptr %t2, i64 136, i1 false)
  %t63 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 935
  call void @llvm.memcpy.p0.p0.i64(ptr %t63, ptr %t2, i64 136, i1 false)
  %t64 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 952
  call void @llvm.memcpy.p0.p0.i64(ptr %t64, ptr %t2, i64 136, i1 false)
  %t65 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 969
  call void @llvm.memcpy.p0.p0.i64(ptr %t65, ptr %t2, i64 136, i1 false)
  %t66 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 986
  call void @llvm.memcpy.p0.p0.i64(ptr %t66, ptr %t2, i64 136, i1 false)
  %t67 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 1003
  call void @llvm.memcpy.p0.p0.i64(ptr %t67, ptr %t2, i64 136, i1 false)
  %t68 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 1020
  call void @llvm.memcpy.p0.p0.i64(ptr %t68, ptr %t2, i64 136, i1 false)
  %t69 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 1037
  call void @llvm.memcpy.p0.p0.i64(ptr %t69, ptr %t2, i64 136, i1 false)
  %t70 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 1054
  call void @llvm.memcpy.p0.p0.i64(ptr %t70, ptr %t2, i64 136, i1 false)
  %t71 = getelementptr [1088 x i64], ptr %t1, i64 0, i64 1071
  call void @llvm.memcpy.p0.p0.i64(ptr %t71, ptr %t2, i64 136, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t72, ptr %t1, i64 8704, i1 false)
  %t74 = trunc i64 12345 to i32
  %t75 = sext i32 %t74 to i64
  store i64 %t75, ptr %t73
  %t76 = load i64, ptr %t73
  %t77 = call i64 @init_population(ptr %t72, ptr %t73)
  %t79 = trunc i64 0 to i32
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  br label %while1
while1:
  %t81 = load i64, ptr %t78
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 50 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = icmp slt i64 %t83, %t85
  %t87 = zext i1 %t86 to i64
  %t88 = icmp ne i64 %t87, 0
  br i1 %t88, label %whilebody2, label %whileexit3
whilebody2:
  %t89 = call i64 @evaluate_population(ptr %t72)
  %t90 = alloca [1088 x i64]
  %t91 = alloca [17 x i64]
  %t92 = alloca [16 x i64]
  call void @llvm.memset.p0.i64(ptr %t92, i8 0, i64 128, i1 false)
  %t93 = getelementptr [17 x i64], ptr %t91, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t93, ptr %t92, i64 128, i1 false)
  %t94 = trunc i64 0 to i32
  %t95 = sext i32 %t94 to i64
  %t96 = getelementptr [17 x i64], ptr %t91, i64 0, i64 16
  store i64 %t95, ptr %t96
  %t97 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 0
  call void @llvm.memcpy.p0.p0.i64(ptr %t97, ptr %t91, i64 136, i1 false)
  %t98 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 17
  call void @llvm.memcpy.p0.p0.i64(ptr %t98, ptr %t91, i64 136, i1 false)
  %t99 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 34
  call void @llvm.memcpy.p0.p0.i64(ptr %t99, ptr %t91, i64 136, i1 false)
  %t100 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 51
  call void @llvm.memcpy.p0.p0.i64(ptr %t100, ptr %t91, i64 136, i1 false)
  %t101 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 68
  call void @llvm.memcpy.p0.p0.i64(ptr %t101, ptr %t91, i64 136, i1 false)
  %t102 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 85
  call void @llvm.memcpy.p0.p0.i64(ptr %t102, ptr %t91, i64 136, i1 false)
  %t103 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 102
  call void @llvm.memcpy.p0.p0.i64(ptr %t103, ptr %t91, i64 136, i1 false)
  %t104 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 119
  call void @llvm.memcpy.p0.p0.i64(ptr %t104, ptr %t91, i64 136, i1 false)
  %t105 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 136
  call void @llvm.memcpy.p0.p0.i64(ptr %t105, ptr %t91, i64 136, i1 false)
  %t106 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 153
  call void @llvm.memcpy.p0.p0.i64(ptr %t106, ptr %t91, i64 136, i1 false)
  %t107 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 170
  call void @llvm.memcpy.p0.p0.i64(ptr %t107, ptr %t91, i64 136, i1 false)
  %t108 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 187
  call void @llvm.memcpy.p0.p0.i64(ptr %t108, ptr %t91, i64 136, i1 false)
  %t109 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 204
  call void @llvm.memcpy.p0.p0.i64(ptr %t109, ptr %t91, i64 136, i1 false)
  %t110 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 221
  call void @llvm.memcpy.p0.p0.i64(ptr %t110, ptr %t91, i64 136, i1 false)
  %t111 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 238
  call void @llvm.memcpy.p0.p0.i64(ptr %t111, ptr %t91, i64 136, i1 false)
  %t112 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 255
  call void @llvm.memcpy.p0.p0.i64(ptr %t112, ptr %t91, i64 136, i1 false)
  %t113 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 272
  call void @llvm.memcpy.p0.p0.i64(ptr %t113, ptr %t91, i64 136, i1 false)
  %t114 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 289
  call void @llvm.memcpy.p0.p0.i64(ptr %t114, ptr %t91, i64 136, i1 false)
  %t115 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 306
  call void @llvm.memcpy.p0.p0.i64(ptr %t115, ptr %t91, i64 136, i1 false)
  %t116 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 323
  call void @llvm.memcpy.p0.p0.i64(ptr %t116, ptr %t91, i64 136, i1 false)
  %t117 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 340
  call void @llvm.memcpy.p0.p0.i64(ptr %t117, ptr %t91, i64 136, i1 false)
  %t118 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 357
  call void @llvm.memcpy.p0.p0.i64(ptr %t118, ptr %t91, i64 136, i1 false)
  %t119 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 374
  call void @llvm.memcpy.p0.p0.i64(ptr %t119, ptr %t91, i64 136, i1 false)
  %t120 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 391
  call void @llvm.memcpy.p0.p0.i64(ptr %t120, ptr %t91, i64 136, i1 false)
  %t121 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 408
  call void @llvm.memcpy.p0.p0.i64(ptr %t121, ptr %t91, i64 136, i1 false)
  %t122 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 425
  call void @llvm.memcpy.p0.p0.i64(ptr %t122, ptr %t91, i64 136, i1 false)
  %t123 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 442
  call void @llvm.memcpy.p0.p0.i64(ptr %t123, ptr %t91, i64 136, i1 false)
  %t124 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 459
  call void @llvm.memcpy.p0.p0.i64(ptr %t124, ptr %t91, i64 136, i1 false)
  %t125 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 476
  call void @llvm.memcpy.p0.p0.i64(ptr %t125, ptr %t91, i64 136, i1 false)
  %t126 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 493
  call void @llvm.memcpy.p0.p0.i64(ptr %t126, ptr %t91, i64 136, i1 false)
  %t127 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 510
  call void @llvm.memcpy.p0.p0.i64(ptr %t127, ptr %t91, i64 136, i1 false)
  %t128 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 527
  call void @llvm.memcpy.p0.p0.i64(ptr %t128, ptr %t91, i64 136, i1 false)
  %t129 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 544
  call void @llvm.memcpy.p0.p0.i64(ptr %t129, ptr %t91, i64 136, i1 false)
  %t130 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 561
  call void @llvm.memcpy.p0.p0.i64(ptr %t130, ptr %t91, i64 136, i1 false)
  %t131 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 578
  call void @llvm.memcpy.p0.p0.i64(ptr %t131, ptr %t91, i64 136, i1 false)
  %t132 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 595
  call void @llvm.memcpy.p0.p0.i64(ptr %t132, ptr %t91, i64 136, i1 false)
  %t133 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 612
  call void @llvm.memcpy.p0.p0.i64(ptr %t133, ptr %t91, i64 136, i1 false)
  %t134 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 629
  call void @llvm.memcpy.p0.p0.i64(ptr %t134, ptr %t91, i64 136, i1 false)
  %t135 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 646
  call void @llvm.memcpy.p0.p0.i64(ptr %t135, ptr %t91, i64 136, i1 false)
  %t136 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 663
  call void @llvm.memcpy.p0.p0.i64(ptr %t136, ptr %t91, i64 136, i1 false)
  %t137 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 680
  call void @llvm.memcpy.p0.p0.i64(ptr %t137, ptr %t91, i64 136, i1 false)
  %t138 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 697
  call void @llvm.memcpy.p0.p0.i64(ptr %t138, ptr %t91, i64 136, i1 false)
  %t139 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 714
  call void @llvm.memcpy.p0.p0.i64(ptr %t139, ptr %t91, i64 136, i1 false)
  %t140 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 731
  call void @llvm.memcpy.p0.p0.i64(ptr %t140, ptr %t91, i64 136, i1 false)
  %t141 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 748
  call void @llvm.memcpy.p0.p0.i64(ptr %t141, ptr %t91, i64 136, i1 false)
  %t142 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 765
  call void @llvm.memcpy.p0.p0.i64(ptr %t142, ptr %t91, i64 136, i1 false)
  %t143 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 782
  call void @llvm.memcpy.p0.p0.i64(ptr %t143, ptr %t91, i64 136, i1 false)
  %t144 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 799
  call void @llvm.memcpy.p0.p0.i64(ptr %t144, ptr %t91, i64 136, i1 false)
  %t145 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 816
  call void @llvm.memcpy.p0.p0.i64(ptr %t145, ptr %t91, i64 136, i1 false)
  %t146 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 833
  call void @llvm.memcpy.p0.p0.i64(ptr %t146, ptr %t91, i64 136, i1 false)
  %t147 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 850
  call void @llvm.memcpy.p0.p0.i64(ptr %t147, ptr %t91, i64 136, i1 false)
  %t148 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 867
  call void @llvm.memcpy.p0.p0.i64(ptr %t148, ptr %t91, i64 136, i1 false)
  %t149 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 884
  call void @llvm.memcpy.p0.p0.i64(ptr %t149, ptr %t91, i64 136, i1 false)
  %t150 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 901
  call void @llvm.memcpy.p0.p0.i64(ptr %t150, ptr %t91, i64 136, i1 false)
  %t151 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 918
  call void @llvm.memcpy.p0.p0.i64(ptr %t151, ptr %t91, i64 136, i1 false)
  %t152 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 935
  call void @llvm.memcpy.p0.p0.i64(ptr %t152, ptr %t91, i64 136, i1 false)
  %t153 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 952
  call void @llvm.memcpy.p0.p0.i64(ptr %t153, ptr %t91, i64 136, i1 false)
  %t154 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 969
  call void @llvm.memcpy.p0.p0.i64(ptr %t154, ptr %t91, i64 136, i1 false)
  %t155 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 986
  call void @llvm.memcpy.p0.p0.i64(ptr %t155, ptr %t91, i64 136, i1 false)
  %t156 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 1003
  call void @llvm.memcpy.p0.p0.i64(ptr %t156, ptr %t91, i64 136, i1 false)
  %t157 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 1020
  call void @llvm.memcpy.p0.p0.i64(ptr %t157, ptr %t91, i64 136, i1 false)
  %t158 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 1037
  call void @llvm.memcpy.p0.p0.i64(ptr %t158, ptr %t91, i64 136, i1 false)
  %t159 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 1054
  call void @llvm.memcpy.p0.p0.i64(ptr %t159, ptr %t91, i64 136, i1 false)
  %t160 = getelementptr [1088 x i64], ptr %t90, i64 0, i64 1071
  call void @llvm.memcpy.p0.p0.i64(ptr %t160, ptr %t91, i64 136, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t161, ptr %t90, i64 8704, i1 false)
  %t163 = trunc i64 0 to i32
  %t164 = sext i32 %t163 to i64
  store i64 %t164, ptr %t162
  br label %while4
while4:
  %t165 = load i64, ptr %t162
  %t166 = trunc i64 %t165 to i32
  %t167 = sext i32 %t166 to i64
  %t168 = trunc i64 64 to i32
  %t169 = sext i32 %t168 to i64
  %t170 = icmp slt i64 %t167, %t169
  %t171 = zext i1 %t170 to i64
  %t172 = icmp ne i64 %t171, 0
  br i1 %t172, label %whilebody5, label %whileexit6
whilebody5:
  %t173 = load i64, ptr %t73
  %t174 = call i64 @selection(ptr %t72, ptr %t73)
  store i64 %t174, ptr %t175
  %t176 = load i64, ptr %t73
  %t177 = call i64 @selection(ptr %t72, ptr %t73)
  store i64 %t177, ptr %t178
  %t179 = load i64, ptr %t175
  %t180 = mul i64 %t179, 17
  %t181 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t180
  %t182 = load i64, ptr %t175
  %t183 = mul i64 %t182, 17
  %t184 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t183
  %t185 = load i64, ptr %t178
  %t186 = mul i64 %t185, 17
  %t187 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t186
  %t188 = load i64, ptr %t178
  %t189 = mul i64 %t188, 17
  %t190 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t189
  %t191 = load i64, ptr %t162
  %t192 = mul i64 %t191, 17
  %t193 = getelementptr [1088 x i64], ptr %t161, i64 0, i64 %t192
  %t194 = load i64, ptr %t162
  %t195 = mul i64 %t194, 17
  %t196 = getelementptr [1088 x i64], ptr %t161, i64 0, i64 %t195
  %t197 = load i64, ptr %t73
  %t198 = call i64 @crossover(ptr %t184, ptr %t190, ptr %t196, ptr %t73)
  %t199 = load i64, ptr %t162
  %t200 = mul i64 %t199, 17
  %t201 = getelementptr [1088 x i64], ptr %t161, i64 0, i64 %t200
  %t202 = load i64, ptr %t162
  %t203 = mul i64 %t202, 17
  %t204 = getelementptr [1088 x i64], ptr %t161, i64 0, i64 %t203
  %t205 = load i64, ptr %t73
  %t206 = call i64 @mutate(ptr %t204, ptr %t73)
  %t207 = load i64, ptr %t162
  %t208 = add i64 %t207, 1
  store i64 %t208, ptr %t162
  br label %while4
whileexit6:
  %t210 = trunc i64 0 to i32
  %t211 = sext i32 %t210 to i64
  store i64 %t211, ptr %t209
  br label %while7
while7:
  %t212 = load i64, ptr %t209
  %t213 = trunc i64 %t212 to i32
  %t214 = sext i32 %t213 to i64
  %t215 = trunc i64 64 to i32
  %t216 = sext i32 %t215 to i64
  %t217 = icmp slt i64 %t214, %t216
  %t218 = zext i1 %t217 to i64
  %t219 = icmp ne i64 %t218, 0
  br i1 %t219, label %whilebody8, label %whileexit9
whilebody8:
  %t220 = load i64, ptr %t209
  %t221 = mul i64 %t220, 17
  %t222 = getelementptr [1088 x i64], ptr %t161, i64 0, i64 %t221
  %t223 = load i64, ptr %t209
  %t224 = mul i64 %t223, 17
  %t225 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t224
  call void @llvm.memcpy.p0.p0.i64(ptr %t225, ptr %t222, i64 136, i1 false)
  %t226 = load i64, ptr %t209
  %t227 = add i64 %t226, 1
  store i64 %t227, ptr %t209
  br label %while7
whileexit9:
  %t228 = load i64, ptr %t78
  %t229 = trunc i64 %t228 to i32
  %t230 = sext i32 %t229 to i64
  %t231 = trunc i64 1 to i32
  %t232 = sext i32 %t231 to i64
  %t233 = add i64 %t230, %t232
  %t234 = trunc i64 %t233 to i32
  %t235 = sext i32 %t234 to i64
  %t236 = trunc i64 %t235 to i32
  %t237 = sext i32 %t236 to i64
  store i64 %t237, ptr %t78
  br label %while1
whileexit3:
  %t238 = call i64 @evaluate_population(ptr %t72)
  %t240 = trunc i64 -99999999 to i32
  %t241 = sext i32 %t240 to i64
  store i64 %t241, ptr %t239
  %t243 = trunc i64 0 to i32
  %t244 = sext i32 %t243 to i64
  store i64 %t244, ptr %t242
  br label %while10
while10:
  %t245 = load i64, ptr %t242
  %t246 = trunc i64 %t245 to i32
  %t247 = sext i32 %t246 to i64
  %t248 = trunc i64 64 to i32
  %t249 = sext i32 %t248 to i64
  %t250 = icmp slt i64 %t247, %t249
  %t251 = zext i1 %t250 to i64
  %t252 = icmp ne i64 %t251, 0
  br i1 %t252, label %whilebody11, label %whileexit12
whilebody11:
  %t253 = load i64, ptr %t242
  %t254 = mul i64 %t253, 17
  %t255 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t254
  %t256 = getelementptr i64, ptr %t255, i64 16
  %t257 = load i64, ptr %t256
  %t258 = load i64, ptr %t239
  %t259 = trunc i64 %t257 to i32
  %t260 = sext i32 %t259 to i64
  %t261 = trunc i64 %t258 to i32
  %t262 = sext i32 %t261 to i64
  %t263 = icmp sgt i64 %t260, %t262
  %t264 = zext i1 %t263 to i64
  %t265 = icmp ne i64 %t264, 0
  br i1 %t265, label %then13, label %else14
then13:
  %t266 = load i64, ptr %t242
  %t267 = mul i64 %t266, 17
  %t268 = getelementptr [1088 x i64], ptr %t72, i64 0, i64 %t267
  %t269 = getelementptr i64, ptr %t268, i64 16
  %t270 = load i64, ptr %t269
  %t271 = trunc i64 %t270 to i32
  %t272 = sext i32 %t271 to i64
  store i64 %t272, ptr %t239
  br label %ifend15
else14:
  br label %ifend15
ifend15:
  %t273 = load i64, ptr %t242
  %t274 = add i64 %t273, 1
  store i64 %t274, ptr %t242
  br label %while10
whileexit12:
  %t275 = load i64, ptr %t239
  %t276 = call i64 @printlnInt(i64 %t275)
  ret i64 0
}

define i64 @pseudo_rand(ptr %p0) {
entry:
  %t1 = load i64, ptr %p0
  %t2 = trunc i64 %t1 to i32
  %t3 = sext i32 %t2 to i64
  %t4 = trunc i64 127 to i32
  %t5 = sext i32 %t4 to i64
  %t6 = mul i64 %t3, %t5
  %t7 = trunc i64 %t6 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = trunc i64 %t8 to i32
  %t10 = sext i32 %t9 to i64
  %t11 = trunc i64 16777337 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = add i64 %t10, %t12
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 16777215 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = and i64 %t17, %t19
  %t21 = trunc i64 %t20 to i32
  %t22 = sext i32 %t21 to i64
  %t23 = trunc i64 %t22 to i32
  %t24 = sext i32 %t23 to i64
  store i64 %t24, ptr %p0
  %t25 = load i64, ptr %p0
  ret i64 %t25
}

define i64 @init_population(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t12 = alloca i64
  store i64 0, ptr %t12
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 64 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t13 = trunc i64 0 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t12
  br label %while4
while4:
  %t15 = load i64, ptr %t12
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 16 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = icmp slt i64 %t17, %t19
  %t21 = zext i1 %t20 to i64
  %t22 = icmp ne i64 %t21, 0
  br i1 %t22, label %whilebody5, label %whileexit6
whilebody5:
  %t23 = call i64 @pseudo_rand(ptr %p1)
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 200 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = srem i64 %t25, %t27
  %t29 = trunc i64 %t28 to i32
  %t30 = sext i32 %t29 to i64
  %t31 = trunc i64 %t30 to i32
  %t32 = sext i32 %t31 to i64
  %t33 = trunc i64 100 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = sub i64 %t32, %t34
  %t36 = trunc i64 %t35 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = load i64, ptr %t1
  %t39 = mul i64 %t38, 17
  %t40 = getelementptr [1088 x i64], ptr %p0, i64 0, i64 %t39
  %t41 = getelementptr i64, ptr %t40, i64 0
  %t42 = load i64, ptr %t12
  %t43 = mul i64 %t42, 1
  %t44 = getelementptr i64, ptr %t41, i64 %t43
  %t45 = trunc i64 %t37 to i32
  %t46 = sext i32 %t45 to i64
  store i64 %t46, ptr %t44
  %t47 = load i64, ptr %t12
  %t48 = add i64 %t47, 1
  store i64 %t48, ptr %t12
  br label %while4
whileexit6:
  %t49 = load i64, ptr %t1
  %t50 = add i64 %t49, 1
  store i64 %t50, ptr %t1
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @calculate_fitness(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t10 = alloca i64
  store i64 0, ptr %t10
  %t101 = alloca i64
  store i64 0, ptr %t101
  %t2 = trunc i64 500 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 0 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  %t8 = trunc i64 0 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  %t11 = trunc i64 0 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  br label %while1
while1:
  %t13 = load i64, ptr %t10
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 16 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = icmp slt i64 %t15, %t17
  %t19 = zext i1 %t18 to i64
  %t20 = icmp ne i64 %t19, 0
  br i1 %t20, label %whilebody2, label %whileexit3
whilebody2:
  %t21 = load i64, ptr %t4
  %t22 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t23 = load i64, ptr %t10
  %t24 = mul i64 %t23, 1
  %t25 = getelementptr i64, ptr %t22, i64 %t24
  %t26 = load i64, ptr %t25
  %t27 = trunc i64 %t21 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = trunc i64 %t26 to i32
  %t30 = sext i32 %t29 to i64
  %t31 = add i64 %t28, %t30
  %t32 = trunc i64 %t31 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = trunc i64 %t33 to i32
  %t35 = sext i32 %t34 to i64
  store i64 %t35, ptr %t4
  %t36 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t37 = load i64, ptr %t10
  %t38 = mul i64 %t37, 1
  %t39 = getelementptr i64, ptr %t36, i64 %t38
  %t40 = load i64, ptr %t39
  %t41 = trunc i64 %t40 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = trunc i64 90 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = icmp sgt i64 %t42, %t44
  %t46 = zext i1 %t45 to i64
  %t47 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t48 = load i64, ptr %t10
  %t49 = mul i64 %t48, 1
  %t50 = getelementptr i64, ptr %t47, i64 %t49
  %t51 = load i64, ptr %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = trunc i64 -90 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = icmp slt i64 %t53, %t55
  %t57 = zext i1 %t56 to i64
  %t58 = icmp ne i64 %t46, 0
  %t59 = icmp ne i64 %t57, 0
  %t60 = or i1 %t58, %t59
  %t61 = zext i1 %t60 to i64
  %t62 = icmp ne i64 %t61, 0
  br i1 %t62, label %then4, label %else5
then4:
  %t63 = load i64, ptr %t7
  %t64 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t65 = load i64, ptr %t10
  %t66 = mul i64 %t65, 1
  %t67 = getelementptr i64, ptr %t64, i64 %t66
  %t68 = load i64, ptr %t67
  %t69 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t70 = load i64, ptr %t10
  %t71 = mul i64 %t70, 1
  %t72 = getelementptr i64, ptr %t69, i64 %t71
  %t73 = load i64, ptr %t72
  %t74 = trunc i64 %t68 to i32
  %t75 = sext i32 %t74 to i64
  %t76 = trunc i64 %t73 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = mul i64 %t75, %t77
  %t79 = trunc i64 %t78 to i32
  %t80 = sext i32 %t79 to i64
  %t81 = trunc i64 %t63 to i32
  %t82 = sext i32 %t81 to i64
  %t83 = trunc i64 %t80 to i32
  %t84 = sext i32 %t83 to i64
  %t85 = add i64 %t82, %t84
  %t86 = trunc i64 %t85 to i32
  %t87 = sext i32 %t86 to i64
  %t88 = trunc i64 %t87 to i32
  %t89 = sext i32 %t88 to i64
  store i64 %t89, ptr %t7
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t90 = load i64, ptr %t10
  %t91 = add i64 %t90, 1
  store i64 %t91, ptr %t10
  br label %while1
whileexit3:
  %t92 = load i64, ptr %t1
  %t93 = load i64, ptr %t4
  %t94 = trunc i64 %t92 to i32
  %t95 = sext i32 %t94 to i64
  %t96 = trunc i64 %t93 to i32
  %t97 = sext i32 %t96 to i64
  %t98 = sub i64 %t95, %t97
  %t99 = trunc i64 %t98 to i32
  %t100 = sext i32 %t99 to i64
  %t102 = trunc i64 %t100 to i32
  %t103 = sext i32 %t102 to i64
  store i64 %t103, ptr %t101
  %t104 = load i64, ptr %t101
  %t105 = load i64, ptr %t101
  %t106 = trunc i64 %t104 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = trunc i64 %t105 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = mul i64 %t107, %t109
  %t111 = trunc i64 %t110 to i32
  %t112 = sext i32 %t111 to i64
  %t113 = trunc i64 %t112 to i32
  %t114 = sext i32 %t113 to i64
  %t115 = sub i64 0, %t114
  %t116 = trunc i64 %t115 to i32
  %t117 = sext i32 %t116 to i64
  %t118 = load i64, ptr %t7
  %t119 = trunc i64 %t117 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = trunc i64 %t118 to i32
  %t122 = sext i32 %t121 to i64
  %t123 = sub i64 %t120, %t122
  %t124 = trunc i64 %t123 to i32
  %t125 = sext i32 %t124 to i64
  %t126 = getelementptr [17 x i64], ptr %p0, i64 0, i64 16
  %t127 = trunc i64 %t125 to i32
  %t128 = sext i32 %t127 to i64
  store i64 %t128, ptr %t126
  ret i64 0
}

define i64 @evaluate_population(ptr %p0) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t2 = trunc i64 0 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  br label %while1
while1:
  %t4 = load i64, ptr %t1
  %t5 = trunc i64 %t4 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 64 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp slt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %whilebody2, label %whileexit3
whilebody2:
  %t12 = load i64, ptr %t1
  %t13 = mul i64 %t12, 17
  %t14 = getelementptr [1088 x i64], ptr %p0, i64 0, i64 %t13
  %t15 = load i64, ptr %t1
  %t16 = mul i64 %t15, 17
  %t17 = getelementptr [1088 x i64], ptr %p0, i64 0, i64 %t16
  %t18 = call i64 @calculate_fitness(ptr %t17)
  %t19 = load i64, ptr %t1
  %t20 = add i64 %t19, 1
  store i64 %t20, ptr %t1
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @selection(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t10 = alloca i64
  store i64 0, ptr %t10
  %t24 = alloca i64
  store i64 0, ptr %t24
  %t2 = trunc i64 5 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 -1 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  %t8 = trunc i64 -99999999 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  %t11 = trunc i64 0 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  br label %while1
while1:
  %t13 = load i64, ptr %t10
  %t14 = load i64, ptr %t1
  %t15 = trunc i64 %t13 to i32
  %t16 = sext i32 %t15 to i64
  %t17 = trunc i64 %t14 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = icmp slt i64 %t16, %t18
  %t20 = zext i1 %t19 to i64
  %t21 = icmp ne i64 %t20, 0
  br i1 %t21, label %whilebody2, label %whileexit3
whilebody2:
  %t22 = call i64 @pseudo_rand(ptr %p1)
  %t23 = srem i64 %t22, 64
  store i64 %t23, ptr %t24
  %t25 = load i64, ptr %t24
  %t26 = mul i64 %t25, 17
  %t27 = getelementptr [1088 x i64], ptr %p0, i64 0, i64 %t26
  %t28 = getelementptr i64, ptr %t27, i64 16
  %t29 = load i64, ptr %t28
  %t30 = load i64, ptr %t7
  %t31 = trunc i64 %t29 to i32
  %t32 = sext i32 %t31 to i64
  %t33 = trunc i64 %t30 to i32
  %t34 = sext i32 %t33 to i64
  %t35 = icmp sgt i64 %t32, %t34
  %t36 = zext i1 %t35 to i64
  %t37 = icmp ne i64 %t36, 0
  br i1 %t37, label %then4, label %else5
then4:
  %t38 = load i64, ptr %t24
  %t39 = mul i64 %t38, 17
  %t40 = getelementptr [1088 x i64], ptr %p0, i64 0, i64 %t39
  %t41 = getelementptr i64, ptr %t40, i64 16
  %t42 = load i64, ptr %t41
  %t43 = trunc i64 %t42 to i32
  %t44 = sext i32 %t43 to i64
  store i64 %t44, ptr %t7
  %t45 = load i64, ptr %t24
  %t46 = trunc i64 %t45 to i32
  %t47 = sext i32 %t46 to i64
  store i64 %t47, ptr %t4
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t48 = load i64, ptr %t10
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = trunc i64 1 to i32
  %t52 = sext i32 %t51 to i64
  %t53 = add i64 %t50, %t52
  %t54 = trunc i64 %t53 to i32
  %t55 = sext i32 %t54 to i64
  %t56 = trunc i64 %t55 to i32
  %t57 = sext i32 %t56 to i64
  store i64 %t57, ptr %t10
  br label %while1
whileexit3:
  %t58 = load i64, ptr %t4
  ret i64 %t58
}

define i64 @crossover(ptr %p0, ptr %p1, ptr %p2, ptr %p3) {
entry:
  %t9 = alloca i64
  store i64 0, ptr %t9
  %t12 = alloca i64
  store i64 0, ptr %t12
  %t1 = call i64 @pseudo_rand(ptr %p3)
  %t2 = trunc i64 %t1 to i32
  %t3 = sext i32 %t2 to i64
  %t4 = trunc i64 16 to i32
  %t5 = sext i32 %t4 to i64
  %t6 = srem i64 %t3, %t5
  %t7 = trunc i64 %t6 to i32
  %t8 = sext i32 %t7 to i64
  %t10 = trunc i64 %t8 to i32
  %t11 = sext i32 %t10 to i64
  store i64 %t11, ptr %t9
  %t13 = trunc i64 0 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t12
  br label %while1
while1:
  %t15 = load i64, ptr %t12
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 16 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = icmp slt i64 %t17, %t19
  %t21 = zext i1 %t20 to i64
  %t22 = icmp ne i64 %t21, 0
  br i1 %t22, label %whilebody2, label %whileexit3
whilebody2:
  %t23 = load i64, ptr %t12
  %t24 = load i64, ptr %t9
  %t25 = trunc i64 %t23 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = trunc i64 %t24 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = icmp slt i64 %t26, %t28
  %t30 = zext i1 %t29 to i64
  %t31 = icmp ne i64 %t30, 0
  br i1 %t31, label %then4, label %else5
then4:
  %t32 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t33 = load i64, ptr %t12
  %t34 = mul i64 %t33, 1
  %t35 = getelementptr i64, ptr %t32, i64 %t34
  %t36 = load i64, ptr %t35
  %t37 = getelementptr [17 x i64], ptr %p2, i64 0, i64 0
  %t38 = load i64, ptr %t12
  %t39 = mul i64 %t38, 1
  %t40 = getelementptr i64, ptr %t37, i64 %t39
  %t41 = trunc i64 %t36 to i32
  %t42 = sext i32 %t41 to i64
  store i64 %t42, ptr %t40
  br label %ifend6
else5:
  %t43 = getelementptr [17 x i64], ptr %p1, i64 0, i64 0
  %t44 = load i64, ptr %t12
  %t45 = mul i64 %t44, 1
  %t46 = getelementptr i64, ptr %t43, i64 %t45
  %t47 = load i64, ptr %t46
  %t48 = getelementptr [17 x i64], ptr %p2, i64 0, i64 0
  %t49 = load i64, ptr %t12
  %t50 = mul i64 %t49, 1
  %t51 = getelementptr i64, ptr %t48, i64 %t50
  %t52 = trunc i64 %t47 to i32
  %t53 = sext i32 %t52 to i64
  store i64 %t53, ptr %t51
  br label %ifend6
ifend6:
  %t54 = load i64, ptr %t12
  %t55 = add i64 %t54, 1
  store i64 %t55, ptr %t12
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @mutate(ptr %p0, ptr %p1) {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t2 = trunc i64 10 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 0 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  br label %while1
while1:
  %t7 = load i64, ptr %t4
  %t8 = trunc i64 %t7 to i32
  %t9 = sext i32 %t8 to i64
  %t10 = trunc i64 16 to i32
  %t11 = sext i32 %t10 to i64
  %t12 = icmp slt i64 %t9, %t11
  %t13 = zext i1 %t12 to i64
  %t14 = icmp ne i64 %t13, 0
  br i1 %t14, label %whilebody2, label %whileexit3
whilebody2:
  %t15 = call i64 @pseudo_rand(ptr %p1)
  %t16 = trunc i64 %t15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = trunc i64 100 to i32
  %t19 = sext i32 %t18 to i64
  %t20 = srem i64 %t17, %t19
  %t21 = trunc i64 %t20 to i32
  %t22 = sext i32 %t21 to i64
  %t23 = load i64, ptr %t1
  %t24 = trunc i64 %t22 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 %t23 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = icmp slt i64 %t25, %t27
  %t29 = zext i1 %t28 to i64
  %t30 = icmp ne i64 %t29, 0
  br i1 %t30, label %then4, label %else5
then4:
  %t31 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t32 = load i64, ptr %t4
  %t33 = mul i64 %t32, 1
  %t34 = getelementptr i64, ptr %t31, i64 %t33
  %t35 = load i64, ptr %t34
  %t36 = call i64 @pseudo_rand(ptr %p1)
  %t37 = trunc i64 %t36 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = trunc i64 20 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = srem i64 %t38, %t40
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  %t44 = trunc i64 %t43 to i32
  %t45 = sext i32 %t44 to i64
  %t46 = trunc i64 10 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = sub i64 %t45, %t47
  %t49 = trunc i64 %t48 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = trunc i64 %t35 to i32
  %t52 = sext i32 %t51 to i64
  %t53 = trunc i64 %t50 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = add i64 %t52, %t54
  %t56 = trunc i64 %t55 to i32
  %t57 = sext i32 %t56 to i64
  %t58 = getelementptr [17 x i64], ptr %p0, i64 0, i64 0
  %t59 = load i64, ptr %t4
  %t60 = mul i64 %t59, 1
  %t61 = getelementptr i64, ptr %t58, i64 %t60
  %t62 = trunc i64 %t57 to i32
  %t63 = sext i32 %t62 to i64
  store i64 %t63, ptr %t61
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t64 = load i64, ptr %t4
  %t65 = add i64 %t64, 1
  store i64 %t65, ptr %t4
  br label %while1
whileexit3:
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

