; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t1 = alloca i64
  store i64 0, ptr %t1
  %t4 = alloca i64
  store i64 0, ptr %t4
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t10 = alloca i64
  store i64 0, ptr %t10
  %t13 = alloca i64
  store i64 0, ptr %t13
  %t16 = alloca i64
  store i64 0, ptr %t16
  %t19 = alloca i64
  store i64 0, ptr %t19
  %t22 = alloca i64
  store i64 0, ptr %t22
  %t25 = alloca i64
  store i64 0, ptr %t25
  %t28 = alloca i64
  store i64 0, ptr %t28
  %t31 = alloca i64
  store i64 0, ptr %t31
  %t34 = alloca i64
  store i64 0, ptr %t34
  %t53 = alloca i64
  store i64 0, ptr %t53
  %t85 = alloca i64
  store i64 0, ptr %t85
  %t182 = alloca i64
  store i64 0, ptr %t182
  %t186 = alloca i64
  store i64 0, ptr %t186
  %t190 = alloca i64
  store i64 0, ptr %t190
  %t254 = alloca i64
  store i64 0, ptr %t254
  %t267 = alloca i64
  store i64 0, ptr %t267
  %t299 = alloca i64
  store i64 0, ptr %t299
  %t347 = alloca i64
  store i64 0, ptr %t347
  %t377 = alloca i64
  store i64 0, ptr %t377
  %t425 = alloca i64
  store i64 0, ptr %t425
  %t455 = alloca i64
  store i64 0, ptr %t455
  %t513 = alloca i64
  store i64 0, ptr %t513
  %t2 = trunc i64 1000 to i32
  %t3 = sext i32 %t2 to i64
  store i64 %t3, ptr %t1
  %t5 = trunc i64 1500 to i32
  %t6 = sext i32 %t5 to i64
  store i64 %t6, ptr %t4
  %t8 = trunc i64 800 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  %t11 = trunc i64 0 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  %t14 = trunc i64 0 to i32
  %t15 = sext i32 %t14 to i64
  store i64 %t15, ptr %t13
  %t17 = trunc i64 0 to i32
  %t18 = sext i32 %t17 to i64
  store i64 %t18, ptr %t16
  %t20 = trunc i64 0 to i32
  %t21 = sext i32 %t20 to i64
  store i64 %t21, ptr %t19
  %t23 = trunc i64 0 to i32
  %t24 = sext i32 %t23 to i64
  store i64 %t24, ptr %t22
  %t26 = trunc i64 10 to i32
  %t27 = sext i32 %t26 to i64
  store i64 %t27, ptr %t25
  %t29 = trunc i64 15 to i32
  %t30 = sext i32 %t29 to i64
  store i64 %t30, ptr %t28
  %t32 = trunc i64 20 to i32
  %t33 = sext i32 %t32 to i64
  store i64 %t33, ptr %t31
  %t35 = trunc i64 0 to i32
  %t36 = sext i32 %t35 to i64
  store i64 %t36, ptr %t34
  br label %while1
while1:
  %t37 = load i64, ptr %t34
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = trunc i64 200 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = icmp slt i64 %t39, %t41
  %t43 = zext i1 %t42 to i64
  %t44 = icmp ne i64 %t43, 0
  br i1 %t44, label %whilebody2, label %whileexit3
whilebody2:
  %t45 = load i64, ptr %t34
  %t46 = trunc i64 %t45 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = trunc i64 3 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = srem i64 %t47, %t49
  %t51 = trunc i64 %t50 to i32
  %t52 = sext i32 %t51 to i64
  %t54 = trunc i64 %t52 to i32
  %t55 = sext i32 %t54 to i64
  store i64 %t55, ptr %t53
  %t56 = load i64, ptr %t34
  %t57 = trunc i64 %t56 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = trunc i64 7 to i32
  %t60 = sext i32 %t59 to i64
  %t61 = mul i64 %t58, %t60
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 %t63 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = trunc i64 15 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = add i64 %t65, %t67
  %t69 = trunc i64 %t68 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = trunc i64 %t70 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = trunc i64 50 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = srem i64 %t72, %t74
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = trunc i64 %t77 to i32
  %t79 = sext i32 %t78 to i64
  %t80 = trunc i64 10 to i32
  %t81 = sext i32 %t80 to i64
  %t82 = add i64 %t79, %t81
  %t83 = trunc i64 %t82 to i32
  %t84 = sext i32 %t83 to i64
  %t86 = trunc i64 %t84 to i32
  %t87 = sext i32 %t86 to i64
  store i64 %t87, ptr %t85
  %t88 = load i64, ptr %t53
  %t89 = trunc i64 %t88 to i32
  %t90 = sext i32 %t89 to i64
  %t91 = trunc i64 0 to i32
  %t92 = sext i32 %t91 to i64
  %t93 = icmp eq i64 %t90, %t92
  %t94 = zext i1 %t93 to i64
  %t95 = icmp ne i64 %t94, 0
  br i1 %t95, label %then4, label %else5
then4:
  %t96 = load i64, ptr %t10
  %t97 = load i64, ptr %t85
  %t98 = trunc i64 %t96 to i32
  %t99 = sext i32 %t98 to i64
  %t100 = trunc i64 %t97 to i32
  %t101 = sext i32 %t100 to i64
  %t102 = add i64 %t99, %t101
  %t103 = trunc i64 %t102 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = trunc i64 %t104 to i32
  %t106 = sext i32 %t105 to i64
  store i64 %t106, ptr %t10
  br label %ifend6
else5:
  %t107 = load i64, ptr %t53
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  %t110 = trunc i64 1 to i32
  %t111 = sext i32 %t110 to i64
  %t112 = icmp eq i64 %t109, %t111
  %t113 = zext i1 %t112 to i64
  %t114 = icmp ne i64 %t113, 0
  br i1 %t114, label %then7, label %else8
then7:
  %t115 = load i64, ptr %t13
  %t116 = load i64, ptr %t85
  %t117 = trunc i64 %t115 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = trunc i64 %t116 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = add i64 %t118, %t120
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  %t124 = trunc i64 %t123 to i32
  %t125 = sext i32 %t124 to i64
  store i64 %t125, ptr %t13
  br label %ifend9
else8:
  %t126 = load i64, ptr %t16
  %t127 = load i64, ptr %t85
  %t128 = trunc i64 %t126 to i32
  %t129 = sext i32 %t128 to i64
  %t130 = trunc i64 %t127 to i32
  %t131 = sext i32 %t130 to i64
  %t132 = add i64 %t129, %t131
  %t133 = trunc i64 %t132 to i32
  %t134 = sext i32 %t133 to i64
  %t135 = trunc i64 %t134 to i32
  %t136 = sext i32 %t135 to i64
  store i64 %t136, ptr %t16
  br label %ifend9
ifend9:
  br label %ifend6
ifend6:
  %t137 = load i64, ptr %t34
  %t138 = trunc i64 %t137 to i32
  %t139 = sext i32 %t138 to i64
  %t140 = trunc i64 10 to i32
  %t141 = sext i32 %t140 to i64
  %t142 = srem i64 %t139, %t141
  %t143 = trunc i64 %t142 to i32
  %t144 = sext i32 %t143 to i64
  %t145 = trunc i64 %t144 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = trunc i64 0 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = icmp eq i64 %t146, %t148
  %t150 = zext i1 %t149 to i64
  %t151 = icmp ne i64 %t150, 0
  br i1 %t151, label %then10, label %else11
then10:
  %t152 = load i64, ptr %t1
  %t153 = trunc i64 %t152 to i32
  %t154 = sext i32 %t153 to i64
  %t155 = trunc i64 200 to i32
  %t156 = sext i32 %t155 to i64
  %t157 = add i64 %t154, %t156
  %t158 = trunc i64 %t157 to i32
  %t159 = sext i32 %t158 to i64
  %t160 = trunc i64 %t159 to i32
  %t161 = sext i32 %t160 to i64
  store i64 %t161, ptr %t1
  %t162 = load i64, ptr %t4
  %t163 = trunc i64 %t162 to i32
  %t164 = sext i32 %t163 to i64
  %t165 = trunc i64 300 to i32
  %t166 = sext i32 %t165 to i64
  %t167 = add i64 %t164, %t166
  %t168 = trunc i64 %t167 to i32
  %t169 = sext i32 %t168 to i64
  %t170 = trunc i64 %t169 to i32
  %t171 = sext i32 %t170 to i64
  store i64 %t171, ptr %t4
  %t172 = load i64, ptr %t7
  %t173 = trunc i64 %t172 to i32
  %t174 = sext i32 %t173 to i64
  %t175 = trunc i64 150 to i32
  %t176 = sext i32 %t175 to i64
  %t177 = add i64 %t174, %t176
  %t178 = trunc i64 %t177 to i32
  %t179 = sext i32 %t178 to i64
  %t180 = trunc i64 %t179 to i32
  %t181 = sext i32 %t180 to i64
  store i64 %t181, ptr %t7
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  %t183 = zext i1 0 to i64
  %t184 = trunc i64 %t183 to i32
  %t185 = sext i32 %t184 to i64
  store i64 %t185, ptr %t182
  %t187 = zext i1 0 to i64
  %t188 = trunc i64 %t187 to i32
  %t189 = sext i32 %t188 to i64
  store i64 %t189, ptr %t186
  %t191 = zext i1 0 to i64
  %t192 = trunc i64 %t191 to i32
  %t193 = sext i32 %t192 to i64
  store i64 %t193, ptr %t190
  %t194 = load i64, ptr %t10
  %t195 = trunc i64 %t194 to i32
  %t196 = sext i32 %t195 to i64
  %t197 = trunc i64 0 to i32
  %t198 = sext i32 %t197 to i64
  %t199 = icmp sgt i64 %t196, %t198
  %t200 = zext i1 %t199 to i64
  %t201 = icmp ne i64 %t200, 0
  br i1 %t201, label %then13, label %else14
then13:
  %t202 = load i64, ptr %t1
  %t203 = load i64, ptr %t10
  %t204 = trunc i64 %t202 to i32
  %t205 = sext i32 %t204 to i64
  %t206 = trunc i64 %t203 to i32
  %t207 = sext i32 %t206 to i64
  %t208 = icmp sge i64 %t205, %t207
  %t209 = zext i1 %t208 to i64
  %t210 = icmp ne i64 %t209, 0
  br i1 %t210, label %then16, label %else17
then16:
  %t211 = zext i1 1 to i64
  %t212 = trunc i64 %t211 to i32
  %t213 = sext i32 %t212 to i64
  store i64 %t213, ptr %t182
  br label %ifend18
else17:
  br label %ifend18
ifend18:
  br label %ifend15
else14:
  br label %ifend15
ifend15:
  %t214 = load i64, ptr %t13
  %t215 = trunc i64 %t214 to i32
  %t216 = sext i32 %t215 to i64
  %t217 = trunc i64 0 to i32
  %t218 = sext i32 %t217 to i64
  %t219 = icmp sgt i64 %t216, %t218
  %t220 = zext i1 %t219 to i64
  %t221 = icmp ne i64 %t220, 0
  br i1 %t221, label %then19, label %else20
then19:
  %t222 = load i64, ptr %t4
  %t223 = load i64, ptr %t13
  %t224 = trunc i64 %t222 to i32
  %t225 = sext i32 %t224 to i64
  %t226 = trunc i64 %t223 to i32
  %t227 = sext i32 %t226 to i64
  %t228 = icmp sge i64 %t225, %t227
  %t229 = zext i1 %t228 to i64
  %t230 = icmp ne i64 %t229, 0
  br i1 %t230, label %then22, label %else23
then22:
  %t231 = zext i1 1 to i64
  %t232 = trunc i64 %t231 to i32
  %t233 = sext i32 %t232 to i64
  store i64 %t233, ptr %t186
  br label %ifend24
else23:
  br label %ifend24
ifend24:
  br label %ifend21
else20:
  br label %ifend21
ifend21:
  %t234 = load i64, ptr %t16
  %t235 = trunc i64 %t234 to i32
  %t236 = sext i32 %t235 to i64
  %t237 = trunc i64 0 to i32
  %t238 = sext i32 %t237 to i64
  %t239 = icmp sgt i64 %t236, %t238
  %t240 = zext i1 %t239 to i64
  %t241 = icmp ne i64 %t240, 0
  br i1 %t241, label %then25, label %else26
then25:
  %t242 = load i64, ptr %t7
  %t243 = load i64, ptr %t16
  %t244 = trunc i64 %t242 to i32
  %t245 = sext i32 %t244 to i64
  %t246 = trunc i64 %t243 to i32
  %t247 = sext i32 %t246 to i64
  %t248 = icmp sge i64 %t245, %t247
  %t249 = zext i1 %t248 to i64
  %t250 = icmp ne i64 %t249, 0
  br i1 %t250, label %then28, label %else29
then28:
  %t251 = zext i1 1 to i64
  %t252 = trunc i64 %t251 to i32
  %t253 = sext i32 %t252 to i64
  store i64 %t253, ptr %t190
  br label %ifend30
else29:
  br label %ifend30
ifend30:
  br label %ifend27
else26:
  br label %ifend27
ifend27:
  %t255 = trunc i64 0 to i32
  %t256 = sext i32 %t255 to i64
  store i64 %t256, ptr %t254
  %t257 = load i64, ptr %t182
  %t258 = icmp ne i64 %t257, 0
  br i1 %t258, label %then31, label %else32
then31:
  %t259 = load i64, ptr %t10
  %t260 = trunc i64 %t259 to i32
  %t261 = sext i32 %t260 to i64
  %t262 = trunc i64 50 to i32
  %t263 = sext i32 %t262 to i64
  %t264 = icmp sgt i64 %t261, %t263
  %t265 = zext i1 %t264 to i64
  %t266 = icmp ne i64 %t265, 0
  br i1 %t266, label %then34, label %else35
then34:
  %t268 = trunc i64 5 to i32
  %t269 = sext i32 %t268 to i64
  store i64 %t269, ptr %t267
  %t270 = trunc i64 100 to i32
  %t271 = sext i32 %t270 to i64
  store i64 %t271, ptr %t254
  %t272 = load i64, ptr %t10
  %t273 = load i64, ptr %t25
  %t274 = load i64, ptr %t267
  %t275 = trunc i64 %t273 to i32
  %t276 = sext i32 %t275 to i64
  %t277 = trunc i64 %t274 to i32
  %t278 = sext i32 %t277 to i64
  %t279 = sub i64 %t276, %t278
  %t280 = trunc i64 %t279 to i32
  %t281 = sext i32 %t280 to i64
  %t282 = trunc i64 %t272 to i32
  %t283 = sext i32 %t282 to i64
  %t284 = trunc i64 %t281 to i32
  %t285 = sext i32 %t284 to i64
  %t286 = mul i64 %t283, %t285
  %t287 = trunc i64 %t286 to i32
  %t288 = sext i32 %t287 to i64
  br label %thencont37
thencont37:
  br label %ifend36
else35:
  %t289 = load i64, ptr %t10
  %t290 = load i64, ptr %t25
  %t291 = trunc i64 %t289 to i32
  %t292 = sext i32 %t291 to i64
  %t293 = trunc i64 %t290 to i32
  %t294 = sext i32 %t293 to i64
  %t295 = mul i64 %t292, %t294
  %t296 = trunc i64 %t295 to i32
  %t297 = sext i32 %t296 to i64
  br label %elsecont38
elsecont38:
  br label %ifend36
ifend36:
  %t298 = phi i64 [ %t288, %thencont37 ], [ %t297, %elsecont38 ]
  %t300 = trunc i64 %t298 to i32
  %t301 = sext i32 %t300 to i64
  store i64 %t301, ptr %t299
  %t302 = load i64, ptr %t1
  %t303 = load i64, ptr %t10
  %t304 = trunc i64 %t302 to i32
  %t305 = sext i32 %t304 to i64
  %t306 = trunc i64 %t303 to i32
  %t307 = sext i32 %t306 to i64
  %t308 = sub i64 %t305, %t307
  %t309 = trunc i64 %t308 to i32
  %t310 = sext i32 %t309 to i64
  %t311 = trunc i64 %t310 to i32
  %t312 = sext i32 %t311 to i64
  store i64 %t312, ptr %t1
  %t313 = load i64, ptr %t22
  %t314 = load i64, ptr %t299
  %t315 = trunc i64 %t313 to i32
  %t316 = sext i32 %t315 to i64
  %t317 = trunc i64 %t314 to i32
  %t318 = sext i32 %t317 to i64
  %t319 = add i64 %t316, %t318
  %t320 = trunc i64 %t319 to i32
  %t321 = sext i32 %t320 to i64
  %t322 = trunc i64 %t321 to i32
  %t323 = sext i32 %t322 to i64
  store i64 %t323, ptr %t22
  %t324 = load i64, ptr %t19
  %t325 = load i64, ptr %t10
  %t326 = trunc i64 %t324 to i32
  %t327 = sext i32 %t326 to i64
  %t328 = trunc i64 %t325 to i32
  %t329 = sext i32 %t328 to i64
  %t330 = add i64 %t327, %t329
  %t331 = trunc i64 %t330 to i32
  %t332 = sext i32 %t331 to i64
  %t333 = trunc i64 %t332 to i32
  %t334 = sext i32 %t333 to i64
  store i64 %t334, ptr %t19
  %t335 = trunc i64 0 to i32
  %t336 = sext i32 %t335 to i64
  store i64 %t336, ptr %t10
  br label %ifend33
else32:
  br label %ifend33
ifend33:
  %t337 = load i64, ptr %t186
  %t338 = icmp ne i64 %t337, 0
  br i1 %t338, label %then39, label %else40
then39:
  %t339 = load i64, ptr %t13
  %t340 = trunc i64 %t339 to i32
  %t341 = sext i32 %t340 to i64
  %t342 = trunc i64 40 to i32
  %t343 = sext i32 %t342 to i64
  %t344 = icmp sgt i64 %t341, %t343
  %t345 = zext i1 %t344 to i64
  %t346 = icmp ne i64 %t345, 0
  br i1 %t346, label %then42, label %else43
then42:
  %t348 = trunc i64 3 to i32
  %t349 = sext i32 %t348 to i64
  store i64 %t349, ptr %t347
  %t350 = load i64, ptr %t13
  %t351 = load i64, ptr %t28
  %t352 = load i64, ptr %t347
  %t353 = trunc i64 %t351 to i32
  %t354 = sext i32 %t353 to i64
  %t355 = trunc i64 %t352 to i32
  %t356 = sext i32 %t355 to i64
  %t357 = sub i64 %t354, %t356
  %t358 = trunc i64 %t357 to i32
  %t359 = sext i32 %t358 to i64
  %t360 = trunc i64 %t350 to i32
  %t361 = sext i32 %t360 to i64
  %t362 = trunc i64 %t359 to i32
  %t363 = sext i32 %t362 to i64
  %t364 = mul i64 %t361, %t363
  %t365 = trunc i64 %t364 to i32
  %t366 = sext i32 %t365 to i64
  br label %thencont45
thencont45:
  br label %ifend44
else43:
  %t367 = load i64, ptr %t13
  %t368 = load i64, ptr %t28
  %t369 = trunc i64 %t367 to i32
  %t370 = sext i32 %t369 to i64
  %t371 = trunc i64 %t368 to i32
  %t372 = sext i32 %t371 to i64
  %t373 = mul i64 %t370, %t372
  %t374 = trunc i64 %t373 to i32
  %t375 = sext i32 %t374 to i64
  br label %elsecont46
elsecont46:
  br label %ifend44
ifend44:
  %t376 = phi i64 [ %t366, %thencont45 ], [ %t375, %elsecont46 ]
  %t378 = trunc i64 %t376 to i32
  %t379 = sext i32 %t378 to i64
  store i64 %t379, ptr %t377
  %t380 = load i64, ptr %t4
  %t381 = load i64, ptr %t13
  %t382 = trunc i64 %t380 to i32
  %t383 = sext i32 %t382 to i64
  %t384 = trunc i64 %t381 to i32
  %t385 = sext i32 %t384 to i64
  %t386 = sub i64 %t383, %t385
  %t387 = trunc i64 %t386 to i32
  %t388 = sext i32 %t387 to i64
  %t389 = trunc i64 %t388 to i32
  %t390 = sext i32 %t389 to i64
  store i64 %t390, ptr %t4
  %t391 = load i64, ptr %t22
  %t392 = load i64, ptr %t377
  %t393 = trunc i64 %t391 to i32
  %t394 = sext i32 %t393 to i64
  %t395 = trunc i64 %t392 to i32
  %t396 = sext i32 %t395 to i64
  %t397 = add i64 %t394, %t396
  %t398 = trunc i64 %t397 to i32
  %t399 = sext i32 %t398 to i64
  %t400 = trunc i64 %t399 to i32
  %t401 = sext i32 %t400 to i64
  store i64 %t401, ptr %t22
  %t402 = load i64, ptr %t19
  %t403 = load i64, ptr %t13
  %t404 = trunc i64 %t402 to i32
  %t405 = sext i32 %t404 to i64
  %t406 = trunc i64 %t403 to i32
  %t407 = sext i32 %t406 to i64
  %t408 = add i64 %t405, %t407
  %t409 = trunc i64 %t408 to i32
  %t410 = sext i32 %t409 to i64
  %t411 = trunc i64 %t410 to i32
  %t412 = sext i32 %t411 to i64
  store i64 %t412, ptr %t19
  %t413 = trunc i64 0 to i32
  %t414 = sext i32 %t413 to i64
  store i64 %t414, ptr %t13
  br label %ifend41
else40:
  br label %ifend41
ifend41:
  %t415 = load i64, ptr %t190
  %t416 = icmp ne i64 %t415, 0
  br i1 %t416, label %then47, label %else48
then47:
  %t417 = load i64, ptr %t16
  %t418 = trunc i64 %t417 to i32
  %t419 = sext i32 %t418 to i64
  %t420 = trunc i64 30 to i32
  %t421 = sext i32 %t420 to i64
  %t422 = icmp sgt i64 %t419, %t421
  %t423 = zext i1 %t422 to i64
  %t424 = icmp ne i64 %t423, 0
  br i1 %t424, label %then50, label %else51
then50:
  %t426 = trunc i64 2 to i32
  %t427 = sext i32 %t426 to i64
  store i64 %t427, ptr %t425
  %t428 = load i64, ptr %t16
  %t429 = load i64, ptr %t31
  %t430 = load i64, ptr %t425
  %t431 = trunc i64 %t429 to i32
  %t432 = sext i32 %t431 to i64
  %t433 = trunc i64 %t430 to i32
  %t434 = sext i32 %t433 to i64
  %t435 = sub i64 %t432, %t434
  %t436 = trunc i64 %t435 to i32
  %t437 = sext i32 %t436 to i64
  %t438 = trunc i64 %t428 to i32
  %t439 = sext i32 %t438 to i64
  %t440 = trunc i64 %t437 to i32
  %t441 = sext i32 %t440 to i64
  %t442 = mul i64 %t439, %t441
  %t443 = trunc i64 %t442 to i32
  %t444 = sext i32 %t443 to i64
  br label %thencont53
thencont53:
  br label %ifend52
else51:
  %t445 = load i64, ptr %t16
  %t446 = load i64, ptr %t31
  %t447 = trunc i64 %t445 to i32
  %t448 = sext i32 %t447 to i64
  %t449 = trunc i64 %t446 to i32
  %t450 = sext i32 %t449 to i64
  %t451 = mul i64 %t448, %t450
  %t452 = trunc i64 %t451 to i32
  %t453 = sext i32 %t452 to i64
  br label %elsecont54
elsecont54:
  br label %ifend52
ifend52:
  %t454 = phi i64 [ %t444, %thencont53 ], [ %t453, %elsecont54 ]
  %t456 = trunc i64 %t454 to i32
  %t457 = sext i32 %t456 to i64
  store i64 %t457, ptr %t455
  %t458 = load i64, ptr %t7
  %t459 = load i64, ptr %t16
  %t460 = trunc i64 %t458 to i32
  %t461 = sext i32 %t460 to i64
  %t462 = trunc i64 %t459 to i32
  %t463 = sext i32 %t462 to i64
  %t464 = sub i64 %t461, %t463
  %t465 = trunc i64 %t464 to i32
  %t466 = sext i32 %t465 to i64
  %t467 = trunc i64 %t466 to i32
  %t468 = sext i32 %t467 to i64
  store i64 %t468, ptr %t7
  %t469 = load i64, ptr %t22
  %t470 = load i64, ptr %t455
  %t471 = trunc i64 %t469 to i32
  %t472 = sext i32 %t471 to i64
  %t473 = trunc i64 %t470 to i32
  %t474 = sext i32 %t473 to i64
  %t475 = add i64 %t472, %t474
  %t476 = trunc i64 %t475 to i32
  %t477 = sext i32 %t476 to i64
  %t478 = trunc i64 %t477 to i32
  %t479 = sext i32 %t478 to i64
  store i64 %t479, ptr %t22
  %t480 = load i64, ptr %t19
  %t481 = load i64, ptr %t16
  %t482 = trunc i64 %t480 to i32
  %t483 = sext i32 %t482 to i64
  %t484 = trunc i64 %t481 to i32
  %t485 = sext i32 %t484 to i64
  %t486 = add i64 %t483, %t485
  %t487 = trunc i64 %t486 to i32
  %t488 = sext i32 %t487 to i64
  %t489 = trunc i64 %t488 to i32
  %t490 = sext i32 %t489 to i64
  store i64 %t490, ptr %t19
  %t491 = trunc i64 0 to i32
  %t492 = sext i32 %t491 to i64
  store i64 %t492, ptr %t16
  br label %ifend49
else48:
  br label %ifend49
ifend49:
  %t493 = load i64, ptr %t34
  %t494 = trunc i64 %t493 to i32
  %t495 = sext i32 %t494 to i64
  %t496 = trunc i64 25 to i32
  %t497 = sext i32 %t496 to i64
  %t498 = srem i64 %t495, %t497
  %t499 = trunc i64 %t498 to i32
  %t500 = sext i32 %t499 to i64
  %t501 = trunc i64 %t500 to i32
  %t502 = sext i32 %t501 to i64
  %t503 = trunc i64 0 to i32
  %t504 = sext i32 %t503 to i64
  %t505 = icmp eq i64 %t502, %t504
  %t506 = zext i1 %t505 to i64
  %t507 = icmp ne i64 %t506, 0
  br i1 %t507, label %then55, label %else56
then55:
  %t508 = load i64, ptr %t1
  %t509 = load i64, ptr %t4
  %t510 = load i64, ptr %t7
  %t511 = load i64, ptr %t22
  %t512 = call i64 @perform_audit(i64 %t508, i64 %t509, i64 %t510, i64 %t511)
  %t514 = trunc i64 %t512 to i32
  %t515 = sext i32 %t514 to i64
  store i64 %t515, ptr %t513
  %t516 = load i64, ptr %t513
  %t517 = trunc i64 %t516 to i32
  %t518 = sext i32 %t517 to i64
  %t519 = trunc i64 0 to i32
  %t520 = sext i32 %t519 to i64
  %t521 = icmp slt i64 %t518, %t520
  %t522 = zext i1 %t521 to i64
  %t523 = icmp ne i64 %t522, 0
  br i1 %t523, label %then58, label %else59
then58:
  %t524 = load i64, ptr %t22
  %t525 = load i64, ptr %t254
  %t526 = trunc i64 %t524 to i32
  %t527 = sext i32 %t526 to i64
  %t528 = trunc i64 %t525 to i32
  %t529 = sext i32 %t528 to i64
  %t530 = add i64 %t527, %t529
  %t531 = trunc i64 %t530 to i32
  %t532 = sext i32 %t531 to i64
  %t533 = trunc i64 %t532 to i32
  %t534 = sext i32 %t533 to i64
  store i64 %t534, ptr %t22
  br label %ifend60
else59:
  br label %ifend60
ifend60:
  br label %ifend57
else56:
  br label %ifend57
ifend57:
  %t535 = load i64, ptr %t34
  %t536 = trunc i64 %t535 to i32
  %t537 = sext i32 %t536 to i64
  %t538 = trunc i64 1 to i32
  %t539 = sext i32 %t538 to i64
  %t540 = add i64 %t537, %t539
  %t541 = trunc i64 %t540 to i32
  %t542 = sext i32 %t541 to i64
  %t543 = trunc i64 %t542 to i32
  %t544 = sext i32 %t543 to i64
  store i64 %t544, ptr %t34
  br label %while1
whileexit3:
  %t545 = load i64, ptr %t22
  %t546 = call i64 @printlnInt(i64 %t545)
  %t547 = load i64, ptr %t19
  %t548 = call i64 @printlnInt(i64 %t547)
  %t549 = load i64, ptr %t1
  %t550 = call i64 @printlnInt(i64 %t549)
  %t551 = load i64, ptr %t4
  %t552 = call i64 @printlnInt(i64 %t551)
  %t553 = load i64, ptr %t7
  %t554 = call i64 @printlnInt(i64 %t553)
  ret i64 0
}

define i64 @perform_audit(i64 %p0, i64 %p1, i64 %p2, i64 %p3) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 %p1, ptr %t2
  %t3 = alloca i64
  store i64 %p2, ptr %t3
  %t4 = alloca i64
  store i64 %p3, ptr %t4
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t128 = alloca i64
  store i64 0, ptr %t128
  %t132 = alloca i64
  store i64 0, ptr %t132
  %t6 = trunc i64 0 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t8 = load i64, ptr %t1
  %t9 = trunc i64 %t8 to i32
  %t10 = sext i32 %t9 to i64
  %t11 = trunc i64 100 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = icmp slt i64 %t10, %t12
  %t14 = zext i1 %t13 to i64
  %t15 = icmp ne i64 %t14, 0
  br i1 %t15, label %then1, label %else2
then1:
  %t16 = load i64, ptr %t5
  %t17 = trunc i64 %t16 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = trunc i64 10 to i32
  %t20 = sext i32 %t19 to i64
  %t21 = sub i64 %t18, %t20
  %t22 = trunc i64 %t21 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  store i64 %t25, ptr %t5
  br label %ifend3
else2:
  %t26 = load i64, ptr %t5
  %t27 = trunc i64 %t26 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = trunc i64 5 to i32
  %t30 = sext i32 %t29 to i64
  %t31 = add i64 %t28, %t30
  %t32 = trunc i64 %t31 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = trunc i64 %t33 to i32
  %t35 = sext i32 %t34 to i64
  store i64 %t35, ptr %t5
  br label %ifend3
ifend3:
  %t36 = load i64, ptr %t2
  %t37 = trunc i64 %t36 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = trunc i64 150 to i32
  %t40 = sext i32 %t39 to i64
  %t41 = icmp slt i64 %t38, %t40
  %t42 = zext i1 %t41 to i64
  %t43 = icmp ne i64 %t42, 0
  br i1 %t43, label %then4, label %else5
then4:
  %t44 = load i64, ptr %t5
  %t45 = trunc i64 %t44 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = trunc i64 10 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = sub i64 %t46, %t48
  %t50 = trunc i64 %t49 to i32
  %t51 = sext i32 %t50 to i64
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  store i64 %t53, ptr %t5
  br label %ifend6
else5:
  %t54 = load i64, ptr %t5
  %t55 = trunc i64 %t54 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = trunc i64 5 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = add i64 %t56, %t58
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  store i64 %t63, ptr %t5
  br label %ifend6
ifend6:
  %t64 = load i64, ptr %t3
  %t65 = trunc i64 %t64 to i32
  %t66 = sext i32 %t65 to i64
  %t67 = trunc i64 80 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = icmp slt i64 %t66, %t68
  %t70 = zext i1 %t69 to i64
  %t71 = icmp ne i64 %t70, 0
  br i1 %t71, label %then7, label %else8
then7:
  %t72 = load i64, ptr %t5
  %t73 = trunc i64 %t72 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = trunc i64 10 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = sub i64 %t74, %t76
  %t78 = trunc i64 %t77 to i32
  %t79 = sext i32 %t78 to i64
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  store i64 %t81, ptr %t5
  br label %ifend9
else8:
  %t82 = load i64, ptr %t5
  %t83 = trunc i64 %t82 to i32
  %t84 = sext i32 %t83 to i64
  %t85 = trunc i64 5 to i32
  %t86 = sext i32 %t85 to i64
  %t87 = add i64 %t84, %t86
  %t88 = trunc i64 %t87 to i32
  %t89 = sext i32 %t88 to i64
  %t90 = trunc i64 %t89 to i32
  %t91 = sext i32 %t90 to i64
  store i64 %t91, ptr %t5
  br label %ifend9
ifend9:
  %t92 = load i64, ptr %t4
  %t93 = trunc i64 %t92 to i32
  %t94 = sext i32 %t93 to i64
  %t95 = trunc i64 50000 to i32
  %t96 = sext i32 %t95 to i64
  %t97 = icmp sgt i64 %t94, %t96
  %t98 = zext i1 %t97 to i64
  %t99 = icmp ne i64 %t98, 0
  br i1 %t99, label %then10, label %else11
then10:
  %t100 = load i64, ptr %t5
  %t101 = trunc i64 %t100 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = trunc i64 20 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = add i64 %t102, %t104
  %t106 = trunc i64 %t105 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  store i64 %t109, ptr %t5
  br label %ifend12
else11:
  %t110 = load i64, ptr %t4
  %t111 = trunc i64 %t110 to i32
  %t112 = sext i32 %t111 to i64
  %t113 = trunc i64 20000 to i32
  %t114 = sext i32 %t113 to i64
  %t115 = icmp sgt i64 %t112, %t114
  %t116 = zext i1 %t115 to i64
  %t117 = icmp ne i64 %t116, 0
  br i1 %t117, label %then13, label %else14
then13:
  %t118 = load i64, ptr %t5
  %t119 = trunc i64 %t118 to i32
  %t120 = sext i32 %t119 to i64
  %t121 = trunc i64 10 to i32
  %t122 = sext i32 %t121 to i64
  %t123 = add i64 %t120, %t122
  %t124 = trunc i64 %t123 to i32
  %t125 = sext i32 %t124 to i64
  %t126 = trunc i64 %t125 to i32
  %t127 = sext i32 %t126 to i64
  store i64 %t127, ptr %t5
  br label %ifend15
else14:
  br label %ifend15
ifend15:
  br label %ifend12
ifend12:
  %t129 = trunc i64 0 to i32
  %t130 = sext i32 %t129 to i64
  store i64 %t130, ptr %t128
  %t131 = load i64, ptr %t4
  %t133 = trunc i64 %t131 to i32
  %t134 = sext i32 %t133 to i64
  store i64 %t134, ptr %t132
  br label %while16
while16:
  %t135 = load i64, ptr %t128
  %t136 = trunc i64 %t135 to i32
  %t137 = sext i32 %t136 to i64
  %t138 = trunc i64 5 to i32
  %t139 = sext i32 %t138 to i64
  %t140 = icmp slt i64 %t137, %t139
  %t141 = zext i1 %t140 to i64
  %t142 = icmp ne i64 %t141, 0
  br i1 %t142, label %whilebody17, label %whileexit18
whilebody17:
  %t143 = load i64, ptr %t132
  %t144 = load i64, ptr %t128
  %t145 = trunc i64 %t144 to i32
  %t146 = sext i32 %t145 to i64
  %t147 = trunc i64 1 to i32
  %t148 = sext i32 %t147 to i64
  %t149 = add i64 %t146, %t148
  %t150 = trunc i64 %t149 to i32
  %t151 = sext i32 %t150 to i64
  %t152 = trunc i64 %t143 to i32
  %t153 = sext i32 %t152 to i64
  %t154 = trunc i64 %t151 to i32
  %t155 = sext i32 %t154 to i64
  %t156 = sdiv i64 %t153, %t155
  %t157 = trunc i64 %t156 to i32
  %t158 = sext i32 %t157 to i64
  %t159 = trunc i64 %t158 to i32
  %t160 = sext i32 %t159 to i64
  store i64 %t160, ptr %t132
  %t161 = load i64, ptr %t128
  %t162 = trunc i64 %t161 to i32
  %t163 = sext i32 %t162 to i64
  %t164 = trunc i64 1 to i32
  %t165 = sext i32 %t164 to i64
  %t166 = add i64 %t163, %t165
  %t167 = trunc i64 %t166 to i32
  %t168 = sext i32 %t167 to i64
  %t169 = trunc i64 %t168 to i32
  %t170 = sext i32 %t169 to i64
  store i64 %t170, ptr %t128
  br label %while16
whileexit18:
  %t171 = load i64, ptr %t5
  %t172 = load i64, ptr %t132
  %t173 = trunc i64 %t172 to i32
  %t174 = sext i32 %t173 to i64
  %t175 = trunc i64 10 to i32
  %t176 = sext i32 %t175 to i64
  %t177 = srem i64 %t174, %t176
  %t178 = trunc i64 %t177 to i32
  %t179 = sext i32 %t178 to i64
  %t180 = trunc i64 %t171 to i32
  %t181 = sext i32 %t180 to i64
  %t182 = trunc i64 %t179 to i32
  %t183 = sext i32 %t182 to i64
  %t184 = add i64 %t181, %t183
  %t185 = trunc i64 %t184 to i32
  %t186 = sext i32 %t185 to i64
  %t187 = trunc i64 %t186 to i32
  %t188 = sext i32 %t187 to i64
  store i64 %t188, ptr %t5
  %t189 = load i64, ptr %t5
  %t190 = trunc i64 %t189 to i32
  %t191 = sext i32 %t190 to i64
  %t192 = trunc i64 15 to i32
  %t193 = sext i32 %t192 to i64
  %t194 = icmp sgt i64 %t191, %t193
  %t195 = zext i1 %t194 to i64
  %t196 = icmp ne i64 %t195, 0
  br i1 %t196, label %then19, label %else20
then19:
  ret i64 1
else20:
  %t197 = load i64, ptr %t5
  %t198 = trunc i64 %t197 to i32
  %t199 = sext i32 %t198 to i64
  %t200 = trunc i64 0 to i32
  %t201 = sext i32 %t200 to i64
  %t202 = icmp sgt i64 %t199, %t201
  %t203 = zext i1 %t202 to i64
  %t204 = icmp ne i64 %t203, 0
  br i1 %t204, label %then22, label %else23
then22:
  ret i64 0
else23:
  ret i64 -1
ifend24:
  br label %ifend21
ifend21:
  ret i64 0
}

define i64 @another_level_of_processing(i64 %p0, i64 %p1) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 %p1, ptr %t2
  %t3 = alloca i64
  store i64 0, ptr %t3
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t78 = alloca i64
  store i64 0, ptr %t78
  %t4 = trunc i64 0 to i32
  %t5 = sext i32 %t4 to i64
  store i64 %t5, ptr %t3
  %t6 = load i64, ptr %t1
  %t8 = trunc i64 %t6 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  br label %while1
while1:
  %t10 = load i64, ptr %t3
  %t11 = trunc i64 %t10 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = trunc i64 10 to i32
  %t14 = sext i32 %t13 to i64
  %t15 = icmp slt i64 %t12, %t14
  %t16 = zext i1 %t15 to i64
  %t17 = icmp ne i64 %t16, 0
  br i1 %t17, label %whilebody2, label %whileexit3
whilebody2:
  %t18 = load i64, ptr %t3
  %t19 = trunc i64 %t18 to i32
  %t20 = sext i32 %t19 to i64
  %t21 = trunc i64 2 to i32
  %t22 = sext i32 %t21 to i64
  %t23 = srem i64 %t20, %t22
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 %t25 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = trunc i64 0 to i32
  %t29 = sext i32 %t28 to i64
  %t30 = icmp eq i64 %t27, %t29
  %t31 = zext i1 %t30 to i64
  %t32 = icmp ne i64 %t31, 0
  br i1 %t32, label %then4, label %else5
then4:
  %t33 = load i64, ptr %t7
  %t34 = load i64, ptr %t2
  %t35 = load i64, ptr %t3
  %t36 = trunc i64 %t34 to i32
  %t37 = sext i32 %t36 to i64
  %t38 = trunc i64 %t35 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = mul i64 %t37, %t39
  %t41 = trunc i64 %t40 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = trunc i64 %t33 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = trunc i64 %t42 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = add i64 %t44, %t46
  %t48 = trunc i64 %t47 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = trunc i64 %t49 to i32
  %t51 = sext i32 %t50 to i64
  store i64 %t51, ptr %t7
  br label %ifend6
else5:
  %t52 = load i64, ptr %t7
  %t53 = load i64, ptr %t2
  %t54 = load i64, ptr %t3
  %t55 = trunc i64 %t53 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = trunc i64 %t54 to i32
  %t58 = sext i32 %t57 to i64
  %t59 = mul i64 %t56, %t58
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = trunc i64 %t61 to i32
  %t63 = sext i32 %t62 to i64
  %t64 = trunc i64 2 to i32
  %t65 = sext i32 %t64 to i64
  %t66 = sdiv i64 %t63, %t65
  %t67 = trunc i64 %t66 to i32
  %t68 = sext i32 %t67 to i64
  %t69 = trunc i64 %t52 to i32
  %t70 = sext i32 %t69 to i64
  %t71 = trunc i64 %t68 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = sub i64 %t70, %t72
  %t74 = trunc i64 %t73 to i32
  %t75 = sext i32 %t74 to i64
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  store i64 %t77, ptr %t7
  br label %ifend6
ifend6:
  %t79 = trunc i64 0 to i32
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  br label %while7
while7:
  %t81 = load i64, ptr %t78
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 5 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = icmp slt i64 %t83, %t85
  %t87 = zext i1 %t86 to i64
  %t88 = icmp ne i64 %t87, 0
  br i1 %t88, label %whilebody8, label %whileexit9
whilebody8:
  %t89 = load i64, ptr %t7
  %t90 = load i64, ptr %t78
  %t91 = trunc i64 %t89 to i32
  %t92 = sext i32 %t91 to i64
  %t93 = trunc i64 %t90 to i32
  %t94 = sext i32 %t93 to i64
  %t95 = add i64 %t92, %t94
  %t96 = trunc i64 %t95 to i32
  %t97 = sext i32 %t96 to i64
  %t98 = trunc i64 %t97 to i32
  %t99 = sext i32 %t98 to i64
  store i64 %t99, ptr %t7
  %t100 = load i64, ptr %t78
  %t101 = trunc i64 %t100 to i32
  %t102 = sext i32 %t101 to i64
  %t103 = trunc i64 1 to i32
  %t104 = sext i32 %t103 to i64
  %t105 = add i64 %t102, %t104
  %t106 = trunc i64 %t105 to i32
  %t107 = sext i32 %t106 to i64
  %t108 = trunc i64 %t107 to i32
  %t109 = sext i32 %t108 to i64
  store i64 %t109, ptr %t78
  br label %while7
whileexit9:
  %t110 = load i64, ptr %t3
  %t111 = trunc i64 %t110 to i32
  %t112 = sext i32 %t111 to i64
  %t113 = trunc i64 1 to i32
  %t114 = sext i32 %t113 to i64
  %t115 = add i64 %t112, %t114
  %t116 = trunc i64 %t115 to i32
  %t117 = sext i32 %t116 to i64
  %t118 = trunc i64 %t117 to i32
  %t119 = sext i32 %t118 to i64
  store i64 %t119, ptr %t3
  br label %while1
whileexit3:
  %t120 = load i64, ptr %t7
  ret i64 %t120
}

define i64 @yet_another_function(i64 %p0, i64 %p1) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 %p1, ptr %t2
  %t31 = alloca i64
  store i64 0, ptr %t31
  %t34 = alloca i64
  store i64 0, ptr %t34
  %t3 = load i64, ptr %t1
  %t4 = load i64, ptr %t2
  %t5 = trunc i64 %t3 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = trunc i64 %t4 to i32
  %t8 = sext i32 %t7 to i64
  %t9 = icmp sgt i64 %t6, %t8
  %t10 = zext i1 %t9 to i64
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %then1, label %else2
then1:
  %t12 = load i64, ptr %t1
  %t13 = load i64, ptr %t2
  %t14 = trunc i64 %t12 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 %t13 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = sub i64 %t15, %t17
  %t19 = trunc i64 %t18 to i32
  %t20 = sext i32 %t19 to i64
  br label %thencont4
thencont4:
  br label %ifend3
else2:
  %t21 = load i64, ptr %t2
  %t22 = load i64, ptr %t1
  %t23 = trunc i64 %t21 to i32
  %t24 = sext i32 %t23 to i64
  %t25 = trunc i64 %t22 to i32
  %t26 = sext i32 %t25 to i64
  %t27 = sub i64 %t24, %t26
  %t28 = trunc i64 %t27 to i32
  %t29 = sext i32 %t28 to i64
  br label %elsecont5
elsecont5:
  br label %ifend3
ifend3:
  %t30 = phi i64 [ %t20, %thencont4 ], [ %t29, %elsecont5 ]
  %t32 = trunc i64 %t30 to i32
  %t33 = sext i32 %t32 to i64
  store i64 %t33, ptr %t31
  %t35 = trunc i64 0 to i32
  %t36 = sext i32 %t35 to i64
  store i64 %t36, ptr %t34
  br label %while6
while6:
  %t37 = load i64, ptr %t34
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = trunc i64 5 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = icmp slt i64 %t39, %t41
  %t43 = zext i1 %t42 to i64
  %t44 = icmp ne i64 %t43, 0
  br i1 %t44, label %whilebody7, label %whileexit8
whilebody7:
  %t45 = load i64, ptr %t31
  %t46 = load i64, ptr %t34
  %t47 = trunc i64 %t46 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = trunc i64 1 to i32
  %t50 = sext i32 %t49 to i64
  %t51 = add i64 %t48, %t50
  %t52 = trunc i64 %t51 to i32
  %t53 = sext i32 %t52 to i64
  %t54 = call i64 @another_level_of_processing(i64 %t45, i64 %t53)
  %t55 = trunc i64 %t54 to i32
  %t56 = sext i32 %t55 to i64
  store i64 %t56, ptr %t31
  %t57 = load i64, ptr %t34
  %t58 = trunc i64 %t57 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = trunc i64 1 to i32
  %t61 = sext i32 %t60 to i64
  %t62 = add i64 %t59, %t61
  %t63 = trunc i64 %t62 to i32
  %t64 = sext i32 %t63 to i64
  %t65 = trunc i64 %t64 to i32
  %t66 = sext i32 %t65 to i64
  store i64 %t66, ptr %t34
  br label %while6
whileexit8:
  %t67 = load i64, ptr %t31
  %t68 = trunc i64 %t67 to i32
  %t69 = sext i32 %t68 to i64
  %t70 = trunc i64 1000 to i32
  %t71 = sext i32 %t70 to i64
  %t72 = icmp sgt i64 %t69, %t71
  %t73 = zext i1 %t72 to i64
  %t74 = icmp ne i64 %t73, 0
  br i1 %t74, label %then9, label %else10
then9:
  ret i64 1000
else10:
  br label %ifend11
ifend11:
  %t75 = load i64, ptr %t31
  ret i64 %t75
}

define i64 @process_complex_data(i64 %p0, i64 %p1, i64 %p2) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 %p1, ptr %t2
  %t3 = alloca i64
  store i64 %p2, ptr %t3
  %t7 = alloca i64
  store i64 0, ptr %t7
  %t13 = alloca i64
  store i64 0, ptr %t13
  %t19 = alloca i64
  store i64 0, ptr %t19
  %t39 = alloca i64
  store i64 0, ptr %t39
  %t42 = alloca i64
  store i64 0, ptr %t42
  %t4 = load i64, ptr %t1
  %t5 = load i64, ptr %t2
  %t6 = call i64 @yet_another_function(i64 %t4, i64 %t5)
  %t8 = trunc i64 %t6 to i32
  %t9 = sext i32 %t8 to i64
  store i64 %t9, ptr %t7
  %t10 = load i64, ptr %t2
  %t11 = load i64, ptr %t3
  %t12 = call i64 @yet_another_function(i64 %t10, i64 %t11)
  %t14 = trunc i64 %t12 to i32
  %t15 = sext i32 %t14 to i64
  store i64 %t15, ptr %t13
  %t16 = load i64, ptr %t1
  %t17 = load i64, ptr %t3
  %t18 = call i64 @yet_another_function(i64 %t16, i64 %t17)
  %t20 = trunc i64 %t18 to i32
  %t21 = sext i32 %t20 to i64
  store i64 %t21, ptr %t19
  %t22 = load i64, ptr %t7
  %t23 = load i64, ptr %t13
  %t24 = trunc i64 %t22 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = trunc i64 %t23 to i32
  %t27 = sext i32 %t26 to i64
  %t28 = add i64 %t25, %t27
  %t29 = trunc i64 %t28 to i32
  %t30 = sext i32 %t29 to i64
  %t31 = load i64, ptr %t19
  %t32 = trunc i64 %t30 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = trunc i64 %t31 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = add i64 %t33, %t35
  %t37 = trunc i64 %t36 to i32
  %t38 = sext i32 %t37 to i64
  %t40 = trunc i64 %t38 to i32
  %t41 = sext i32 %t40 to i64
  store i64 %t41, ptr %t39
  %t43 = trunc i64 0 to i32
  %t44 = sext i32 %t43 to i64
  store i64 %t44, ptr %t42
  br label %while1
while1:
  %t45 = load i64, ptr %t42
  %t46 = trunc i64 %t45 to i32
  %t47 = sext i32 %t46 to i64
  %t48 = trunc i64 10 to i32
  %t49 = sext i32 %t48 to i64
  %t50 = icmp slt i64 %t47, %t49
  %t51 = zext i1 %t50 to i64
  %t52 = icmp ne i64 %t51, 0
  br i1 %t52, label %whilebody2, label %whileexit3
whilebody2:
  %t53 = load i64, ptr %t39
  %t54 = load i64, ptr %t42
  %t55 = load i64, ptr %t42
  %t56 = trunc i64 %t54 to i32
  %t57 = sext i32 %t56 to i64
  %t58 = trunc i64 %t55 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = mul i64 %t57, %t59
  %t61 = trunc i64 %t60 to i32
  %t62 = sext i32 %t61 to i64
  %t63 = trunc i64 %t53 to i32
  %t64 = sext i32 %t63 to i64
  %t65 = trunc i64 %t62 to i32
  %t66 = sext i32 %t65 to i64
  %t67 = sub i64 %t64, %t66
  %t68 = trunc i64 %t67 to i32
  %t69 = sext i32 %t68 to i64
  %t70 = trunc i64 %t69 to i32
  %t71 = sext i32 %t70 to i64
  store i64 %t71, ptr %t39
  %t72 = load i64, ptr %t42
  %t73 = trunc i64 %t72 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = trunc i64 1 to i32
  %t76 = sext i32 %t75 to i64
  %t77 = add i64 %t74, %t76
  %t78 = trunc i64 %t77 to i32
  %t79 = sext i32 %t78 to i64
  %t80 = trunc i64 %t79 to i32
  %t81 = sext i32 %t80 to i64
  store i64 %t81, ptr %t42
  br label %while1
whileexit3:
  %t82 = load i64, ptr %t39
  ret i64 %t82
}

define i64 @simulate_external_factors(i64 %p0) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t10 = alloca i64
  store i64 0, ptr %t10
  %t2 = load i64, ptr %t1
  %t3 = trunc i64 %t2 to i32
  %t4 = sext i32 %t3 to i64
  %t5 = trunc i64 5 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = srem i64 %t4, %t6
  %t8 = trunc i64 %t7 to i32
  %t9 = sext i32 %t8 to i64
  %t11 = trunc i64 %t9 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  %t13 = load i64, ptr %t10
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 0 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = icmp eq i64 %t15, %t17
  %t19 = zext i1 %t18 to i64
  %t20 = icmp ne i64 %t19, 0
  br i1 %t20, label %then1, label %else2
then1:
  ret i64 -500
else2:
  %t21 = load i64, ptr %t10
  %t22 = trunc i64 %t21 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = trunc i64 1 to i32
  %t25 = sext i32 %t24 to i64
  %t26 = icmp eq i64 %t23, %t25
  %t27 = zext i1 %t26 to i64
  %t28 = icmp ne i64 %t27, 0
  br i1 %t28, label %then4, label %else5
then4:
  ret i64 200
else5:
  %t29 = load i64, ptr %t10
  %t30 = trunc i64 %t29 to i32
  %t31 = sext i32 %t30 to i64
  %t32 = trunc i64 2 to i32
  %t33 = sext i32 %t32 to i64
  %t34 = icmp eq i64 %t31, %t33
  %t35 = zext i1 %t34 to i64
  %t36 = icmp ne i64 %t35, 0
  br i1 %t36, label %then7, label %else8
then7:
  ret i64 0
else8:
  %t37 = load i64, ptr %t10
  %t38 = trunc i64 %t37 to i32
  %t39 = sext i32 %t38 to i64
  %t40 = trunc i64 3 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = icmp eq i64 %t39, %t41
  %t43 = zext i1 %t42 to i64
  %t44 = icmp ne i64 %t43, 0
  br i1 %t44, label %then10, label %else11
then10:
  ret i64 1000
else11:
  ret i64 -100
ifend12:
  br label %ifend9
ifend9:
  br label %ifend6
ifend6:
  br label %ifend3
ifend3:
  ret i64 0
}

define i64 @final_check(i64 %p0, i64 %p1, i64 %p2, i64 %p3) {
entry:
  %t1 = alloca i64
  store i64 %p0, ptr %t1
  %t2 = alloca i64
  store i64 %p1, ptr %t2
  %t3 = alloca i64
  store i64 %p2, ptr %t3
  %t4 = alloca i64
  store i64 %p3, ptr %t4
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t6 = trunc i64 0 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t8 = load i64, ptr %t1
  %t9 = trunc i64 %t8 to i32
  %t10 = sext i32 %t9 to i64
  %t11 = trunc i64 500 to i32
  %t12 = sext i32 %t11 to i64
  %t13 = icmp sgt i64 %t10, %t12
  %t14 = zext i1 %t13 to i64
  %t15 = icmp ne i64 %t14, 0
  br i1 %t15, label %then1, label %else2
then1:
  %t16 = load i64, ptr %t5
  %t17 = trunc i64 %t16 to i32
  %t18 = sext i32 %t17 to i64
  %t19 = trunc i64 1 to i32
  %t20 = sext i32 %t19 to i64
  %t21 = add i64 %t18, %t20
  %t22 = trunc i64 %t21 to i32
  %t23 = sext i32 %t22 to i64
  %t24 = trunc i64 %t23 to i32
  %t25 = sext i32 %t24 to i64
  store i64 %t25, ptr %t5
  br label %ifend3
else2:
  br label %ifend3
ifend3:
  %t26 = load i64, ptr %t2
  %t27 = trunc i64 %t26 to i32
  %t28 = sext i32 %t27 to i64
  %t29 = trunc i64 800 to i32
  %t30 = sext i32 %t29 to i64
  %t31 = icmp sgt i64 %t28, %t30
  %t32 = zext i1 %t31 to i64
  %t33 = icmp ne i64 %t32, 0
  br i1 %t33, label %then4, label %else5
then4:
  %t34 = load i64, ptr %t5
  %t35 = trunc i64 %t34 to i32
  %t36 = sext i32 %t35 to i64
  %t37 = trunc i64 1 to i32
  %t38 = sext i32 %t37 to i64
  %t39 = add i64 %t36, %t38
  %t40 = trunc i64 %t39 to i32
  %t41 = sext i32 %t40 to i64
  %t42 = trunc i64 %t41 to i32
  %t43 = sext i32 %t42 to i64
  store i64 %t43, ptr %t5
  br label %ifend6
else5:
  br label %ifend6
ifend6:
  %t44 = load i64, ptr %t3
  %t45 = trunc i64 %t44 to i32
  %t46 = sext i32 %t45 to i64
  %t47 = trunc i64 400 to i32
  %t48 = sext i32 %t47 to i64
  %t49 = icmp sgt i64 %t46, %t48
  %t50 = zext i1 %t49 to i64
  %t51 = icmp ne i64 %t50, 0
  br i1 %t51, label %then7, label %else8
then7:
  %t52 = load i64, ptr %t5
  %t53 = trunc i64 %t52 to i32
  %t54 = sext i32 %t53 to i64
  %t55 = trunc i64 1 to i32
  %t56 = sext i32 %t55 to i64
  %t57 = add i64 %t54, %t56
  %t58 = trunc i64 %t57 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = trunc i64 %t59 to i32
  %t61 = sext i32 %t60 to i64
  store i64 %t61, ptr %t5
  br label %ifend9
else8:
  br label %ifend9
ifend9:
  %t62 = load i64, ptr %t4
  %t63 = trunc i64 %t62 to i32
  %t64 = sext i32 %t63 to i64
  %t65 = trunc i64 100000 to i32
  %t66 = sext i32 %t65 to i64
  %t67 = icmp sgt i64 %t64, %t66
  %t68 = zext i1 %t67 to i64
  %t69 = icmp ne i64 %t68, 0
  br i1 %t69, label %then10, label %else11
then10:
  %t70 = load i64, ptr %t5
  %t71 = trunc i64 %t70 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = trunc i64 2 to i32
  %t74 = sext i32 %t73 to i64
  %t75 = add i64 %t72, %t74
  %t76 = trunc i64 %t75 to i32
  %t77 = sext i32 %t76 to i64
  %t78 = trunc i64 %t77 to i32
  %t79 = sext i32 %t78 to i64
  store i64 %t79, ptr %t5
  br label %ifend12
else11:
  br label %ifend12
ifend12:
  %t80 = load i64, ptr %t5
  ret i64 %t80
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

