; Autogenerated textual LLVM IR
source_filename = "RCompiler"

define i64 @main() {
entry:
  %t2 = alloca [256 x i64]
  %t4 = alloca [256 x i64]
  %t5 = alloca i64
  store i64 0, ptr %t5
  %t8 = alloca i64
  store i64 0, ptr %t8
  %t11 = alloca i64
  store i64 0, ptr %t11
  %t25 = alloca i64
  store i64 0, ptr %t25
  %t52 = alloca i64
  store i64 0, ptr %t52
  %t111 = alloca i64
  store i64 0, ptr %t111
  %t128 = alloca i64
  store i64 0, ptr %t128
  %t157 = alloca i64
  store i64 0, ptr %t157
  %t174 = alloca i64
  store i64 0, ptr %t174
  %t203 = alloca i64
  store i64 0, ptr %t203
  %t220 = alloca i64
  store i64 0, ptr %t220
  %t249 = alloca i64
  store i64 0, ptr %t249
  %t266 = alloca i64
  store i64 0, ptr %t266
  %t309 = alloca i64
  store i64 0, ptr %t309
  %t358 = alloca i64
  store i64 0, ptr %t358
  %t407 = alloca i64
  store i64 0, ptr %t407
  %t424 = alloca i64
  store i64 0, ptr %t424
  %t458 = alloca i64
  store i64 0, ptr %t458
  %t475 = alloca i64
  store i64 0, ptr %t475
  %t509 = alloca i64
  store i64 0, ptr %t509
  %t526 = alloca i64
  store i64 0, ptr %t526
  %t584 = alloca i64
  store i64 0, ptr %t584
  %t1 = alloca [256 x i64]
  call void @llvm.memset.p0.i64(ptr %t1, i8 0, i64 2048, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t2, ptr %t1, i64 2048, i1 false)
  %t3 = alloca [256 x i64]
  call void @llvm.memset.p0.i64(ptr %t3, i8 0, i64 2048, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %t4, ptr %t3, i64 2048, i1 false)
  %t6 = trunc i64 -1 to i32
  %t7 = sext i32 %t6 to i64
  store i64 %t7, ptr %t5
  %t9 = trunc i64 0 to i32
  %t10 = sext i32 %t9 to i64
  store i64 %t10, ptr %t8
  %t12 = zext i1 0 to i64
  %t13 = trunc i64 %t12 to i32
  %t14 = sext i32 %t13 to i64
  store i64 %t14, ptr %t11
  %t15 = call i64 @load_program(ptr %t2)
  br label %while1
while1:
  %t16 = load i64, ptr %t11
  %t17 = icmp ne i64 %t16, 0
  %t18 = xor i1 %t17, 1
  %t19 = zext i1 %t18 to i64
  %t20 = icmp ne i64 %t19, 0
  br i1 %t20, label %whilebody2, label %whileexit3
whilebody2:
  %t21 = load i64, ptr %t8
  %t22 = mul i64 %t21, 1
  %t23 = getelementptr [256 x i64], ptr %t2, i64 0, i64 %t22
  %t24 = load i64, ptr %t23
  %t26 = trunc i64 %t24 to i32
  %t27 = sext i32 %t26 to i64
  store i64 %t27, ptr %t25
  %t28 = load i64, ptr %t8
  %t29 = trunc i64 %t28 to i32
  %t30 = sext i32 %t29 to i64
  %t31 = trunc i64 1 to i32
  %t32 = sext i32 %t31 to i64
  %t33 = add i64 %t30, %t32
  %t34 = trunc i64 %t33 to i32
  %t35 = sext i32 %t34 to i64
  %t36 = trunc i64 %t35 to i32
  %t37 = sext i32 %t36 to i64
  store i64 %t37, ptr %t8
  %t38 = load i64, ptr %t8
  %t39 = call i64 @self_modify_code(ptr %t2, i64 %t38)
  %t40 = load i64, ptr %t25
  %t41 = trunc i64 %t40 to i32
  %t42 = sext i32 %t41 to i64
  %t43 = trunc i64 1 to i32
  %t44 = sext i32 %t43 to i64
  %t45 = icmp eq i64 %t42, %t44
  %t46 = zext i1 %t45 to i64
  %t47 = icmp ne i64 %t46, 0
  br i1 %t47, label %then4, label %else5
then4:
  %t48 = load i64, ptr %t8
  %t49 = mul i64 %t48, 1
  %t50 = getelementptr [256 x i64], ptr %t2, i64 0, i64 %t49
  %t51 = load i64, ptr %t50
  %t53 = trunc i64 %t51 to i32
  %t54 = sext i32 %t53 to i64
  store i64 %t54, ptr %t52
  %t55 = load i64, ptr %t8
  %t56 = trunc i64 %t55 to i32
  %t57 = sext i32 %t56 to i64
  %t58 = trunc i64 1 to i32
  %t59 = sext i32 %t58 to i64
  %t60 = add i64 %t57, %t59
  %t61 = trunc i64 %t60 to i32
  %t62 = sext i32 %t61 to i64
  %t63 = trunc i64 %t62 to i32
  %t64 = sext i32 %t63 to i64
  store i64 %t64, ptr %t8
  %t65 = load i64, ptr %t5
  %t66 = trunc i64 %t65 to i32
  %t67 = sext i32 %t66 to i64
  %t68 = trunc i64 1 to i32
  %t69 = sext i32 %t68 to i64
  %t70 = add i64 %t67, %t69
  %t71 = trunc i64 %t70 to i32
  %t72 = sext i32 %t71 to i64
  %t73 = trunc i64 %t72 to i32
  %t74 = sext i32 %t73 to i64
  store i64 %t74, ptr %t5
  %t75 = load i64, ptr %t52
  %t76 = load i64, ptr %t5
  %t77 = mul i64 %t76, 1
  %t78 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t77
  %t79 = trunc i64 %t75 to i32
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  br label %ifend6
else5:
  %t81 = load i64, ptr %t25
  %t82 = trunc i64 %t81 to i32
  %t83 = sext i32 %t82 to i64
  %t84 = trunc i64 2 to i32
  %t85 = sext i32 %t84 to i64
  %t86 = icmp eq i64 %t83, %t85
  %t87 = zext i1 %t86 to i64
  %t88 = icmp ne i64 %t87, 0
  br i1 %t88, label %then7, label %else8
then7:
  %t89 = load i64, ptr %t5
  %t90 = trunc i64 %t89 to i32
  %t91 = sext i32 %t90 to i64
  %t92 = trunc i64 1 to i32
  %t93 = sext i32 %t92 to i64
  %t94 = sub i64 %t91, %t93
  %t95 = trunc i64 %t94 to i32
  %t96 = sext i32 %t95 to i64
  %t97 = trunc i64 %t96 to i32
  %t98 = sext i32 %t97 to i64
  store i64 %t98, ptr %t5
  br label %ifend9
else8:
  %t99 = load i64, ptr %t25
  %t100 = trunc i64 %t99 to i32
  %t101 = sext i32 %t100 to i64
  %t102 = trunc i64 3 to i32
  %t103 = sext i32 %t102 to i64
  %t104 = icmp eq i64 %t101, %t103
  %t105 = zext i1 %t104 to i64
  %t106 = icmp ne i64 %t105, 0
  br i1 %t106, label %then10, label %else11
then10:
  %t107 = load i64, ptr %t5
  %t108 = mul i64 %t107, 1
  %t109 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t108
  %t110 = load i64, ptr %t109
  %t112 = trunc i64 %t110 to i32
  %t113 = sext i32 %t112 to i64
  store i64 %t113, ptr %t111
  %t114 = load i64, ptr %t5
  %t115 = trunc i64 %t114 to i32
  %t116 = sext i32 %t115 to i64
  %t117 = trunc i64 1 to i32
  %t118 = sext i32 %t117 to i64
  %t119 = sub i64 %t116, %t118
  %t120 = trunc i64 %t119 to i32
  %t121 = sext i32 %t120 to i64
  %t122 = trunc i64 %t121 to i32
  %t123 = sext i32 %t122 to i64
  store i64 %t123, ptr %t5
  %t124 = load i64, ptr %t5
  %t125 = mul i64 %t124, 1
  %t126 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t125
  %t127 = load i64, ptr %t126
  %t129 = trunc i64 %t127 to i32
  %t130 = sext i32 %t129 to i64
  store i64 %t130, ptr %t128
  %t131 = load i64, ptr %t128
  %t132 = load i64, ptr %t111
  %t133 = trunc i64 %t131 to i32
  %t134 = sext i32 %t133 to i64
  %t135 = trunc i64 %t132 to i32
  %t136 = sext i32 %t135 to i64
  %t137 = add i64 %t134, %t136
  %t138 = trunc i64 %t137 to i32
  %t139 = sext i32 %t138 to i64
  %t140 = load i64, ptr %t5
  %t141 = mul i64 %t140, 1
  %t142 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t141
  %t143 = trunc i64 %t139 to i32
  %t144 = sext i32 %t143 to i64
  store i64 %t144, ptr %t142
  br label %ifend12
else11:
  %t145 = load i64, ptr %t25
  %t146 = trunc i64 %t145 to i32
  %t147 = sext i32 %t146 to i64
  %t148 = trunc i64 4 to i32
  %t149 = sext i32 %t148 to i64
  %t150 = icmp eq i64 %t147, %t149
  %t151 = zext i1 %t150 to i64
  %t152 = icmp ne i64 %t151, 0
  br i1 %t152, label %then13, label %else14
then13:
  %t153 = load i64, ptr %t5
  %t154 = mul i64 %t153, 1
  %t155 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t154
  %t156 = load i64, ptr %t155
  %t158 = trunc i64 %t156 to i32
  %t159 = sext i32 %t158 to i64
  store i64 %t159, ptr %t157
  %t160 = load i64, ptr %t5
  %t161 = trunc i64 %t160 to i32
  %t162 = sext i32 %t161 to i64
  %t163 = trunc i64 1 to i32
  %t164 = sext i32 %t163 to i64
  %t165 = sub i64 %t162, %t164
  %t166 = trunc i64 %t165 to i32
  %t167 = sext i32 %t166 to i64
  %t168 = trunc i64 %t167 to i32
  %t169 = sext i32 %t168 to i64
  store i64 %t169, ptr %t5
  %t170 = load i64, ptr %t5
  %t171 = mul i64 %t170, 1
  %t172 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t171
  %t173 = load i64, ptr %t172
  %t175 = trunc i64 %t173 to i32
  %t176 = sext i32 %t175 to i64
  store i64 %t176, ptr %t174
  %t177 = load i64, ptr %t174
  %t178 = load i64, ptr %t157
  %t179 = trunc i64 %t177 to i32
  %t180 = sext i32 %t179 to i64
  %t181 = trunc i64 %t178 to i32
  %t182 = sext i32 %t181 to i64
  %t183 = sub i64 %t180, %t182
  %t184 = trunc i64 %t183 to i32
  %t185 = sext i32 %t184 to i64
  %t186 = load i64, ptr %t5
  %t187 = mul i64 %t186, 1
  %t188 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t187
  %t189 = trunc i64 %t185 to i32
  %t190 = sext i32 %t189 to i64
  store i64 %t190, ptr %t188
  br label %ifend15
else14:
  %t191 = load i64, ptr %t25
  %t192 = trunc i64 %t191 to i32
  %t193 = sext i32 %t192 to i64
  %t194 = trunc i64 5 to i32
  %t195 = sext i32 %t194 to i64
  %t196 = icmp eq i64 %t193, %t195
  %t197 = zext i1 %t196 to i64
  %t198 = icmp ne i64 %t197, 0
  br i1 %t198, label %then16, label %else17
then16:
  %t199 = load i64, ptr %t5
  %t200 = mul i64 %t199, 1
  %t201 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t200
  %t202 = load i64, ptr %t201
  %t204 = trunc i64 %t202 to i32
  %t205 = sext i32 %t204 to i64
  store i64 %t205, ptr %t203
  %t206 = load i64, ptr %t5
  %t207 = trunc i64 %t206 to i32
  %t208 = sext i32 %t207 to i64
  %t209 = trunc i64 1 to i32
  %t210 = sext i32 %t209 to i64
  %t211 = sub i64 %t208, %t210
  %t212 = trunc i64 %t211 to i32
  %t213 = sext i32 %t212 to i64
  %t214 = trunc i64 %t213 to i32
  %t215 = sext i32 %t214 to i64
  store i64 %t215, ptr %t5
  %t216 = load i64, ptr %t5
  %t217 = mul i64 %t216, 1
  %t218 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t217
  %t219 = load i64, ptr %t218
  %t221 = trunc i64 %t219 to i32
  %t222 = sext i32 %t221 to i64
  store i64 %t222, ptr %t220
  %t223 = load i64, ptr %t220
  %t224 = load i64, ptr %t203
  %t225 = trunc i64 %t223 to i32
  %t226 = sext i32 %t225 to i64
  %t227 = trunc i64 %t224 to i32
  %t228 = sext i32 %t227 to i64
  %t229 = mul i64 %t226, %t228
  %t230 = trunc i64 %t229 to i32
  %t231 = sext i32 %t230 to i64
  %t232 = load i64, ptr %t5
  %t233 = mul i64 %t232, 1
  %t234 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t233
  %t235 = trunc i64 %t231 to i32
  %t236 = sext i32 %t235 to i64
  store i64 %t236, ptr %t234
  br label %ifend18
else17:
  %t237 = load i64, ptr %t25
  %t238 = trunc i64 %t237 to i32
  %t239 = sext i32 %t238 to i64
  %t240 = trunc i64 6 to i32
  %t241 = sext i32 %t240 to i64
  %t242 = icmp eq i64 %t239, %t241
  %t243 = zext i1 %t242 to i64
  %t244 = icmp ne i64 %t243, 0
  br i1 %t244, label %then19, label %else20
then19:
  %t245 = load i64, ptr %t5
  %t246 = mul i64 %t245, 1
  %t247 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t246
  %t248 = load i64, ptr %t247
  %t250 = trunc i64 %t248 to i32
  %t251 = sext i32 %t250 to i64
  store i64 %t251, ptr %t249
  %t252 = load i64, ptr %t5
  %t253 = trunc i64 %t252 to i32
  %t254 = sext i32 %t253 to i64
  %t255 = trunc i64 1 to i32
  %t256 = sext i32 %t255 to i64
  %t257 = sub i64 %t254, %t256
  %t258 = trunc i64 %t257 to i32
  %t259 = sext i32 %t258 to i64
  %t260 = trunc i64 %t259 to i32
  %t261 = sext i32 %t260 to i64
  store i64 %t261, ptr %t5
  %t262 = load i64, ptr %t5
  %t263 = mul i64 %t262, 1
  %t264 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t263
  %t265 = load i64, ptr %t264
  %t267 = trunc i64 %t265 to i32
  %t268 = sext i32 %t267 to i64
  store i64 %t268, ptr %t266
  %t269 = load i64, ptr %t266
  %t270 = load i64, ptr %t249
  %t271 = trunc i64 %t269 to i32
  %t272 = sext i32 %t271 to i64
  %t273 = trunc i64 %t270 to i32
  %t274 = sext i32 %t273 to i64
  %t275 = sdiv i64 %t272, %t274
  %t276 = trunc i64 %t275 to i32
  %t277 = sext i32 %t276 to i64
  %t278 = load i64, ptr %t5
  %t279 = mul i64 %t278, 1
  %t280 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t279
  %t281 = trunc i64 %t277 to i32
  %t282 = sext i32 %t281 to i64
  store i64 %t282, ptr %t280
  br label %ifend21
else20:
  %t283 = load i64, ptr %t25
  %t284 = trunc i64 %t283 to i32
  %t285 = sext i32 %t284 to i64
  %t286 = trunc i64 7 to i32
  %t287 = sext i32 %t286 to i64
  %t288 = icmp eq i64 %t285, %t287
  %t289 = zext i1 %t288 to i64
  %t290 = icmp ne i64 %t289, 0
  br i1 %t290, label %then22, label %else23
then22:
  %t291 = load i64, ptr %t8
  %t292 = mul i64 %t291, 1
  %t293 = getelementptr [256 x i64], ptr %t2, i64 0, i64 %t292
  %t294 = load i64, ptr %t293
  %t295 = trunc i64 %t294 to i32
  %t296 = sext i32 %t295 to i64
  store i64 %t296, ptr %t8
  br label %ifend24
else23:
  %t297 = load i64, ptr %t25
  %t298 = trunc i64 %t297 to i32
  %t299 = sext i32 %t298 to i64
  %t300 = trunc i64 8 to i32
  %t301 = sext i32 %t300 to i64
  %t302 = icmp eq i64 %t299, %t301
  %t303 = zext i1 %t302 to i64
  %t304 = icmp ne i64 %t303, 0
  br i1 %t304, label %then25, label %else26
then25:
  %t305 = load i64, ptr %t5
  %t306 = mul i64 %t305, 1
  %t307 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t306
  %t308 = load i64, ptr %t307
  %t310 = trunc i64 %t308 to i32
  %t311 = sext i32 %t310 to i64
  store i64 %t311, ptr %t309
  %t312 = load i64, ptr %t5
  %t313 = trunc i64 %t312 to i32
  %t314 = sext i32 %t313 to i64
  %t315 = trunc i64 1 to i32
  %t316 = sext i32 %t315 to i64
  %t317 = sub i64 %t314, %t316
  %t318 = trunc i64 %t317 to i32
  %t319 = sext i32 %t318 to i64
  %t320 = trunc i64 %t319 to i32
  %t321 = sext i32 %t320 to i64
  store i64 %t321, ptr %t5
  %t322 = load i64, ptr %t309
  %t323 = trunc i64 %t322 to i32
  %t324 = sext i32 %t323 to i64
  %t325 = trunc i64 0 to i32
  %t326 = sext i32 %t325 to i64
  %t327 = icmp eq i64 %t324, %t326
  %t328 = zext i1 %t327 to i64
  %t329 = icmp ne i64 %t328, 0
  br i1 %t329, label %then28, label %else29
then28:
  %t330 = load i64, ptr %t8
  %t331 = mul i64 %t330, 1
  %t332 = getelementptr [256 x i64], ptr %t2, i64 0, i64 %t331
  %t333 = load i64, ptr %t332
  %t334 = trunc i64 %t333 to i32
  %t335 = sext i32 %t334 to i64
  store i64 %t335, ptr %t8
  br label %ifend30
else29:
  %t336 = load i64, ptr %t8
  %t337 = trunc i64 %t336 to i32
  %t338 = sext i32 %t337 to i64
  %t339 = trunc i64 1 to i32
  %t340 = sext i32 %t339 to i64
  %t341 = add i64 %t338, %t340
  %t342 = trunc i64 %t341 to i32
  %t343 = sext i32 %t342 to i64
  %t344 = trunc i64 %t343 to i32
  %t345 = sext i32 %t344 to i64
  store i64 %t345, ptr %t8
  br label %ifend30
ifend30:
  br label %ifend27
else26:
  %t346 = load i64, ptr %t25
  %t347 = trunc i64 %t346 to i32
  %t348 = sext i32 %t347 to i64
  %t349 = trunc i64 9 to i32
  %t350 = sext i32 %t349 to i64
  %t351 = icmp eq i64 %t348, %t350
  %t352 = zext i1 %t351 to i64
  %t353 = icmp ne i64 %t352, 0
  br i1 %t353, label %then31, label %else32
then31:
  %t354 = load i64, ptr %t5
  %t355 = mul i64 %t354, 1
  %t356 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t355
  %t357 = load i64, ptr %t356
  %t359 = trunc i64 %t357 to i32
  %t360 = sext i32 %t359 to i64
  store i64 %t360, ptr %t358
  %t361 = load i64, ptr %t5
  %t362 = trunc i64 %t361 to i32
  %t363 = sext i32 %t362 to i64
  %t364 = trunc i64 1 to i32
  %t365 = sext i32 %t364 to i64
  %t366 = sub i64 %t363, %t365
  %t367 = trunc i64 %t366 to i32
  %t368 = sext i32 %t367 to i64
  %t369 = trunc i64 %t368 to i32
  %t370 = sext i32 %t369 to i64
  store i64 %t370, ptr %t5
  %t371 = load i64, ptr %t358
  %t372 = trunc i64 %t371 to i32
  %t373 = sext i32 %t372 to i64
  %t374 = trunc i64 0 to i32
  %t375 = sext i32 %t374 to i64
  %t376 = icmp ne i64 %t373, %t375
  %t377 = zext i1 %t376 to i64
  %t378 = icmp ne i64 %t377, 0
  br i1 %t378, label %then34, label %else35
then34:
  %t379 = load i64, ptr %t8
  %t380 = mul i64 %t379, 1
  %t381 = getelementptr [256 x i64], ptr %t2, i64 0, i64 %t380
  %t382 = load i64, ptr %t381
  %t383 = trunc i64 %t382 to i32
  %t384 = sext i32 %t383 to i64
  store i64 %t384, ptr %t8
  br label %ifend36
else35:
  %t385 = load i64, ptr %t8
  %t386 = trunc i64 %t385 to i32
  %t387 = sext i32 %t386 to i64
  %t388 = trunc i64 1 to i32
  %t389 = sext i32 %t388 to i64
  %t390 = add i64 %t387, %t389
  %t391 = trunc i64 %t390 to i32
  %t392 = sext i32 %t391 to i64
  %t393 = trunc i64 %t392 to i32
  %t394 = sext i32 %t393 to i64
  store i64 %t394, ptr %t8
  br label %ifend36
ifend36:
  br label %ifend33
else32:
  %t395 = load i64, ptr %t25
  %t396 = trunc i64 %t395 to i32
  %t397 = sext i32 %t396 to i64
  %t398 = trunc i64 10 to i32
  %t399 = sext i32 %t398 to i64
  %t400 = icmp eq i64 %t397, %t399
  %t401 = zext i1 %t400 to i64
  %t402 = icmp ne i64 %t401, 0
  br i1 %t402, label %then37, label %else38
then37:
  %t403 = load i64, ptr %t5
  %t404 = mul i64 %t403, 1
  %t405 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t404
  %t406 = load i64, ptr %t405
  %t408 = trunc i64 %t406 to i32
  %t409 = sext i32 %t408 to i64
  store i64 %t409, ptr %t407
  %t410 = load i64, ptr %t5
  %t411 = trunc i64 %t410 to i32
  %t412 = sext i32 %t411 to i64
  %t413 = trunc i64 1 to i32
  %t414 = sext i32 %t413 to i64
  %t415 = sub i64 %t412, %t414
  %t416 = trunc i64 %t415 to i32
  %t417 = sext i32 %t416 to i64
  %t418 = trunc i64 %t417 to i32
  %t419 = sext i32 %t418 to i64
  store i64 %t419, ptr %t5
  %t420 = load i64, ptr %t5
  %t421 = mul i64 %t420, 1
  %t422 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t421
  %t423 = load i64, ptr %t422
  %t425 = trunc i64 %t423 to i32
  %t426 = sext i32 %t425 to i64
  store i64 %t426, ptr %t424
  %t427 = load i64, ptr %t424
  %t428 = load i64, ptr %t407
  %t429 = trunc i64 %t427 to i32
  %t430 = sext i32 %t429 to i64
  %t431 = trunc i64 %t428 to i32
  %t432 = sext i32 %t431 to i64
  %t433 = icmp eq i64 %t430, %t432
  %t434 = zext i1 %t433 to i64
  %t435 = icmp ne i64 %t434, 0
  br i1 %t435, label %then40, label %else41
then40:
  %t436 = load i64, ptr %t5
  %t437 = mul i64 %t436, 1
  %t438 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t437
  %t439 = trunc i64 1 to i32
  %t440 = sext i32 %t439 to i64
  store i64 %t440, ptr %t438
  br label %ifend42
else41:
  %t441 = load i64, ptr %t5
  %t442 = mul i64 %t441, 1
  %t443 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t442
  %t444 = trunc i64 0 to i32
  %t445 = sext i32 %t444 to i64
  store i64 %t445, ptr %t443
  br label %ifend42
ifend42:
  br label %ifend39
else38:
  %t446 = load i64, ptr %t25
  %t447 = trunc i64 %t446 to i32
  %t448 = sext i32 %t447 to i64
  %t449 = trunc i64 11 to i32
  %t450 = sext i32 %t449 to i64
  %t451 = icmp eq i64 %t448, %t450
  %t452 = zext i1 %t451 to i64
  %t453 = icmp ne i64 %t452, 0
  br i1 %t453, label %then43, label %else44
then43:
  %t454 = load i64, ptr %t5
  %t455 = mul i64 %t454, 1
  %t456 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t455
  %t457 = load i64, ptr %t456
  %t459 = trunc i64 %t457 to i32
  %t460 = sext i32 %t459 to i64
  store i64 %t460, ptr %t458
  %t461 = load i64, ptr %t5
  %t462 = trunc i64 %t461 to i32
  %t463 = sext i32 %t462 to i64
  %t464 = trunc i64 1 to i32
  %t465 = sext i32 %t464 to i64
  %t466 = sub i64 %t463, %t465
  %t467 = trunc i64 %t466 to i32
  %t468 = sext i32 %t467 to i64
  %t469 = trunc i64 %t468 to i32
  %t470 = sext i32 %t469 to i64
  store i64 %t470, ptr %t5
  %t471 = load i64, ptr %t5
  %t472 = mul i64 %t471, 1
  %t473 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t472
  %t474 = load i64, ptr %t473
  %t476 = trunc i64 %t474 to i32
  %t477 = sext i32 %t476 to i64
  store i64 %t477, ptr %t475
  %t478 = load i64, ptr %t475
  %t479 = load i64, ptr %t458
  %t480 = trunc i64 %t478 to i32
  %t481 = sext i32 %t480 to i64
  %t482 = trunc i64 %t479 to i32
  %t483 = sext i32 %t482 to i64
  %t484 = icmp slt i64 %t481, %t483
  %t485 = zext i1 %t484 to i64
  %t486 = icmp ne i64 %t485, 0
  br i1 %t486, label %then46, label %else47
then46:
  %t487 = load i64, ptr %t5
  %t488 = mul i64 %t487, 1
  %t489 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t488
  %t490 = trunc i64 1 to i32
  %t491 = sext i32 %t490 to i64
  store i64 %t491, ptr %t489
  br label %ifend48
else47:
  %t492 = load i64, ptr %t5
  %t493 = mul i64 %t492, 1
  %t494 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t493
  %t495 = trunc i64 0 to i32
  %t496 = sext i32 %t495 to i64
  store i64 %t496, ptr %t494
  br label %ifend48
ifend48:
  br label %ifend45
else44:
  %t497 = load i64, ptr %t25
  %t498 = trunc i64 %t497 to i32
  %t499 = sext i32 %t498 to i64
  %t500 = trunc i64 12 to i32
  %t501 = sext i32 %t500 to i64
  %t502 = icmp eq i64 %t499, %t501
  %t503 = zext i1 %t502 to i64
  %t504 = icmp ne i64 %t503, 0
  br i1 %t504, label %then49, label %else50
then49:
  %t505 = load i64, ptr %t5
  %t506 = mul i64 %t505, 1
  %t507 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t506
  %t508 = load i64, ptr %t507
  %t510 = trunc i64 %t508 to i32
  %t511 = sext i32 %t510 to i64
  store i64 %t511, ptr %t509
  %t512 = load i64, ptr %t5
  %t513 = trunc i64 %t512 to i32
  %t514 = sext i32 %t513 to i64
  %t515 = trunc i64 1 to i32
  %t516 = sext i32 %t515 to i64
  %t517 = sub i64 %t514, %t516
  %t518 = trunc i64 %t517 to i32
  %t519 = sext i32 %t518 to i64
  %t520 = trunc i64 %t519 to i32
  %t521 = sext i32 %t520 to i64
  store i64 %t521, ptr %t5
  %t522 = load i64, ptr %t5
  %t523 = mul i64 %t522, 1
  %t524 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t523
  %t525 = load i64, ptr %t524
  %t527 = trunc i64 %t525 to i32
  %t528 = sext i32 %t527 to i64
  store i64 %t528, ptr %t526
  %t529 = load i64, ptr %t526
  %t530 = load i64, ptr %t509
  %t531 = trunc i64 %t529 to i32
  %t532 = sext i32 %t531 to i64
  %t533 = trunc i64 %t530 to i32
  %t534 = sext i32 %t533 to i64
  %t535 = icmp sgt i64 %t532, %t534
  %t536 = zext i1 %t535 to i64
  %t537 = icmp ne i64 %t536, 0
  br i1 %t537, label %then52, label %else53
then52:
  %t538 = load i64, ptr %t5
  %t539 = mul i64 %t538, 1
  %t540 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t539
  %t541 = trunc i64 1 to i32
  %t542 = sext i32 %t541 to i64
  store i64 %t542, ptr %t540
  br label %ifend54
else53:
  %t543 = load i64, ptr %t5
  %t544 = mul i64 %t543, 1
  %t545 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t544
  %t546 = trunc i64 0 to i32
  %t547 = sext i32 %t546 to i64
  store i64 %t547, ptr %t545
  br label %ifend54
ifend54:
  br label %ifend51
else50:
  %t548 = load i64, ptr %t25
  %t549 = trunc i64 %t548 to i32
  %t550 = sext i32 %t549 to i64
  %t551 = trunc i64 13 to i32
  %t552 = sext i32 %t551 to i64
  %t553 = icmp eq i64 %t550, %t552
  %t554 = zext i1 %t553 to i64
  %t555 = icmp ne i64 %t554, 0
  br i1 %t555, label %then55, label %else56
then55:
  %t556 = load i64, ptr %t5
  %t557 = mul i64 %t556, 1
  %t558 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t557
  %t559 = load i64, ptr %t558
  %t560 = call i64 @printlnInt(i64 %t559)
  br label %ifend57
else56:
  %t561 = load i64, ptr %t25
  %t562 = trunc i64 %t561 to i32
  %t563 = sext i32 %t562 to i64
  %t564 = trunc i64 14 to i32
  %t565 = sext i32 %t564 to i64
  %t566 = icmp eq i64 %t563, %t565
  %t567 = zext i1 %t566 to i64
  %t568 = icmp ne i64 %t567, 0
  br i1 %t568, label %then58, label %else59
then58:
  %t569 = zext i1 1 to i64
  %t570 = trunc i64 %t569 to i32
  %t571 = sext i32 %t570 to i64
  store i64 %t571, ptr %t11
  br label %ifend60
else59:
  %t572 = load i64, ptr %t25
  %t573 = trunc i64 %t572 to i32
  %t574 = sext i32 %t573 to i64
  %t575 = trunc i64 15 to i32
  %t576 = sext i32 %t575 to i64
  %t577 = icmp eq i64 %t574, %t576
  %t578 = zext i1 %t577 to i64
  %t579 = icmp ne i64 %t578, 0
  br i1 %t579, label %then61, label %else62
then61:
  %t580 = load i64, ptr %t5
  %t581 = mul i64 %t580, 1
  %t582 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t581
  %t583 = load i64, ptr %t582
  %t585 = trunc i64 %t583 to i32
  %t586 = sext i32 %t585 to i64
  store i64 %t586, ptr %t584
  %t587 = load i64, ptr %t5
  %t588 = trunc i64 %t587 to i32
  %t589 = sext i32 %t588 to i64
  %t590 = trunc i64 1 to i32
  %t591 = sext i32 %t590 to i64
  %t592 = add i64 %t589, %t591
  %t593 = trunc i64 %t592 to i32
  %t594 = sext i32 %t593 to i64
  %t595 = trunc i64 %t594 to i32
  %t596 = sext i32 %t595 to i64
  store i64 %t596, ptr %t5
  %t597 = load i64, ptr %t584
  %t598 = load i64, ptr %t5
  %t599 = mul i64 %t598, 1
  %t600 = getelementptr [256 x i64], ptr %t4, i64 0, i64 %t599
  %t601 = trunc i64 %t597 to i32
  %t602 = sext i32 %t601 to i64
  store i64 %t602, ptr %t600
  br label %ifend63
else62:
  br label %ifend63
ifend63:
  br label %ifend60
ifend60:
  br label %ifend57
ifend57:
  br label %ifend51
ifend51:
  br label %ifend45
ifend45:
  br label %ifend39
ifend39:
  br label %ifend33
ifend33:
  br label %ifend27
ifend27:
  br label %ifend24
ifend24:
  br label %ifend21
ifend21:
  br label %ifend18
ifend18:
  br label %ifend15
ifend15:
  br label %ifend12
ifend12:
  br label %ifend9
ifend9:
  br label %ifend6
ifend6:
  %t603 = load i64, ptr %t8
  %t604 = trunc i64 %t603 to i32
  %t605 = sext i32 %t604 to i64
  %t606 = trunc i64 0 to i32
  %t607 = sext i32 %t606 to i64
  %t608 = icmp slt i64 %t605, %t607
  %t609 = zext i1 %t608 to i64
  %t610 = load i64, ptr %t8
  %t611 = trunc i64 %t610 to i32
  %t612 = sext i32 %t611 to i64
  %t613 = trunc i64 256 to i32
  %t614 = sext i32 %t613 to i64
  %t615 = icmp sge i64 %t612, %t614
  %t616 = zext i1 %t615 to i64
  %t617 = icmp ne i64 %t609, 0
  %t618 = icmp ne i64 %t616, 0
  %t619 = or i1 %t617, %t618
  %t620 = zext i1 %t619 to i64
  %t621 = icmp ne i64 %t620, 0
  br i1 %t621, label %then64, label %else65
then64:
  %t622 = zext i1 1 to i64
  %t623 = trunc i64 %t622 to i32
  %t624 = sext i32 %t623 to i64
  store i64 %t624, ptr %t11
  br label %ifend66
else65:
  br label %ifend66
ifend66:
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @load_program(ptr %p0) {
entry:
  %t93 = alloca i64
  store i64 0, ptr %t93
  %t1 = mul i64 0, 1
  %t2 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t1
  %t3 = trunc i64 1 to i32
  %t4 = sext i32 %t3 to i64
  store i64 %t4, ptr %t2
  %t5 = mul i64 1, 1
  %t6 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t5
  %t7 = trunc i64 8 to i32
  %t8 = sext i32 %t7 to i64
  store i64 %t8, ptr %t6
  %t9 = mul i64 2, 1
  %t10 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t9
  %t11 = trunc i64 1 to i32
  %t12 = sext i32 %t11 to i64
  store i64 %t12, ptr %t10
  %t13 = mul i64 3, 1
  %t14 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t13
  %t15 = trunc i64 1 to i32
  %t16 = sext i32 %t15 to i64
  store i64 %t16, ptr %t14
  %t17 = mul i64 4, 1
  %t18 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t17
  %t19 = trunc i64 15 to i32
  %t20 = sext i32 %t19 to i64
  store i64 %t20, ptr %t18
  %t21 = mul i64 5, 1
  %t22 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t21
  %t23 = trunc i64 1 to i32
  %t24 = sext i32 %t23 to i64
  store i64 %t24, ptr %t22
  %t25 = mul i64 6, 1
  %t26 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t25
  %t27 = trunc i64 1 to i32
  %t28 = sext i32 %t27 to i64
  store i64 %t28, ptr %t26
  %t29 = mul i64 7, 1
  %t30 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t29
  %t31 = trunc i64 11 to i32
  %t32 = sext i32 %t31 to i64
  store i64 %t32, ptr %t30
  %t33 = mul i64 8, 1
  %t34 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t33
  %t35 = trunc i64 9 to i32
  %t36 = sext i32 %t35 to i64
  store i64 %t36, ptr %t34
  %t37 = mul i64 9, 1
  %t38 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t37
  %t39 = trunc i64 14 to i32
  %t40 = sext i32 %t39 to i64
  store i64 %t40, ptr %t38
  %t41 = mul i64 10, 1
  %t42 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t41
  %t43 = trunc i64 7 to i32
  %t44 = sext i32 %t43 to i64
  store i64 %t44, ptr %t42
  %t45 = mul i64 11, 1
  %t46 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t45
  %t47 = trunc i64 20 to i32
  %t48 = sext i32 %t47 to i64
  store i64 %t48, ptr %t46
  %t49 = mul i64 12, 1
  %t50 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t49
  %t51 = trunc i64 5 to i32
  %t52 = sext i32 %t51 to i64
  store i64 %t52, ptr %t50
  %t53 = mul i64 13, 1
  %t54 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t53
  %t55 = trunc i64 1 to i32
  %t56 = sext i32 %t55 to i64
  store i64 %t56, ptr %t54
  %t57 = mul i64 14, 1
  %t58 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t57
  %t59 = trunc i64 -1 to i32
  %t60 = sext i32 %t59 to i64
  store i64 %t60, ptr %t58
  %t61 = mul i64 15, 1
  %t62 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t61
  %t63 = trunc i64 3 to i32
  %t64 = sext i32 %t63 to i64
  store i64 %t64, ptr %t62
  %t65 = mul i64 16, 1
  %t66 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t65
  %t67 = trunc i64 7 to i32
  %t68 = sext i32 %t67 to i64
  store i64 %t68, ptr %t66
  %t69 = mul i64 17, 1
  %t70 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t69
  %t71 = trunc i64 4 to i32
  %t72 = sext i32 %t71 to i64
  store i64 %t72, ptr %t70
  %t73 = mul i64 18, 1
  %t74 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t73
  %t75 = trunc i64 2 to i32
  %t76 = sext i32 %t75 to i64
  store i64 %t76, ptr %t74
  %t77 = mul i64 19, 1
  %t78 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t77
  %t79 = trunc i64 7 to i32
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  %t81 = mul i64 20, 1
  %t82 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t81
  %t83 = trunc i64 12 to i32
  %t84 = sext i32 %t83 to i64
  store i64 %t84, ptr %t82
  %t85 = mul i64 21, 1
  %t86 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t85
  %t87 = trunc i64 13 to i32
  %t88 = sext i32 %t87 to i64
  store i64 %t88, ptr %t86
  %t89 = mul i64 22, 1
  %t90 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t89
  %t91 = trunc i64 14 to i32
  %t92 = sext i32 %t91 to i64
  store i64 %t92, ptr %t90
  %t94 = trunc i64 30 to i32
  %t95 = sext i32 %t94 to i64
  store i64 %t95, ptr %t93
  br label %while1
while1:
  %t96 = load i64, ptr %t93
  %t97 = trunc i64 %t96 to i32
  %t98 = sext i32 %t97 to i64
  %t99 = trunc i64 250 to i32
  %t100 = sext i32 %t99 to i64
  %t101 = icmp slt i64 %t98, %t100
  %t102 = zext i1 %t101 to i64
  %t103 = icmp ne i64 %t102, 0
  br i1 %t103, label %whilebody2, label %whileexit3
whilebody2:
  %t104 = load i64, ptr %t93
  %t105 = mul i64 %t104, 1
  %t106 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t105
  %t107 = trunc i64 1 to i32
  %t108 = sext i32 %t107 to i64
  store i64 %t108, ptr %t106
  %t109 = load i64, ptr %t93
  %t110 = load i64, ptr %t93
  %t111 = add i64 %t110, 1
  %t112 = mul i64 %t111, 1
  %t113 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t112
  %t114 = trunc i64 %t109 to i32
  %t115 = sext i32 %t114 to i64
  store i64 %t115, ptr %t113
  %t116 = load i64, ptr %t93
  %t117 = add i64 %t116, 2
  %t118 = mul i64 %t117, 1
  %t119 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t118
  %t120 = trunc i64 15 to i32
  %t121 = sext i32 %t120 to i64
  store i64 %t121, ptr %t119
  %t122 = load i64, ptr %t93
  %t123 = add i64 %t122, 3
  %t124 = mul i64 %t123, 1
  %t125 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t124
  %t126 = trunc i64 2 to i32
  %t127 = sext i32 %t126 to i64
  store i64 %t127, ptr %t125
  %t128 = load i64, ptr %t93
  %t129 = trunc i64 %t128 to i32
  %t130 = sext i32 %t129 to i64
  %t131 = trunc i64 4 to i32
  %t132 = sext i32 %t131 to i64
  %t133 = add i64 %t130, %t132
  %t134 = trunc i64 %t133 to i32
  %t135 = sext i32 %t134 to i64
  %t136 = trunc i64 %t135 to i32
  %t137 = sext i32 %t136 to i64
  store i64 %t137, ptr %t93
  br label %while1
whileexit3:
  ret i64 0
}

define i64 @self_modify_code(ptr %p0, i64 %p1) {
entry:
  %t1 = alloca i64
  store i64 %p1, ptr %t1
  %t2 = load i64, ptr %t1
  %t3 = trunc i64 %t2 to i32
  %t4 = sext i32 %t3 to i64
  %t5 = trunc i64 10 to i32
  %t6 = sext i32 %t5 to i64
  %t7 = icmp sgt i64 %t4, %t6
  %t8 = zext i1 %t7 to i64
  %t9 = load i64, ptr %t1
  %t10 = sub i64 %t9, 1
  %t11 = mul i64 %t10, 1
  %t12 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t11
  %t13 = load i64, ptr %t12
  %t14 = trunc i64 %t13 to i32
  %t15 = sext i32 %t14 to i64
  %t16 = trunc i64 15 to i32
  %t17 = sext i32 %t16 to i64
  %t18 = icmp eq i64 %t15, %t17
  %t19 = zext i1 %t18 to i64
  %t20 = icmp ne i64 %t8, 0
  %t21 = icmp ne i64 %t19, 0
  %t22 = and i1 %t20, %t21
  %t23 = zext i1 %t22 to i64
  %t24 = icmp ne i64 %t23, 0
  br i1 %t24, label %then1, label %else2
then1:
  %t25 = load i64, ptr %t1
  %t26 = mul i64 %t25, 1
  %t27 = getelementptr [256 x i64], ptr %p0, i64 0, i64 %t26
  %t28 = trunc i64 2 to i32
  %t29 = sext i32 %t28 to i64
  store i64 %t29, ptr %t27
  br label %ifend3
else2:
  br label %ifend3
ifend3:
  ret i64 0
}

declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)
declare void @exit(i32)
declare i64 @printInt(i64)
declare i64 @printlnInt(i64)
declare i64 @printlnStr(ptr)
declare i64 @getInt()
declare void @exit_rt(i64)

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

